import { Client } from 'pg';

interface QuestionSeed {
  domaine: string;
  sous_domaine?: string;
  niveau: number;
  madhab: string;
  texte_fr: string;
  texte_ar?: string;
  dalil_ref?: string;
  dalil_texte_ar?: string;
  dalil_texte_fr?: string;
  explication?: string;
  savant_reference?: string;
  grade_hadith?: string;
  reponses: { texte_fr: string; texte_ar?: string; est_correcte: boolean }[];
}

const QUESTIONS_EXTRA2: QuestionSeed[] = [
  // ===================== FIQH (15) =====================
  {
    domaine: 'fiqh', sous_domaine: 'taharah', niveau: 1, madhab: 'general',
    texte_fr: "Combien d'obligations (fard) comporte le ghusl (grande ablution) selon la majorité des savants ?",
    texte_ar: 'كم فرضًا للغسل عند جمهور العلماء؟',
    dalil_ref: 'Sourate Al-Maida 5:6',
    dalil_texte_ar: 'وَإِن كُنتُمْ جُنُبًا فَاطَّهَّرُوا',
    dalil_texte_fr: 'Et si vous êtes en état de janaba, purifiez-vous.',
    explication: "Le ghusl obligatoire comporte : l'intention, couvrir tout le corps d'eau. Certains savants ajoutent le rinçage de la bouche et du nez.",
    reponses: [
      { texte_fr: 'Deux : intention et couvrir tout le corps d\'eau', est_correcte: true },
      { texte_fr: 'Cinq', est_correcte: false },
      { texte_fr: 'Sept', est_correcte: false },
      { texte_fr: 'Un seul : l\'eau', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la prière la plus courte en termes de rak'at obligatoires ?",
    texte_ar: 'ما أقصر صلاة من حيث الركعات الواجبة؟',
    explication: "La prière du Fajr (aube) ne comporte que 2 rak'at obligatoires, ce qui en fait la plus courte des cinq prières.",
    reponses: [
      { texte_fr: 'Fajr (2 rak\'at)', texte_ar: 'الفجر', est_correcte: true },
      { texte_fr: 'Dhuhr (4 rak\'at)', texte_ar: 'الظهر', est_correcte: false },
      { texte_fr: 'Asr (4 rak\'at)', texte_ar: 'العصر', est_correcte: false },
      { texte_fr: 'Maghrib (3 rak\'at)', texte_ar: 'المغرب', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: "Quel est le jugement de la prière du vendredi (Jumu'a) pour l'homme musulman libre, résident, et sain ?",
    texte_ar: 'ما حكم صلاة الجمعة على الرجل المسلم الحر المقيم الصحيح؟',
    dalil_ref: 'Sourate Al-Jumu\'a 62:9',
    dalil_texte_ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا نُودِيَ لِلصَّلَاةِ مِن يَوْمِ الْجُمُعَةِ فَاسْعَوْا إِلَىٰ ذِكْرِ اللَّهِ',
    dalil_texte_fr: 'Ô croyants ! Quand on appelle à la prière du vendredi, empressez-vous vers le rappel d\'Allah.',
    explication: "La prière du Jumu'a est une obligation individuelle (fard 'ayn) pour l'homme musulman adulte, libre, résident et capable.",
    reponses: [
      { texte_fr: 'Obligatoire (fard \'ayn)', texte_ar: 'فرض عين', est_correcte: true },
      { texte_fr: 'Recommandée (sunnah)', texte_ar: 'سنة', est_correcte: false },
      { texte_fr: 'Obligation collective (fard kifaya)', texte_ar: 'فرض كفاية', est_correcte: false },
      { texte_fr: 'Permise (mubah)', texte_ar: 'مباح', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'zakat', niveau: 2, madhab: 'general',
    texte_fr: "Quel est le nisab de la zakat sur l'argent (en équivalent grammes d'argent) ?",
    texte_ar: 'ما نصاب زكاة الفضة بالجرامات؟',
    explication: "Le nisab de l'argent est 595 grammes d'argent (5 uqiya = 200 dirhams). Si on possède cet équivalent pendant un an complet (hawl), la zakat est due.",
    reponses: [
      { texte_fr: '595 grammes d\'argent', est_correcte: true },
      { texte_fr: '85 grammes d\'or', est_correcte: false },
      { texte_fr: '100 grammes d\'argent', est_correcte: false },
      { texte_fr: '1000 grammes d\'argent', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'zakat', niveau: 1, madhab: 'general',
    texte_fr: "Quel est le taux de la zakat sur l'or, l'argent et les billets de banque ?",
    texte_ar: 'ما مقدار زكاة الذهب والفضة والأوراق النقدية؟',
    explication: "Le taux de la zakat sur l'or, l'argent et les billets de banque est de 2,5% (un quart du dixième) une fois le nisab atteint et le hawl (année lunaire) écoulé.",
    reponses: [
      { texte_fr: '2,5%', texte_ar: '٢٫٥٪', est_correcte: true },
      { texte_fr: '5%', est_correcte: false },
      { texte_fr: '10%', est_correcte: false },
      { texte_fr: '1%', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: "Quelles sont les personnes exemptées du jeûne de Ramadan mais devant le rattraper ?",
    texte_ar: 'من يُعفى من صيام رمضان ويجب عليه القضاء؟',
    dalil_ref: 'Sourate Al-Baqara 2:184',
    dalil_texte_ar: 'فَمَن كَانَ مِنكُم مَّرِيضًا أَوْ عَلَىٰ سَفَرٍ فَعِدَّةٌ مِّنْ أَيَّامٍ أُخَرَ',
    dalil_texte_fr: 'Quiconque d\'entre vous est malade ou en voyage, qu\'il jeûne un nombre égal d\'autres jours.',
    explication: "Le malade et le voyageur peuvent rompre le jeûne mais doivent le rattraper. La femme enceinte ou allaitante peut aussi l\'être selon certains savants.",
    reponses: [
      { texte_fr: 'Le malade et le voyageur', est_correcte: true },
      { texte_fr: 'Le vieillard et la femme enceinte uniquement', est_correcte: false },
      { texte_fr: 'L\'étudiant en période d\'examens', est_correcte: false },
      { texte_fr: 'Celui qui travaille dur physiquement', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'nikah', niveau: 2, madhab: 'general',
    texte_fr: "Quel est le pilier du mariage islamique sans lequel le contrat est invalide selon tous les madhhabs ?",
    texte_ar: 'ما الركن الذي بدونه لا يصح عقد النكاح باتفاق المذاهب؟',
    explication: "L'Ijab (offre) et le Qabul (acceptation) prononcés devant témoins sont les piliers fondamentaux du contrat de mariage islamique. Sans eux, le mariage est nul.",
    reponses: [
      { texte_fr: "L'Ijab (offre) et le Qabul (acceptation) devant témoins", est_correcte: true },
      { texte_fr: 'La dot (mahr) uniquement', est_correcte: false },
      { texte_fr: 'La présence du qadi', est_correcte: false },
      { texte_fr: 'Le consentement des deux familles', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'salat', niveau: 3, madhab: 'hanafi',
    texte_fr: "Selon le madhhab hanafi, quelle est la position des mains pour la femme pendant la prière ?",
    texte_ar: 'أين تضع المرأة يديها في الصلاة عند الحنفية؟',
    explication: "Selon le madhhab hanafi, la femme place ses mains sur sa poitrine, contrairement à l'homme qui les place sous le nombril.",
    reponses: [
      { texte_fr: 'Sur la poitrine', texte_ar: 'على الصدر', est_correcte: true },
      { texte_fr: 'Sous le nombril comme l\'homme', est_correcte: false },
      { texte_fr: 'Le long du corps', est_correcte: false },
      { texte_fr: 'Sur les genoux', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'taharah', niveau: 2, madhab: 'maliki',
    texte_fr: "Selon le madhhab maliki, l'eau qui a servi à l'ablution (ma' musta'mal) est-elle encore pure ?",
    texte_ar: 'هل الماء المستعمل في الوضوء طاهر عند المالكية؟',
    explication: "Selon le madhhab maliki, l'eau qui a servi à l'ablution reste pure (tahir) mais n'est plus purifiante (ghayr mutahhir). Elle ne peut donc pas resservir à une nouvelle ablution.",
    reponses: [
      { texte_fr: 'Oui, elle est pure mais ne peut resservir', est_correcte: true },
      { texte_fr: 'Non, elle est impure (najis)', est_correcte: false },
      { texte_fr: 'Oui, elle peut resservir une deuxième fois', est_correcte: false },
      { texte_fr: 'Cela dépend de la quantité', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'salat', niveau: 2, madhab: 'shafii',
    texte_fr: "Selon le madhhab shafi'i, quelle est la position des mains (qabd) pendant la prière pour l'homme ?",
    texte_ar: 'أين يضع الرجل يديه في الصلاة عند الشافعية؟',
    explication: "Selon le madhhab shafi'i, l'homme place ses mains sur la poitrine, en-dessous du nombril étant makruh.",
    reponses: [
      { texte_fr: 'Sur la poitrine', texte_ar: 'على الصدر', est_correcte: true },
      { texte_fr: 'Sous le nombril', est_correcte: false },
      { texte_fr: 'Sur les hanches', est_correcte: false },
      { texte_fr: 'Le long du corps', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'salat', niveau: 3, madhab: 'hanbali',
    texte_fr: "Selon le madhhab hanbali, que doit faire le fidèle s'il doute du nombre de rak'at accomplies ?",
    texte_ar: 'ماذا يفعل المصلي إذا شك في عدد الركعات عند الحنابلة؟',
    explication: "Selon le madhhab hanbali (et la majorité), il prend le nombre le plus faible (al-yaqin) et complète sa prière, puis effectue les deux prosternations d'oubli (sajdat as-sahw) avant le salam.",
    reponses: [
      { texte_fr: 'Il prend le nombre le plus faible et complète, puis fait sajdat as-sahw', est_correcte: true },
      { texte_fr: 'Il recommence la prière depuis le début', est_correcte: false },
      { texte_fr: 'Il prend le nombre le plus élevé', est_correcte: false },
      { texte_fr: 'Il n\'a rien à faire, la prière est valide', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: "Combien de fois faut-il courir entre As-Safa et Al-Marwa lors du sa'y ?",
    texte_ar: 'كم مرة يُسعى بين الصفا والمروة؟',
    explication: "Le sa'y comporte sept allers-retours : on commence à As-Safa et on termine à Al-Marwa. Chaque aller ou retour est compté comme une course.",
    reponses: [
      { texte_fr: 'Sept allers-retours (en terminant à Al-Marwa)', est_correcte: true },
      { texte_fr: 'Sept allers (sans retour)', est_correcte: false },
      { texte_fr: 'Cinq allers-retours', est_correcte: false },
      { texte_fr: 'Trois allers-retours', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'muamalat', niveau: 3, madhab: 'general',
    texte_fr: "Quel type de transaction est explicitement interdit par le Coran sous le nom de riba ?",
    texte_ar: 'ما نوع المعاملة المحرمة صراحة في القرآن باسم الربا؟',
    dalil_ref: 'Sourate Al-Baqara 2:275',
    dalil_texte_ar: 'وَأَحَلَّ اللَّهُ الْبَيْعَ وَحَرَّمَ الرِّبَا',
    dalil_texte_fr: 'Allah a rendu licite la vente et illicite le riba.',
    explication: "Le riba (usure/intérêt) est toute augmentation conditionnée dans un échange de biens de même nature ou dans un prêt. Il est interdit par le Coran, la Sunnah et le consensus.",
    reponses: [
      { texte_fr: 'L\'intérêt et l\'usure (riba)', texte_ar: 'الربا', est_correcte: true },
      { texte_fr: 'La vente à perte', est_correcte: false },
      { texte_fr: 'Le troc entre marchandises différentes', est_correcte: false },
      { texte_fr: 'La vente à crédit sans intérêt', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh', sous_domaine: 'janaza', niveau: 2, madhab: 'general',
    texte_fr: "Combien de takbirat comporte la prière funèbre (salat al-janaza) ?",
    texte_ar: 'كم تكبيرة في صلاة الجنازة؟',
    explication: "La prière funèbre comporte quatre takbirat selon le consensus des savants. C'est une obligation collective (fard kifaya).",
    reponses: [
      { texte_fr: 'Quatre takbirat', texte_ar: 'أربع تكبيرات', est_correcte: true },
      { texte_fr: 'Cinq takbirat', est_correcte: false },
      { texte_fr: 'Trois takbirat', est_correcte: false },
      { texte_fr: 'Sept takbirat', est_correcte: false },
    ],
  },
  // ===================== AQIDA (15) =====================
  {
    domaine: 'aqida', niveau: 1, madhab: 'general',
    texte_fr: "Combien y a-t-il de piliers de l'islam ?",
    texte_ar: 'كم ركنًا للإسلام؟',
    dalil_ref: 'Sahih Al-Bukhari 8, Muslim 16',
    dalil_texte_ar: 'بُنِيَ الْإِسْلَامُ عَلَى خَمْسٍ',
    dalil_texte_fr: "L'islam est bâti sur cinq choses.",
    grade_hadith: 'mutawatir',
    explication: "Les cinq piliers sont : la Shahada, la Salat, la Zakat, le Sawm de Ramadan, et le Hajj pour qui en est capable.",
    reponses: [
      { texte_fr: 'Cinq', texte_ar: 'خمسة', est_correcte: true },
      { texte_fr: 'Six', est_correcte: false },
      { texte_fr: 'Quatre', est_correcte: false },
      { texte_fr: 'Sept', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 1, madhab: 'general',
    texte_fr: "Combien y a-t-il de piliers de l'iman (foi) ?",
    texte_ar: 'كم ركنًا للإيمان؟',
    dalil_ref: 'Sahih Muslim 8',
    dalil_texte_ar: 'أَنْ تُؤْمِنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ وَالْيَوْمِ الْآخِرِ وَتُؤْمِنَ بِالْقَدَرِ',
    dalil_texte_fr: "Croire en Allah, Ses anges, Ses livres, Ses messagers, au Jour dernier et au destin.",
    grade_hadith: 'sahih',
    explication: "Les six piliers de l'iman sont : foi en Allah, les anges, les livres révélés, les messagers, le Jour dernier, et le destin (qadar).",
    reponses: [
      { texte_fr: 'Six', texte_ar: 'ستة', est_correcte: true },
      { texte_fr: 'Cinq', est_correcte: false },
      { texte_fr: 'Sept', est_correcte: false },
      { texte_fr: 'Quatre', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Qu'est-ce que le Tawhid Al-Uluhiyya ?",
    texte_ar: 'ما معنى توحيد الألوهية؟',
    explication: "Le Tawhid Al-Uluhiyya (ou Tawhid Al-Ibada) consiste à n'adresser toute forme d'adoration (du'a, peur, espoir, amour...) qu'à Allah seul. C'est le sens du 'La ilaha illallah'.",
    reponses: [
      { texte_fr: "N'adorer qu'Allah seul dans tous les actes d'adoration", texte_ar: 'إفراد الله بالعبادة', est_correcte: true },
      { texte_fr: 'Croire qu\'Allah est le seul créateur', est_correcte: false },
      { texte_fr: 'Connaître les noms et attributs d\'Allah', est_correcte: false },
      { texte_fr: 'Croire en l\'existence d\'Allah', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Selon Ahlu Sunnah Wal Jama'a, comment doit-on comprendre les attributs divins comme 'la Main d\'Allah' ?",
    texte_ar: "كيف يفهم أهل السنة والجماعة صفات الله كـ'يد الله'؟",
    dalil_ref: 'Sourate Ash-Shura 42:11',
    dalil_texte_ar: 'لَيْسَ كَمِثْلِهِ شَيْءٌ وَهُوَ السَّمِيعُ الْبَصِيرُ',
    dalil_texte_fr: "Il n'y a rien de semblable à Lui, et Il est l'Audient, le Clairvoyant.",
    explication: "Ahlu Sunnah affirme les attributs comme ils sont mentionnés, sans les déformer (tahrif), les nier (ta'til), les questionner sur la modalité (takyif), ni les comparer à la création (tamthil).",
    reponses: [
      { texte_fr: "Les affirmer sans déformation ni comparaison avec la création", est_correcte: true },
      { texte_fr: 'Les interpréter systématiquement de manière métaphorique', est_correcte: false },
      { texte_fr: 'Les nier car Allah n\'a pas de corps', est_correcte: false },
      { texte_fr: 'Décrire leur modalité exacte', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la définition du shirk al-akbar (grand polythéisme) ?",
    texte_ar: 'ما تعريف الشرك الأكبر؟',
    dalil_ref: 'Sourate An-Nisa 4:48',
    dalil_texte_ar: 'إِنَّ اللَّهَ لَا يَغْفِرُ أَن يُشْرَكَ بِهِ وَيَغْفِرُ مَا دُونَ ذَٰلِكَ لِمَن يَشَاءُ',
    dalil_texte_fr: "Allah ne pardonne pas qu'on Lui associe quelque chose, mais Il pardonne ce qui est moins grave à qui Il veut.",
    explication: "Le shirk al-akbar consiste à associer un partenaire à Allah dans les actes d'adoration. C'est le seul péché qu'Allah ne pardonne pas si on meurt sans s'en repentir.",
    reponses: [
      { texte_fr: "Associer un partenaire à Allah dans les actes d'adoration", est_correcte: true },
      { texte_fr: "Manquer des prières obligatoires", est_correcte: false },
      { texte_fr: "Commettre un grand péché", est_correcte: false },
      { texte_fr: "Douter de l'existence d'Allah", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Qu'est-ce que la Bid'a dans le contexte islamique ?",
    texte_ar: 'ما البدعة في الإسلام؟',
    dalil_ref: 'Sahih Muslim 867',
    dalil_texte_ar: 'وَكُلَّ بِدْعَةٍ ضَلَالَةٌ',
    dalil_texte_fr: "Toute bid'a est un égarement.",
    grade_hadith: 'sahih',
    explication: "La bid'a est toute innovation en matière de culte qui n'a pas de fondement dans le Coran, la Sunnah ou le consensus des Compagnons. Elle est considérée comme un égarement selon le hadith.",
    reponses: [
      { texte_fr: "Une innovation en matière de culte sans fondement dans le Coran et la Sunnah", est_correcte: true },
      { texte_fr: "Toute nouveauté dans la vie quotidienne", est_correcte: false },
      { texte_fr: "Une opinion divergente entre savants", est_correcte: false },
      { texte_fr: "Un acte permis pratiqué pour la première fois", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 3, madhab: 'general',
    texte_fr: "Selon Ahlu Sunnah, les pécheurs (fussaq) parmi les croyants sont-ils définitivement en enfer ?",
    texte_ar: 'هل فساق المؤمنين مخلدون في النار عند أهل السنة؟',
    explication: "Selon Ahlu Sunnah, les croyants qui commettent de grands péchés (fussaq) ne sont ni kuffar ni définitivement en enfer. Ils sont sous la volonté d'Allah : Il peut les pardonner ou les punir temporairement avant le paradis.",
    reponses: [
      { texte_fr: "Non, ils sont sous la volonté d'Allah et peuvent être pardonnés", est_correcte: true },
      { texte_fr: "Oui, ils sont kuffar et en enfer pour l'éternité (position khawarij)", est_correcte: false },
      { texte_fr: "Ils sont entre deux positions, ni mu'min ni kafir (position mu'tazila)", est_correcte: false },
      { texte_fr: "Ils seront tous pardonnés sans châtiment", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Combien y a-t-il de niveaux du qadar (destin) selon les savants de la Sunnah ?",
    texte_ar: 'كم مرتبة للقدر عند علماء السنة؟',
    explication: "Les savants de la Sunnah mentionnent quatre niveaux du qadar : 1) 'Ilm (connaissance divine), 2) Kitaba (écriture dans Al-Lawh Al-Mahfuz), 3) Mashi'a (volonté divine), 4) Khalq (création par Allah).",
    reponses: [
      { texte_fr: 'Quatre niveaux', texte_ar: 'أربع مراتب', est_correcte: true },
      { texte_fr: 'Deux niveaux', est_correcte: false },
      { texte_fr: 'Six niveaux', est_correcte: false },
      { texte_fr: 'Un seul niveau', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 1, madhab: 'general',
    texte_fr: "Quel est le premier devoir de l'être humain selon les savants islamiques ?",
    texte_ar: 'ما أول واجب على المكلف؟',
    explication: "Le premier devoir est de connaître Allah (ma'rifatullah) par le témoignage de la foi (Shahada) et de croire en Son existence, Sa seigneurie, Son unicité, et Ses noms et attributs.",
    reponses: [
      { texte_fr: "Connaître Allah et témoigner de Son unicité", est_correcte: true },
      { texte_fr: "Apprendre le Coran par cœur", est_correcte: false },
      { texte_fr: "Effectuer la prière du Fajr", est_correcte: false },
      { texte_fr: "Mémoriser les 99 noms d'Allah", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 3, madhab: 'general',
    texte_fr: "Selon Ahlu Sunnah, la vision d'Allah (ru'yatullah) au Paradis est-elle possible ?",
    texte_ar: 'هل رؤية الله في الجنة ممكنة عند أهل السنة؟',
    dalil_ref: 'Sahih Al-Bukhari 7437',
    dalil_texte_ar: 'إِنَّكُمْ سَتَرَوْنَ رَبَّكُمْ كَمَا تَرَوْنَ الْقَمَرَ لَيْلَةَ الْبَدْرِ',
    dalil_texte_fr: "Vous verrez votre Seigneur comme vous voyez la pleine lune.",
    grade_hadith: 'mutawatir',
    explication: "Ahlu Sunnah affirme que les croyants verront Allah au Paradis. C'est la plus grande récompense pour les croyants, confirmée par des hadiths mutawatir.",
    reponses: [
      { texte_fr: "Oui, c'est possible et c'est la plus grande récompense", est_correcte: true },
      { texte_fr: "Non, Allah ne peut pas être vu (position mu'tazila)", est_correcte: false },
      { texte_fr: "Seulement les prophètes pourront Le voir", est_correcte: false },
      { texte_fr: "Ce n'est pas mentionné dans les textes", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Qui sont les Compagnons (Sahaba) du Prophète ﷺ ?",
    texte_ar: 'من هم الصحابة رضي الله عنهم؟',
    explication: "Les Sahaba sont ceux qui ont rencontré le Prophète ﷺ en croyant en lui et sont morts dans l'islam. Ahlu Sunnah les respecte tous et s'abstient de critiquer leurs différends.",
    reponses: [
      { texte_fr: "Ceux qui ont rencontré le Prophète ﷺ en croyant en lui et morts dans l'islam", est_correcte: true },
      { texte_fr: "Les 10 Compagnons promis au Paradis uniquement", est_correcte: false },
      { texte_fr: "Uniquement les Muhajirun et Ansar", est_correcte: false },
      { texte_fr: "Ceux qui ont mémorisé le Coran de son vivant", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 3, madhab: 'general',
    texte_fr: "Qu'est-ce que le Tawassul permis selon Ahlu Sunnah ?",
    texte_ar: 'ما التوسل المشروع عند أهل السنة؟',
    explication: "Le tawassul permis inclut : se rapprocher d'Allah par Ses noms et attributs, par les bonnes œuvres, et par la supplication d'une personne vivante. Le tawassul par les morts est une question de divergence, la majorité des savants contemporains l'interdisant.",
    reponses: [
      { texte_fr: "Par les noms d'Allah, les bonnes œuvres, et la supplication d'une personne vivante", est_correcte: true },
      { texte_fr: "Par les tombes des saints", est_correcte: false },
      { texte_fr: "Par les reliques des prophètes", est_correcte: false },
      { texte_fr: "Il n'y a aucun tawassul permis", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 1, madhab: 'general',
    texte_fr: "Quel est le nom de l'ange chargé de souffler dans la Trompe (As-Sur) au Jour du Jugement ?",
    texte_ar: 'ما اسم الملك الموكل بالنفخ في الصور يوم القيامة؟',
    explication: "L'ange Israfil est chargé de souffler dans la Trompe. Le premier souffle annonce la fin du monde, le deuxième la résurrection.",
    reponses: [
      { texte_fr: 'Israfil', texte_ar: 'إسرافيل', est_correcte: true },
      { texte_fr: 'Jibril', texte_ar: 'جبريل', est_correcte: false },
      { texte_fr: 'Mikail', texte_ar: 'ميكائيل', est_correcte: false },
      { texte_fr: 'Izrail', texte_ar: 'عزرائيل', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Quels sont les quatre livres révélés majeurs mentionnés dans le Coran et la Sunnah ?",
    texte_ar: 'ما الكتب الأربعة الكبرى المذكورة في القرآن والسنة؟',
    explication: "Les quatre livres révélés majeurs sont : la Torah (Tawrat) révélée à Moïse, les Psaumes (Zabur) à David, l'Évangile (Injil) à Jésus, et le Coran révélé à Muhammad ﷺ.",
    reponses: [
      { texte_fr: "Torah, Zabur, Injil, Coran", texte_ar: 'التوراة والزبور والإنجيل والقرآن', est_correcte: true },
      { texte_fr: "Torah, Injil, Coran, et les Rouleaux d'Ibrahim", est_correcte: false },
      { texte_fr: "Coran, Torah, Injil, et l'Ancien Testament", est_correcte: false },
      { texte_fr: "Seulement le Coran et la Torah", est_correcte: false },
    ],
  },
  {
    domaine: 'aqida', niveau: 2, madhab: 'general',
    texte_fr: "Quel est le nombre de prophètes mentionnés par leur nom dans le Coran ?",
    texte_ar: 'كم نبيًا ذُكر باسمه في القرآن الكريم؟',
    explication: "Le Coran mentionne 25 prophètes par leur nom, d'Adam à Muhammad ﷺ. Le total des prophètes envoyés est estimé à 124 000 selon certains hadiths (la chaîne n'étant pas solide).",
    reponses: [
      { texte_fr: '25 prophètes', texte_ar: 'خمسة وعشرون نبيًا', est_correcte: true },
      { texte_fr: '12 prophètes', est_correcte: false },
      { texte_fr: '30 prophètes', est_correcte: false },
      { texte_fr: '18 prophètes', est_correcte: false },
    ],
  },
  // ===================== TAFSIR (15) =====================
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: "Quel est le sens du mot 'Al-Hamd' dans 'Al-Hamdulillah' ?",
    texte_ar: "ما معنى 'الحمد' في 'الحمد لله'؟",
    dalil_ref: 'Sourate Al-Fatiha 1:2',
    dalil_texte_ar: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
    dalil_texte_fr: "Louange à Allah, Seigneur des mondes.",
    explication: "'Al-Hamd' signifie la louange accompagnée d'amour et de révérence. Elle est plus complète que 'ash-shukr' (gratitude) car elle inclut les louanges pour les attributs divins même sans bienfait reçu.",
    reponses: [
      { texte_fr: "La louange accompagnée d'amour et de révérence", est_correcte: true },
      { texte_fr: "La gratitude pour un bienfait reçu", est_correcte: false },
      { texte_fr: "La glorification", est_correcte: false },
      { texte_fr: "La supplication", est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la sourate surnommée 'Umm Al-Kitab' (Mère du Livre) ?",
    texte_ar: "ما السورة الملقبة بـ'أم الكتاب'؟",
    explication: "La sourate Al-Fatiha est surnommée 'Umm Al-Kitab' car elle contient en résumé tous les thèmes du Coran : tawhid, dua, guidance, rétribution.",
    reponses: [
      { texte_fr: 'Al-Fatiha', texte_ar: 'الفاتحة', est_correcte: true },
      { texte_fr: 'Al-Baqara', est_correcte: false },
      { texte_fr: 'Al-Ikhlas', est_correcte: false },
      { texte_fr: 'Yasin', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: "Quelle est la signification du 'Ayat Al-Kursi' (verset du Trône, Baqara 2:255) ?",
    texte_ar: 'ما مضمون آية الكرسي؟',
    dalil_ref: 'Sourate Al-Baqara 2:255',
    dalil_texte_ar: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
    dalil_texte_fr: "Allah ! Pas de divinité sauf Lui, le Vivant, Celui qui subsiste par Lui-même.",
    explication: "L'Ayat Al-Kursi décrit la grandeur absolue d'Allah : Sa vie éternelle, Sa subsistance par Lui-même, Sa connaissance totale, et Sa maîtrise des cieux et de la terre.",
    reponses: [
      { texte_fr: "La grandeur d'Allah, Sa vie éternelle et Sa maîtrise de toute chose", est_correcte: true },
      { texte_fr: "La description du Paradis", est_correcte: false },
      { texte_fr: "Les règles du jeûne", est_correcte: false },
      { texte_fr: "L'histoire de la création", est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: "Combien de fois la Basmala ('Bismillah Ar-Rahman Ar-Rahim') apparaît-elle dans le Coran ?",
    texte_ar: 'كم مرة وردت البسملة في القرآن الكريم؟',
    explication: "La Basmala apparaît 114 fois dans le Coran : au début de 113 sourates (sauf At-Tawba) et une fois dans la sourate An-Naml (verset 30) dans la lettre de Soulayman.",
    reponses: [
      { texte_fr: '114 fois', texte_ar: '١١٤ مرة', est_correcte: true },
      { texte_fr: '113 fois', est_correcte: false },
      { texte_fr: '115 fois', est_correcte: false },
      { texte_fr: '100 fois', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: "Quel prophète est le plus mentionné dans le Coran par son nom ?",
    texte_ar: 'من أكثر الأنبياء ذكرًا في القرآن الكريم بالاسم؟',
    explication: "Le prophète Musa (Moïse) est le plus mentionné dans le Coran par son nom, environ 136 fois. Il est suivi par Ibrahim, Isa, et Nuh.",
    reponses: [
      { texte_fr: 'Musa (Moïse)', texte_ar: 'موسى عليه السلام', est_correcte: true },
      { texte_fr: 'Ibrahim (Abraham)', est_correcte: false },
      { texte_fr: 'Muhammad ﷺ', est_correcte: false },
      { texte_fr: 'Isa (Jésus)', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: "Quelle sourate est surnommée 'le cœur du Coran' ?",
    texte_ar: 'ما السورة التي تُعدّ قلب القرآن؟',
    dalil_ref: 'Sunan At-Tirmidhi 2887',
    dalil_texte_ar: 'إِنَّ لِكُلِّ شَيْءٍ قَلْبًا وَإِنَّ قَلْبَ الْقُرْآنِ يس',
    dalil_texte_fr: "Toute chose a un cœur, et le cœur du Coran est Yasin.",
    grade_hadith: 'hassan',
    explication: "La sourate Yasin est surnommée 'le cœur du Coran'. Elle traite des thèmes fondamentaux : tawhid, résurrection, et les signes d'Allah.",
    reponses: [
      { texte_fr: 'Yasin', texte_ar: 'يس', est_correcte: true },
      { texte_fr: 'Al-Fatiha', est_correcte: false },
      { texte_fr: 'Al-Kahf', est_correcte: false },
      { texte_fr: 'Al-Baqara', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 3, madhab: 'general',
    texte_fr: "Que signifie 'Alif Lam Mim' au début de certaines sourates (huruf muqatta'at) ?",
    texte_ar: "ما معنى الحروف المقطعة مثل 'الم' في أوائل بعض السور؟",
    explication: "Les huruf muqatta'at sont des lettres mystérieuses dont la signification exacte n'est connue que d'Allah. La position majoritaire des savants est de s'abstenir d'en donner une interprétation définitive et de les réciter en croyant qu'elles contiennent une sagesse connue d'Allah.",
    reponses: [
      { texte_fr: "Leur signification exacte n'est connue que d'Allah (position de la majorité)", est_correcte: true },
      { texte_fr: "Ce sont des abréviations des noms divins", est_correcte: false },
      { texte_fr: "Ce sont des chiffres en code arabe", est_correcte: false },
      { texte_fr: "Ils représentent les noms des Compagnons", est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la sourate la plus longue du Coran ?",
    texte_ar: 'ما أطول سورة في القرآن الكريم؟',
    explication: "La sourate Al-Baqara est la plus longue sourate du Coran avec 286 versets. Elle contient le verset le plus long (2:282) et l'Ayat Al-Kursi (2:255).",
    reponses: [
      { texte_fr: 'Al-Baqara (286 versets)', texte_ar: 'البقرة', est_correcte: true },
      { texte_fr: 'Al-Imran', est_correcte: false },
      { texte_fr: 'An-Nisa', est_correcte: false },
      { texte_fr: 'Al-Maida', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: "Quelle est la sourate recommandée par le Prophète ﷺ à réciter chaque vendredi ?",
    texte_ar: 'ما السورة التي حثّ النبي ﷺ على قراءتها كل جمعة؟',
    dalil_ref: 'Sahih Al-Hakim 2/399',
    dalil_texte_ar: 'مَنْ قَرَأَ سُورَةَ الْكَهْفِ فِي يَوْمِ الْجُمُعَةِ أَضَاءَ لَهُ مِنَ النُّورِ مَا بَيْنَ الْجُمُعَتَيْنِ',
    dalil_texte_fr: "Celui qui récite la sourate Al-Kahf le vendredi bénéficiera d'une lumière entre les deux vendredis.",
    grade_hadith: 'sahih',
    explication: "La sourate Al-Kahf est recommandée à réciter le vendredi. Elle contient quatre grandes histoires : les gens de la caverne, le propriétaire des deux jardins, Musa et Al-Khidr, et Dhul-Qarnayn.",
    reponses: [
      { texte_fr: 'Al-Kahf', texte_ar: 'الكهف', est_correcte: true },
      { texte_fr: 'Al-Fatiha', est_correcte: false },
      { texte_fr: 'Yasin', est_correcte: false },
      { texte_fr: 'Al-Baqara', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 3, madhab: 'general',
    texte_fr: "Dans la sourate Al-Kahf, quelle est la leçon principale de l'histoire de Musa et Al-Khidr ?",
    texte_ar: 'ما الدرس الرئيسي من قصة موسى والخضر في سورة الكهف؟',
    dalil_ref: 'Sourate Al-Kahf 18:65-82',
    explication: "La principale leçon est que la connaissance d'Allah est au-delà de la compréhension humaine. Ce qui semble mauvais peut cacher une sagesse divine, et l'humilité devant la connaissance de notre Seigneur est essentielle.",
    reponses: [
      { texte_fr: "La connaissance d'Allah dépasse la compréhension humaine, l'humilité est essentielle", est_correcte: true },
      { texte_fr: "Il faut toujours obéir aux savants sans question", est_correcte: false },
      { texte_fr: "La fin justifie les moyens", est_correcte: false },
      { texte_fr: "Les miracles sont réservés aux prophètes", est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: "Quel est le verset coranique considéré comme le plus grand (sayyid al-ayat) selon le Prophète ﷺ ?",
    texte_ar: "ما أعظم آية في القرآن الكريم وفق حديث النبي ﷺ؟",
    dalil_ref: 'Sahih Muslim 810',
    grade_hadith: 'sahih',
    explication: "L'Ayat Al-Kursi (Al-Baqara 2:255) est le verset le plus grand du Coran, comme l'a déclaré le Prophète ﷺ lui-même.",
    reponses: [
      { texte_fr: "Ayat Al-Kursi (Al-Baqara 2:255)", texte_ar: 'آية الكرسي', est_correcte: true },
      { texte_fr: "Al-Fatiha 1:1", est_correcte: false },
      { texte_fr: "Al-Ikhlas 112:1", est_correcte: false },
      { texte_fr: "Al-Baqara 2:286", est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: "Quelle sourate est équivalente au tiers du Coran selon un hadith authentique ?",
    texte_ar: 'ما السورة التي تعدل ثلث القرآن؟',
    dalil_ref: 'Sahih Al-Bukhari 5015',
    dalil_texte_ar: 'قُلْ هُوَ اللَّهُ أَحَدٌ تَعْدِلُ ثُلُثَ الْقُرْآنِ',
    grade_hadith: 'sahih',
    explication: "La sourate Al-Ikhlas (Qul huwa Allahu ahad) équivaut au tiers du Coran en termes de récompense selon le Prophète ﷺ, car elle contient le tawhid pur.",
    reponses: [
      { texte_fr: 'Al-Ikhlas', texte_ar: 'الإخلاص', est_correcte: true },
      { texte_fr: 'Al-Fatiha', est_correcte: false },
      { texte_fr: 'Al-Falaq', est_correcte: false },
      { texte_fr: 'An-Nas', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: "Quelle est la dernière sourate révélée selon les savants du tafsir ?",
    texte_ar: 'ما آخر سورة نزلت من القرآن؟',
    explication: "Selon la majorité des savants, la sourate An-Nasr est la dernière sourate entière révélée. Certains savants mentionnent Al-Ma'ida ou At-Tawba pour certains versets.",
    reponses: [
      { texte_fr: 'An-Nasr (Le Secours)', texte_ar: 'النصر', est_correcte: true },
      { texte_fr: 'Al-Maida', est_correcte: false },
      { texte_fr: 'Al-Baqara', est_correcte: false },
      { texte_fr: 'At-Tawba', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 3, madhab: 'general',
    texte_fr: "Dans quelle sourate Allah décrit-Il le Coran comme un 'remède pour les âmes' (shifa) ?",
    texte_ar: 'في أي سورة وصف الله القرآن بأنه شفاء لما في الصدور؟',
    dalil_ref: 'Sourate Yunus 10:57',
    dalil_texte_ar: 'يَا أَيُّهَا النَّاسُ قَدْ جَاءَتْكُم مَّوْعِظَةٌ مِّن رَّبِّكُمْ وَشِفَاءٌ لِّمَا فِي الصُّدُورِ',
    dalil_texte_fr: "Ô gens ! Une exhortation vous est venue de votre Seigneur, une guérison pour ce qui est dans les poitrines.",
    reponses: [
      { texte_fr: 'Yunus (10:57)', texte_ar: 'يونس', est_correcte: true },
      { texte_fr: 'Al-Isra', est_correcte: false },
      { texte_fr: 'Al-Baqara', est_correcte: false },
      { texte_fr: 'An-Nahl', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la première sourate révélée au Prophète Muhammad ﷺ ?",
    texte_ar: 'ما أول سورة نزلت على النبي محمد ﷺ؟',
    dalil_ref: 'Sourate Al-Alaq 96:1-5',
    dalil_texte_ar: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',
    dalil_texte_fr: "Lis au nom de ton Seigneur qui a créé.",
    explication: "Les cinq premiers versets de la sourate Al-Alaq ('Iqra') furent les premiers révélés au Prophète ﷺ par l'ange Jibril dans la grotte de Hira.",
    reponses: [
      { texte_fr: 'Al-Alaq (les 5 premiers versets)', texte_ar: 'العلق', est_correcte: true },
      { texte_fr: 'Al-Fatiha', est_correcte: false },
      { texte_fr: 'Al-Muddaththir', est_correcte: false },
      { texte_fr: 'Al-Muzzammil', est_correcte: false },
    ],
  },
  // ===================== HADITH (15) =====================
  {
    domaine: 'hadith', niveau: 1, madhab: 'general',
    texte_fr: "Quel est l'auteur du recueil de hadiths considéré comme le plus authentique après le Coran ?",
    texte_ar: 'من صاحب أصح كتاب بعد القرآن الكريم؟',
    explication: "L'Imam Al-Bukhari (194-256 H) est l'auteur du Sahih Al-Bukhari, considéré par les savants comme le livre le plus authentique après le Coran. Il a sélectionné 7275 hadiths parmi 600 000.",
    reponses: [
      { texte_fr: 'Imam Al-Bukhari', texte_ar: 'الإمام البخاري', est_correcte: true },
      { texte_fr: 'Imam Muslim', est_correcte: false },
      { texte_fr: 'Imam An-Nawawi', est_correcte: false },
      { texte_fr: 'Imam Ahmad ibn Hanbal', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 2, madhab: 'general',
    texte_fr: "Que signifie le terme 'isnad' (chaîne de transmission) dans les sciences du hadith ?",
    texte_ar: 'ما معنى الإسناد في علوم الحديث؟',
    explication: "L'isnad est la chaîne de transmetteurs qui relie le chercheur au Prophète ﷺ. Les savants du hadith ont développé des sciences complexes pour évaluer la fiabilité de chaque transmetteur.",
    reponses: [
      { texte_fr: "La chaîne de transmetteurs reliant le chercheur au Prophète ﷺ", est_correcte: true },
      { texte_fr: "Le texte du hadith lui-même", est_correcte: false },
      { texte_fr: "La explication du hadith", est_correcte: false },
      { texte_fr: "Le livre dans lequel le hadith est enregistré", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 1, madhab: 'general',
    texte_fr: "Quel est le hadith de Jibril qui résume les fondements de la religion islamique ?",
    texte_ar: 'ما حديث جبريل الذي يلخص أركان الدين الإسلامي؟',
    dalil_ref: 'Sahih Muslim 8',
    grade_hadith: 'sahih',
    explication: "Le hadith de Jibril (Muslim 8) est celui où l'ange Jibril vint sous forme humaine et interrogea le Prophète ﷺ sur l'Islam, l'Iman, et l'Ihsan. Il résume les trois dimensions de la religion.",
    reponses: [
      { texte_fr: "Le hadith où Jibril interroge le Prophète ﷺ sur l'Islam, l'Iman et l'Ihsan", est_correcte: true },
      { texte_fr: "Le hadith sur les piliers de l'Islam uniquement", est_correcte: false },
      { texte_fr: "Le hadith de la première révélation", est_correcte: false },
      { texte_fr: "Le hadith sur le Jour du Jugement", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 2, madhab: 'general',
    texte_fr: "Selon le célèbre hadith des Kutub as-Sitta, qu'est-ce que l'Ihsan ?",
    texte_ar: 'ما الإحسان وفق حديث جبريل المشهور؟',
    dalil_ref: 'Sahih Muslim 8',
    dalil_texte_ar: 'أَنْ تَعْبُدَ اللَّهَ كَأَنَّكَ تَرَاهُ فَإِنْ لَمْ تَكُنْ تَرَاهُ فَإِنَّهُ يَرَاكَ',
    dalil_texte_fr: "Adorer Allah comme si tu Le voyais, et si tu ne Le vois pas, certes Lui te voit.",
    grade_hadith: 'sahih',
    explication: "L'Ihsan est le plus haut niveau spirituel : adorer Allah avec une pleine conscience de Sa présence, comme si on Le voyait, ou au minimum en sachant qu'Il nous voit.",
    reponses: [
      { texte_fr: "Adorer Allah comme si tu Le voyais, sachant qu'Il te voit", est_correcte: true },
      { texte_fr: "Faire beaucoup de bonnes œuvres", est_correcte: false },
      { texte_fr: "S'abstenir de tous les péchés", est_correcte: false },
      { texte_fr: "Accomplir les cinq piliers parfaitement", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 2, madhab: 'general',
    texte_fr: "Le hadith 'Les actions ne valent que par les intentions' est le premier hadith de quel recueil célèbre ?",
    texte_ar: "حديث 'إنما الأعمال بالنيات' هو أول حديث في أي كتاب مشهور؟",
    dalil_ref: 'Sahih Al-Bukhari 1',
    grade_hadith: 'mutawatir',
    explication: "Ce hadith célèbre est le premier hadith du Sahih Al-Bukhari. Il est également le premier hadith dans de nombreux autres recueils car il pose le principe fondamental de l'intention.",
    reponses: [
      { texte_fr: 'Sahih Al-Bukhari', texte_ar: 'صحيح البخاري', est_correcte: true },
      { texte_fr: 'Sahih Muslim', est_correcte: false },
      { texte_fr: 'Al-Arba\'in An-Nawawiyya', est_correcte: false },
      { texte_fr: 'Sunan Abu Dawud', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 3, madhab: 'general',
    texte_fr: "Qu'est-ce qu'un hadith 'mawdu'' (forgé) ?",
    texte_ar: "ما الحديث الموضوع؟",
    explication: "Un hadith mawdu' est un hadith inventé de toutes pièces et faussement attribué au Prophète ﷺ. C'est le pire type de hadith faible. Les savants ont consacré des ouvrages entiers à les identifier et mettre en garde contre eux.",
    reponses: [
      { texte_fr: "Un hadith entièrement inventé et faussement attribué au Prophète ﷺ", est_correcte: true },
      { texte_fr: "Un hadith avec un seul transmetteur peu fiable", est_correcte: false },
      { texte_fr: "Un hadith dont la chaîne est interrompue", est_correcte: false },
      { texte_fr: "Un hadith contredisant le Coran", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 1, madhab: 'general',
    texte_fr: "Selon un hadith authentique, quels sont les 7 types de personnes qu'Allah mettra à l'ombre le Jour du Jugement ?",
    texte_ar: 'من السبعة الذين يظلهم الله في ظله يوم القيامة؟',
    dalil_ref: 'Sahih Al-Bukhari 660, Muslim 1031',
    grade_hadith: 'mutawatir',
    explication: "Les 7 types : l'imam juste, le jeune homme élevé dans l'adoration d'Allah, celui dont le cœur est attaché aux mosquées, deux personnes qui s'aiment pour Allah, celui qui refuse la séduction par crainte d'Allah, celui qui donne en cachette, et celui qui pleure en invoquant Allah en solitaire.",
    reponses: [
      { texte_fr: "L'imam juste, le jeune pieux, celui attaché à la mosquée, et autres", est_correcte: true },
      { texte_fr: "Les prophètes et leurs familles", est_correcte: false },
      { texte_fr: "Les martyrs et les savants", est_correcte: false },
      { texte_fr: "Les hafiz du Coran", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 2, madhab: 'general',
    texte_fr: "Qu'est-ce que les 'Arba'in' (quarante hadiths) d'An-Nawawi ?",
    texte_ar: "ما الأربعون النووية؟",
    explication: "Les Arba'in An-Nawawiyya est un recueil de 42 hadiths fondamentaux compilé par l'Imam An-Nawawi (631-676 H). Chaque hadith est considéré comme un pilier majeur de la religion islamique.",
    reponses: [
      { texte_fr: "Un recueil de 42 hadiths fondamentaux de l'Imam An-Nawawi", est_correcte: true },
      { texte_fr: "Un livre de jurisprudence shafi'ite", est_correcte: false },
      { texte_fr: "Le titre d'un chapitre du Sahih Muslim", est_correcte: false },
      { texte_fr: "Un recueil de 40 fatwas", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 3, madhab: 'general',
    texte_fr: "Quelle est la différence entre un hadith 'sahih' et un hadith 'hassan' ?",
    texte_ar: 'ما الفرق بين الحديث الصحيح والحسن؟',
    explication: "Le hadith sahih (authentique) a une chaîne continue de transmetteurs fiables et mémorisés, sans anomalie ni défaut. Le hadith hassan est similaire mais avec des transmetteurs de mémoire légèrement inférieure. Les deux sont acceptés comme arguments.",
    reponses: [
      { texte_fr: "Le hassan a des transmetteurs de mémoire légèrement inférieure au sahih", est_correcte: true },
      { texte_fr: "Le hassan est faible et non accepté", est_correcte: false },
      { texte_fr: "Ils sont identiques, c'est juste une terminologie différente", est_correcte: false },
      { texte_fr: "Le hassan a une chaîne interrompue contrairement au sahih", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 2, madhab: 'general',
    texte_fr: "Selon un hadith, qu'est-ce qui continue de bénéficier à un croyant après sa mort ?",
    texte_ar: 'ما الذي ينفع المؤمن بعد موته وفق الحديث؟',
    dalil_ref: 'Sahih Muslim 1631',
    dalil_texte_ar: 'إِذَا مَاتَ الْإِنسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ: صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ',
    dalil_texte_fr: "Quand l'homme meurt, ses actions s'arrêtent sauf trois : une aumône continue, une science dont on profite, ou un enfant pieux qui prie pour lui.",
    grade_hadith: 'sahih',
    explication: "Les trois sadaqat jariya sont la charité permanente, le savoir utile, et un enfant pieux qui prie pour ses parents défunts.",
    reponses: [
      { texte_fr: "Une aumône continue, une science utile, ou un enfant pieux qui prie", est_correcte: true },
      { texte_fr: "Ses prières et ses jeûnes uniquement", est_correcte: false },
      { texte_fr: "La récitation du Coran par ses proches", est_correcte: false },
      { texte_fr: "Ses bonnes actions sont préservées dans Al-Lawh Al-Mahfuz", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 1, madhab: 'general',
    texte_fr: "Quel hadith célèbre mentionne que 'La religion est le bon conseil (nasihah)' ?",
    texte_ar: "ما حديث 'الدين النصيحة'؟",
    dalil_ref: 'Sahih Muslim 55',
    dalil_texte_ar: 'الدِّينُ النَّصِيحَةُ. قُلْنَا: لِمَنْ؟ قَالَ: لِلَّهِ وَلِكِتَابِهِ وَلِرَسُولِهِ وَلِأَئِمَّةِ الْمُسْلِمِينَ وَعَامَّتِهِمْ',
    dalil_texte_fr: "La religion est le conseil sincère. Pour qui ? Pour Allah, Son Livre, Son messager, les imams des musulmans et leur ensemble.",
    grade_hadith: 'sahih',
    explication: "Ce hadith résume que la religion consiste à être sincère envers Allah, Son Livre, Son Prophète, les dirigeants et l'ensemble des musulmans.",
    reponses: [
      { texte_fr: "Sahih Muslim 55, narré par Tamim Ad-Dari", est_correcte: true },
      { texte_fr: "Sahih Al-Bukhari 1, narré par Umar", est_correcte: false },
      { texte_fr: "Sunan Abu Dawud, narré par Abu Hurairah", est_correcte: false },
      { texte_fr: "Sunan At-Tirmidhi, narré par Anas", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 3, madhab: 'general',
    texte_fr: "Qu'appelle-t-on 'Al-Kutub As-Sitta' dans les sciences du hadith ?",
    texte_ar: "ما المقصود بالكتب الستة في علم الحديث؟",
    explication: "Al-Kutub As-Sitta (les Six Livres) sont les six recueils de hadiths les plus importants : Sahih Al-Bukhari, Sahih Muslim, Sunan Abu Dawud, Sunan At-Tirmidhi, Sunan An-Nasa'i, et Sunan Ibn Majah.",
    reponses: [
      { texte_fr: "Les six recueils canoniques : Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasa'i, Ibn Majah", est_correcte: true },
      { texte_fr: "Les six premiers volumes du Musnad d'Ahmad", est_correcte: false },
      { texte_fr: "Six hadith fondamentaux sur les piliers de l'Islam", est_correcte: false },
      { texte_fr: "Les six compagnons transmetteurs principaux", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 2, madhab: 'general',
    texte_fr: "Qu'est-ce qu'un hadith 'mursal' ?",
    texte_ar: "ما الحديث المرسل؟",
    explication: "Un hadith mursal est un hadith dont la chaîne de transmission est interrompue : un Tabi'i (successeur des Compagnons) rapporte directement du Prophète ﷺ sans mentionner le Compagnon intermédiaire.",
    reponses: [
      { texte_fr: "Un hadith rapporté par un Tabi'i directement du Prophète ﷺ sans mentionner le Compagnon", est_correcte: true },
      { texte_fr: "Un hadith dont le texte est très court", est_correcte: false },
      { texte_fr: "Un hadith narré par un seul transmetteur", est_correcte: false },
      { texte_fr: "Un hadith authentique dans Bukhari et Muslim", est_correcte: false },
    ],
  },
  {
    domaine: 'hadith', niveau: 1, madhab: 'general',
    texte_fr: "Selon un hadith authentique, combien de fois doit-on laver un ustensile touché par un chien ?",
    texte_ar: 'كم مرة يُغسل الإناء الذي ولغ فيه الكلب؟',
    dalil_ref: 'Sahih Muslim 279',
    dalil_texte_ar: 'طَهُورُ إِنَاءِ أَحَدِكُمْ إِذَا وَلَغَ فِيهِ الْكَلْبُ أَنْ يَغْسِلَهُ سَبْعَ مَرَّاتٍ أُولَاهُنَّ بِالتُّرَابِ',
    dalil_texte_fr: "La purification du récipient de l'un d'entre vous, si un chien y a léché, est de le laver sept fois, la première avec de la terre.",
    grade_hadith: 'sahih',
    explication: "Selon le hadith sahih, l'ustensile léché par un chien doit être lavé sept fois, dont une fois avec de la terre (ou son équivalent aujourd'hui : savon).",
    reponses: [
      { texte_fr: "Sept fois, dont une avec de la terre", texte_ar: 'سبع مرات إحداها بالتراب', est_correcte: true },
      { texte_fr: "Trois fois", est_correcte: false },
      { texte_fr: "Une seule fois avec du savon", est_correcte: false },
      { texte_fr: "Cinq fois", est_correcte: false },
    ],
  },
  // ===================== AKHLAQ (15) =====================
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: "Selon le Prophète ﷺ, qu'est-ce qui sera le plus lourd dans la balance des bonnes œuvres le Jour du Jugement ?",
    texte_ar: 'ما أثقل شيء في الميزان يوم القيامة؟',
    dalil_ref: 'Sunan At-Tirmidhi 2002',
    dalil_texte_ar: 'مَا شَيْءٌ أَثْقَلُ فِي مِيزَانِ الْمُؤْمِنِ يَوْمَ الْقِيَامَةِ مِنْ حُسْنِ الْخُلُقِ',
    dalil_texte_fr: "Rien n'est plus lourd dans la balance du croyant le Jour du Jugement que le bon caractère.",
    grade_hadith: 'sahih',
    explication: "Le bon caractère (husn al-khuluq) sera la chose la plus lourde dans la balance du croyant. C'est pourquoi le Prophète ﷺ dit qu'il a été envoyé pour parfaire les bonnes mœurs.",
    reponses: [
      { texte_fr: "Le bon caractère (husn al-khuluq)", texte_ar: 'حسن الخلق', est_correcte: true },
      { texte_fr: "Le nombre de prières accomplies", est_correcte: false },
      { texte_fr: "Le jeûne du Ramadan", est_correcte: false },
      { texte_fr: "La récitation du Coran", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: "Selon le Prophète ﷺ, quelle est la définition du 'miskin' (pauvre) au sens véritable ?",
    texte_ar: 'من المسكين الحقيقي وفق حديث النبي ﷺ؟',
    dalil_ref: 'Sahih Al-Bukhari 1479, Muslim 1039',
    dalil_texte_ar: 'لَيْسَ الْمِسْكِينُ الَّذِي يَطُوفُ عَلَى النَّاسِ تَرُدُّهُ اللُّقْمَةُ وَاللُّقْمَتَانِ... وَلَكِنَّ الْمِسْكِينَ الَّذِي لَا يَجِدُ غِنًى يُغْنِيهِ وَلَا يُفْطَنُ لَهُ فَيُتَصَدَّقَ عَلَيْهِ',
    dalil_texte_fr: "Le pauvre n'est pas celui qui fait le tour des gens en demandant... le vrai pauvre est celui qui ne trouve pas de quoi se suffire et qui n'est pas remarqué pour qu'on lui fasse la charité.",
    grade_hadith: 'sahih',
    explication: "Le vrai pauvre n'est pas le mendiant visible mais celui qui souffre en silence sans mendier. L'Islam encourage à rechercher et aider ces personnes discrètes.",
    reponses: [
      { texte_fr: "Celui qui souffre en silence sans mendier ni être remarqué", est_correcte: true },
      { texte_fr: "Celui qui mendie dans les rues", est_correcte: false },
      { texte_fr: "Celui qui n'a pas de maison", est_correcte: false },
      { texte_fr: "Celui qui n'a pas mangé depuis trois jours", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: "Quels sont les droits du voisin selon les nombreux hadiths à ce sujet ?",
    texte_ar: 'ما حقوق الجار في الإسلام؟',
    dalil_ref: 'Sahih Al-Bukhari 6015',
    dalil_texte_ar: 'مَا زَالَ جِبْرِيلُ يُوصِينِي بِالْجَارِ حَتَّى ظَنَنتُ أَنَّهُ سَيُوَرِّثُهُ',
    dalil_texte_fr: "Jibril n'a cessé de me recommander le voisin au point que je pensais qu'il allait lui donner un droit d'héritage.",
    grade_hadith: 'sahih',
    explication: "Les droits du voisin incluent : ne pas lui faire de mal, le saluer, lui rendre visite en cas de maladie, l'aider dans le besoin, partager la nourriture, protéger son honneur et ses biens.",
    reponses: [
      { texte_fr: "Ne pas lui nuire, le saluer, le visiter, l'aider, protéger son honneur", est_correcte: true },
      { texte_fr: "Lui prêter de l'argent quand il le demande", est_correcte: false },
      { texte_fr: "Il n'a aucun droit particulier sauf ne pas faire de bruit", est_correcte: false },
      { texte_fr: "Lui donner la zakat en priorité", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la recommandation islamique concernant le maintien des liens de parenté (silat ar-rahim) ?",
    texte_ar: 'ما حكم صلة الرحم في الإسلام؟',
    dalil_ref: 'Sahih Al-Bukhari 5985',
    dalil_texte_ar: 'مَنْ أَحَبَّ أَنْ يُبْسَطَ لَهُ فِي رِزْقِهِ وَيُنْسَأَ لَهُ فِي أَثَرِهِ فَلْيَصِلْ رَحِمَهُ',
    dalil_texte_fr: "Celui qui veut voir son rizq élargi et sa vie prolongée qu'il maintienne les liens de parenté.",
    grade_hadith: 'sahih',
    explication: "Le maintien des liens de parenté est obligatoire (wajib). Il apporte des bénédictions dans le rizq et la longévité. Le couper est un grand péché.",
    reponses: [
      { texte_fr: "Obligatoire (wajib), apporte bénédictions dans le rizq et la vie", est_correcte: true },
      { texte_fr: "Recommandé (mustahabb) uniquement", est_correcte: false },
      { texte_fr: "Permis (mubah), selon les circonstances", est_correcte: false },
      { texte_fr: "Obligatoire seulement pour les parents directs", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: "Selon le Prophète ﷺ, qu'est-ce que le 'zuhd' (ascétisme) islamique ?",
    texte_ar: 'ما الزهد الإسلامي وفق السنة النبوية؟',
    dalil_ref: 'Sunan Ibn Majah 4100',
    dalil_texte_ar: 'الزُّهْدُ فِي الدُّنْيَا لَيْسَ بِتَحْرِيمِ الْحَلَالِ وَلَا إِضَاعَةِ الْمَالِ وَلَكِنِ الزُّهْدُ أَنْ تَكُونَ بِمَا فِي يَدِ اللَّهِ أَوْثَقَ مِنْكَ بِمَا فِي يَدِكَ',
    dalil_texte_fr: "Le zuhd dans ce bas monde n'est pas d'interdire le licite ni de gaspiller l'argent, mais que tu aies plus confiance en ce qu'Allah détient qu'en ce que tu détiens.",
    grade_hadith: 'hassan',
    explication: "Le zuhd islamique n'est pas de refuser ce qui est permis ou de vivre dans la pauvreté forcée, mais d'avoir le cœur détaché de ce bas monde tout en gérant ses responsabilités.",
    reponses: [
      { texte_fr: "Avoir plus confiance en Allah qu'en ses propres biens, cœur détaché", est_correcte: true },
      { texte_fr: "Ne posséder aucun bien matériel", est_correcte: false },
      { texte_fr: "Interdire tout luxe même licite", est_correcte: false },
      { texte_fr: "Quitter la société pour l'isolement (khalwa permanente)", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est la récompense promise à celui qui soutient une veuve ou un pauvre selon le hadith ?",
    texte_ar: 'ما ثواب الساعي على الأرملة والمسكين؟',
    dalil_ref: 'Sahih Al-Bukhari 6007',
    dalil_texte_ar: 'السَّاعِي عَلَى الأَرْمَلَةِ وَالْمِسْكِينِ كَالْمُجَاهِدِ فِي سَبِيلِ اللَّهِ',
    dalil_texte_fr: "Celui qui œuvre pour la veuve et le pauvre est comme le moudjahid sur le chemin d'Allah.",
    grade_hadith: 'sahih',
    explication: "Soutenir les personnes vulnérables (veuves, orphelins, pauvres) est récompensé comme le jihad ou comme celui qui prie toute la nuit et jeûne tout le jour.",
    reponses: [
      { texte_fr: "Comme le moudjahid sur le chemin d'Allah", est_correcte: true },
      { texte_fr: "Comme celui qui fait la prière de nuit", est_correcte: false },
      { texte_fr: "Une récompense mineure", est_correcte: false },
      { texte_fr: "Comme le pèlerin qui fait le Hajj", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: "Selon l'Islam, quelle est l'attitude correcte face à une calamité (musiba) ?",
    texte_ar: 'ما الموقف الصحيح من المصيبة في الإسلام؟',
    dalil_ref: 'Sourate Al-Baqara 2:155-157',
    dalil_texte_ar: 'الَّذِينَ إِذَا أَصَابَتْهُم مُّصِيبَةٌ قَالُوا إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
    dalil_texte_fr: "Ceux qui, lorsqu'un malheur les atteint, disent : 'Certes, nous appartenons à Allah et c'est à Lui que nous retournerons.'",
    explication: "La réponse islamique à la calamité est la patience (sabr), la résignation à Allah (tawakkul), et la récitation d'Inna lillahi wa inna ilayhi raji'un.",
    reponses: [
      { texte_fr: "La patience, la résignation, et réciter 'Inna lillahi...'", est_correcte: true },
      { texte_fr: "Pleurer abondamment et se lamenter", est_correcte: false },
      { texte_fr: "Ignorer l'émotion et faire semblant que rien ne s'est passé", est_correcte: false },
      { texte_fr: "Chercher à se venger si quelqu'un est responsable", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 3, madhab: 'general',
    texte_fr: "Selon les savants islamiques, qu'est-ce que la 'tawadu'' (humilité) ?",
    texte_ar: "ما التواضع عند العلماء؟",
    dalil_ref: 'Sahih Muslim 2588',
    dalil_texte_ar: 'إِنَّ اللَّهَ أَوْحَى إِلَيَّ أَنْ تَوَاضَعُوا حَتَّى لَا يَفْخَرَ أَحَدٌ عَلَى أَحَدٍ',
    dalil_texte_fr: "Allah m'a révélé de vous humilier au point que nul ne se vante sur l'autre.",
    grade_hadith: 'sahih',
    explication: "La tawadu' est de se considérer inférieur à sa vraie valeur devant Allah, de traiter les autres avec respect quelle que soit leur condition sociale, et d'éviter l'arrogance (kibr).",
    reponses: [
      { texte_fr: "Se considérer petit devant Allah, traiter les autres avec respect, éviter l'arrogance", est_correcte: true },
      { texte_fr: "Se déprécier publiquement et refuser tout compliment", est_correcte: false },
      { texte_fr: "Obéir à tout le monde sans discernement", est_correcte: false },
      { texte_fr: "Ne jamais exprimer sa propre opinion", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: "Quel est le jugement islamique sur la jalousie permise (ghipta) selon les savants ?",
    texte_ar: 'ما حكم الغبطة في الإسلام؟',
    dalil_ref: 'Sahih Al-Bukhari 1409',
    dalil_texte_ar: 'لَا حَسَدَ إِلَّا فِي اثْنَتَيْنِ: رَجُلٌ آتَاهُ اللَّهُ مَالًا فَسَلَّطَهُ عَلَى هَلَكَتِهِ فِي الْحَقِّ، وَرَجُلٌ آتَاهُ اللَّهُ الْحِكْمَةَ فَهُوَ يَقْضِي بِهَا وَيُعَلِّمُهَا',
    dalil_texte_fr: "Pas d'envie sauf en deux cas : un homme à qui Allah a donné de l'argent et lui a permis de le dépenser dans la vérité, et un homme à qui Allah a donné la sagesse et il juge et enseigne avec elle.",
    grade_hadith: 'sahih',
    explication: "La ghipta (jalousie permise) consiste à souhaiter avoir un bienfait similaire à quelqu'un sans souhaiter qu'il perde le sien. C'est différent du hasad (jalousie interdite) qui inclut le souhait que l'autre perde son bienfait.",
    reponses: [
      { texte_fr: "Permise : vouloir le même bienfait sans souhaiter que l'autre le perde", est_correcte: true },
      { texte_fr: "Interdite comme tout type de jalousie", est_correcte: false },
      { texte_fr: "Recommandée pour se motiver", est_correcte: false },
      { texte_fr: "Neutre, ni permis ni interdit", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: "Que dit le Coran concernant l'honneur de l'être humain (karama al-insan) ?",
    texte_ar: 'ماذا قال الله في القرآن عن كرامة الإنسان؟',
    dalil_ref: 'Sourate Al-Isra 17:70',
    dalil_texte_ar: 'وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ وَحَمَلْنَاهُمْ فِي الْبَرِّ وَالْبَحْرِ',
    dalil_texte_fr: "Certes, Nous avons honoré les fils d'Adam, Nous les avons transportés sur terre et sur mer.",
    explication: "Allah a accordé une dignité intrinsèque à tous les êtres humains. C'est la base de l'interdiction de l'humiliation, des injustices, et du respect dû à chaque personne.",
    reponses: [
      { texte_fr: "Allah a honoré les fils d'Adam et les a élevés sur de nombreuses créatures", est_correcte: true },
      { texte_fr: "L'honneur n'appartient qu'aux musulmans", est_correcte: false },
      { texte_fr: "L'honneur dépend des actes de chacun", est_correcte: false },
      { texte_fr: "L'homme est faible et sans honneur particulier", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: "Comment l'Islam définit-il la sincérité (ikhlas) dans les actes d'adoration ?",
    texte_ar: 'كيف يعرّف الإسلام الإخلاص في العبادة؟',
    dalil_ref: 'Sourate Al-Bayyina 98:5',
    dalil_texte_ar: 'وَمَا أُمِرُوا إِلَّا لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ',
    dalil_texte_fr: "Or, il ne leur a été commandé que d'adorer Allah en Lui vouant un culte exclusif.",
    explication: "L'ikhlas est de faire chaque acte d'adoration uniquement pour Allah, sans chercher la gloire humaine (riya), la réputation, ou tout autre motif mondain.",
    reponses: [
      { texte_fr: "Accomplir les actes uniquement pour Allah, sans chercher la gloire humaine", est_correcte: true },
      { texte_fr: "Faire beaucoup d'actes d'adoration", est_correcte: false },
      { texte_fr: "Cacher tous ses actes d'adoration", est_correcte: false },
      { texte_fr: "Ne jamais accepter de récompense pour ses bonnes actions", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 3, madhab: 'general',
    texte_fr: "Selon le hadith, quel est le signe du munafiq (hypocrite) ?",
    texte_ar: 'ما آية المنافق وفق الحديث النبوي؟',
    dalil_ref: 'Sahih Al-Bukhari 33, Muslim 59',
    dalil_texte_ar: 'آيَةُ الْمُنَافِقِ ثَلَاثٌ: إِذَا حَدَّثَ كَذَبَ، وَإِذَا وَعَدَ أَخْلَفَ، وَإِذَا اؤْتُمِنَ خَانَ',
    dalil_texte_fr: "Le signe du munafiq est trois choses : quand il parle, il ment ; quand il promet, il ne tient pas sa promesse ; quand on lui fait confiance, il trahit.",
    grade_hadith: 'mutawatir',
    explication: "Ces trois signes sont les signes de la nifaq (hypocrisie) de comportement. Ils n'impliquent pas nécessairement la nifaq de croyance. Un musulman doit s'en préserver absolument.",
    reponses: [
      { texte_fr: "Mentir, ne pas tenir ses promesses, trahir la confiance", est_correcte: true },
      { texte_fr: "Ne pas prier la prière du Fajr", est_correcte: false },
      { texte_fr: "Critiquer les savants", est_correcte: false },
      { texte_fr: "Ne pas payer la zakat", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: "Quelle est l'importance du salut (as-salam alaykum) dans l'Islam ?",
    texte_ar: 'ما أهمية السلام في الإسلام؟',
    dalil_ref: 'Sahih Muslim 54',
    dalil_texte_ar: 'لَا تَدْخُلُوا الْجَنَّةَ حَتَّى تُؤْمِنُوا وَلَا تُؤْمِنُوا حَتَّى تَحَابُّوا أَوَلَا أَدُلُّكُمْ عَلَى شَيْءٍ إِذَا فَعَلْتُمُوهُ تَحَابَبْتُمْ أَفْشُوا السَّلَامَ بَيْنَكُمْ',
    dalil_texte_fr: "Vous n'entrerez pas au Paradis tant que vous ne croirez pas, et vous ne croirez pas tant que vous ne vous aimerez pas. Voulez-vous que je vous indique quelque chose qui, si vous le faites, vous fera vous aimer ? Répandez le salut entre vous.",
    grade_hadith: 'sahih',
    explication: "Répandre le salut entre les musulmans est une sunna fortement recommandée qui renforce l'amour et la fraternité. C'est une clé de l'entrée au Paradis selon ce hadith.",
    reponses: [
      { texte_fr: "Sunna fortement recommandée, renforce l'amour et la fraternité islamique", est_correcte: true },
      { texte_fr: "Simple politesse sociale sans valeur spirituelle", est_correcte: false },
      { texte_fr: "Obligatoire seulement en entrant dans une mosquée", est_correcte: false },
      { texte_fr: "Réservé aux savants et imams", est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: "Comment l'Islam encourage-t-il à traiter les non-musulmans qui ne sont pas en guerre avec les musulmans ?",
    texte_ar: 'كيف يأمر الإسلام بالتعامل مع غير المسلمين السلميين؟',
    dalil_ref: 'Sourate Al-Mumtahana 60:8',
    dalil_texte_ar: 'لَّا يَنْهَاكُمُ اللَّهُ عَنِ الَّذِينَ لَمْ يُقَاتِلُوكُمْ فِي الدِّينِ وَلَمْ يُخْرِجُوكُم مِّن دِيَارِكُمْ أَن تَبَرُّوهُمْ وَتُقْسِطُوا إِلَيْهِمْ',
    dalil_texte_fr: "Allah ne vous interdit pas d'être bienfaisants et équitables envers ceux qui ne vous ont pas combattus pour la religion et ne vous ont pas chassés de vos demeures.",
    explication: "L'Islam ordonne d'être juste et bienfaisant envers les non-musulmans pacifiques. La relation avec eux doit être basée sur la justice, le respect, et la bonté.",
    reponses: [
      { texte_fr: "Être bienfaisants et équitables envers eux", est_correcte: true },
      { texte_fr: "Les éviter systématiquement", est_correcte: false },
      { texte_fr: "Les traiter avec méfiance", est_correcte: false },
      { texte_fr: "Ne jamais leur adresser la parole", est_correcte: false },
    ],
  },
];

export async function seedQuestionsExtra2(client: Client): Promise<void> {
  console.log('Seeding extra questions (batch 2)...');

  for (const q of QUESTIONS_EXTRA2) {
    const qResult = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, dalil_texte_ar, dalil_texte_fr, explication, savant_reference, grade_hadith, est_valide)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true)
       RETURNING id`,
      [
        q.domaine, q.sous_domaine || null, q.niveau, q.madhab,
        q.texte_fr, q.texte_ar || null,
        q.dalil_ref || null, q.dalil_texte_ar || null, q.dalil_texte_fr || null,
        q.explication || null, q.savant_reference || null, q.grade_hadith || null,
      ]
    );

    const questionId = qResult.rows[0].id;

    for (const r of q.reponses) {
      await client.query(
        `INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte)
         VALUES ($1,$2,$3,$4)`,
        [questionId, r.texte_fr, r.texte_ar || null, r.est_correcte]
      );
    }
  }

  console.log(`Seeded ${QUESTIONS_EXTRA2.length} extra questions (batch 2).`);
}
