import { Client } from 'pg';

interface QuestionSeed {
  domaine: string;
  sous_domaine?: string;
  niveau: number;
  madhab: string;
  texte_fr: string;
  texte_ar?: string;
  dalil_ref?: string;
  dalil_texte_ar?: string;
  dalil_texte_fr?: string;
  explication?: string;
  savant_reference?: string;
  grade_hadith?: string;
  reponses: { texte_fr: string; texte_ar?: string; est_correcte: boolean }[];
}

const QUESTIONS_EXTRA5: QuestionSeed[] = [
  // ===================== SALAT (25) =====================
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Combien y a-t-il de prières obligatoires par jour ?',
    texte_ar: 'كم عدد الصلوات المفروضة في اليوم؟',
    explication: "Les cinq prières obligatoires sont : Fajr, Dhuhr, Asr, Maghrib et Isha. Elles ont été prescrites lors du voyage nocturne (Isra wal Mi'raj).",
    reponses: [
      { texte_fr: 'Cinq', est_correcte: true },
      { texte_fr: 'Trois', est_correcte: false },
      { texte_fr: 'Sept', est_correcte: false },
      { texte_fr: 'Quatre', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Combien de rakats compte la prière du Fajr ?',
    texte_ar: 'كم ركعة في صلاة الفجر؟',
    explication: 'La prière obligatoire du Fajr compte 2 rakats, précédées de 2 rakats sunna confirmées.',
    reponses: [
      { texte_fr: '2 rakats', est_correcte: true },
      { texte_fr: '3 rakats', est_correcte: false },
      { texte_fr: '4 rakats', est_correcte: false },
      { texte_fr: '1 rakat', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Combien de rakats compte la prière du Maghrib ?',
    texte_ar: 'كم ركعة في صلاة المغرب؟',
    explication: 'La prière du Maghrib compte 3 rakats obligatoires.',
    reponses: [
      { texte_fr: '3 rakats', est_correcte: true },
      { texte_fr: '2 rakats', est_correcte: false },
      { texte_fr: '4 rakats', est_correcte: false },
      { texte_fr: '5 rakats', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Combien de rakats compte la prière du Dhuhr ?',
    texte_ar: 'كم ركعة في صلاة الظهر؟',
    explication: 'La prière du Dhuhr compte 4 rakats obligatoires.',
    reponses: [
      { texte_fr: '4 rakats', est_correcte: true },
      { texte_fr: '2 rakats', est_correcte: false },
      { texte_fr: '3 rakats', est_correcte: false },
      { texte_fr: '5 rakats', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Vers quelle direction le musulman se tourne-t-il pour prier ?',
    texte_ar: 'إلى أي جهة يتوجه المسلم في الصلاة؟',
    dalil_ref: 'Sourate Al-Baqara 2:144',
    explication: 'Le musulman se tourne vers la Qibla, c\'est-à-dire la Ka\'ba à La Mecque.',
    reponses: [
      { texte_fr: 'La Ka\'ba à La Mecque', est_correcte: true },
      { texte_fr: 'Jérusalem', est_correcte: false },
      { texte_fr: 'Médine', est_correcte: false },
      { texte_fr: 'Le soleil levant', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Quelle sourate doit être récitée dans chaque rakat de la prière ?',
    texte_ar: 'ما السورة التي تُقرأ في كل ركعة؟',
    explication: 'Al-Fatiha doit être récitée dans chaque rakat. Le Prophète ﷺ a dit : "Pas de prière pour celui qui ne récite pas Fatihat al-Kitab" (Bukhari et Muslim).',
    dalil_ref: 'Sahih al-Bukhari 756',
    reponses: [
      { texte_fr: 'Al-Fatiha', est_correcte: true },
      { texte_fr: 'Al-Ikhlas', est_correcte: false },
      { texte_fr: 'Yasin', est_correcte: false },
      { texte_fr: 'Al-Mulk', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Par quelle expression débute-t-on la prière ?',
    texte_ar: 'بأي عبارة تُفتتح الصلاة؟',
    explication: 'La prière débute par le takbir al-ihram : "Allahu Akbar".',
    reponses: [
      { texte_fr: 'Allahu Akbar', est_correcte: true },
      { texte_fr: 'Bismillah', est_correcte: false },
      { texte_fr: 'SubhanAllah', est_correcte: false },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Par quelle expression termine-t-on la prière ?',
    texte_ar: 'بأي عبارة تُختم الصلاة؟',
    explication: 'On termine la prière par le taslim : "As-salamu alaykum wa rahmatullah" à droite puis à gauche.',
    reponses: [
      { texte_fr: 'As-salamu alaykum wa rahmatullah', est_correcte: true },
      { texte_fr: 'Allahu Akbar', est_correcte: false },
      { texte_fr: 'Amin', est_correcte: false },
      { texte_fr: 'Bismillah', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Comment appelle-t-on l\'appel à la prière ?',
    texte_ar: 'ماذا يسمى النداء للصلاة؟',
    explication: 'L\'appel à la prière s\'appelle l\'adhan. Celui qui le prononce est appelé mu\'adhdhin.',
    reponses: [
      { texte_fr: 'Adhan', est_correcte: true },
      { texte_fr: 'Iqama', est_correcte: false },
      { texte_fr: 'Khutba', est_correcte: false },
      { texte_fr: 'Dhikr', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'Quelle prière est accomplie collectivement le vendredi à la place du Dhuhr ?',
    texte_ar: 'ما الصلاة التي تُؤدى جماعة يوم الجمعة بدل الظهر؟',
    explication: 'La prière du Jumu\'a (vendredi) remplace celle du Dhuhr et se compose de 2 rakats précédées d\'un sermon (khutba).',
    dalil_ref: 'Sourate Al-Jumu\'a 62:9',
    reponses: [
      { texte_fr: 'Salat al-Jumu\'a', est_correcte: true },
      { texte_fr: 'Salat al-Witr', est_correcte: false },
      { texte_fr: 'Salat al-Tahajjud', est_correcte: false },
      { texte_fr: 'Salat al-Istikhara', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 1, madhab: 'general',
    texte_fr: 'À quel moment se prie le Fajr ?',
    texte_ar: 'متى تُصلى صلاة الفجر؟',
    explication: 'Le Fajr se prie depuis l\'aube véritable (fajr sadiq) jusqu\'au lever du soleil.',
    reponses: [
      { texte_fr: 'De l\'aube véritable jusqu\'au lever du soleil', est_correcte: true },
      { texte_fr: 'Après le lever du soleil', est_correcte: false },
      { texte_fr: 'À minuit', est_correcte: false },
      { texte_fr: 'Au coucher du soleil', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est la prière surérogatoire de la nuit appelée "qiyam al-layl" ou "tahajjud" ?',
    texte_ar: 'ما هي صلاة قيام الليل أو التهجد؟',
    explication: 'Le tahajjud est une prière nocturne surérogatoire accomplie après s\'être réveillé du sommeil, particulièrement recommandée dans le dernier tiers de la nuit.',
    dalil_ref: 'Sourate Al-Isra 17:79',
    reponses: [
      { texte_fr: 'Prière nocturne après le sommeil, dernier tiers de la nuit', est_correcte: true },
      { texte_fr: 'Prière juste avant le Maghrib', est_correcte: false },
      { texte_fr: 'Prière du milieu de la journée', est_correcte: false },
      { texte_fr: 'Prière collective du vendredi', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Combien y a-t-il de rakats dans la prière du Witr selon la sunna courante ?',
    texte_ar: 'كم ركعة في صلاة الوتر؟',
    explication: 'Le Witr est un nombre impair de rakats, le minimum étant 1 et le maximum 11. La pratique la plus courante est 3 rakats.',
    reponses: [
      { texte_fr: 'Un nombre impair (1, 3, 5, 7, 9 ou 11)', est_correcte: true },
      { texte_fr: 'Toujours 4 rakats', est_correcte: false },
      { texte_fr: 'Toujours 2 rakats', est_correcte: false },
      { texte_fr: 'Toujours 6 rakats', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que la prière de l\'Istikhara ?',
    texte_ar: 'ما هي صلاة الاستخارة؟',
    dalil_ref: 'Sahih al-Bukhari 1162',
    explication: 'L\'Istikhara est une prière de 2 rakats suivie d\'une du\'a spécifique, accomplie pour demander à Allah de guider vers le meilleur choix dans une affaire.',
    reponses: [
      { texte_fr: '2 rakats pour demander la guidance d\'Allah dans une affaire', est_correcte: true },
      { texte_fr: '4 rakats obligatoires avant un voyage', est_correcte: false },
      { texte_fr: 'Une prière funéraire', est_correcte: false },
      { texte_fr: 'Une prière de remerciement', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Combien de rakats sont raccourcies pour le voyageur dans les prières de 4 rakats ?',
    texte_ar: 'كم ركعة يصلي المسافر في الصلوات الرباعية؟',
    dalil_ref: 'Sourate An-Nisa 4:101',
    explication: 'Le voyageur raccourcit les prières de 4 rakats (Dhuhr, Asr, Isha) à 2 rakats (qasr). Le Maghrib et le Fajr ne changent pas.',
    reponses: [
      { texte_fr: '2 rakats au lieu de 4', est_correcte: true },
      { texte_fr: '3 rakats au lieu de 4', est_correcte: false },
      { texte_fr: '1 rakat au lieu de 4', est_correcte: false },
      { texte_fr: 'Aucun raccourcissement n\'est permis', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Que doit-on faire si on oublie un pilier (rukn) dans la prière ?',
    texte_ar: 'ماذا يفعل من نسي ركناً في الصلاة؟',
    explication: 'Si on oublie un pilier, il faut le rattraper. Si on s\'en souvient avant le taslim, on accomplit ce qui manque puis on fait le sujud as-sahw (prosternation d\'oubli).',
    reponses: [
      { texte_fr: 'Rattraper le pilier et faire le sujud as-sahw', est_correcte: true },
      { texte_fr: 'Continuer la prière sans rien faire', est_correcte: false },
      { texte_fr: 'Recommencer la prière dans tous les cas', est_correcte: false },
      { texte_fr: 'Jeûner un jour en expiation', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que la prière du Tarawih ?',
    texte_ar: 'ما هي صلاة التراويح؟',
    explication: 'Le Tarawih est une prière surérogatoire accomplie en groupe pendant les nuits du mois de Ramadan, après la prière de l\'Isha.',
    reponses: [
      { texte_fr: 'Prière surérogatoire des nuits de Ramadan après l\'Isha', est_correcte: true },
      { texte_fr: 'Prière obligatoire du vendredi', est_correcte: false },
      { texte_fr: 'Prière de l\'Aïd', est_correcte: false },
      { texte_fr: 'Prière des deux éclipses', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Quelles sont les conditions de validité (shurut) de la prière ?',
    texte_ar: 'ما شروط صحة الصلاة؟',
    explication: 'Les conditions principales sont : la pureté (taharah), couvrir la awra, l\'entrée du temps de la prière, se diriger vers la Qibla et l\'intention (niyya).',
    reponses: [
      { texte_fr: 'Pureté, awra couverte, temps, Qibla, intention', est_correcte: true },
      { texte_fr: 'Uniquement avoir fait les ablutions', est_correcte: false },
      { texte_fr: 'Réciter le Coran en arabe uniquement', est_correcte: false },
      { texte_fr: 'Prier en groupe obligatoirement', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Que dit-on en se relevant du ruku ?',
    texte_ar: 'ماذا يقال عند الرفع من الركوع؟',
    dalil_ref: 'Sahih al-Bukhari 795',
    explication: 'En se relevant du ruku on dit "Sami\'a Allahu liman hamidah" puis debout "Rabbana wa laka al-hamd".',
    reponses: [
      { texte_fr: 'Sami\'a Allahu liman hamidah, puis Rabbana wa laka al-hamd', est_correcte: true },
      { texte_fr: 'Subhana rabbi al-a\'la', est_correcte: false },
      { texte_fr: 'Allahu akbar uniquement', est_correcte: false },
      { texte_fr: 'Astaghfirullah', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Que récite-t-on dans le ruku (inclinaison) ?',
    texte_ar: 'ماذا يقال في الركوع؟',
    explication: 'Dans le ruku on dit "Subhana rabbiya al-\'adhim" (Gloire à mon Seigneur le Très-Grand), au minimum trois fois.',
    dalil_ref: 'Sunan Abi Dawud 869',
    reponses: [
      { texte_fr: 'Subhana rabbiya al-\'adhim', est_correcte: true },
      { texte_fr: 'Subhana rabbiya al-a\'la', est_correcte: false },
      { texte_fr: 'Rabbi ighfir li', est_correcte: false },
      { texte_fr: 'Allahu akbar kabiran', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 2, madhab: 'general',
    texte_fr: 'Que récite-t-on dans le sujud (prosternation) ?',
    texte_ar: 'ماذا يقال في السجود؟',
    explication: 'Dans le sujud on dit "Subhana rabbiya al-a\'la" (Gloire à mon Seigneur le Très-Haut), au minimum trois fois.',
    reponses: [
      { texte_fr: 'Subhana rabbiya al-a\'la', est_correcte: true },
      { texte_fr: 'Subhana rabbiya al-\'adhim', est_correcte: false },
      { texte_fr: 'La ilaha illa Allah', est_correcte: false },
      { texte_fr: 'Sami\'a Allahu liman hamidah', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 3, madhab: 'general',
    texte_fr: 'Sur combien de membres se fait le sujud (prosternation) ?',
    texte_ar: 'على كم عضو يكون السجود؟',
    dalil_ref: 'Sahih al-Bukhari 812',
    explication: 'Le sujud se fait sur 7 membres : le front (avec le nez), les deux mains, les deux genoux, les pointes des deux pieds.',
    reponses: [
      { texte_fr: '7 membres : front (avec nez), 2 mains, 2 genoux, 2 pieds', est_correcte: true },
      { texte_fr: '3 membres uniquement', est_correcte: false },
      { texte_fr: '5 membres', est_correcte: false },
      { texte_fr: '9 membres', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 3, madhab: 'general',
    texte_fr: 'Qu\'est-ce que le sujud as-sahw (prosternation d\'oubli) ?',
    texte_ar: 'ما هو سجود السهو؟',
    explication: 'C\'est deux prosternations supplémentaires faites avant ou après le taslim pour compenser un oubli, un ajout ou un doute dans la prière.',
    reponses: [
      { texte_fr: 'Deux prosternations pour compenser un oubli ou doute dans la prière', est_correcte: true },
      { texte_fr: 'Une prosternation faite avant la prière', est_correcte: false },
      { texte_fr: 'Trois prosternations en cas de péché', est_correcte: false },
      { texte_fr: 'Une prière de remplacement', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 3, madhab: 'general',
    texte_fr: 'Quel est le mérite de la prière en groupe selon le hadith ?',
    texte_ar: 'ما فضل صلاة الجماعة؟',
    dalil_ref: 'Sahih al-Bukhari 645',
    dalil_texte_ar: 'صَلَاةُ الْجَمَاعَةِ تَفْضُلُ صَلَاةَ الْفَذِّ بِسَبْعٍ وَعِشْرِينَ دَرَجَةً',
    dalil_texte_fr: 'La prière en groupe surpasse la prière individuelle de 27 degrés.',
    explication: 'Le Prophète ﷺ a indiqué que la prière en congrégation vaut 27 degrés de plus que la prière effectuée seul.',
    reponses: [
      { texte_fr: '27 degrés de plus que la prière individuelle', est_correcte: true },
      { texte_fr: '10 degrés de plus', est_correcte: false },
      { texte_fr: '7 degrés de plus', est_correcte: false },
      { texte_fr: 'Aucune différence', est_correcte: false },
    ],
  },
  {
    domaine: 'salat', niveau: 3, madhab: 'general',
    texte_fr: 'Qu\'est-ce que la prière de l\'éclipse (kusuf) ?',
    texte_ar: 'ما هي صلاة الكسوف؟',
    dalil_ref: 'Sahih al-Bukhari 1041',
    explication: 'Lors d\'une éclipse solaire ou lunaire, le Prophète ﷺ accomplissait une prière de 2 rakats particulière avec deux ruku et deux récitations dans chaque rakat.',
    reponses: [
      { texte_fr: '2 rakats avec deux ruku et deux récitations dans chaque rakat', est_correcte: true },
      { texte_fr: '4 rakats normales', est_correcte: false },
      { texte_fr: '3 rakats comme le Maghrib', est_correcte: false },
      { texte_fr: '1 seule rakat', est_correcte: false },
    ],
  },

  // ===================== SAWM (15) =====================
  {
    domaine: 'sawm', niveau: 1, madhab: 'general',
    texte_fr: 'Quel mois lunaire est consacré au jeûne obligatoire ?',
    texte_ar: 'ما الشهر الذي فُرض فيه الصيام؟',
    dalil_ref: 'Sourate Al-Baqara 2:185',
    explication: 'Le mois de Ramadan, le 9e mois du calendrier hijri, est consacré au jeûne obligatoire pour tous les musulmans pubères et capables.',
    reponses: [
      { texte_fr: 'Ramadan', est_correcte: true },
      { texte_fr: 'Sha\'ban', est_correcte: false },
      { texte_fr: 'Muharram', est_correcte: false },
      { texte_fr: 'Dhul-Hijja', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 1, madhab: 'general',
    texte_fr: 'Le jeûne du Ramadan commence à quelle heure ?',
    texte_ar: 'متى يبدأ صيام رمضان في اليوم؟',
    explication: 'Le jeûne débute à l\'aube véritable (fajr sadiq) et se termine au coucher du soleil (maghrib).',
    reponses: [
      { texte_fr: 'À l\'aube véritable (fajr sadiq)', est_correcte: true },
      { texte_fr: 'Au lever du soleil', est_correcte: false },
      { texte_fr: 'À minuit', est_correcte: false },
      { texte_fr: 'À midi', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 1, madhab: 'general',
    texte_fr: 'Comment appelle-t-on le repas du soir qui rompt le jeûne ?',
    texte_ar: 'ماذا يسمى الطعام الذي يُفطر به الصائم؟',
    explication: 'Le repas qui rompt le jeûne au coucher du soleil s\'appelle l\'iftar. Le repas pris avant l\'aube s\'appelle le suhur.',
    reponses: [
      { texte_fr: 'Iftar', est_correcte: true },
      { texte_fr: 'Suhur', est_correcte: false },
      { texte_fr: 'Sahur', est_correcte: false },
      { texte_fr: 'Aïd', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 1, madhab: 'general',
    texte_fr: 'Comment appelle-t-on le repas pris avant l\'aube pendant le Ramadan ?',
    texte_ar: 'ماذا يسمى الطعام قبل الفجر في رمضان؟',
    dalil_ref: 'Sahih al-Bukhari 1923',
    explication: 'Le repas pris avant l\'aube s\'appelle le suhur. Le Prophète ﷺ a dit : "Prenez le suhur, car il y a une bénédiction dans le suhur".',
    reponses: [
      { texte_fr: 'Suhur', est_correcte: true },
      { texte_fr: 'Iftar', est_correcte: false },
      { texte_fr: 'Walima', est_correcte: false },
      { texte_fr: 'Aqiqa', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 1, madhab: 'general',
    texte_fr: 'Qu\'est-ce qui rompt le jeûne ?',
    texte_ar: 'ما الذي يُفطر الصائم؟',
    explication: 'Le jeûne est rompu par : manger ou boire intentionnellement, les rapports conjugaux, les menstruations/lochies, et les vomissements provoqués volontairement.',
    reponses: [
      { texte_fr: 'Manger ou boire intentionnellement, rapports conjugaux, règles', est_correcte: true },
      { texte_fr: 'Parler durant la journée', est_correcte: false },
      { texte_fr: 'Se brosser les dents avec un siwak', est_correcte: false },
      { texte_fr: 'Sentir un parfum', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 1, madhab: 'general',
    texte_fr: 'Quelle nuit du Ramadan est appelée "la nuit du Destin" ?',
    texte_ar: 'ما الليلة المسماة ليلة القدر؟',
    dalil_ref: 'Sourate Al-Qadr 97',
    explication: 'Laylat al-Qadr est meilleure que mille mois. Elle est recherchée dans les nuits impaires des dix dernières nuits du Ramadan.',
    reponses: [
      { texte_fr: 'Laylat al-Qadr', est_correcte: true },
      { texte_fr: 'Laylat al-Isra', est_correcte: false },
      { texte_fr: 'Laylat al-Bara\'a', est_correcte: false },
      { texte_fr: 'Laylat al-Miraj', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Qui est dispensé du jeûne du Ramadan ?',
    texte_ar: 'من يُعفى من صيام رمضان؟',
    dalil_ref: 'Sourate Al-Baqara 2:184',
    explication: 'Sont dispensés (avec rattrapage ou expiation selon le cas) : le malade, le voyageur, la femme enceinte ou allaitante si elle craint pour elle ou son enfant, la femme en menstrues, le vieillard incapable.',
    reponses: [
      { texte_fr: 'Le malade, le voyageur, la femme enceinte/allaitante, le vieillard incapable', est_correcte: true },
      { texte_fr: 'Uniquement les enfants', est_correcte: false },
      { texte_fr: 'Personne n\'est dispensé', est_correcte: false },
      { texte_fr: 'Uniquement les voyageurs', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que l\'i\'tikaf ?',
    texte_ar: 'ما هو الاعتكاف؟',
    explication: 'L\'i\'tikaf est la retraite spirituelle en mosquée pour adorer Allah, particulièrement recommandée dans les dix derniers jours du Ramadan, pratique du Prophète ﷺ.',
    dalil_ref: 'Sahih al-Bukhari 2025',
    reponses: [
      { texte_fr: 'Retraite spirituelle en mosquée, surtout les 10 derniers jours du Ramadan', est_correcte: true },
      { texte_fr: 'Voyage pour visiter La Mecque', est_correcte: false },
      { texte_fr: 'Aumône donnée à la fin du Ramadan', est_correcte: false },
      { texte_fr: 'Jeûne ininterrompu de plusieurs jours', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Quels sont les jours où il est interdit de jeûner ?',
    texte_ar: 'ما الأيام التي يحرم صيامها؟',
    dalil_ref: 'Sahih al-Bukhari 1990',
    explication: 'Il est interdit de jeûner les jours des deux Aïd (Aïd al-Fitr et Aïd al-Adha) ainsi que les jours du Tashriq (11, 12, 13 Dhul-Hijja).',
    reponses: [
      { texte_fr: 'Les jours des deux Aïd et les jours du Tashriq', est_correcte: true },
      { texte_fr: 'Tous les vendredis', est_correcte: false },
      { texte_fr: 'Le premier jour de chaque mois lunaire', est_correcte: false },
      { texte_fr: 'Aucun jour n\'est interdit', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le jeûne surérogatoire hebdomadaire recommandé ?',
    texte_ar: 'ما الصيام المستحب أسبوعياً؟',
    dalil_ref: 'Sahih Muslim 1162',
    explication: 'Le Prophète ﷺ jeûnait habituellement le lundi et le jeudi, car les actions sont présentées à Allah ces jours-là.',
    reponses: [
      { texte_fr: 'Le lundi et le jeudi', est_correcte: true },
      { texte_fr: 'Le samedi et le dimanche', est_correcte: false },
      { texte_fr: 'Le vendredi seul', est_correcte: false },
      { texte_fr: 'Le mercredi seul', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que le jeûne des "Ayyam al-Bid" ?',
    texte_ar: 'ما هي صيام أيام البيض؟',
    explication: 'Les Ayyam al-Bid (jours blancs) sont les 13, 14 et 15 de chaque mois lunaire. Le Prophète ﷺ recommandait de les jeûner.',
    dalil_ref: 'Sunan an-Nasa\'i 2422',
    reponses: [
      { texte_fr: 'Les 13, 14 et 15 de chaque mois lunaire', est_correcte: true },
      { texte_fr: 'Les trois premiers jours du Ramadan', est_correcte: false },
      { texte_fr: 'Les vendredis du mois de Sha\'ban', est_correcte: false },
      { texte_fr: 'Les 10 premiers jours de Dhul-Hijja', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le mérite du jeûne du jour d\'Arafa pour celui qui n\'est pas en pèlerinage ?',
    texte_ar: 'ما فضل صيام يوم عرفة لغير الحاج؟',
    dalil_ref: 'Sahih Muslim 1162',
    explication: 'Le Prophète ﷺ a dit que le jeûne du jour d\'Arafa expie les péchés de l\'année précédente et de l\'année suivante.',
    reponses: [
      { texte_fr: 'Il expie les péchés de l\'année précédente et de l\'année suivante', est_correcte: true },
      { texte_fr: 'Il garantit l\'entrée au Paradis sans jugement', est_correcte: false },
      { texte_fr: 'Il remplace les cinq prières quotidiennes', est_correcte: false },
      { texte_fr: 'Il vaut le pèlerinage', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le mérite du jeûne d\'\'Achoura ?',
    texte_ar: 'ما فضل صيام يوم عاشوراء؟',
    dalil_ref: 'Sahih Muslim 1162',
    explication: 'Le Prophète ﷺ a dit que le jeûne du jour d\'Achoura (10 Muharram) expie les péchés de l\'année écoulée.',
    reponses: [
      { texte_fr: 'Il expie les péchés de l\'année écoulée', est_correcte: true },
      { texte_fr: 'Il garantit la pluie pour l\'année', est_correcte: false },
      { texte_fr: 'Il remplace le jeûne du Ramadan', est_correcte: false },
      { texte_fr: 'Il est interdit', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 3, madhab: 'general',
    texte_fr: 'Que doit faire celui qui rompt délibérément le jeûne du Ramadan par un rapport conjugal ?',
    texte_ar: 'ما كفارة من جامع في نهار رمضان متعمداً؟',
    dalil_ref: 'Sahih al-Bukhari 1936',
    explication: 'L\'expiation (kaffara) est : affranchir un esclave, sinon jeûner 60 jours consécutifs, sinon nourrir 60 pauvres. Il doit aussi rattraper le jour.',
    reponses: [
      { texte_fr: 'Affranchir un esclave, sinon 60 jours de jeûne, sinon nourrir 60 pauvres', est_correcte: true },
      { texte_fr: 'Donner une simple aumône', est_correcte: false },
      { texte_fr: 'Rattraper uniquement le jour manqué', est_correcte: false },
      { texte_fr: 'Faire le pèlerinage à La Mecque', est_correcte: false },
    ],
  },
  {
    domaine: 'sawm', niveau: 3, madhab: 'general',
    texte_fr: 'Quel est le statut du jeûne de 6 jours en Shawwal ?',
    texte_ar: 'ما حكم صيام ست من شوال؟',
    dalil_ref: 'Sahih Muslim 1164',
    explication: 'Le Prophète ﷺ a dit : "Quiconque jeûne le Ramadan puis le fait suivre de six jours en Shawwal, c\'est comme s\'il avait jeûné toute l\'année".',
    reponses: [
      { texte_fr: 'Recommandé : équivaut au jeûne de toute l\'année', est_correcte: true },
      { texte_fr: 'Obligatoire pour tous', est_correcte: false },
      { texte_fr: 'Interdit', est_correcte: false },
      { texte_fr: 'Sans aucune récompense particulière', est_correcte: false },
    ],
  },

  // ===================== ZAKAT (10) =====================
  {
    domaine: 'zakat', niveau: 1, madhab: 'general',
    texte_fr: 'La zakat fait-elle partie des piliers de l\'Islam ?',
    texte_ar: 'هل الزكاة من أركان الإسلام؟',
    explication: 'Oui, la zakat est le 3e pilier de l\'Islam, après la shahada et la salat.',
    reponses: [
      { texte_fr: 'Oui, c\'est le 3e pilier', est_correcte: true },
      { texte_fr: 'Non, c\'est seulement recommandé', est_correcte: false },
      { texte_fr: 'C\'est un acte facultatif', est_correcte: false },
      { texte_fr: 'C\'est uniquement pour les riches volontaires', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 1, madhab: 'general',
    texte_fr: 'Qu\'est-ce que la zakat al-fitr ?',
    texte_ar: 'ما هي زكاة الفطر؟',
    dalil_ref: 'Sahih al-Bukhari 1503',
    explication: 'La zakat al-fitr est une aumône obligatoire donnée à la fin du Ramadan, avant la prière de l\'Aïd al-Fitr, pour chaque musulman (homme, femme, enfant, libre, esclave).',
    reponses: [
      { texte_fr: 'Aumône obligatoire à la fin du Ramadan avant l\'Aïd', est_correcte: true },
      { texte_fr: 'Aumône volontaire de tous les jours', est_correcte: false },
      { texte_fr: 'Impôt prélevé par l\'État', est_correcte: false },
      { texte_fr: 'Don au début du Ramadan uniquement', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le taux de la zakat sur l\'or, l\'argent et la monnaie ?',
    texte_ar: 'ما نسبة الزكاة على الذهب والفضة والنقود؟',
    explication: 'Le taux de la zakat sur l\'or, l\'argent et l\'argent monétaire est de 2,5% (1/40) de la valeur, une fois le nisab atteint et après un an lunaire (hawl).',
    reponses: [
      { texte_fr: '2,5% (1/40)', est_correcte: true },
      { texte_fr: '10%', est_correcte: false },
      { texte_fr: '5%', est_correcte: false },
      { texte_fr: '20%', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que le "nisab" ?',
    texte_ar: 'ما هو النصاب؟',
    explication: 'Le nisab est le seuil minimum de richesse à partir duquel la zakat devient obligatoire. Pour l\'argent, il équivaut à 85g d\'or ou 595g d\'argent.',
    reponses: [
      { texte_fr: 'Le seuil minimum de richesse rendant la zakat obligatoire', est_correcte: true },
      { texte_fr: 'Le montant maximum permis de richesse', est_correcte: false },
      { texte_fr: 'Le nom du collecteur de la zakat', est_correcte: false },
      { texte_fr: 'Le jour du paiement de la zakat', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est la durée minimale de possession du nisab pour devoir la zakat (hawl) ?',
    texte_ar: 'ما هي مدة الحول لوجوب الزكاة؟',
    explication: 'Le hawl est d\'une année lunaire complète (environ 354 jours). Sauf pour les récoltes agricoles, où la zakat est due à la récolte.',
    reponses: [
      { texte_fr: 'Une année lunaire complète', est_correcte: true },
      { texte_fr: 'Six mois', est_correcte: false },
      { texte_fr: 'Trois mois', est_correcte: false },
      { texte_fr: 'Aucune durée requise', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 2, madhab: 'general',
    texte_fr: 'Combien y a-t-il de catégories de bénéficiaires de la zakat selon le Coran ?',
    texte_ar: 'كم عدد مصارف الزكاة في القرآن؟',
    dalil_ref: 'Sourate At-Tawba 9:60',
    explication: 'Le Coran mentionne 8 catégories : pauvres, nécessiteux, collecteurs, ceux dont les cœurs sont à rallier, esclaves à affranchir, endettés, dans la voie d\'Allah, voyageurs.',
    reponses: [
      { texte_fr: '8 catégories', est_correcte: true },
      { texte_fr: '5 catégories', est_correcte: false },
      { texte_fr: '3 catégories', est_correcte: false },
      { texte_fr: '10 catégories', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 2, madhab: 'general',
    texte_fr: 'À qui la zakat ne peut-elle PAS être donnée ?',
    texte_ar: 'لمن لا تجوز الزكاة؟',
    explication: 'La zakat ne peut être donnée aux Banu Hashim (descendants de Hashim, famille du Prophète), aux riches capables, ni aux ascendants/descendants directs de celui qui la donne.',
    reponses: [
      { texte_fr: 'Aux Banu Hashim, aux riches, et aux ascendants/descendants directs', est_correcte: true },
      { texte_fr: 'Aux pauvres seulement', est_correcte: false },
      { texte_fr: 'Aux voyageurs', est_correcte: false },
      { texte_fr: 'Aux endettés', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est la quantité de la zakat al-fitr par personne ?',
    texte_ar: 'ما مقدار زكاة الفطر؟',
    dalil_ref: 'Sahih al-Bukhari 1503',
    explication: 'Un sa\' (environ 2,5 à 3 kg) de la nourriture courante : dattes, orge, blé, riz, etc. Selon les Hanafis, on peut donner sa valeur monétaire.',
    reponses: [
      { texte_fr: 'Un sa\' (environ 2,5 à 3 kg) de nourriture courante', est_correcte: true },
      { texte_fr: 'Un dinar d\'or', est_correcte: false },
      { texte_fr: '10 kg de céréales', est_correcte: false },
      { texte_fr: 'Aucune quantité fixe', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 3, madhab: 'general',
    texte_fr: 'Quel est le nisab de l\'or ?',
    texte_ar: 'ما نصاب الذهب؟',
    explication: 'Le nisab de l\'or est de 20 dinars, équivalant à environ 85 grammes d\'or pur.',
    reponses: [
      { texte_fr: '20 dinars (environ 85g d\'or pur)', est_correcte: true },
      { texte_fr: '200 dinars', est_correcte: false },
      { texte_fr: '40 dinars', est_correcte: false },
      { texte_fr: '10 dinars', est_correcte: false },
    ],
  },
  {
    domaine: 'zakat', niveau: 3, madhab: 'general',
    texte_fr: 'Quel est le nisab de l\'argent ?',
    texte_ar: 'ما نصاب الفضة؟',
    explication: 'Le nisab de l\'argent est de 200 dirhams, équivalant à environ 595 grammes d\'argent pur.',
    reponses: [
      { texte_fr: '200 dirhams (environ 595g d\'argent pur)', est_correcte: true },
      { texte_fr: '20 dirhams', est_correcte: false },
      { texte_fr: '100 dirhams', est_correcte: false },
      { texte_fr: '500 dirhams', est_correcte: false },
    ],
  },

  // ===================== HAJJ/UMRAH (15) =====================
  {
    domaine: 'hajj', niveau: 1, madhab: 'general',
    texte_fr: 'Combien de fois le Hajj est-il obligatoire dans une vie ?',
    texte_ar: 'كم مرة يجب الحج في العمر؟',
    explication: 'Le Hajj est obligatoire une seule fois dans la vie, pour celui qui en a la capacité physique et financière.',
    dalil_ref: 'Sourate Aal Imran 3:97',
    reponses: [
      { texte_fr: 'Une seule fois pour celui qui en a la capacité', est_correcte: true },
      { texte_fr: 'Chaque année', est_correcte: false },
      { texte_fr: 'Cinq fois dans la vie', est_correcte: false },
      { texte_fr: 'Tous les dix ans', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 1, madhab: 'general',
    texte_fr: 'Dans quel mois lunaire se déroule le Hajj ?',
    texte_ar: 'في أي شهر يكون الحج؟',
    explication: 'Le Hajj se déroule pendant le mois de Dhul-Hijja, le 12e mois du calendrier hijri.',
    reponses: [
      { texte_fr: 'Dhul-Hijja', est_correcte: true },
      { texte_fr: 'Ramadan', est_correcte: false },
      { texte_fr: 'Muharram', est_correcte: false },
      { texte_fr: 'Rajab', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 1, madhab: 'general',
    texte_fr: 'Qu\'est-ce que l\'ihram ?',
    texte_ar: 'ما هو الإحرام؟',
    explication: 'L\'ihram est l\'état de sacralisation que le pèlerin entreprend pour effectuer le Hajj ou la Umrah, marqué par des vêtements spécifiques (deux pièces blanches non cousues pour les hommes) et des interdictions.',
    reponses: [
      { texte_fr: 'État de sacralisation pour le Hajj ou la Umrah avec vêtements spécifiques', est_correcte: true },
      { texte_fr: 'Une prière particulière de La Mecque', est_correcte: false },
      { texte_fr: 'Le sermon final du Prophète ﷺ', est_correcte: false },
      { texte_fr: 'Le sacrifice de l\'Aïd', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 1, madhab: 'general',
    texte_fr: 'Qu\'est-ce que le tawaf ?',
    texte_ar: 'ما هو الطواف؟',
    explication: 'Le tawaf est la circumambulation de la Ka\'ba, sept tours dans le sens inverse des aiguilles d\'une montre, en débutant par la Pierre Noire.',
    reponses: [
      { texte_fr: 'Sept tours autour de la Ka\'ba', est_correcte: true },
      { texte_fr: 'Course entre Safa et Marwa', est_correcte: false },
      { texte_fr: 'Lapidation des stèles à Mina', est_correcte: false },
      { texte_fr: 'Station à Arafa', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 1, madhab: 'general',
    texte_fr: 'Qu\'est-ce que le sa\'i ?',
    texte_ar: 'ما هو السعي؟',
    explication: 'Le sa\'i est la marche/course entre les collines de Safa et Marwa, sept allers-retours, en commémoration du parcours de Hajar (femme d\'Ibrahim) cherchant de l\'eau pour son fils Isma\'il.',
    reponses: [
      { texte_fr: 'Sept allers-retours entre Safa et Marwa', est_correcte: true },
      { texte_fr: 'Sept tours autour de la Ka\'ba', est_correcte: false },
      { texte_fr: 'Sept jets de pierres sur les stèles', est_correcte: false },
      { texte_fr: 'Sept prières surérogatoires', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le jour le plus important du Hajj ?',
    texte_ar: 'ما أعظم يوم في الحج؟',
    dalil_ref: 'Sahih Muslim 1218',
    explication: 'Le jour d\'Arafa (9 Dhul-Hijja) est le jour le plus important. Le Prophète ﷺ a dit : "Le Hajj, c\'est Arafa".',
    reponses: [
      { texte_fr: 'Le jour d\'Arafa (9 Dhul-Hijja)', est_correcte: true },
      { texte_fr: 'Le jour de l\'Aïd al-Adha', est_correcte: false },
      { texte_fr: 'Le 1er Dhul-Hijja', est_correcte: false },
      { texte_fr: 'Le dernier jour du Hajj', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que la station à Arafa (wuquf) ?',
    texte_ar: 'ما هو الوقوف بعرفة؟',
    explication: 'Le wuquf à Arafa est de se tenir sur la plaine d\'Arafa le 9 Dhul-Hijja, de midi au coucher du soleil, dans l\'invocation et la méditation. C\'est le pilier essentiel du Hajj.',
    reponses: [
      { texte_fr: 'Se tenir à Arafa le 9 Dhul-Hijja, pilier essentiel du Hajj', est_correcte: true },
      { texte_fr: 'Camper à Mina pendant 3 jours', est_correcte: false },
      { texte_fr: 'Boire de l\'eau de Zamzam', est_correcte: false },
      { texte_fr: 'Toucher la Pierre Noire', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: 'Où se déroule la lapidation des stèles (jamarat) ?',
    texte_ar: 'أين يكون رمي الجمرات؟',
    explication: 'La lapidation des trois stèles (jamarat) se déroule à Mina, durant les jours du Tashriq.',
    reponses: [
      { texte_fr: 'À Mina', est_correcte: true },
      { texte_fr: 'À Arafa', est_correcte: false },
      { texte_fr: 'À Muzdalifa', est_correcte: false },
      { texte_fr: 'À La Mecque', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que la Umrah ?',
    texte_ar: 'ما هي العمرة؟',
    explication: 'La Umrah est le petit pèlerinage, comprenant l\'ihram, le tawaf, le sa\'i et le rasage/raccourcissement des cheveux. Elle peut se faire à tout moment de l\'année.',
    reponses: [
      { texte_fr: 'Petit pèlerinage à La Mecque, possible toute l\'année', est_correcte: true },
      { texte_fr: 'Pèlerinage obligatoire annuel', est_correcte: false },
      { texte_fr: 'Visite à la mosquée du Prophète à Médine', est_correcte: false },
      { texte_fr: 'Sacrifice du jour de l\'Aïd', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: 'Quelles sont les conditions du Hajj ?',
    texte_ar: 'ما شروط وجوب الحج؟',
    explication: 'Les conditions sont : être musulman, pubère, sain d\'esprit, libre et avoir la capacité (istita\'a) physique et financière.',
    dalil_ref: 'Sourate Aal Imran 3:97',
    reponses: [
      { texte_fr: 'Islam, puberté, raison, liberté, capacité physique et financière', est_correcte: true },
      { texte_fr: 'Uniquement la capacité financière', est_correcte: false },
      { texte_fr: 'Avoir plus de 40 ans', est_correcte: false },
      { texte_fr: 'Avoir déjà fait la Umrah', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 2, madhab: 'general',
    texte_fr: 'Qu\'est-ce que Muzdalifa ?',
    texte_ar: 'ما هي المزدلفة؟',
    explication: 'Muzdalifa est un lieu situé entre Arafa et Mina, où les pèlerins passent la nuit du 9 au 10 Dhul-Hijja après la station d\'Arafa, prient Maghrib et Isha groupées, et collectent les cailloux pour la lapidation.',
    reponses: [
      { texte_fr: 'Lieu entre Arafa et Mina où les pèlerins passent la nuit du 9 au 10', est_correcte: true },
      { texte_fr: 'Petite mosquée à La Mecque', est_correcte: false },
      { texte_fr: 'Une des stèles à lapider', est_correcte: false },
      { texte_fr: 'Le puits de Zamzam', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 3, madhab: 'general',
    texte_fr: 'Quels sont les trois types de Hajj ?',
    texte_ar: 'ما أنواع الحج الثلاثة؟',
    explication: 'Les trois types sont : Tamattu\' (Umrah puis Hajj avec libération de l\'ihram entre les deux), Qiran (Umrah et Hajj ensemble sous un même ihram), Ifrad (Hajj seul sans Umrah).',
    reponses: [
      { texte_fr: 'Tamattu\', Qiran et Ifrad', est_correcte: true },
      { texte_fr: 'Sunna, wajib et fard', est_correcte: false },
      { texte_fr: 'Mecque, Médine et Jérusalem', est_correcte: false },
      { texte_fr: 'Petit, moyen et grand Hajj', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 3, madhab: 'general',
    texte_fr: 'Qu\'est-ce que les "miqat" ?',
    texte_ar: 'ما هي المواقيت؟',
    explication: 'Les miqat sont les points géographiques où le pèlerin doit entrer en état d\'ihram avant de pénétrer dans la zone sacrée. Il existe 5 miqat principaux fixés par le Prophète ﷺ.',
    dalil_ref: 'Sahih al-Bukhari 1524',
    reponses: [
      { texte_fr: 'Les points géographiques où entrer en état d\'ihram', est_correcte: true },
      { texte_fr: 'Les heures de prière à La Mecque', est_correcte: false },
      { texte_fr: 'Les jours du Hajj', est_correcte: false },
      { texte_fr: 'Les types de sacrifices possibles', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 3, madhab: 'general',
    texte_fr: 'Qu\'est-ce que le "tawaf al-ifada" ?',
    texte_ar: 'ما هو طواف الإفاضة؟',
    explication: 'Le tawaf al-ifada est le tawaf accompli après être descendu d\'Arafa, le jour de l\'Aïd al-Adha. C\'est un pilier (rukn) du Hajj sans lequel le Hajj n\'est pas complet.',
    reponses: [
      { texte_fr: 'Tawaf accompli le jour de l\'Aïd, pilier du Hajj', est_correcte: true },
      { texte_fr: 'Tawaf d\'adieu avant de quitter La Mecque', est_correcte: false },
      { texte_fr: 'Tawaf à l\'arrivée à La Mecque', est_correcte: false },
      { texte_fr: 'Tawaf surérogatoire libre', est_correcte: false },
    ],
  },
  {
    domaine: 'hajj', niveau: 3, madhab: 'general',
    texte_fr: 'Que dit le pèlerin lors de la talbiya ?',
    texte_ar: 'ماذا يقول الحاج في التلبية؟',
    dalil_ref: 'Sahih al-Bukhari 1549',
    dalil_texte_ar: 'لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ',
    explication: 'La talbiya est la formule récitée par le pèlerin : "Labbayka Allahumma labbayk, labbayka la sharika laka labbayk, inna al-hamda wa an-ni\'mata laka wa al-mulk, la sharika lak".',
    reponses: [
      { texte_fr: 'Labbayka Allahumma labbayk... (formule de réponse à l\'appel)', est_correcte: true },
      { texte_fr: 'Allahu akbar uniquement', est_correcte: false },
      { texte_fr: 'Bismillah ar-rahman ar-rahim', est_correcte: false },
      { texte_fr: 'La ilaha illa Allah', est_correcte: false },
    ],
  },

  // ===================== ADKAR & DU'A (20) =====================
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on en commençant un repas ?',
    texte_ar: 'ماذا يقال عند بدء الطعام؟',
    dalil_ref: 'Sunan Abi Dawud 3767',
    explication: 'Avant de manger, on dit "Bismillah". Si on oublie au début, on dit "Bismillah awwalahu wa akhirah".',
    reponses: [
      { texte_fr: 'Bismillah', est_correcte: true },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
      { texte_fr: 'Allahu akbar', est_correcte: false },
      { texte_fr: 'Astaghfirullah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on après avoir fini un repas ?',
    texte_ar: 'ماذا يقال بعد انتهاء الطعام؟',
    dalil_ref: 'Sunan Abi Dawud 4023',
    explication: 'Après le repas, on dit "Alhamdulillah" (la louange est à Allah). Une formule plus complète est rapportée du Prophète ﷺ.',
    reponses: [
      { texte_fr: 'Alhamdulillah', est_correcte: true },
      { texte_fr: 'Bismillah', est_correcte: false },
      { texte_fr: 'Subhan Allah', est_correcte: false },
      { texte_fr: 'La hawla wa la quwwata illa billah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on en entrant aux toilettes ?',
    texte_ar: 'ماذا يقال عند دخول الخلاء؟',
    dalil_ref: 'Sahih al-Bukhari 142',
    dalil_texte_ar: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    explication: 'Le Prophète ﷺ disait en entrant aux toilettes : "Allahumma inni a\'udhu bika min al-khubuthi wa al-khaba\'ith" (Ô Allah, je me réfugie auprès de Toi contre les démons mâles et femelles).',
    reponses: [
      { texte_fr: 'Allahumma inni a\'udhu bika min al-khubuthi wa al-khaba\'ith', est_correcte: true },
      { texte_fr: 'Bismillah', est_correcte: false },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
      { texte_fr: 'Ghufranak', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on en sortant des toilettes ?',
    texte_ar: 'ماذا يقال عند الخروج من الخلاء؟',
    dalil_ref: 'Sunan at-Tirmidhi 7',
    explication: 'En sortant des toilettes, on dit "Ghufranak" (Je demande Ton pardon).',
    reponses: [
      { texte_fr: 'Ghufranak', est_correcte: true },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
      { texte_fr: 'Subhan Allah', est_correcte: false },
      { texte_fr: 'Bismillah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on en éternuant ?',
    texte_ar: 'ماذا يقال عند العطاس؟',
    dalil_ref: 'Sahih al-Bukhari 6224',
    explication: 'Celui qui éternue dit "Alhamdulillah". Celui qui l\'entend dit "Yarhamuka Allah". L\'éternueur répond "Yahdikumu Allah wa yuslihu balakum".',
    reponses: [
      { texte_fr: 'Alhamdulillah', est_correcte: true },
      { texte_fr: 'Bismillah', est_correcte: false },
      { texte_fr: 'SubhanAllah', est_correcte: false },
      { texte_fr: 'La ilaha illa Allah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que répond-on à celui qui éternue et dit "Alhamdulillah" ?',
    texte_ar: 'بماذا يُرد على من عطس وحمد الله؟',
    dalil_ref: 'Sahih al-Bukhari 6224',
    explication: 'On lui dit "Yarhamuka Allah" (Qu\'Allah te fasse miséricorde).',
    reponses: [
      { texte_fr: 'Yarhamuka Allah', est_correcte: true },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
      { texte_fr: 'Astaghfirullah', est_correcte: false },
      { texte_fr: 'Wa alaykum as-salam', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Quelle est la formule de salutation islamique ?',
    texte_ar: 'ما تحية الإسلام؟',
    explication: 'La salutation islamique est "As-salamu alaykum wa rahmatullahi wa barakatuh" (Que la paix, la miséricorde et la bénédiction d\'Allah soient sur vous).',
    reponses: [
      { texte_fr: 'As-salamu alaykum wa rahmatullahi wa barakatuh', est_correcte: true },
      { texte_fr: 'Bismillah ar-rahman ar-rahim', est_correcte: false },
      { texte_fr: 'Marhaban bikum', est_correcte: false },
      { texte_fr: 'Ahlan wa sahlan', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on en entrant dans la mosquée ?',
    texte_ar: 'ماذا يقال عند دخول المسجد؟',
    dalil_ref: 'Sahih Muslim 713',
    explication: 'En entrant à la mosquée, on entre du pied droit en disant "Bismillah wa as-salatu wa as-salamu \'ala Rasulillah, Allahumma iftah li abwaba rahmatik".',
    reponses: [
      { texte_fr: 'Allahumma iftah li abwaba rahmatik', est_correcte: true },
      { texte_fr: 'Allahumma inni as\'aluka min fadlik', est_correcte: false },
      { texte_fr: 'Bismillah uniquement', est_correcte: false },
      { texte_fr: 'Aucun dhikr spécifique', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que dit-on en sortant de la mosquée ?',
    texte_ar: 'ماذا يقال عند الخروج من المسجد؟',
    dalil_ref: 'Sahih Muslim 713',
    explication: 'En sortant de la mosquée, on sort du pied gauche en disant "Allahumma inni as\'aluka min fadlik" (Ô Allah, je Te demande de Ta grâce).',
    reponses: [
      { texte_fr: 'Allahumma inni as\'aluka min fadlik', est_correcte: true },
      { texte_fr: 'Allahumma iftah li abwaba rahmatik', est_correcte: false },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
      { texte_fr: 'Allahu akbar', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 1, madhab: 'general',
    texte_fr: 'Que signifie "InshaAllah" ?',
    texte_ar: 'ما معنى "إن شاء الله"؟',
    dalil_ref: 'Sourate Al-Kahf 18:23-24',
    explication: 'InshaAllah signifie "si Allah le veut". Il est recommandé de le dire en parlant de toute action future.',
    reponses: [
      { texte_fr: 'Si Allah le veut', est_correcte: true },
      { texte_fr: 'Allah est le plus grand', est_correcte: false },
      { texte_fr: 'Allah me suffit', est_correcte: false },
      { texte_fr: 'Allah a décrété', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Combien de fois récite-t-on "SubhanAllah", "Alhamdulillah" et "Allahu akbar" après la prière ?',
    texte_ar: 'كم مرة يقال سبحان الله والحمد لله والله أكبر بعد الصلاة؟',
    dalil_ref: 'Sahih Muslim 597',
    explication: 'Le Prophète ﷺ a recommandé de dire après chaque prière : SubhanAllah 33 fois, Alhamdulillah 33 fois, Allahu akbar 33 fois, complétés par "La ilaha illa Allah wahdahu la sharika lah..." pour atteindre 100.',
    reponses: [
      { texte_fr: '33 fois chacun (puis tahlil pour 100)', est_correcte: true },
      { texte_fr: '10 fois chacun', est_correcte: false },
      { texte_fr: '100 fois chacun', est_correcte: false },
      { texte_fr: '7 fois chacun', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Quel dhikr est le meilleur selon le hadith ?',
    texte_ar: 'ما أفضل الذكر؟',
    dalil_ref: 'Sunan at-Tirmidhi 3383',
    explication: 'Le Prophète ﷺ a dit : "Le meilleur dhikr est : La ilaha illa Allah".',
    reponses: [
      { texte_fr: 'La ilaha illa Allah', est_correcte: true },
      { texte_fr: 'Alhamdulillah', est_correcte: false },
      { texte_fr: 'Allahu akbar', est_correcte: false },
      { texte_fr: 'Astaghfirullah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est la formule "kalimat at-tawhid" ?',
    texte_ar: 'ما هي كلمة التوحيد؟',
    explication: 'La kalimat at-tawhid est : "La ilaha illa Allah" (Il n\'y a de divinité [digne d\'adoration] qu\'Allah).',
    reponses: [
      { texte_fr: 'La ilaha illa Allah', est_correcte: true },
      { texte_fr: 'Muhammad rasul Allah', est_correcte: false },
      { texte_fr: 'Bismillah ar-rahman ar-rahim', est_correcte: false },
      { texte_fr: 'Alhamdulillah rabbi al-\'alamin', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Que dit-on lorsqu\'une calamité ou une mort survient ?',
    texte_ar: 'ماذا يقال عند المصيبة؟',
    dalil_ref: 'Sourate Al-Baqara 2:156',
    dalil_texte_ar: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
    dalil_texte_fr: 'Certes nous appartenons à Allah et c\'est à Lui que nous retournerons.',
    explication: 'On dit "Inna lillahi wa inna ilayhi raji\'un" lors d\'une épreuve, particulièrement à l\'annonce d\'un décès.',
    reponses: [
      { texte_fr: 'Inna lillahi wa inna ilayhi raji\'un', est_correcte: true },
      { texte_fr: 'Astaghfirullah', est_correcte: false },
      { texte_fr: 'La hawla wa la quwwata illa billah', est_correcte: false },
      { texte_fr: 'MashaAllah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Quelles sourates sont récitées le matin et le soir comme protection ?',
    texte_ar: 'ما السور التي تُقرأ صباحاً ومساءً للحفظ؟',
    dalil_ref: 'Sunan Abi Dawud 5082',
    explication: 'Les "mu\'awwidhat" : Sourate Al-Ikhlas, Al-Falaq et An-Nas, trois fois chacune le matin et le soir, sont une protection.',
    reponses: [
      { texte_fr: 'Al-Ikhlas, Al-Falaq et An-Nas', est_correcte: true },
      { texte_fr: 'Yasin uniquement', est_correcte: false },
      { texte_fr: 'Al-Mulk uniquement', est_correcte: false },
      { texte_fr: 'Al-Fatiha uniquement', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Quel verset est appelé le verset du Trône ?',
    texte_ar: 'ما هي آية الكرسي؟',
    dalil_ref: 'Sourate Al-Baqara 2:255',
    explication: 'Ayat al-Kursi est le verset 255 de la sourate Al-Baqara, considéré comme le plus grand verset du Coran. Le réciter après chaque prière obligatoire fait entrer au Paradis.',
    reponses: [
      { texte_fr: 'Verset 255 de Al-Baqara', est_correcte: true },
      { texte_fr: 'Premier verset de Yasin', est_correcte: false },
      { texte_fr: 'Verset 1 d\'Al-Fatiha', est_correcte: false },
      { texte_fr: 'Dernier verset d\'Al-Baqara', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Que dit-on avant de dormir selon la sunna ?',
    texte_ar: 'ماذا يقال عند النوم؟',
    dalil_ref: 'Sahih al-Bukhari 6320',
    explication: 'Parmi les adkar du sommeil : dire "Bismika Allahumma amutu wa ahya", lire Ayat al-Kursi, et les trois dernières sourates en soufflant dans les mains et les passant sur le corps.',
    reponses: [
      { texte_fr: 'Bismika Allahumma amutu wa ahya, Ayat al-Kursi, mu\'awwidhat', est_correcte: true },
      { texte_fr: 'Aucun dhikr particulier', est_correcte: false },
      { texte_fr: 'Uniquement Bismillah', est_correcte: false },
      { texte_fr: 'Faire une longue prière', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 2, madhab: 'general',
    texte_fr: 'Que dit-on au réveil ?',
    texte_ar: 'ماذا يقال عند الاستيقاظ؟',
    dalil_ref: 'Sahih al-Bukhari 6324',
    dalil_texte_ar: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    explication: 'Au réveil, le Prophète ﷺ disait : "Alhamdu lillahi alladhi ahyana ba\'da ma amatana wa ilayhi an-nushur".',
    reponses: [
      { texte_fr: 'Alhamdu lillahi alladhi ahyana ba\'da ma amatana wa ilayhi an-nushur', est_correcte: true },
      { texte_fr: 'La ilaha illa Allah', est_correcte: false },
      { texte_fr: 'Bismillah uniquement', est_correcte: false },
      { texte_fr: 'Astaghfirullah', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 3, madhab: 'general',
    texte_fr: 'Quelle est la "sayyid al-istighfar" (le maître des demandes de pardon) ?',
    texte_ar: 'ما هو سيد الاستغفار؟',
    dalil_ref: 'Sahih al-Bukhari 6306',
    explication: 'C\'est l\'invocation : "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana \'abduka, wa ana \'ala \'ahdika wa wa\'dika mastata\'tu, a\'udhu bika min sharri ma sana\'tu, abu\'u laka bi ni\'matika \'alayya wa abu\'u bi dhanbi, faghfir li fa innahu la yaghfiru adh-dhunuba illa anta". Celui qui la dit avec certitude le jour et meurt avant le soir entre au Paradis.',
    reponses: [
      { texte_fr: 'Allahumma anta rabbi la ilaha illa anta khalaqtani wa ana \'abduk...', est_correcte: true },
      { texte_fr: 'Astaghfirullah al-\'adhim seulement', est_correcte: false },
      { texte_fr: 'La ilaha illa Allah seulement', est_correcte: false },
      { texte_fr: 'Subhana Allah wa bi hamdihi', est_correcte: false },
    ],
  },
  {
    domaine: 'adkar', niveau: 3, madhab: 'general',
    texte_fr: 'Combien de fois le Prophète ﷺ demandait-il pardon par jour ?',
    texte_ar: 'كم مرة كان النبي ﷺ يستغفر في اليوم؟',
    dalil_ref: 'Sahih al-Bukhari 6307',
    explication: 'Le Prophète ﷺ a dit : "Par Allah, je demande pardon à Allah et je me repens à Lui plus de soixante-dix fois par jour". Selon une autre version : plus de 100 fois.',
    reponses: [
      { texte_fr: 'Plus de 70 fois (selon une autre version, plus de 100)', est_correcte: true },
      { texte_fr: 'Une seule fois', est_correcte: false },
      { texte_fr: '5 fois après chaque prière', est_correcte: false },
      { texte_fr: 'Il ne demandait jamais pardon', est_correcte: false },
    ],
  },

  // ===================== AKHLAQ (15) =====================
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le meilleur trait de caractère selon le Prophète ﷺ ?',
    texte_ar: 'ما أفضل خلق في الإسلام؟',
    dalil_ref: 'Sunan at-Tirmidhi 2003',
    explication: 'Le Prophète ﷺ a dit : "Rien ne pèsera plus lourd dans la balance d\'un croyant le Jour du Jugement que les bons caractères".',
    reponses: [
      { texte_fr: 'Le bon caractère (husn al-khuluq)', est_correcte: true },
      { texte_fr: 'La richesse', est_correcte: false },
      { texte_fr: 'La force physique', est_correcte: false },
      { texte_fr: 'La beauté', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: 'Quelle est la récompense pour celui qui dit la vérité ?',
    texte_ar: 'ما جزاء الصدق؟',
    dalil_ref: 'Sahih al-Bukhari 6094',
    dalil_texte_ar: 'إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ',
    explication: 'Le Prophète ﷺ a dit : "Certes, la véracité conduit à la piété, et la piété conduit au Paradis".',
    reponses: [
      { texte_fr: 'La véracité conduit à la piété et au Paradis', est_correcte: true },
      { texte_fr: 'Aucune récompense particulière', est_correcte: false },
      { texte_fr: 'Une augmentation de la richesse', est_correcte: false },
      { texte_fr: 'Une plus longue vie', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le statut du mensonge en Islam ?',
    texte_ar: 'ما حكم الكذب في الإسلام؟',
    dalil_ref: 'Sahih al-Bukhari 6094',
    explication: 'Le mensonge est strictement interdit (haram). Le Prophète ﷺ a dit : "Le mensonge conduit à la débauche et la débauche conduit à l\'Enfer".',
    reponses: [
      { texte_fr: 'Interdit (haram)', est_correcte: true },
      { texte_fr: 'Recommandé en société', est_correcte: false },
      { texte_fr: 'Neutre', est_correcte: false },
      { texte_fr: 'Permis sans restriction', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le statut de l\'obéissance aux parents en Islam ?',
    texte_ar: 'ما حكم بر الوالدين؟',
    dalil_ref: 'Sourate Al-Isra 17:23',
    explication: 'Le birr al-walidayn (bonté envers les parents) est une obligation majeure, mentionnée juste après le tawhid dans le Coran.',
    reponses: [
      { texte_fr: 'Obligation majeure, juste après le tawhid', est_correcte: true },
      { texte_fr: 'Recommandé seulement', est_correcte: false },
      { texte_fr: 'Uniquement envers la mère', est_correcte: false },
      { texte_fr: 'Uniquement durant l\'enfance', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le statut de la médisance (ghiba) en Islam ?',
    texte_ar: 'ما حكم الغيبة؟',
    dalil_ref: 'Sourate Al-Hujurat 49:12',
    explication: 'La médisance est interdite (haram). Allah la compare à manger la chair de son frère mort.',
    reponses: [
      { texte_fr: 'Interdite (haram), comparée à manger la chair de son frère mort', est_correcte: true },
      { texte_fr: 'Permise si c\'est vrai', est_correcte: false },
      { texte_fr: 'Recommandée pour avertir les autres', est_correcte: false },
      { texte_fr: 'Neutre', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est l\'attribut majeur d\'Allah qui doit inspirer le caractère du musulman ?',
    texte_ar: 'ما الصفة العظيمة لله التي يقتدي بها المسلم؟',
    explication: 'La miséricorde (ar-rahma). Allah est Ar-Rahman Ar-Rahim, et le Prophète ﷺ a dit : "Ceux qui font miséricorde, Le Tout-Miséricordieux leur fait miséricorde".',
    dalil_ref: 'Sunan Abi Dawud 4941',
    reponses: [
      { texte_fr: 'La miséricorde (ar-rahma)', est_correcte: true },
      { texte_fr: 'La sévérité', est_correcte: false },
      { texte_fr: 'L\'isolement', est_correcte: false },
      { texte_fr: 'La richesse', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est la définition de l\'ihsan selon le célèbre hadith de Jibril ?',
    texte_ar: 'ما تعريف الإحسان في حديث جبريل؟',
    dalil_ref: 'Sahih Muslim 8',
    dalil_texte_ar: 'أَنْ تَعْبُدَ اللَّهَ كَأَنَّكَ تَرَاهُ، فَإِنْ لَمْ تَكُنْ تَرَاهُ فَإِنَّهُ يَرَاكَ',
    explication: 'L\'ihsan c\'est "adorer Allah comme si tu Le voyais, car si tu ne Le vois pas, Lui te voit".',
    reponses: [
      { texte_fr: 'Adorer Allah comme si tu Le voyais', est_correcte: true },
      { texte_fr: 'Donner beaucoup d\'aumônes', est_correcte: false },
      { texte_fr: 'Jeûner tous les jours', est_correcte: false },
      { texte_fr: 'Mémoriser le Coran', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le droit du voisin en Islam ?',
    texte_ar: 'ما حق الجار في الإسلام؟',
    dalil_ref: 'Sahih al-Bukhari 6014',
    explication: 'Le Prophète ﷺ a dit : "Jibril ne cessa de me recommander le voisin, à tel point que j\'ai cru qu\'il allait l\'établir comme héritier".',
    reponses: [
      { texte_fr: 'Droit immense, recommandé par Jibril au Prophète ﷺ', est_correcte: true },
      { texte_fr: 'Aucun droit particulier', est_correcte: false },
      { texte_fr: 'Uniquement le salam', est_correcte: false },
      { texte_fr: 'Uniquement les voisins musulmans ont des droits', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: 'Que signifie la "hilm" (clémence/longanimité) ?',
    texte_ar: 'ما معنى الحلم؟',
    explication: 'La hilm est la maîtrise de soi face à la colère, la patience et la douceur dans la réaction. Allah aime cet attribut.',
    dalil_ref: 'Sahih Muslim 17',
    reponses: [
      { texte_fr: 'Maîtrise de soi face à la colère, patience et douceur', est_correcte: true },
      { texte_fr: 'L\'éloignement des gens', est_correcte: false },
      { texte_fr: 'La timidité excessive', est_correcte: false },
      { texte_fr: 'L\'acceptation passive de l\'injustice', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est l\'importance de l\'ikhlas (sincérité) ?',
    texte_ar: 'ما أهمية الإخلاص في الأعمال؟',
    dalil_ref: 'Sahih al-Bukhari 1',
    explication: 'L\'ikhlas (intention pure pour Allah seul) est la condition d\'acceptation des œuvres. Le Prophète ﷺ a dit : "Les actes ne valent que par les intentions".',
    reponses: [
      { texte_fr: 'Condition d\'acceptation des œuvres auprès d\'Allah', est_correcte: true },
      { texte_fr: 'Recommandé mais non essentiel', est_correcte: false },
      { texte_fr: 'Uniquement pour les œuvres obligatoires', est_correcte: false },
      { texte_fr: 'Réservé aux savants', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: 'Que signifie le "shukr" (gratitude) ?',
    texte_ar: 'ما معنى الشكر؟',
    dalil_ref: 'Sourate Ibrahim 14:7',
    explication: 'Le shukr est la gratitude envers Allah pour Ses bienfaits, manifestée par le cœur (reconnaissance), la langue (louange) et les membres (obéissance).',
    reponses: [
      { texte_fr: 'Reconnaissance manifestée par le cœur, la langue et les actes', est_correcte: true },
      { texte_fr: 'Uniquement dire "Alhamdulillah"', est_correcte: false },
      { texte_fr: 'Demander plus de bienfaits', est_correcte: false },
      { texte_fr: 'Ne jamais se plaindre', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le mérite du sourire selon le Prophète ﷺ ?',
    texte_ar: 'ما فضل التبسم في وجه المسلم؟',
    dalil_ref: 'Sunan at-Tirmidhi 1956',
    explication: 'Le Prophète ﷺ a dit : "Ton sourire au visage de ton frère est une sadaqa (aumône)".',
    reponses: [
      { texte_fr: 'Il est une aumône (sadaqa)', est_correcte: true },
      { texte_fr: 'Il est neutre', est_correcte: false },
      { texte_fr: 'Il est déconseillé', est_correcte: false },
      { texte_fr: 'Il vaut une prière complète', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 3, madhab: 'general',
    texte_fr: 'Que signifie "tawakkul" (confiance en Allah) ?',
    texte_ar: 'ما معنى التوكل على الله؟',
    dalil_ref: 'Sunan at-Tirmidhi 2344',
    explication: 'Le tawakkul est la confiance totale en Allah après avoir pris les moyens (asbab). Le Prophète ﷺ a dit : "Attache ta monture et place ta confiance en Allah".',
    reponses: [
      { texte_fr: 'Confiance en Allah après avoir pris les moyens nécessaires', est_correcte: true },
      { texte_fr: 'Attendre passivement sans agir', est_correcte: false },
      { texte_fr: 'Refuser tous les moyens matériels', est_correcte: false },
      { texte_fr: 'Ne compter que sur ses efforts', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 3, madhab: 'general',
    texte_fr: 'Que signifie le "hayaa" (pudeur/modestie) en Islam ?',
    texte_ar: 'ما معنى الحياء في الإسلام؟',
    dalil_ref: 'Sahih al-Bukhari 9',
    explication: 'Le Prophète ﷺ a dit : "La pudeur est une branche de la foi". Et : "Si tu n\'as pas de pudeur, fais ce que tu veux". La pudeur empêche de commettre des indécences.',
    reponses: [
      { texte_fr: 'Une branche de la foi qui empêche de commettre l\'indécence', est_correcte: true },
      { texte_fr: 'La timidité excessive uniquement', est_correcte: false },
      { texte_fr: 'Réservée aux femmes', est_correcte: false },
      { texte_fr: 'Une faiblesse à corriger', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq', niveau: 3, madhab: 'general',
    texte_fr: 'Quel est le statut de la colère selon le Prophète ﷺ ?',
    texte_ar: 'ما حكم الغضب في الإسلام؟',
    dalil_ref: 'Sahih al-Bukhari 6116',
    explication: 'Un homme demanda un conseil au Prophète ﷺ qui lui dit "Ne te mets pas en colère" et le répéta plusieurs fois. La maîtrise de la colère est un signe de force réelle.',
    reponses: [
      { texte_fr: 'Le Prophète ﷺ a recommandé de la maîtriser', est_correcte: true },
      { texte_fr: 'Elle est encouragée pour la cause religieuse', est_correcte: false },
      { texte_fr: 'Elle est totalement interdite quelles que soient les circonstances', est_correcte: false },
      { texte_fr: 'Aucune mention dans la sunna', est_correcte: false },
    ],
  },

  // ===================== SIRAH (20) =====================
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'En quelle année lunaire est né le Prophète Muhammad ﷺ (calendrier de l\'éléphant) ?',
    texte_ar: 'في أي عام وُلد النبي محمد ﷺ؟',
    explication: 'Le Prophète ﷺ est né l\'année de l\'Éléphant (\'Am al-Fil), correspondant à environ 570 du calendrier grégorien.',
    reponses: [
      { texte_fr: 'L\'année de l\'Éléphant (vers 570)', est_correcte: true },
      { texte_fr: 'L\'an 1 hijri', est_correcte: false },
      { texte_fr: 'L\'année 600 de notre ère', est_correcte: false },
      { texte_fr: 'L\'année 622', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Dans quelle ville le Prophète ﷺ est-il né ?',
    texte_ar: 'في أي مدينة وُلد النبي ﷺ؟',
    explication: 'Le Prophète ﷺ est né à La Mecque, en Arabie.',
    reponses: [
      { texte_fr: 'La Mecque', est_correcte: true },
      { texte_fr: 'Médine', est_correcte: false },
      { texte_fr: 'Taif', est_correcte: false },
      { texte_fr: 'Jérusalem', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était le père du Prophète ﷺ ?',
    texte_ar: 'من والد النبي ﷺ؟',
    explication: 'Son père était Abdullah ibn Abd al-Muttalib, mort avant la naissance du Prophète ﷺ.',
    reponses: [
      { texte_fr: 'Abdullah ibn Abd al-Muttalib', est_correcte: true },
      { texte_fr: 'Abu Talib', est_correcte: false },
      { texte_fr: 'Abu Sufyan', est_correcte: false },
      { texte_fr: 'Hashim', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était la mère du Prophète ﷺ ?',
    texte_ar: 'من والدة النبي ﷺ؟',
    explication: 'Sa mère était Amina bint Wahb, morte quand le Prophète ﷺ avait environ 6 ans.',
    reponses: [
      { texte_fr: 'Amina bint Wahb', est_correcte: true },
      { texte_fr: 'Khadija bint Khuwaylid', est_correcte: false },
      { texte_fr: 'Aisha bint Abi Bakr', est_correcte: false },
      { texte_fr: 'Halima as-Sa\'diyya', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était la première épouse du Prophète ﷺ ?',
    texte_ar: 'من أول زوجة للنبي ﷺ؟',
    explication: 'Sa première épouse fut Khadija bint Khuwaylid, qu\'il épousa à 25 ans alors qu\'elle en avait environ 40. Elle resta sa seule épouse jusqu\'à sa mort.',
    reponses: [
      { texte_fr: 'Khadija bint Khuwaylid', est_correcte: true },
      { texte_fr: 'Aisha bint Abi Bakr', est_correcte: false },
      { texte_fr: 'Hafsa bint Umar', est_correcte: false },
      { texte_fr: 'Sawda bint Zam\'a', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'À quel âge le Prophète ﷺ a-t-il reçu la révélation ?',
    texte_ar: 'في أي عمر أُوحي إلى النبي ﷺ؟',
    explication: 'Le Prophète ﷺ a reçu la première révélation à l\'âge de 40 ans, dans la grotte de Hira.',
    reponses: [
      { texte_fr: '40 ans', est_correcte: true },
      { texte_fr: '25 ans', est_correcte: false },
      { texte_fr: '30 ans', est_correcte: false },
      { texte_fr: '50 ans', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Dans quelle grotte le Prophète ﷺ a-t-il reçu la première révélation ?',
    texte_ar: 'في أي غار نزل الوحي على النبي ﷺ أول مرة؟',
    explication: 'La première révélation eut lieu dans la grotte de Hira, sur la montagne Jabal an-Nur près de La Mecque, apportée par l\'ange Jibril.',
    reponses: [
      { texte_fr: 'La grotte de Hira', est_correcte: true },
      { texte_fr: 'La grotte de Thawr', est_correcte: false },
      { texte_fr: 'La grotte d\'Uhud', est_correcte: false },
      { texte_fr: 'La grotte de Badr', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Quels furent les premiers versets révélés ?',
    texte_ar: 'ما أول ما نزل من القرآن؟',
    dalil_ref: 'Sourate Al-\'Alaq 96:1-5',
    explication: 'Les premiers versets révélés furent les cinq premiers de la sourate Al-\'Alaq : "Iqra bismi rabbika alladhi khalaq..." (Lis au nom de ton Seigneur qui a créé...).',
    reponses: [
      { texte_fr: 'Les 5 premiers versets de sourate Al-\'Alaq', est_correcte: true },
      { texte_fr: 'Al-Fatiha', est_correcte: false },
      { texte_fr: 'Al-Baqara verset 1', est_correcte: false },
      { texte_fr: 'Al-Ikhlas', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Vers quelle ville le Prophète ﷺ a-t-il émigré (hijra) ?',
    texte_ar: 'إلى أي مدينة هاجر النبي ﷺ؟',
    explication: 'Le Prophète ﷺ a émigré de La Mecque vers Yathrib, qui fut renommée Médine (Madinat an-Nabi, la ville du Prophète) en l\'an 1 hijri (622 EC).',
    reponses: [
      { texte_fr: 'Médine (Yathrib)', est_correcte: true },
      { texte_fr: 'Taif', est_correcte: false },
      { texte_fr: 'Abyssinie', est_correcte: false },
      { texte_fr: 'Damas', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 1, madhab: 'general',
    texte_fr: 'Quelle est la première bataille majeure de l\'Islam ?',
    texte_ar: 'ما أول معركة كبرى في الإسلام؟',
    explication: 'La bataille de Badr, en 2 hijri, opposa 313 musulmans à environ 1000 Mecquois. Allah accorda la victoire aux musulmans malgré leur infériorité numérique.',
    dalil_ref: 'Sourate Aal Imran 3:123',
    reponses: [
      { texte_fr: 'La bataille de Badr (2 hijri)', est_correcte: true },
      { texte_fr: 'La bataille d\'Uhud', est_correcte: false },
      { texte_fr: 'La bataille du Fossé (Khandaq)', est_correcte: false },
      { texte_fr: 'La conquête de La Mecque', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'Qui accompagna le Prophète ﷺ dans la grotte de Thawr durant la hijra ?',
    texte_ar: 'من رافق النبي ﷺ في غار ثور؟',
    dalil_ref: 'Sourate At-Tawba 9:40',
    explication: 'Abu Bakr as-Siddiq accompagna le Prophète ﷺ dans la grotte de Thawr lors de l\'émigration vers Médine.',
    reponses: [
      { texte_fr: 'Abu Bakr as-Siddiq', est_correcte: true },
      { texte_fr: 'Umar ibn al-Khattab', est_correcte: false },
      { texte_fr: 'Ali ibn Abi Talib', est_correcte: false },
      { texte_fr: 'Uthman ibn Affan', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'En quelle année eut lieu l\'Isra wal Mi\'raj ?',
    texte_ar: 'متى كان الإسراء والمعراج؟',
    explication: 'L\'Isra wal Mi\'raj (voyage nocturne et ascension) eut lieu environ un an avant la Hijra, soit vers l\'an 10 de la mission prophétique. C\'est lors de cet événement que les 5 prières quotidiennes furent prescrites.',
    reponses: [
      { texte_fr: 'Environ un an avant la Hijra', est_correcte: true },
      { texte_fr: 'La nuit de la révélation initiale', est_correcte: false },
      { texte_fr: 'Après la bataille de Badr', est_correcte: false },
      { texte_fr: 'Après la conquête de La Mecque', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'En quelle année eut lieu la conquête de La Mecque (Fath Makka) ?',
    texte_ar: 'متى كان فتح مكة؟',
    explication: 'La conquête pacifique de La Mecque eut lieu en l\'an 8 hijri (630 EC), suite à la violation du traité de Hudaybiyya par les Quraysh.',
    reponses: [
      { texte_fr: 'An 8 hijri (630 EC)', est_correcte: true },
      { texte_fr: 'An 1 hijri', est_correcte: false },
      { texte_fr: 'An 5 hijri', est_correcte: false },
      { texte_fr: 'An 10 hijri', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le nom du dernier pèlerinage du Prophète ﷺ ?',
    texte_ar: 'ما اسم آخر حجة للنبي ﷺ؟',
    explication: 'Hijjat al-Wada\' (le pèlerinage d\'adieu) eut lieu en l\'an 10 hijri, environ trois mois avant le décès du Prophète ﷺ. Le célèbre sermon d\'adieu y fut prononcé.',
    reponses: [
      { texte_fr: 'Hijjat al-Wada\' (le pèlerinage d\'adieu)', est_correcte: true },
      { texte_fr: 'Hijjat al-Fath', est_correcte: false },
      { texte_fr: 'Hijjat al-Akbar', est_correcte: false },
      { texte_fr: 'Hijjat at-Tamattu\'', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'À quel âge le Prophète ﷺ est-il décédé ?',
    texte_ar: 'في أي عمر توفي النبي ﷺ؟',
    explication: 'Le Prophète ﷺ est décédé à 63 ans (selon le calendrier lunaire) en l\'an 11 hijri (632 EC), dans la maison d\'Aisha à Médine.',
    reponses: [
      { texte_fr: '63 ans', est_correcte: true },
      { texte_fr: '40 ans', est_correcte: false },
      { texte_fr: '70 ans', est_correcte: false },
      { texte_fr: '53 ans', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'Où est enterré le Prophète ﷺ ?',
    texte_ar: 'أين قبر النبي ﷺ؟',
    explication: 'Le Prophète ﷺ est enterré à Médine, dans la chambre d\'Aisha, qui se trouve aujourd\'hui dans la Mosquée du Prophète (Masjid an-Nabawi).',
    reponses: [
      { texte_fr: 'À Médine, dans la Mosquée du Prophète', est_correcte: true },
      { texte_fr: 'À La Mecque, près de la Ka\'ba', est_correcte: false },
      { texte_fr: 'À Jérusalem, près de Al-Aqsa', est_correcte: false },
      { texte_fr: 'Au mont Uhud', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'Combien de fils du Prophète ﷺ ont atteint l\'âge adulte ?',
    texte_ar: 'كم من أبناء النبي ﷺ بلغ سن الرشد؟',
    explication: 'Aucun. Tous les fils du Prophète ﷺ (Al-Qasim, Abdullah, Ibrahim) sont morts en bas âge. Seules quatre de ses filles ont atteint l\'âge adulte.',
    reponses: [
      { texte_fr: 'Aucun', est_correcte: true },
      { texte_fr: 'Deux', est_correcte: false },
      { texte_fr: 'Trois', est_correcte: false },
      { texte_fr: 'Quatre', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle est la fille du Prophète ﷺ qui fut l\'épouse d\'Ali ibn Abi Talib ?',
    texte_ar: 'من بنت النبي ﷺ التي تزوجها علي بن أبي طالب؟',
    explication: 'Fatima az-Zahra, la plus jeune fille du Prophète ﷺ, fut l\'épouse d\'Ali ibn Abi Talib. Leurs fils Hasan et Husayn sont les petits-fils du Prophète.',
    reponses: [
      { texte_fr: 'Fatima az-Zahra', est_correcte: true },
      { texte_fr: 'Zaynab', est_correcte: false },
      { texte_fr: 'Ruqayya', est_correcte: false },
      { texte_fr: 'Umm Kulthum', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 3, madhab: 'general',
    texte_fr: 'En quelle année eut lieu le traité de Hudaybiyya ?',
    texte_ar: 'متى كانت صلح الحديبية؟',
    explication: 'Le traité de Hudaybiyya fut signé en l\'an 6 hijri entre le Prophète ﷺ et les Quraysh, instaurant une trêve de 10 ans. Le Coran l\'a qualifié de "victoire éclatante" (Fath Mubin).',
    dalil_ref: 'Sourate Al-Fath 48:1',
    reponses: [
      { texte_fr: 'An 6 hijri', est_correcte: true },
      { texte_fr: 'An 2 hijri', est_correcte: false },
      { texte_fr: 'An 8 hijri', est_correcte: false },
      { texte_fr: 'An 10 hijri', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah', niveau: 3, madhab: 'general',
    texte_fr: 'Combien d\'années a duré la mission prophétique de Muhammad ﷺ ?',
    texte_ar: 'كم استمرت بعثة النبي ﷺ؟',
    explication: '23 ans : 13 ans à La Mecque puis 10 ans à Médine.',
    reponses: [
      { texte_fr: '23 ans (13 à La Mecque, 10 à Médine)', est_correcte: true },
      { texte_fr: '40 ans', est_correcte: false },
      { texte_fr: '10 ans', est_correcte: false },
      { texte_fr: '63 ans', est_correcte: false },
    ],
  },

  // ===================== SAHABA (15) =====================
  {
    domaine: 'sahaba', niveau: 1, madhab: 'general',
    texte_fr: 'Qui fut le premier calife après le Prophète ﷺ ?',
    texte_ar: 'من أول الخلفاء الراشدين؟',
    explication: 'Abu Bakr as-Siddiq fut le premier calife (khalifa) après le décès du Prophète ﷺ, de 11 à 13 hijri.',
    reponses: [
      { texte_fr: 'Abu Bakr as-Siddiq', est_correcte: true },
      { texte_fr: 'Umar ibn al-Khattab', est_correcte: false },
      { texte_fr: 'Uthman ibn Affan', est_correcte: false },
      { texte_fr: 'Ali ibn Abi Talib', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était le deuxième calife rashidoun ?',
    texte_ar: 'من ثاني الخلفاء الراشدين؟',
    explication: 'Umar ibn al-Khattab fut le deuxième calife, de 13 à 23 hijri. Sous son califat, l\'Islam s\'étendit considérablement.',
    reponses: [
      { texte_fr: 'Umar ibn al-Khattab', est_correcte: true },
      { texte_fr: 'Abu Bakr', est_correcte: false },
      { texte_fr: 'Uthman', est_correcte: false },
      { texte_fr: 'Ali', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était le troisième calife rashidoun ?',
    texte_ar: 'من ثالث الخلفاء الراشدين؟',
    explication: 'Uthman ibn Affan, surnommé Dhun-Nurayn (l\'homme aux deux lumières), fut le troisième calife de 23 à 35 hijri. Il rassembla le Coran en un seul mushaf de référence.',
    reponses: [
      { texte_fr: 'Uthman ibn Affan', est_correcte: true },
      { texte_fr: 'Ali ibn Abi Talib', est_correcte: false },
      { texte_fr: 'Mu\'awiya', est_correcte: false },
      { texte_fr: 'Talha ibn Ubaydillah', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était le quatrième calife rashidoun ?',
    texte_ar: 'من رابع الخلفاء الراشدين؟',
    explication: 'Ali ibn Abi Talib, cousin et gendre du Prophète ﷺ, fut le quatrième calife de 35 à 40 hijri.',
    reponses: [
      { texte_fr: 'Ali ibn Abi Talib', est_correcte: true },
      { texte_fr: 'Hasan ibn Ali', est_correcte: false },
      { texte_fr: 'Mu\'awiya ibn Abi Sufyan', est_correcte: false },
      { texte_fr: 'Sa\'d ibn Abi Waqqas', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 1, madhab: 'general',
    texte_fr: 'Qui fut le premier homme libre adulte à se convertir à l\'Islam ?',
    texte_ar: 'من أول الرجال الأحرار إسلاماً؟',
    explication: 'Abu Bakr as-Siddiq fut le premier homme libre adulte à embrasser l\'Islam. Khadija fut la première femme, Ali le premier enfant, et Zayd le premier ancien esclave.',
    reponses: [
      { texte_fr: 'Abu Bakr as-Siddiq', est_correcte: true },
      { texte_fr: 'Umar ibn al-Khattab', est_correcte: false },
      { texte_fr: 'Hamza ibn Abd al-Muttalib', est_correcte: false },
      { texte_fr: 'Bilal ibn Rabah', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 1, madhab: 'general',
    texte_fr: 'Qui était le mu\'adhdhin (muezzin) du Prophète ﷺ ?',
    texte_ar: 'من مؤذن النبي ﷺ؟',
    explication: 'Bilal ibn Rabah al-Habashi fut le premier muezzin de l\'Islam. Ancien esclave d\'origine éthiopienne, il fut affranchi par Abu Bakr.',
    reponses: [
      { texte_fr: 'Bilal ibn Rabah', est_correcte: true },
      { texte_fr: 'Abdullah ibn Umm Maktum', est_correcte: false },
      { texte_fr: 'Zayd ibn Haritha', est_correcte: false },
      { texte_fr: 'Salman al-Farisi', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 2, madhab: 'general',
    texte_fr: 'Qui fut surnommé "Sayf Allah al-Maslul" (le sabre dégainé d\'Allah) ?',
    texte_ar: 'من المعروف بسيف الله المسلول؟',
    explication: 'Khalid ibn al-Walid, brillant général musulman, reçut ce surnom du Prophète ﷺ. Il dirigea de nombreuses batailles victorieuses.',
    reponses: [
      { texte_fr: 'Khalid ibn al-Walid', est_correcte: true },
      { texte_fr: 'Sa\'d ibn Abi Waqqas', est_correcte: false },
      { texte_fr: 'Hamza ibn Abd al-Muttalib', est_correcte: false },
      { texte_fr: 'Abu Ubayda ibn al-Jarrah', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 2, madhab: 'general',
    texte_fr: 'Qui était l\'oncle du Prophète ﷺ, surnommé "Asad Allah" (le lion d\'Allah) ?',
    texte_ar: 'من عم النبي ﷺ الملقب بأسد الله؟',
    explication: 'Hamza ibn Abd al-Muttalib, oncle paternel du Prophète ﷺ. Il fut tué en martyr à la bataille d\'Uhud par Wahshi.',
    reponses: [
      { texte_fr: 'Hamza ibn Abd al-Muttalib', est_correcte: true },
      { texte_fr: 'Abu Talib', est_correcte: false },
      { texte_fr: 'Al-\'Abbas', est_correcte: false },
      { texte_fr: 'Abu Lahab', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 2, madhab: 'general',
    texte_fr: 'Qui est la femme nommée "mère des croyants" et qui a rapporté le plus de hadiths ?',
    texte_ar: 'من أم المؤمنين الأكثر رواية للحديث؟',
    explication: 'Aisha bint Abi Bakr, épouse du Prophète ﷺ, est l\'une des plus grandes savantes de la première génération et a rapporté plus de 2200 hadiths.',
    reponses: [
      { texte_fr: 'Aisha bint Abi Bakr', est_correcte: true },
      { texte_fr: 'Khadija bint Khuwaylid', est_correcte: false },
      { texte_fr: 'Hafsa bint Umar', est_correcte: false },
      { texte_fr: 'Umm Salama', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 2, madhab: 'general',
    texte_fr: 'Quel compagnon est connu comme "Tarjuman al-Qur\'an" (l\'interprète du Coran) ?',
    texte_ar: 'من المعروف بترجمان القرآن؟',
    explication: 'Abdullah ibn Abbas, cousin du Prophète ﷺ, reçut ce surnom car le Prophète ﷺ invoqua Allah pour qu\'Il lui enseigne le ta\'wil (interprétation).',
    reponses: [
      { texte_fr: 'Abdullah ibn Abbas', est_correcte: true },
      { texte_fr: 'Abdullah ibn Mas\'ud', est_correcte: false },
      { texte_fr: 'Abdullah ibn Umar', est_correcte: false },
      { texte_fr: 'Abu Hurayra', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 2, madhab: 'general',
    texte_fr: 'Quel compagnon a rapporté le plus grand nombre de hadiths ?',
    texte_ar: 'من أكثر الصحابة رواية للحديث؟',
    explication: 'Abu Hurayra a rapporté environ 5374 hadiths. Bien qu\'il n\'ait été en compagnie du Prophète ﷺ que pendant 3 ans, il avait une mémoire prodigieuse.',
    reponses: [
      { texte_fr: 'Abu Hurayra', est_correcte: true },
      { texte_fr: 'Aisha', est_correcte: false },
      { texte_fr: 'Anas ibn Malik', est_correcte: false },
      { texte_fr: 'Ibn Umar', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 2, madhab: 'general',
    texte_fr: 'Combien d\'années a duré le califat des "Rashidoun" (bien-guidés) ?',
    texte_ar: 'كم استمرت خلافة الراشدين؟',
    explication: 'Le califat rashidoun a duré environ 30 ans (de 11 à 40 hijri), conformément au hadith du Prophète ﷺ : "Le califat sera 30 ans après moi, puis viendra un royaume".',
    dalil_ref: 'Sunan Abi Dawud 4646',
    reponses: [
      { texte_fr: 'Environ 30 ans', est_correcte: true },
      { texte_fr: '100 ans', est_correcte: false },
      { texte_fr: '10 ans', est_correcte: false },
      { texte_fr: '50 ans', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 3, madhab: 'general',
    texte_fr: 'Qui sont les "Ashara al-Mubashshara" (les 10 promis au Paradis) ?',
    texte_ar: 'من العشرة المبشرون بالجنة؟',
    dalil_ref: 'Sunan at-Tirmidhi 3747',
    explication: 'Les 10 compagnons à qui le Prophète ﷺ a explicitement promis le Paradis : Abu Bakr, Umar, Uthman, Ali, Talha, Az-Zubayr, Abdurrahman ibn Awf, Sa\'d ibn Abi Waqqas, Sa\'id ibn Zayd, Abu Ubayda ibn al-Jarrah.',
    reponses: [
      { texte_fr: 'Abu Bakr, Umar, Uthman, Ali, Talha, Zubayr, Abdurrahman ibn Awf, Sa\'d, Sa\'id, Abu Ubayda', est_correcte: true },
      { texte_fr: 'Les quatre califes rashidoun seulement', est_correcte: false },
      { texte_fr: 'Les épouses du Prophète ﷺ', est_correcte: false },
      { texte_fr: 'Les muhajirun seulement', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 3, madhab: 'general',
    texte_fr: 'Quel compagnon perse fut adopté par le Prophète ﷺ dans la famille (Ahl al-Bayt) ?',
    texte_ar: 'من الصحابي الفارسي الذي قال عنه النبي ﷺ "منا أهل البيت"؟',
    explication: 'Salman al-Farisi, d\'origine perse, suggéra la stratégie du fossé (Khandaq) lors du siège de Médine. Le Prophète ﷺ a dit de lui : "Salman est des nôtres, Ahl al-Bayt".',
    reponses: [
      { texte_fr: 'Salman al-Farisi', est_correcte: true },
      { texte_fr: 'Bilal al-Habashi', est_correcte: false },
      { texte_fr: 'Suhayb ar-Rumi', est_correcte: false },
      { texte_fr: 'Abu Dharr al-Ghifari', est_correcte: false },
    ],
  },
  {
    domaine: 'sahaba', niveau: 3, madhab: 'general',
    texte_fr: 'Qui était le scribe principal de la révélation du Coran ?',
    texte_ar: 'من أبرز كتبة الوحي؟',
    explication: 'Zayd ibn Thabit fut l\'un des principaux scribes de la révélation. Il fut chargé par Abu Bakr de compiler le Coran après la bataille de Yamama, puis par Uthman d\'établir le mushaf de référence.',
    reponses: [
      { texte_fr: 'Zayd ibn Thabit', est_correcte: true },
      { texte_fr: 'Abu Hurayra', est_correcte: false },
      { texte_fr: 'Anas ibn Malik', est_correcte: false },
      { texte_fr: 'Abdullah ibn Umar', est_correcte: false },
    ],
  },

  // ===================== TAFSIR COURT (15) =====================
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: 'Combien de versets compte la sourate Al-Fatiha ?',
    texte_ar: 'كم آية في سورة الفاتحة؟',
    explication: 'La sourate Al-Fatiha (l\'Ouvrante) compte 7 versets. Elle est appelée "as-Sab\' al-Mathani" (les sept répétés).',
    dalil_ref: 'Sourate Al-Hijr 15:87',
    reponses: [
      { texte_fr: '7 versets', est_correcte: true },
      { texte_fr: '5 versets', est_correcte: false },
      { texte_fr: '10 versets', est_correcte: false },
      { texte_fr: '3 versets', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le thème principal de la sourate Al-Ikhlas ?',
    texte_ar: 'ما موضوع سورة الإخلاص؟',
    dalil_ref: 'Sourate Al-Ikhlas 112',
    explication: 'Sourate Al-Ikhlas traite de l\'unicité absolue d\'Allah (tawhid) : Allah est Unique, Eternel, Il n\'engendre ni n\'est engendré, et nul n\'est égal à Lui.',
    reponses: [
      { texte_fr: 'L\'unicité absolue d\'Allah (tawhid)', est_correcte: true },
      { texte_fr: 'L\'histoire des prophètes', est_correcte: false },
      { texte_fr: 'Le Jour du Jugement', est_correcte: false },
      { texte_fr: 'Les règles du commerce', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: 'Quel est le mérite de réciter sourate Al-Ikhlas trois fois ?',
    texte_ar: 'ما فضل قراءة سورة الإخلاص ثلاث مرات؟',
    dalil_ref: 'Sahih al-Bukhari 5015',
    explication: 'Le Prophète ﷺ a dit que la sourate Al-Ikhlas équivaut à un tiers du Coran. La réciter trois fois équivaut donc à la récitation du Coran entier en récompense.',
    reponses: [
      { texte_fr: 'Équivaut à la récitation du Coran entier (en récompense)', est_correcte: true },
      { texte_fr: 'Aucun mérite particulier', est_correcte: false },
      { texte_fr: 'Garantit la richesse', est_correcte: false },
      { texte_fr: 'Annule toutes les prières', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: 'Contre quoi sourate Al-Falaq nous protège-t-elle ?',
    texte_ar: 'مم تحفظ سورة الفلق؟',
    dalil_ref: 'Sourate Al-Falaq 113',
    explication: 'Sourate Al-Falaq protège contre : le mal de ce qu\'Allah a créé, le mal de l\'obscurité, le mal des sorcières qui soufflent sur les nœuds, et le mal de l\'envieux qui envie.',
    reponses: [
      { texte_fr: 'Le mal de la création, des ténèbres, de la sorcellerie et de l\'envie', est_correcte: true },
      { texte_fr: 'Uniquement contre la maladie physique', est_correcte: false },
      { texte_fr: 'Contre la pauvreté', est_correcte: false },
      { texte_fr: 'Uniquement contre les ennemis humains', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: 'Contre quoi sourate An-Nas nous protège-t-elle ?',
    texte_ar: 'مم تحفظ سورة الناس؟',
    dalil_ref: 'Sourate An-Nas 114',
    explication: 'Sourate An-Nas demande refuge à Allah contre le mal du chuchoteur (waswas) qui souffle dans les poitrines des hommes, qu\'il soit jinn ou homme.',
    reponses: [
      { texte_fr: 'Contre le mal du chuchoteur (waswas), qu\'il soit jinn ou homme', est_correcte: true },
      { texte_fr: 'Contre la pluie', est_correcte: false },
      { texte_fr: 'Contre les animaux sauvages', est_correcte: false },
      { texte_fr: 'Contre la famine', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 1, madhab: 'general',
    texte_fr: 'Que signifie le mot "Al-Fatiha" ?',
    texte_ar: 'ما معنى كلمة "الفاتحة"؟',
    explication: 'Al-Fatiha signifie "l\'Ouvrante" ou "l\'Introductive", car elle ouvre le Coran. Elle est aussi appelée Umm al-Kitab (la mère du Livre).',
    reponses: [
      { texte_fr: 'L\'Ouvrante / L\'Introductive', est_correcte: true },
      { texte_fr: 'La Conclusion', est_correcte: false },
      { texte_fr: 'La Prière', est_correcte: false },
      { texte_fr: 'La Guidance', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: 'Que veut dire "as-sirat al-mustaqim" mentionné dans Al-Fatiha ?',
    texte_ar: 'ما المراد بـ "الصراط المستقيم" في الفاتحة؟',
    dalil_ref: 'Sourate Al-Fatiha 1:6',
    explication: 'As-sirat al-mustaqim est "le droit chemin" : l\'Islam, le chemin de ceux qu\'Allah a comblés de bienfaits (les prophètes, les véridiques, les martyrs et les vertueux).',
    reponses: [
      { texte_fr: 'Le droit chemin de l\'Islam, celui des prophètes et des vertueux', est_correcte: true },
      { texte_fr: 'Un chemin géographique précis', est_correcte: false },
      { texte_fr: 'Le pont au-dessus de l\'Enfer uniquement', est_correcte: false },
      { texte_fr: 'Le chemin du Hajj', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: 'Qui sont "ceux qui ont encouru la colère" et "les égarés" dans Al-Fatiha selon le tafsir ?',
    texte_ar: 'من المغضوب عليهم والضالين في الفاتحة؟',
    dalil_ref: 'Sunan at-Tirmidhi 2954',
    explication: 'Selon un hadith authentique : "ceux qui ont encouru la colère" sont les Juifs (qui ont su et n\'ont pas suivi), et "les égarés" sont les Chrétiens (qui ont cherché sans guidance correcte).',
    reponses: [
      { texte_fr: 'Les Juifs (al-maghdub) et les Chrétiens (ad-dallin) selon le hadith', est_correcte: true },
      { texte_fr: 'Tous les non-musulmans indistinctement', est_correcte: false },
      { texte_fr: 'Les païens uniquement', est_correcte: false },
      { texte_fr: 'Les hypocrites', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le surnom de la sourate Yasin selon la tradition ?',
    texte_ar: 'ما لقب سورة يس؟',
    explication: 'Yasin est appelée "Qalb al-Qur\'an" (le cœur du Coran), selon une tradition attribuée au Prophète ﷺ, bien que la chaîne soit discutée chez certains muhaddithun.',
    reponses: [
      { texte_fr: 'Qalb al-Qur\'an (le cœur du Coran)', est_correcte: true },
      { texte_fr: 'Umm al-Qur\'an', est_correcte: false },
      { texte_fr: 'As-Sab\' al-Mathani', est_correcte: false },
      { texte_fr: 'Al-Khatm', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: 'Quel est le thème principal de sourate Yasin ?',
    texte_ar: 'ما الموضوع الرئيسي لسورة يس؟',
    explication: 'Sourate Yasin traite des grands sujets de l\'aqida : la véracité du Prophète ﷺ, le tawhid, la résurrection et le Jour du Jugement, avec des récits édifiants.',
    reponses: [
      { texte_fr: 'Les fondamentaux de la foi : prophétie, tawhid, résurrection', est_correcte: true },
      { texte_fr: 'Les règles du mariage', est_correcte: false },
      { texte_fr: 'L\'histoire des califes', est_correcte: false },
      { texte_fr: 'Les règles d\'héritage', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: 'Combien de fois le nom d\'Allah "Ar-Rahman Ar-Rahim" apparaît-il dans la Basmala ?',
    texte_ar: 'كم اسماً من أسماء الله في البسملة بعد لفظ الجلالة؟',
    explication: 'Dans la Basmala (Bismillah ar-Rahman ar-Rahim), il y a deux noms d\'Allah après "Allah" : Ar-Rahman (le Tout-Miséricordieux) et Ar-Rahim (le Très-Miséricordieux).',
    reponses: [
      { texte_fr: 'Deux : Ar-Rahman et Ar-Rahim', est_correcte: true },
      { texte_fr: 'Un seul', est_correcte: false },
      { texte_fr: 'Trois', est_correcte: false },
      { texte_fr: 'Aucun', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 2, madhab: 'general',
    texte_fr: 'Quelle sourate récitée chaque nuit protège du châtiment de la tombe selon le hadith ?',
    texte_ar: 'ما السورة التي تنجي من عذاب القبر؟',
    dalil_ref: 'Sunan at-Tirmidhi 2890',
    explication: 'La sourate Al-Mulk (Tabarak), composée de 30 versets, intercède pour celui qui la récite jusqu\'à lui être pardonné. Elle est appelée "Al-Munjiya" (la salvatrice).',
    reponses: [
      { texte_fr: 'Sourate Al-Mulk', est_correcte: true },
      { texte_fr: 'Sourate Al-Kahf uniquement', est_correcte: false },
      { texte_fr: 'Sourate Yasin uniquement', est_correcte: false },
      { texte_fr: 'Sourate Ar-Rahman uniquement', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 3, madhab: 'general',
    texte_fr: 'Quel jour est-il recommandé de réciter sourate Al-Kahf ?',
    texte_ar: 'في أي يوم يستحب قراءة سورة الكهف؟',
    dalil_ref: 'Sahih al-Jami\' 6470',
    explication: 'Le Prophète ﷺ a recommandé de réciter sourate Al-Kahf le vendredi : elle illumine entre les deux vendredis pour celui qui la récite.',
    reponses: [
      { texte_fr: 'Le vendredi (Jumu\'a)', est_correcte: true },
      { texte_fr: 'Le lundi', est_correcte: false },
      { texte_fr: 'Le samedi', est_correcte: false },
      { texte_fr: 'Aucun jour particulier', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 3, madhab: 'general',
    texte_fr: 'Combien d\'histoires principales contient la sourate Al-Kahf ?',
    texte_ar: 'كم قصة رئيسية في سورة الكهف؟',
    explication: 'Sourate Al-Kahf contient 4 histoires principales : les gens de la caverne, le possesseur des deux jardins, Musa et Al-Khidr, et Dhul-Qarnayn. Chacune contient une épreuve (foi, richesse, savoir, pouvoir).',
    reponses: [
      { texte_fr: 'Quatre : les gens de la caverne, les deux jardins, Musa et Al-Khidr, Dhul-Qarnayn', est_correcte: true },
      { texte_fr: 'Une seule', est_correcte: false },
      { texte_fr: 'Sept', est_correcte: false },
      { texte_fr: 'Aucune histoire', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir', niveau: 3, madhab: 'general',
    texte_fr: 'Quels sont les noms (alternatifs) de la sourate Al-Fatiha mentionnés dans la sunna ?',
    texte_ar: 'ما من أسماء سورة الفاتحة في السنة؟',
    explication: 'Al-Fatiha porte plusieurs noms : Umm al-Kitab (mère du Livre), Umm al-Qur\'an, As-Sab\' al-Mathani (les sept répétés), Al-Hamd, Ash-Shifa (la guérison), As-Salat, Ar-Ruqya.',
    reponses: [
      { texte_fr: 'Umm al-Kitab, As-Sab\' al-Mathani, Ash-Shifa, etc.', est_correcte: true },
      { texte_fr: 'Aucun autre nom', est_correcte: false },
      { texte_fr: 'Uniquement Al-Hamd', est_correcte: false },
      { texte_fr: 'Al-Baqara as-Sughra', est_correcte: false },
    ],
  },
];

export async function seedQuestionsExtra5(client: Client): Promise<void> {
  let inserted = 0;
  let skipped = 0;

  console.log('Seeding extra questions (batch 5)...');

  for (const q of QUESTIONS_EXTRA5) {
    const exists = await client.query(
      'SELECT id FROM questions WHERE texte_fr = $1',
      [q.texte_fr]
    );
    if (exists.rows.length > 0) { skipped++; continue; }

    const qResult = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, dalil_texte_ar, dalil_texte_fr, explication, savant_reference, grade_hadith, statut)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'valide')
       RETURNING id`,
      [
        q.domaine, q.sous_domaine ?? null, q.niveau, q.madhab,
        q.texte_fr, q.texte_ar ?? null,
        q.dalil_ref ?? null, q.dalil_texte_ar ?? null, q.dalil_texte_fr ?? null,
        q.explication ?? null, q.savant_reference ?? null, q.grade_hadith ?? null,
      ]
    );

    const questionId = qResult.rows[0].id;
    for (const r of q.reponses) {
      await client.query(
        `INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte)
         VALUES ($1,$2,$3,$4)`,
        [questionId, r.texte_fr, r.texte_ar ?? null, r.est_correcte]
      );
    }
    inserted++;
  }

  console.log(`questions_extra5: ${inserted} inserted, ${skipped} skipped.`);
}
