import { Client } from 'pg';

interface Q { domaine:string; niveau:number; texte_fr:string; texte_ar?:string; explication:string; dalil_ref?:string; grade_hadith?:string; sous_domaine?:string; reponses:{texte_fr:string;texte_ar?:string;est_correcte:boolean}[]; }

const Q: Q[] = [
  // ===== AKHLAQ N4 (+15) =====
  { domaine:'akhlaq', niveau:4, texte_fr:"Quels sont les 3 sortes de péchés selon Ibn al-Qayyim ?", texte_ar:'ما أصناف الذنوب الثلاثة؟', explication:"Péchés des organes (yeux, langue, mains), péchés du cœur (orgueil, envie, ostentation), péchés de l'âme (négligence du dhikr).", dalil_ref:"al-Fawa'id d'Ibn al-Qayyim", reponses:[{texte_fr:"Organes, cœur, âme",est_correcte:true},{texte_fr:"Petits, moyens, grands",est_correcte:false},{texte_fr:"Visibles, cachés, oubliés",est_correcte:false},{texte_fr:"Volontaires, involontaires, hérités",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Qu'est-ce que l'ostentation cachée (Riya' Khafi) ?", texte_ar:'ما هو الرياء الخفي؟', explication:"Faire un acte pour Allah mais se réjouir secrètement quand les gens le voient ou en parlent. Plus subtil que la riya' manifeste, plus difficile à détecter.", dalil_ref:"Madarij as-Salikin", reponses:[{texte_fr:"Se réjouir secrètement d'être vu",est_correcte:true},{texte_fr:"Faire ouvertement",est_correcte:false},{texte_fr:"Cacher complètement",est_correcte:false},{texte_fr:"Ne pas agir",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Quels sont les remèdes au Kibr (orgueil) ?", texte_ar:'ما علاج الكبر؟', explication:"Se souvenir de son origine (goutte d'eau), de sa fin (cadavre), de sa dépendance totale à Allah, et étudier l'humilité du Prophète ﷺ.", reponses:[{texte_fr:"Méditer sur son origine, sa fin et sa dépendance",est_correcte:true},{texte_fr:"S'enrichir",est_correcte:false},{texte_fr:"Rechercher la gloire",est_correcte:false},{texte_fr:"Mépriser les pauvres",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Quelle est la définition du Hayya' (pudeur) en islam ?", texte_ar:'ما الحياء في الإسلام؟', explication:"Le Prophète ﷺ : « La pudeur fait partie de la foi. » C'est un caractère qui repousse l'indécence et incite au bien.", dalil_ref:"Sahih al-Bukhari n°9", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Caractère qui repousse le mal et incite au bien",est_correcte:true},{texte_fr:"Timidité maladive",est_correcte:false},{texte_fr:"Honte de la religion",est_correcte:false},{texte_fr:"Isolement",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Qu'est-ce que la maladie de l'âme appelée 'Ujb (suffisance) ?", texte_ar:'ما هو العجب؟', explication:"S'admirer soi-même pour ses œuvres ou qualités, oubliant que tout vient d'Allah. C'est l'antichambre de l'orgueil et anéantit les œuvres.", reponses:[{texte_fr:"S'admirer soi-même, oubliant qu'Allah est la source",est_correcte:true},{texte_fr:"Être en santé",est_correcte:false},{texte_fr:"Être patient",est_correcte:false},{texte_fr:"Être pauvre",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Quels sont les droits du musulman sur son frère selon le hadith ?", texte_ar:'ما حقوق المسلم على المسلم؟', explication:"Cinq : saluer, visiter le malade, suivre la jinaza, répondre à l'invitation, dire « Yarhamouk Allah » à celui qui éternue.", dalil_ref:"Sahih al-Bukhari n°1240", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Salut, visite, jinaza, invitation, éternuement",est_correcte:true},{texte_fr:"Argent uniquement",est_correcte:false},{texte_fr:"Aide militaire",est_correcte:false},{texte_fr:"Aucun droit",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Que signifie le hadith « Personne ne croit vraiment tant qu'il n'aime... » ?", texte_ar:'ما حديث لا يؤمن أحدكم؟', explication:"« Personne ne croit vraiment tant qu'il n'aime pour son frère ce qu'il aime pour lui-même. » C'est le fondement de la fraternité islamique.", dalil_ref:"Sahih al-Bukhari n°13 ; Muslim n°45", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Aimer pour son frère ce qu'on aime pour soi",est_correcte:true},{texte_fr:"Faire fortune",est_correcte:false},{texte_fr:"Voyager beaucoup",est_correcte:false},{texte_fr:"Vivre seul",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Qu'est-ce que la Khushu' dans la prière ?", texte_ar:'ما هو الخشوع في الصلاة؟', explication:"Concentration du cœur et des membres pendant la prière, conscience de se tenir devant Allah. Première chose retirée à la fin des temps.", dalil_ref:"Sourate Al-Mu'minun 23:1-2", reponses:[{texte_fr:"Concentration du cœur devant Allah",est_correcte:true},{texte_fr:"Pleurer fort",est_correcte:false},{texte_fr:"Mémoriser le Coran",est_correcte:false},{texte_fr:"Prier vite",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Quelle est la sagesse de la mention fréquente d'Allah (Dhikr) ?", texte_ar:'ما حكمة كثرة الذكر؟', explication:"Le dhikr purifie le cœur, repousse Shaytan, attire les anges et la lumière. Allah dit : « C'est par le rappel d'Allah que les cœurs s'apaisent. » (Ar-Ra'd 13:28)", dalil_ref:"Sourate Ar-Ra'd 13:28", reponses:[{texte_fr:"Purifie le cœur, repousse Shaytan, apaise",est_correcte:true},{texte_fr:"Sans utilité",est_correcte:false},{texte_fr:"Fait perdre du temps",est_correcte:false},{texte_fr:"Réservé aux savants",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Quelle est la portée de la sincérité (Sidq) en islam ?", texte_ar:'ما أهمية الصدق؟', explication:"Le Prophète ﷺ : « La véracité mène à la piété et la piété au Paradis. Le mensonge mène à la perversité et la perversité à l'Enfer. »", dalil_ref:"Sahih al-Bukhari n°6094 ; Muslim n°2607", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Mène à la piété et au Paradis",est_correcte:true},{texte_fr:"Sans importance",est_correcte:false},{texte_fr:"Réservée aux affaires",est_correcte:false},{texte_fr:"Égale au mensonge",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Que signifie le hadith « La religion est conseil » ?", texte_ar:'ما معنى الدين النصيحة؟', explication:"Le Prophète ﷺ : « La religion est conseil. À qui ? À Allah, à Son Livre, à Son Messager, aux dirigeants des musulmans et à leurs masses. »", dalil_ref:"Sahih Muslim n°55", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Sincérité envers Allah, Son Livre, Son Messager, les dirigeants et le peuple",est_correcte:true},{texte_fr:"Conseiller son entourage seulement",est_correcte:false},{texte_fr:"Donner son avis sur tout",est_correcte:false},{texte_fr:"Critiquer ouvertement",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Qu'est-ce que la patience en cas d'épreuve (Sabr 'ala al-Bala') ?", texte_ar:'ما الصبر على البلاء؟', explication:"Le 3e et plus difficile degré du sabr : ne pas se révolter contre Allah, ne pas se plaindre aux créatures, accepter le décret sans murmure.", reponses:[{texte_fr:"Ne pas se plaindre, accepter le décret",est_correcte:true},{texte_fr:"Pleurer constamment",est_correcte:false},{texte_fr:"Maudire le destin",est_correcte:false},{texte_fr:"Ignorer l'épreuve",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Qu'est-ce que l'Amr bil Ma'ruf wan Nahy 'an al-Munkar ?", texte_ar:'ما الأمر بالمعروف والنهي عن المنكر؟', explication:"Commander le bien et interdire le mal — devoir collectif (fard kifaya) de la communauté pour préserver son intégrité.", dalil_ref:"Sourate Al-Imran 3:104", reponses:[{texte_fr:"Commander le bien, interdire le mal",est_correcte:true},{texte_fr:"Donner l'aumône",est_correcte:false},{texte_fr:"Faire le jeûne",est_correcte:false},{texte_fr:"Prier en commun",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Quels sont les 3 niveaux de changer le mal selon le hadith ?", texte_ar:'ما درجات تغيير المنكر؟', explication:"« Quiconque voit un mal qu'il le change avec sa main ; s'il ne peut pas, avec sa langue ; s'il ne peut pas, avec son cœur — et c'est la plus faible des fois. »", dalil_ref:"Sahih Muslim n°49", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Main, langue, cœur",est_correcte:true},{texte_fr:"Mémoire, étude, écriture",est_correcte:false},{texte_fr:"Voyage, exil, retour",est_correcte:false},{texte_fr:"Don, prière, jeûne",est_correcte:false}] },
  { domaine:'akhlaq', niveau:4, texte_fr:"Que représente le bon caractère (Husn al-Khuluq) selon le hadith ?", texte_ar:'ما قيمة حسن الخلق؟', explication:"« Rien n'est plus lourd dans la balance du croyant qu'un bon caractère. » Le Prophète ﷺ a été envoyé pour « parfaire les nobles caractères ».", dalil_ref:"Sunan at-Tirmidhi n°2002, n°2018", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Plus lourd que tout dans la balance",est_correcte:true},{texte_fr:"Sans poids",est_correcte:false},{texte_fr:"Moins que la prière",est_correcte:false},{texte_fr:"Égal au jeûne seulement",est_correcte:false}] },

  // ===== AKHLAQ N5 (+15) =====
  { domaine:'akhlaq', niveau:5, texte_fr:"Quels sont les 4 piliers de la purification du cœur selon Ibn al-Qayyim ?", texte_ar:'ما أركان تزكية القلب الأربعة عند ابن القيم؟', explication:"1) Mahabba (amour d'Allah), 2) Khawf (crainte), 3) Raja' (espoir), 4) Tawakkul (confiance). Équilibre indispensable pour la santé spirituelle.", dalil_ref:"Madarij as-Salikin", reponses:[{texte_fr:"Mahabba, Khawf, Raja', Tawakkul",est_correcte:true},{texte_fr:"Salat, Zakat, Sawm, Hajj",est_correcte:false},{texte_fr:"Patience uniquement",est_correcte:false},{texte_fr:"Pauvreté volontaire",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quelle est la différence entre Khawf, Khashya et Rahba ?", texte_ar:'ما الفرق بين الخوف والخشية والرهبة؟', explication:"Khawf = crainte générale du châtiment. Khashya = crainte fondée sur la connaissance de la grandeur d'Allah. Rahba = crainte poussant à fuir le péché.", reponses:[{texte_fr:"Khawf général, Khashya par connaissance, Rahba fuyant",est_correcte:true},{texte_fr:"Identiques",est_correcte:false},{texte_fr:"3 mots étrangers",est_correcte:false},{texte_fr:"3 stades de prière",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quels sont les 3 degrés de l'amour pour Allah ?", texte_ar:'ما درجات محبة الله الثلاث؟', explication:"1) Mahabba 'amma (commune à tous les croyants), 2) Mahabba khassa (des sincères), 3) Mahabba khassat al-khassa (degré le plus élevé : aimer ce qu'Allah aime, détester ce qu'Il déteste).", dalil_ref:"Madarij as-Salikin", reponses:[{texte_fr:"Commune, des sincères, des plus proches",est_correcte:true},{texte_fr:"3 amours interdits",est_correcte:false},{texte_fr:"3 types d'amour humain",est_correcte:false},{texte_fr:"3 prières quotidiennes",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Qu'est-ce que la « Mahabba lillah wa lillah » ?", texte_ar:'ما المحبة لله ولله؟', explication:"Aimer une personne, une œuvre ou une chose pour Allah (parce qu'Allah l'aime) et non pour un intérêt personnel. C'est le plus pur des amours.", dalil_ref:"Sahih al-Bukhari n°6041", reponses:[{texte_fr:"Aimer pour Allah, sans intérêt personnel",est_correcte:true},{texte_fr:"S'aimer soi-même",est_correcte:false},{texte_fr:"Aimer la richesse",est_correcte:false},{texte_fr:"Aimer la fame",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quelle est la définition de l'Inaba (retour à Allah) ?", texte_ar:'ما تعريف الإنابة؟', explication:"Retour fréquent vers Allah par le cœur, plus profond que la tawba. Implique amour, espoir et soumission. Allah l'aime des Awwabin (revenant à Lui).", reponses:[{texte_fr:"Retour fréquent du cœur vers Allah",est_correcte:true},{texte_fr:"Aller en pèlerinage",est_correcte:false},{texte_fr:"Donner de l'argent",est_correcte:false},{texte_fr:"Lire un livre",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Que signifie la Niya (intention) selon les savants ?", texte_ar:'ما النية عند العلماء؟', explication:"« La détermination du cœur à accomplir un acte pour Allah ». L'intention précède l'action et lui donne sa valeur. Hadith n°1 de Bukhari : « Les actions selon les intentions. »", dalil_ref:"Sahih al-Bukhari n°1", reponses:[{texte_fr:"Détermination du cœur à agir pour Allah",est_correcte:true},{texte_fr:"Prononcer en arabe",est_correcte:false},{texte_fr:"Demander conseil",est_correcte:false},{texte_fr:"Faire un vœu écrit",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Que veut dire « Furqan » dans le contexte du cœur ?", texte_ar:'ما الفرقان في القلب؟', explication:"Lumière de la taqwa : la capacité de distinguer vérité du mensonge, bien du mal. Allah dit : « Si vous craignez Allah, Il vous accordera Furqan. » (Al-Anfal 8:29)", dalil_ref:"Sourate Al-Anfal 8:29", reponses:[{texte_fr:"Lumière de la taqwa distinguant vrai du faux",est_correcte:true},{texte_fr:"Un livre",est_correcte:false},{texte_fr:"Une bataille",est_correcte:false},{texte_fr:"Une parole interdite",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quels sont les 4 poisons du cœur selon Ibn al-Qayyim ?", texte_ar:'ما سموم القلب الأربعة؟', explication:"1) Parole excessive, 2) Regards excessifs, 3) Nourriture excessive, 4) Compagnie excessive. Empoisonnent le cœur et l'éloignent d'Allah.", dalil_ref:"al-Fawa'id d'Ibn al-Qayyim", reponses:[{texte_fr:"Parole, regard, nourriture, compagnie en excès",est_correcte:true},{texte_fr:"Pauvreté, richesse, voyage, isolement",est_correcte:false},{texte_fr:"Sommeil, repos, méditation, étude",est_correcte:false},{texte_fr:"4 prières surérogatoires",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Qu'est-ce que la patience absolue selon al-Ghazali ?", texte_ar:'ما الصبر المطلق عند الغزالي؟', explication:"« Persévérer dans l'effort vers Allah malgré les obstacles intérieurs et extérieurs. » Pilier de toutes les vertus.", dalil_ref:"Ihya' Ulum ad-Din d'al-Ghazali", reponses:[{texte_fr:"Persévérer vers Allah malgré les obstacles",est_correcte:true},{texte_fr:"Attendre passivement",est_correcte:false},{texte_fr:"Ignorer la difficulté",est_correcte:false},{texte_fr:"Plaintes silencieuses",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quelle est la définition de la gratitude (Shukr) selon les savants ?", texte_ar:'ما الشكر عند العلماء؟', explication:"Reconnaissance avec 3 dimensions : 1) cœur (sentir le bienfait), 2) langue (louer Allah), 3) membres (utiliser le bienfait en obéissance).", reponses:[{texte_fr:"Cœur (sentir), langue (louer), membres (obéir)",est_correcte:true},{texte_fr:"Dire merci uniquement",est_correcte:false},{texte_fr:"Donner un cadeau",est_correcte:false},{texte_fr:"Pleurer de joie",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quel est le degré le plus élevé de la patience ?", texte_ar:'ما أعلى درجات الصبر؟', explication:"As-Sabr 'ala al-Bala' (face à l'épreuve), surtout l'épreuve qui touche au cœur (perte d'enfant, maladie longue). Le Rida (agrément) y est encore supérieur.", reponses:[{texte_fr:"Face aux épreuves graves du cœur",est_correcte:true},{texte_fr:"Patience dans la nourriture",est_correcte:false},{texte_fr:"Patience au sommeil",est_correcte:false},{texte_fr:"Patience au repos",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Que signifie l'expression « al-Khawf wa ar-Raja' kal-Janahayn » ?", texte_ar:'ما معنى الخوف والرجاء كالجناحين؟', explication:"« La crainte et l'espoir sont comme deux ailes » du croyant. Ne voler que d'une seule mène à la déviation : pure crainte → désespoir, pur espoir → laxisme.", dalil_ref:"Ibn al-Qayyim, Madarij as-Salikin", reponses:[{texte_fr:"Crainte et espoir doivent être équilibrés",est_correcte:true},{texte_fr:"Crainte plus importante",est_correcte:false},{texte_fr:"Espoir plus important",est_correcte:false},{texte_fr:"Sans rapport",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Quelle est la définition du Wara' ?", texte_ar:'ما تعريف الورع؟', explication:"« S'abstenir de ce qui pourrait nuire dans l'au-delà » — y compris les choses douteuses (shubuhat). Plus large que le simple haram.", dalil_ref:"Sahih al-Bukhari n°52", reponses:[{texte_fr:"S'abstenir du douteux et de ce qui pourrait nuire",est_correcte:true},{texte_fr:"Avarice",est_correcte:false},{texte_fr:"Isolement",est_correcte:false},{texte_fr:"Richesse",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Qu'est-ce que la « Suhba » (compagnie) dans le tazkiya ?", texte_ar:'ما الصحبة في التزكية؟', explication:"Choisir des compagnons pieux qui rappellent Allah. Le Prophète ﷺ : « L'homme est sur la religion de son ami intime. »", dalil_ref:"Sunan at-Tirmidhi n°2378", grade_hadith:"Hadith Hasan", reponses:[{texte_fr:"Choisir des compagnons pieux",est_correcte:true},{texte_fr:"Vivre isolé",est_correcte:false},{texte_fr:"Fréquenter les riches",est_correcte:false},{texte_fr:"Voyager seul",est_correcte:false}] },
  { domaine:'akhlaq', niveau:5, texte_fr:"Que signifie la « Faqr » spirituelle ?", texte_ar:'ما الفقر الروحي؟', explication:"Le sentiment profond de dépendance totale à Allah. Allah dit : « Ô gens, vous avez besoin d'Allah, et Allah Se suffit. » (Fatir 35:15). Plus haute que la richesse extérieure.", dalil_ref:"Sourate Fatir 35:15", reponses:[{texte_fr:"Sentiment de dépendance totale à Allah",est_correcte:true},{texte_fr:"Pauvreté matérielle",est_correcte:false},{texte_fr:"Refus du travail",est_correcte:false},{texte_fr:"Mendicité",est_correcte:false}] },

  // ===== AQIDA N4 (+20) =====
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la Hayat al-Barzakh ?", texte_ar:'ما حياة البرزخ؟', explication:"Vie intermédiaire entre la mort et la résurrection. L'âme y connaît bonheur ou châtiment selon ses œuvres. Le corps peut y être conscient.", dalil_ref:"Sourate Al-Mu'minun 23:100", reponses:[{texte_fr:"Vie intermédiaire entre mort et résurrection",est_correcte:true},{texte_fr:"Vie terrestre",est_correcte:false},{texte_fr:"Paradis éternel",est_correcte:false},{texte_fr:"Anéantissement",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Combien de portes y a-t-il au Paradis ?", texte_ar:'كم باباً للجنة؟', explication:"8 portes selon le hadith authentique : porte de la prière, de la zakat, du jihad, du rayyan (pour les jeûneurs), etc.", dalil_ref:"Sahih al-Bukhari n°3257", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"8 portes",est_correcte:true},{texte_fr:"7 portes",est_correcte:false},{texte_fr:"4 portes",est_correcte:false},{texte_fr:"1 porte",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Combien de portes y a-t-il à l'Enfer ?", texte_ar:'كم باباً للنار؟', explication:"7 portes selon Sourate al-Hijr 15:44 : « Elle a sept portes ; à chaque porte une fraction d'eux est assignée. »", dalil_ref:"Sourate Al-Hijr 15:44", reponses:[{texte_fr:"7 portes",est_correcte:true},{texte_fr:"3 portes",est_correcte:false},{texte_fr:"1 porte",est_correcte:false},{texte_fr:"100 portes",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la croyance au Hawd (bassin du Prophète ﷺ) ?", texte_ar:'ما الإيمان بالحوض؟', explication:"Bassin du Prophète ﷺ dans l'au-delà ; son eau est plus blanche que le lait, plus douce que le miel. Qui en boit n'aura plus jamais soif.", dalil_ref:"Sahih al-Bukhari n°6579 ; Muslim n°2292", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Bassin du Prophète ﷺ : qui en boit n'a plus soif",est_correcte:true},{texte_fr:"Mer terrestre",est_correcte:false},{texte_fr:"Métaphore sans réalité",est_correcte:false},{texte_fr:"Puits à Médine",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la croyance à la lecture des œuvres ?", texte_ar:'ما الإيمان بقراءة الصحف؟', explication:"Chaque personne recevra son livre d'œuvres au Jour du Jugement, soit dans la main droite (réussite), soit dans la main gauche (échec).", dalil_ref:"Sourate Al-Haqqa 69:19-25", reponses:[{texte_fr:"Livre dans main droite (réussite) ou gauche (échec)",est_correcte:true},{texte_fr:"Lecture orale collective",est_correcte:false},{texte_fr:"Aucun livre",est_correcte:false},{texte_fr:"Tout est secret",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la « Ru'yat Allah » (la vision d'Allah) ?", texte_ar:'ما رؤية الله؟', explication:"Les croyants verront Allah de leurs yeux au Paradis. Confirmé par plusieurs hadiths mutawatir. Niable par les Mu'tazila — innovation rejetée par Ahlu Sunnah.", dalil_ref:"Sourate Al-Qiyama 75:22-23 ; Sahih al-Bukhari", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Les croyants verront Allah au Paradis",est_correcte:true},{texte_fr:"Personne ne Le verra jamais",est_correcte:false},{texte_fr:"Seuls les anges Le voient",est_correcte:false},{texte_fr:"Vision symbolique uniquement",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qui sont les 4 Imams de Ahlu Sunnah ?", texte_ar:'من هم الأئمة الأربعة عند أهل السنة؟', explication:"Abu Hanifa (80-150 H), Malik ibn Anas (93-179 H), Shafi'i (150-204 H), Ahmad ibn Hanbal (164-241 H). Tous suivent le Coran et la Sunnah.", reponses:[{texte_fr:"Abu Hanifa, Malik, Shafi'i, Ahmad",est_correcte:true},{texte_fr:"Les 4 califes",est_correcte:false},{texte_fr:"Les fils du Prophète",est_correcte:false},{texte_fr:"Les 4 derniers compagnons",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quelle est la position d'Ahlu Sunnah sur les Sahaba ?", texte_ar:'ما موقف أهل السنة من الصحابة؟', explication:"Tous les Compagnons sont 'udul (intègres) : on les aime, on demande le pardon pour eux, on se tait sur les divergences entre eux.", dalil_ref:"al-Aqida al-Wasitiyya d'Ibn Taymiyya", reponses:[{texte_fr:"Tous intègres, aimés, on se tait sur leurs divergences",est_correcte:true},{texte_fr:"Critiquer leurs erreurs",est_correcte:false},{texte_fr:"Insulter certains",est_correcte:false},{texte_fr:"Tous infaillibles",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quelle est la position sur la magie (Sihr) en aqida ?", texte_ar:'ما حكم السحر في العقيدة؟', explication:"La magie existe réellement (Sourate al-Baqara 2:102). Sa pratique est un kufr s'il y a association d'esprits ; même sans, c'est un péché majeur.", dalil_ref:"Sourate Al-Baqara 2:102", reponses:[{texte_fr:"Existe réellement, kufr ou péché majeur",est_correcte:true},{texte_fr:"N'existe pas",est_correcte:false},{texte_fr:"Permise pour le bien",est_correcte:false},{texte_fr:"Simple illusion",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quel est le statut du voyance et de l'astrologie ?", texte_ar:'ما حكم العرافة والتنجيم؟', explication:"Interdites. « Quiconque interroge un voyant et croit ce qu'il dit a mécru en ce qui a été révélé à Muhammad ﷺ. »", dalil_ref:"Sahih Muslim n°2230", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Interdites, croire au voyant = mécréance",est_correcte:true},{texte_fr:"Recommandées",est_correcte:false},{texte_fr:"Permises pour le bien",est_correcte:false},{texte_fr:"Obligatoires",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quels sont les 3 types de Tawassul (intermédiaire) légitimes ?", texte_ar:'ما أنواع التوسل المشروع؟', explication:"1) Par les Noms et Attributs d'Allah, 2) Par ses propres œuvres pieuses, 3) Par l'invocation d'un vivant pieux. Tout autre tawassul (par les morts) est innovation.", reponses:[{texte_fr:"Par Noms d'Allah, ses œuvres, invocation d'un vivant",est_correcte:true},{texte_fr:"Par les tombes uniquement",est_correcte:false},{texte_fr:"Toute forme permise",est_correcte:false},{texte_fr:"Aucun tawassul permis",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la « Hujja » (preuve obligatoire) en aqida ?", texte_ar:'ما الحجة في العقيدة؟', explication:"La preuve issue du Coran et de la Sunnah authentique. C'est la base : « Apportez vos preuves si vous êtes véridiques. » (Al-Baqara 2:111)", dalil_ref:"Sourate Al-Baqara 2:111", reponses:[{texte_fr:"Coran et Sunnah authentique",est_correcte:true},{texte_fr:"Opinion personnelle",est_correcte:false},{texte_fr:"Coutumes",est_correcte:false},{texte_fr:"Rêves",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quelle est la position sur le mariage avec une non-musulmane ?", texte_ar:'ما حكم الزواج من غير المسلمة؟', explication:"Un musulman peut épouser une chaste des Gens du Livre (juive ou chrétienne) selon Al-Maida 5:5. Mais le mariage d'une musulmane avec un non-musulman est interdit.", dalil_ref:"Sourate Al-Maida 5:5 ; Al-Mumtahana 60:10", reponses:[{texte_fr:"Permis avec chaste juive/chrétienne ; interdit l'inverse",est_correcte:true},{texte_fr:"Totalement interdit",est_correcte:false},{texte_fr:"Permis dans les deux sens",est_correcte:false},{texte_fr:"Permis avec toute religion",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la croyance aux Anges (Mala'ika) ?", texte_ar:'ما الإيمان بالملائكة؟', explication:"Croire qu'ils existent, sont créés de lumière, n'ont ni père ni mère, ne désobéissent jamais à Allah. Chaque ange a une mission.", dalil_ref:"Sahih Muslim n°2996", reponses:[{texte_fr:"Créés de lumière, obéissants, ayant chacun une mission",est_correcte:true},{texte_fr:"Métaphores symboliques",est_correcte:false},{texte_fr:"Demi-dieux",est_correcte:false},{texte_fr:"Inventions humaines",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la croyance aux Jinns ?", texte_ar:'ما الإيمان بالجن؟', explication:"Êtres créés de feu (Ar-Rahman 55:15), invisibles, doués de raison et de libre arbitre. Il y a des jinns musulmans et mécréants. Iblis est un jinn.", dalil_ref:"Sourate Ar-Rahman 55:15 ; Sourate Al-Jinn 72", reponses:[{texte_fr:"Créés de feu, libres, dont musulmans et mécréants",est_correcte:true},{texte_fr:"Légendes folkloriques",est_correcte:false},{texte_fr:"Créés de boue",est_correcte:false},{texte_fr:"Tous mauvais",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quelles sont les conditions d'acceptation des œuvres ?", texte_ar:'ما شروط قبول العمل؟', explication:"Deux : Ikhlas (sincérité pour Allah Seul) et Mutaba'a (conformité à la Sunnah). Allah ne regarde pas les œuvres non sincères ni non conformes.", dalil_ref:"Sourate Al-Kahf 18:110", reponses:[{texte_fr:"Ikhlas (sincérité) et Mutaba'a (conformité à la Sunnah)",est_correcte:true},{texte_fr:"Beaucoup d'argent",est_correcte:false},{texte_fr:"Travail acharné uniquement",est_correcte:false},{texte_fr:"Famille pieuse",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la « Wasatiyya » (la voie médiane) ?", texte_ar:'ما هي الوسطية؟', explication:"L'islam est une voie médiane entre les excès (ghuluw) et les laxismes (tafrit). « Nous avons fait de vous une communauté médiane. » (Al-Baqara 2:143)", dalil_ref:"Sourate Al-Baqara 2:143", reponses:[{texte_fr:"Voie médiane entre excès et laxisme",est_correcte:true},{texte_fr:"Extrémisme",est_correcte:false},{texte_fr:"Indifférence",est_correcte:false},{texte_fr:"Compromis sur la foi",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la « Salaf » dans l'expression Ahlu Sunnah ?", texte_ar:'من هم السلف؟', explication:"Les 3 générations bénies : Sahaba, Tabi'in, Tab' at-Tabi'in. Le Prophète ﷺ a dit : « La meilleure génération est la mienne, puis ceux qui les suivent, puis ceux qui les suivent. »", dalil_ref:"Sahih al-Bukhari n°2652", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"3 premières générations bénies",est_correcte:true},{texte_fr:"Les musulmans modernes",est_correcte:false},{texte_fr:"Les califes seulement",est_correcte:false},{texte_fr:"Les imams des 4 madhabs",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Quels sont les attributs de perfection d'Allah ?", texte_ar:'ما صفات الكمال لله؟', explication:"Allah possède tous les attributs de perfection absolue : Vie, Science, Pouvoir, Volonté, Audition, Vision, Parole, etc. Sans limite ni similitude.", dalil_ref:"Sourate Ash-Shura 42:11", reponses:[{texte_fr:"Tous attributs absolus sans similitude",est_correcte:true},{texte_fr:"Aucun attribut",est_correcte:false},{texte_fr:"Identiques aux humains",est_correcte:false},{texte_fr:"Inconnaissables",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la « 'Adala » des Sahaba ?", texte_ar:'ما عدالة الصحابة؟', explication:"L'intégrité reconnue à tous les Compagnons par consensus de Ahlu Sunnah. Allah a témoigné de leur foi dans plusieurs versets.", dalil_ref:"Sourate At-Tawba 9:100", reponses:[{texte_fr:"Intégrité reconnue à tous les Sahaba par consensus",est_correcte:true},{texte_fr:"Doute sur leur foi",est_correcte:false},{texte_fr:"Égalité avec nous",est_correcte:false},{texte_fr:"Infaillibilité totale",est_correcte:false}] },

  // ===== AQIDA N5 (+21) =====
  { domaine:'aqida', niveau:5, texte_fr:"Quels sont les arguments coraniques pour Tawhid ar-Rububiyya ?", texte_ar:'ما الأدلة القرآنية على توحيد الربوبية؟', explication:"Multiples : Al-Anbiya 21:22 (deux divinités créeraient le désordre), Sourate Luqman 31:25 (les polythéistes reconnaissaient Allah comme Créateur), Sourate Ar-Rum 30:40.", reponses:[{texte_fr:"Al-Anbiya 21:22, Luqman 31:25, Ar-Rum 30:40",est_correcte:true},{texte_fr:"Aucun argument",est_correcte:false},{texte_fr:"Argument unique",est_correcte:false},{texte_fr:"Hadith uniquement",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Que signifie la règle « Innocenter Allah de toute imperfection » (Tanzih) ?", texte_ar:'ما التنزيه؟', explication:"Reconnaître qu'Allah n'a aucun défaut ni limite. Sans tomber dans le ta'til (négation des attributs) — équilibre entre tanzih et ithbat.", reponses:[{texte_fr:"Reconnaître Allah sans défaut, sans nier Ses attributs",est_correcte:true},{texte_fr:"Nier tous les attributs",est_correcte:false},{texte_fr:"L'assimiler à la création",est_correcte:false},{texte_fr:"Ne pas en parler",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quel est l'erreur des Jahmiyya sur les Attributs d'Allah ?", texte_ar:'ما خطأ الجهمية في الصفات؟', explication:"Ta'til : nier tous les attributs réels d'Allah, n'en gardant que des sens abstraits. Mène à un Dieu inexistant. Réfutés par Ahmad ibn Hanbal et les Salaf.", reponses:[{texte_fr:"Ta'til : nier tous les attributs",est_correcte:true},{texte_fr:"Tamthil : Le comparer aux créatures",est_correcte:false},{texte_fr:"Affirmation correcte",est_correcte:false},{texte_fr:"Voie médiane",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quelle est l'erreur des Mushabbiha ?", texte_ar:'ما خطأ المشبهة؟', explication:"Tamthil : assimiler les attributs d'Allah à ceux de la création (ex: dire « la main d'Allah est comme la nôtre »). Erreur opposée aux Jahmiyya.", reponses:[{texte_fr:"Tamthil : assimiler Allah aux créatures",est_correcte:true},{texte_fr:"Ta'til : nier les attributs",est_correcte:false},{texte_fr:"Position correcte",est_correcte:false},{texte_fr:"Refus de la révélation",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que le « Tawhid al-Hakimiyya » selon certains contemporains ?", texte_ar:'ما توحيد الحاكمية؟', explication:"Catégorie ajoutée par certains modernes : Allah Seul a le droit de législation. Ahlu Sunnah l'incluent dans Tawhid al-Uluhiyya, sans la séparer.", reponses:[{texte_fr:"Allah Seul législateur, déjà inclus dans Uluhiyya",est_correcte:true},{texte_fr:"5e catégorie séparée obligatoire",est_correcte:false},{texte_fr:"Innovation égarée",est_correcte:false},{texte_fr:"Sans rapport avec Tawhid",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que la croyance à al-Lawh al-Mahfuz (Tablette Préservée) ?", texte_ar:'ما الإيمان باللوح المحفوظ؟', explication:"Tablette où Allah a écrit le destin de toute chose 50 000 ans avant la création des cieux et de la terre.", dalil_ref:"Sahih Muslim n°2653 ; Al-Buruj 85:22", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Tablette où Allah a écrit toutes choses avant la création",est_correcte:true},{texte_fr:"Cahier d'école antique",est_correcte:false},{texte_fr:"Métaphore sans réalité",est_correcte:false},{texte_fr:"Livre des prophètes",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quels sont les 3 degrés du Sabr selon Ibn Taymiyya ?", texte_ar:'ما درجات الصبر عند ابن تيمية؟', explication:"1) Sabr 'ala at-Ta'a (sur l'obéissance), 2) Sabr 'an al-Ma'siya (contre la désobéissance), 3) Sabr 'ala al-Bala' (face à l'épreuve).", reponses:[{texte_fr:"Sur l'obéissance, contre la désobéissance, face au mal",est_correcte:true},{texte_fr:"Avec famille, travail, voyage",est_correcte:false},{texte_fr:"Matin, midi, soir",est_correcte:false},{texte_fr:"Enfance, jeunesse, vieillesse",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Que sont les Asma' Allah al-Husna ?", texte_ar:'ما الأسماء الحسنى؟', explication:"99 Noms majestueux d'Allah. Celui qui les retient (les apprend, comprend, vit) entrera au Paradis. Chacun est une révélation de Sa perfection.", dalil_ref:"Sahih al-Bukhari n°2736", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"99 Noms d'Allah que retenir mène au Paradis",est_correcte:true},{texte_fr:"Noms des prophètes",est_correcte:false},{texte_fr:"Noms des anges",est_correcte:false},{texte_fr:"Noms des califes",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que la « Wahdat al-Wujud » et sa réfutation ?", texte_ar:'ما وحدة الوجود وما الرد عليها؟', explication:"Doctrine d'Ibn Arabi disant que tout est Allah (panthéisme). Ahlu Sunnah la rejettent : c'est une innovation grave contredisant le Tawhid (Allah est distinct de Sa création).", reponses:[{texte_fr:"Panthéisme rejeté car contredit le Tawhid",est_correcte:true},{texte_fr:"Doctrine sunnite",est_correcte:false},{texte_fr:"Position majoritaire",est_correcte:false},{texte_fr:"Sens du Tawhid",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Que dit Ahlu Sunnah sur la possibilité de la magie sur le Prophète ﷺ ?", texte_ar:'هل أصابت السحر النبي ﷺ؟', explication:"Oui, par Labid ibn al-A'sam. Mais elle n'a pas affecté la transmission de la Révélation. Allah l'a guéri et révélé al-Mu'awwidhatayn pour s'en protéger.", dalil_ref:"Sahih al-Bukhari n°5763 ; Muslim n°2189", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Oui (Labid), sans affecter la révélation",est_correcte:true},{texte_fr:"Impossible",est_correcte:false},{texte_fr:"Mais a affecté la révélation",est_correcte:false},{texte_fr:"Légende",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quel est le statut du Mahdi attendu en aqida sunnite ?", texte_ar:'ما حكم الإيمان بالمهدي عند أهل السنة؟', explication:"Croyance authentique : un descendant du Prophète ﷺ apparaîtra à la fin des temps, remplira la terre de justice. Confirmé par des hadiths mutawatir.", dalil_ref:"Sunan Abi Dawud n°4282", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Authentique : descendant qui justifiera la terre",est_correcte:true},{texte_fr:"Innovation chiite",est_correcte:false},{texte_fr:"Légende",est_correcte:false},{texte_fr:"Inconnu",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que la descente d'Isa عليه السلام à la fin des temps ?", texte_ar:'ما نزول عيسى آخر الزمان؟', explication:"Isa fils de Maryam descendra du ciel à Damas, tuera le Dajjal, gouvernera avec la Shariah islamique, brisera la croix, abolira la jizya.", dalil_ref:"Sahih al-Bukhari n°3448 ; Muslim n°155", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Tuera le Dajjal, gouvernera avec l'islam",est_correcte:true},{texte_fr:"Reviendra comme prophète indépendant",est_correcte:false},{texte_fr:"Mort définitivement",est_correcte:false},{texte_fr:"Symbole sans réalité",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qui est le Dajjal selon les hadiths ?", texte_ar:'من هو الدجال؟', explication:"L'imposteur Antéchrist : prétendra à la divinité, montrera des prodiges trompeurs, sera tué par Isa. Le Prophète ﷺ nous a appris à réciter Sourate al-Kahf pour s'en protéger.", dalil_ref:"Sahih Muslim n°2934", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Antéchrist tué par Isa à la fin des temps",est_correcte:true},{texte_fr:"Roi juste",est_correcte:false},{texte_fr:"Compagnon du Prophète",est_correcte:false},{texte_fr:"Personnage symbolique uniquement",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Que signifient les Petits Signes (Ashrat as-Sa'a as-Sughra) ?", texte_ar:'ما علامات الساعة الصغرى؟', explication:"Nombreux signes précédant les grands : multiplication de la richesse, ignorance, alcool, désobéissance, etc. La venue du Prophète ﷺ lui-même est un signe.", dalil_ref:"Sahih al-Bukhari n°6038", reponses:[{texte_fr:"Multiplication des péchés, ignorance, etc.",est_correcte:true},{texte_fr:"3 signes seulement",est_correcte:false},{texte_fr:"Inconnus",est_correcte:false},{texte_fr:"Réservés au Mahdi",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que le « Kursi » (Marchepied) d'Allah ?", texte_ar:'ما الكرسي؟', explication:"Distinct du 'Arsh (Trône). Ibn Abbas : « Le Kursi est le marchepied des pieds (d'Allah). » Affirmé sans modalité par les Salaf. Plus grand que les 7 cieux et la terre.", dalil_ref:"Tafsir Ibn Kathir d'Ayat al-Kursi", reponses:[{texte_fr:"Marchepied d'Allah, plus grand que cieux et terre",est_correcte:true},{texte_fr:"Identique au Trône",est_correcte:false},{texte_fr:"Métaphore vide",est_correcte:false},{texte_fr:"Chaise terrestre",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quelle est l'œuvre de référence d'Ibn Taymiyya en aqida ?", texte_ar:'ما أهم كتاب لابن تيمية في العقيدة؟', explication:"al-'Aqida al-Wasitiyya — exposé clair de la croyance des Salaf, écrit en réponse à un cadi de Wasit. Référence majeure d'Ahlu Sunnah.", reponses:[{texte_fr:"al-'Aqida al-Wasitiyya",est_correcte:true},{texte_fr:"Riyad as-Salihin",est_correcte:false},{texte_fr:"Ihya' Ulum ad-Din",est_correcte:false},{texte_fr:"Muqaddima d'Ibn Khaldun",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quelles sont les conditions du Takfir (déclarer mécréant) ?", texte_ar:'ما شروط التكفير؟', explication:"Strictes : preuve claire, comprehension de la personne, absence de coercition, absence d'interprétation valable. Les empêcheurs sont nombreux. Réservé aux savants.", reponses:[{texte_fr:"Strictes : preuve, compréhension, absence d'excuses",est_correcte:true},{texte_fr:"Très faciles",est_correcte:false},{texte_fr:"Aucune condition",est_correcte:false},{texte_fr:"Réservées à l'État",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Que signifie le verset « Allah ne charge une âme... » ?", texte_ar:'ما معنى لا يكلف الله نفساً إلا وسعها؟', explication:"« Allah ne charge une âme que de ce qu'elle peut supporter. » (Al-Baqara 2:286) — fondement de la justice divine et de l'accessibilité de la religion.", dalil_ref:"Sourate Al-Baqara 2:286", reponses:[{texte_fr:"La Shariah est toujours accessible et juste",est_correcte:true},{texte_fr:"On peut faire ce qu'on veut",est_correcte:false},{texte_fr:"Allah charge tout le monde pareil",est_correcte:false},{texte_fr:"Texte abrogé",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que la croyance à la « Hisab » (compte des actions) ?", texte_ar:'ما الإيمان بالحساب؟', explication:"Chaque personne sera interrogée sur ses œuvres au Jour du Jugement. Certains seront jugés rapidement, d'autres en détail. Les rapprochés d'Allah passeront sans hisab.", dalil_ref:"Sourate Al-Ghashiya 88:26 ; Sahih al-Bukhari n°6537", reponses:[{texte_fr:"Compte précis des œuvres au Jour du Jugement",est_correcte:true},{texte_fr:"Aucun compte",est_correcte:false},{texte_fr:"Tous identiques",est_correcte:false},{texte_fr:"Compte uniquement des mécréants",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Que signifie le terme « Awliya' Allah » (les amis d'Allah) ?", texte_ar:'من هم أولياء الله؟', explication:"« Ceux qui croient et craignent (Allah). » (Yunus 10:62-63). Définition coranique simple. Pas réservés à une élite — tout croyant pieux en fait partie.", dalil_ref:"Sourate Yunus 10:62-63", reponses:[{texte_fr:"Les croyants qui craignent Allah",est_correcte:true},{texte_fr:"Une élite mystique",est_correcte:false},{texte_fr:"Les morts vénérés",est_correcte:false},{texte_fr:"Les rois pieux",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quels sont les piliers de la Tawba (repentir) ?", texte_ar:'ما أركان التوبة؟', explication:"3 si le péché est entre serviteur et Allah : 1) Cesser le péché, 2) Le regretter, 3) Décider de ne pas y revenir. 4e pilier si lésion d'un humain : restituer son droit.", reponses:[{texte_fr:"Cesser, regretter, décider de ne pas y revenir (+restituer si humain lésé)",est_correcte:true},{texte_fr:"Donner de l'argent",est_correcte:false},{texte_fr:"Voyager loin",est_correcte:false},{texte_fr:"Ne rien faire",est_correcte:false}] },

  // ===== HADITH N5 (+18) =====
  { domaine:'hadith', niveau:5, texte_fr:"Combien de hadiths Mutawatirs sont reconnus ?", texte_ar:'كم عدد الأحاديث المتواترة؟', explication:"Les muhaddithun en ont compilé ~310 (selon as-Suyuti dans al-Azhar al-Mutanathira). Tous donnent certitude absolue (yaqin).", reponses:[{texte_fr:"~310 selon as-Suyuti",est_correcte:true},{texte_fr:"10 seulement",est_correcte:false},{texte_fr:"100 000",est_correcte:false},{texte_fr:"Aucun",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qui est l'Imam ad-Daraqutni ?", texte_ar:'من هو الإمام الدارقطني؟', explication:"Ali ibn Umar ad-Daraqutni (306-385 H), grand critique de hadith. Ses Sunan et son 'Ilal sont références. Surnommé Amir al-Mu'minin fi-l-Hadith.", reponses:[{texte_fr:"Grand critique de hadith, IVe siècle",est_correcte:true},{texte_fr:"Calife abbasside",est_correcte:false},{texte_fr:"Prophète",est_correcte:false},{texte_fr:"Compagnon",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qu'est-ce que la science des 'Ilal al-Hadith ?", texte_ar:'ما علم العلل؟', explication:"Science des défauts cachés des hadiths apparemment authentiques. Très subtile, maîtrisée seulement par les grands critiques comme ad-Daraqutni.", reponses:[{texte_fr:"Détecter les défauts cachés des hadiths sains en apparence",est_correcte:true},{texte_fr:"Apprendre les hadiths par cœur",est_correcte:false},{texte_fr:"Réciter avec tajwid",est_correcte:false},{texte_fr:"Comparer aux 4 madhabs",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Combien de générations de critiques sont reconnues en jarh wa ta'dil ?", texte_ar:'كم طبقة في الجرح والتعديل؟', explication:"5 à 6 selon Ibn Hajar dans Taqrib at-Tahdhib : des purs Compagnons aux contemporains. Plus on remonte, plus la fiabilité est haute.", reponses:[{texte_fr:"5 à 6 générations",est_correcte:true},{texte_fr:"1 seule",est_correcte:false},{texte_fr:"100 générations",est_correcte:false},{texte_fr:"Sans hiérarchie",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Que signifie « Thiqa » comme grade de narrateur ?", texte_ar:'ما درجة الثقة في الرجال؟', explication:"« Fiable » : narrateur intègre et précis. Son hadith est sahih en l'absence d'autres défauts. Plus haut grade ordinaire.", reponses:[{texte_fr:"Narrateur fiable : intègre et précis",est_correcte:true},{texte_fr:"Narrateur mauvais",est_correcte:false},{texte_fr:"Narrateur inconnu",est_correcte:false},{texte_fr:"Narrateur menteur",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Quelle est la différence entre « Da'if » et « Matruk » ?", texte_ar:'ما الفرق بين الضعيف والمتروك؟', explication:"Da'if = faible (défaut léger ou modéré). Matruk = abandonné (suspecté de mensonge). Le matruk est plus grave que le simple da'if.", reponses:[{texte_fr:"Da'if = faible, Matruk = abandonné (suspect)",est_correcte:true},{texte_fr:"Identiques",est_correcte:false},{texte_fr:"Tous deux sahih",est_correcte:false},{texte_fr:"Termes inventés",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Que sont les Mubham (narrateurs anonymes) ?", texte_ar:'من هم المبهمون في السند؟', explication:"Narrateurs non nommés dans une chaîne (« un homme m'a rapporté »). Hadith inacceptable s'il dépend d'eux, sauf cas particuliers.", reponses:[{texte_fr:"Narrateurs non identifiés dans la chaîne",est_correcte:true},{texte_fr:"Narrateurs ambigus",est_correcte:false},{texte_fr:"Voleurs",est_correcte:false},{texte_fr:"Étudiants",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qui sont les Mukhadramun ?", texte_ar:'من هم المخضرمون؟', explication:"Ceux qui ont vécu la jahiliyya et l'islam mais n'ont pas rencontré le Prophète ﷺ en croyants (ex: Uways al-Qarani). Ne sont pas Sahaba mais Tabi'in.", reponses:[{texte_fr:"Ont vécu jahiliyya et islam sans rencontrer le Prophète ﷺ",est_correcte:true},{texte_fr:"Les hypocrites",est_correcte:false},{texte_fr:"Les Compagnons",est_correcte:false},{texte_fr:"Les califes",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qu'est-ce que l'« Idtirab » dans un hadith ?", texte_ar:'ما الاضطراب في الحديث؟', explication:"Confusion : un narrateur rapporte le hadith de plusieurs manières différentes sans qu'on puisse les concilier. Rend le hadith faible.", reponses:[{texte_fr:"Confusion : versions contradictoires inconciliables",est_correcte:true},{texte_fr:"Hadith stable",est_correcte:false},{texte_fr:"Narrateur fiable",est_correcte:false},{texte_fr:"Mutawatir",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Quelle est l'œuvre principale d'Ibn Hajar al-Asqalani sur Bukhari ?", texte_ar:'ما أهم شرح للبخاري لابن حجر؟', explication:"Fath al-Bari sharh Sahih al-Bukhari, le plus célèbre commentaire de Sahih al-Bukhari, 13 volumes. Référence incontournable.", reponses:[{texte_fr:"Fath al-Bari",est_correcte:true},{texte_fr:"al-Itqan",est_correcte:false},{texte_fr:"al-Muwatta",est_correcte:false},{texte_fr:"Riyad as-Salihin",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Quel est le commentaire le plus célèbre de Sahih Muslim ?", texte_ar:'ما أشهر شرح لصحيح مسلم؟', explication:"Sharh Sahih Muslim d'an-Nawawi (al-Minhaj). Concis et clair, indispensable pour comprendre Muslim.", reponses:[{texte_fr:"al-Minhaj d'an-Nawawi",est_correcte:true},{texte_fr:"Fath al-Bari",est_correcte:false},{texte_fr:"Ihya' Ulum ad-Din",est_correcte:false},{texte_fr:"Muwatta",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qu'est-ce que la « Ziyada ath-Thiqa » ?", texte_ar:'ما زيادة الثقة؟', explication:"Ajout d'un narrateur fiable absent chez d'autres également fiables. Acceptée si conciliable, sinon devient shadh (irrégulière).", reponses:[{texte_fr:"Ajout par un fiable absent chez d'autres fiables",est_correcte:true},{texte_fr:"Erreur du copiste",est_correcte:false},{texte_fr:"Hadith abrogé",est_correcte:false},{texte_fr:"Mensonge",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Que dit la règle « Tilka kanat sittu mi'a alf hadith » d'al-Bukhari ?", texte_ar:'كم حديث جمع البخاري قبل التصحيح؟', explication:"« J'ai rassemblé 600 000 hadiths, j'ai sélectionné de ce Sahih. » — Témoigne du travail colossal de sélection (1/100).", reponses:[{texte_fr:"Il a sélectionné parmi 600 000 hadiths",est_correcte:true},{texte_fr:"Il a inventé 600 000 hadiths",est_correcte:false},{texte_fr:"Il a ignoré tout le reste",est_correcte:false},{texte_fr:"Source non fiable",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qu'est-ce qu'un « hadith Ghara'ib » ?", texte_ar:'ما حديث الغرائب؟', explication:"Hadith étrange/rare : rapporté par une chaîne unique à un niveau. Peut être sahih, hasan ou da'if selon le narrateur unique.", reponses:[{texte_fr:"Hadith rare avec narrateur unique à un niveau",est_correcte:true},{texte_fr:"Hadith en langue étrangère",est_correcte:false},{texte_fr:"Hadith venant de l'étranger",est_correcte:false},{texte_fr:"Hadith inventé",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Que sont les Mu'jam des Compagnons ?", texte_ar:'ما هي معاجم الصحابة؟', explication:"Ouvrages biographiques recensant tous les Sahaba (al-Isaba d'Ibn Hajar, Usd al-Ghaba d'Ibn al-Athir). Indispensables pour la science du rijal.", reponses:[{texte_fr:"Encyclopédies biographiques des Compagnons",est_correcte:true},{texte_fr:"Dictionnaires linguistiques",est_correcte:false},{texte_fr:"Recueils de poésie",est_correcte:false},{texte_fr:"Tafsir",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Qu'est-ce qu'un hadith Mudraj ?", texte_ar:'ما الحديث المدرج؟', explication:"Hadith dans lequel un ajout d'un narrateur (commentaire ou explication) est confondu avec les paroles du Prophète ﷺ. Doit être distingué par les muhaddithun.", reponses:[{texte_fr:"Hadith où un ajout du narrateur est confondu avec le Prophète",est_correcte:true},{texte_fr:"Hadith complètement faux",est_correcte:false},{texte_fr:"Hadith long",est_correcte:false},{texte_fr:"Hadith court",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Quel est le rang de l'Imam Muslim selon les muhaddithun ?", texte_ar:'ما رتبة الإمام مسلم؟', explication:"L'un des plus grands muhaddithun, juste après al-Bukhari. Certains préfèrent même son agencement à celui de Bukhari pour sa clarté.", reponses:[{texte_fr:"Second après Bukhari, parfois préféré en agencement",est_correcte:true},{texte_fr:"Avant Bukhari",est_correcte:false},{texte_fr:"Non considéré",est_correcte:false},{texte_fr:"Compagnon",est_correcte:false}] },
  { domaine:'hadith', niveau:5, texte_fr:"Quelle est l'œuvre principale d'al-Albani contemporain ?", texte_ar:'ما أهم أعمال الألباني؟', explication:"Silsila al-Ahadith as-Sahiha et Silsila ad-Da'ifa, Sahih al-Jami', Da'if al-Jami'. Critique moderne incontournable des hadiths.", reponses:[{texte_fr:"Silsila Sahiha & Da'ifa, Sahih/Da'if al-Jami'",est_correcte:true},{texte_fr:"Tafsir du Coran",est_correcte:false},{texte_fr:"Livre de sira",est_correcte:false},{texte_fr:"Livre de fiqh seulement",est_correcte:false}] },
];

export async function seedQuestionsCombler3(client: Client): Promise<void> {
  console.log('Seeding lot 3 (Akhlaq/Aqida/Hadith avancés)...');
  let inserted = 0; let skipped = 0;
  for (const q of Q) {
    const exists = await client.query('SELECT id FROM questions WHERE texte_fr = $1', [q.texte_fr]);
    if (exists.rows.length > 0) { skipped++; continue; }
    const r = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, explication, grade_hadith, statut) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'valide') RETURNING id`,
      [q.domaine, q.sous_domaine ?? null, q.niveau, 'general', q.texte_fr, q.texte_ar ?? null, q.dalil_ref ?? null, q.explication, q.grade_hadith ?? null]
    );
    const id = r.rows[0].id;
    for (const rep of q.reponses) {
      await client.query(`INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte) VALUES ($1,$2,$3,$4)`, [id, rep.texte_fr, rep.texte_ar ?? null, rep.est_correcte]);
    }
    inserted++;
  }
  console.log(`Combler3: ${inserted} inserted, ${skipped} skipped.`);
}

if (require.main === module) {
  const { Client } = require('pg');
  const c = new Client({ connectionString: process.env.DATABASE_URL });
  c.connect().then(async () => { await seedQuestionsCombler3(c); await c.end(); }).catch((e: unknown) => { console.error(e); process.exit(1); });
}
