import { Client } from 'pg';

interface QuestionSeed {
  domaine: string;
  sous_domaine?: string;
  niveau: number;
  madhab: string;
  texte_fr: string;
  texte_ar?: string;
  dalil_ref?: string;
  dalil_texte_ar?: string;
  dalil_texte_fr?: string;
  explication?: string;
  savant_reference?: string;
  grade_hadith?: string;
  reponses: { texte_fr: string; texte_ar?: string; est_correcte: boolean }[];
}

const QUESTIONS_EXTRA: QuestionSeed[] = [
  // ===================== FIQH (20) =====================
  {
    domaine: 'fiqh',
    sous_domaine: 'taharah',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Quelle est la condition principale qui rend l'eau apte à la purification (eau pure et purifiante) ?",
    texte_ar: 'ما الشرط الأساسي الذي يجعل الماء طهورًا يصح به التطهر؟',
    dalil_ref: 'Sourate Al-Furqan 25:48',
    dalil_texte_ar: 'وَأَنزَلْنَا مِنَ السَّمَاءِ مَاءً طَهُورًا',
    dalil_texte_fr: 'Et Nous avons fait descendre du ciel une eau pure et purifiante.',
    explication: "L'eau reste pure et purifiante tant que ni sa couleur, ni son goût, ni son odeur n'ont été modifiés par une impureté. C'est le principe de l'eau mutlaq (absolue).",
    savant_reference: "Ibn Uthaymin, Ash-Sharh Al-Mumti'",
    reponses: [
      { texte_fr: "Que ni sa couleur, ni son goût, ni son odeur ne soient modifiés par une impureté", texte_ar: 'ألا يتغير لونه ولا طعمه ولا ريحه بنجاسة', est_correcte: true },
      { texte_fr: "Qu'elle soit froide", texte_ar: 'أن يكون باردًا', est_correcte: false },
      { texte_fr: "Qu'elle provienne d'un puits", texte_ar: 'أن يكون من بئر', est_correcte: false },
      { texte_fr: "Qu'elle soit bénie par un imam", texte_ar: 'أن يباركه إمام', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'taharah',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Quand le tayammum (ablution sèche) est-il permis ?",
    texte_ar: 'متى يجوز التيمم؟',
    dalil_ref: 'Sourate Al-Maida 5:6',
    dalil_texte_ar: 'فَلَمْ تَجِدُوا مَاءً فَتَيَمَّمُوا صَعِيدًا طَيِّبًا',
    dalil_texte_fr: "Et que vous ne trouviez pas d'eau, alors recourez à une terre pure.",
    explication: "Le tayammum est permis en l'absence d'eau ou en cas d'incapacité de l'utiliser (maladie, froid extrême sans moyen de chauffer l'eau).",
    savant_reference: 'Ibn Uthaymin, Ash-Sharh Al-Mumti\'',
    reponses: [
      { texte_fr: "En l'absence d'eau ou en cas d'incapacité de l'utiliser", texte_ar: 'عند فقد الماء أو العجز عن استعماله', est_correcte: true },
      { texte_fr: 'Uniquement en voyage', texte_ar: 'في السفر فقط', est_correcte: false },
      { texte_fr: "Quand on est pressé", texte_ar: 'عند الاستعجال', est_correcte: false },
      { texte_fr: 'Le vendredi seulement', texte_ar: 'يوم الجمعة فقط', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'salat',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Combien de rak'at comporte la prière du Dhuhr (midi) ?",
    texte_ar: 'كم عدد ركعات صلاة الظهر؟',
    explication: "La prière du Dhuhr comporte quatre rak'at obligatoires, comme établi par la pratique constante du Prophète (sallallahu alayhi wa sallam) et la transmission ininterrompue.",
    savant_reference: 'Consensus (ijma\')',
    reponses: [
      { texte_fr: "Quatre rak'at", texte_ar: 'أربع ركعات', est_correcte: true },
      { texte_fr: "Deux rak'at", texte_ar: 'ركعتان', est_correcte: false },
      { texte_fr: "Trois rak'at", texte_ar: 'ثلاث ركعات', est_correcte: false },
      { texte_fr: "Cinq rak'at", texte_ar: 'خمس ركعات', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'salat',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Combien de rak'at comporte la prière du Maghrib (coucher du soleil) ?",
    texte_ar: 'كم عدد ركعات صلاة المغرب؟',
    explication: "La prière du Maghrib comporte trois rak'at ; c'est la seule prière obligatoire à nombre impair de rak'at.",
    savant_reference: 'Consensus (ijma\')',
    reponses: [
      { texte_fr: "Trois rak'at", texte_ar: 'ثلاث ركعات', est_correcte: true },
      { texte_fr: "Deux rak'at", texte_ar: 'ركعتان', est_correcte: false },
      { texte_fr: "Quatre rak'at", texte_ar: 'أربع ركعات', est_correcte: false },
      { texte_fr: "Une rak'a", texte_ar: 'ركعة واحدة', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'salat',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Combien y a-t-il de prières obligatoires (fard) par jour ?",
    texte_ar: 'كم عدد الصلوات المفروضة في اليوم والليلة؟',
    dalil_ref: 'Sahih Al-Bukhari 349',
    dalil_texte_ar: 'فَرَضَ اللَّهُ عَلَى أُمَّتِي لَيْلَةَ الإِسْرَاءِ خَمْسِينَ صَلاةً ... فَهِيَ خَمْسٌ وَهِيَ خَمْسُونَ',
    dalil_texte_fr: "Allah a prescrit à ma communauté cinquante prières la nuit de l'Isra... ce sont cinq (en pratique) et cinquante (en récompense).",
    explication: "Les cinq prières quotidiennes furent prescrites lors du voyage nocturne (Isra wal Mi'raj). Leur récompense est celle de cinquante.",
    savant_reference: 'Al-Bukhari',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: 'Cinq', texte_ar: 'خمس', est_correcte: true },
      { texte_fr: 'Trois', texte_ar: 'ثلاث', est_correcte: false },
      { texte_fr: 'Sept', texte_ar: 'سبع', est_correcte: false },
      { texte_fr: 'Quatre', texte_ar: 'أربع', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'salat',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quel est le pilier (rukn) de la prière constitué par la prosternation ?",
    texte_ar: 'ما حكم السجود في الصلاة؟',
    dalil_ref: 'Sourate Al-Hajj 22:77',
    dalil_texte_ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا ارْكَعُوا وَاسْجُدُوا',
    dalil_texte_fr: 'Ô vous qui avez cru, inclinez-vous et prosternez-vous.',
    explication: "Le sujud (prosternation) est un pilier (rukn) de la prière : sans lui, la prière n'est pas valide. On se prosterne sur sept membres.",
    savant_reference: "Ibn Uthaymin, Ash-Sharh Al-Mumti'",
    reponses: [
      { texte_fr: "C'est un pilier sans lequel la prière est invalide", texte_ar: 'ركن لا تصح الصلاة بدونه', est_correcte: true },
      { texte_fr: "C'est une simple recommandation", texte_ar: 'مجرد مستحب', est_correcte: false },
      { texte_fr: "C'est facultatif", texte_ar: 'اختياري', est_correcte: false },
      { texte_fr: "C'est interdit pour les femmes", texte_ar: 'محرم على النساء', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'salat',
    niveau: 3,
    madhab: 'shafii',
    texte_fr: "Selon l'école shafiite, lever les mains (raf' al-yadayn) au début de la prière est-il :",
    texte_ar: 'عند الشافعية، رفع اليدين عند تكبيرة الإحرام هو:',
    dalil_ref: 'Sahih Al-Bukhari 735',
    dalil_texte_ar: 'كَانَ يَرْفَعُ يَدَيْهِ حَذْوَ مَنْكِبَيْهِ إِذَا افْتَتَحَ الصَّلاَةَ',
    dalil_texte_fr: 'Il levait ses mains à hauteur de ses épaules lorsqu\'il commençait la prière.',
    explication: "Les écoles shafiite et hanbalite recommandent fortement le raf' al-yadayn au takbir d'entrée, au ruku' et en se relevant. Les hanafites le limitent au takbir d'ouverture.",
    savant_reference: "An-Nawawi, Al-Majmu'",
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: 'Une sunna recommandée', texte_ar: 'سنة مستحبة', est_correcte: true },
      { texte_fr: 'Une obligation stricte', texte_ar: 'فرض', est_correcte: false },
      { texte_fr: 'Une innovation', texte_ar: 'بدعة', est_correcte: false },
      { texte_fr: 'Interdit', texte_ar: 'محرم', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'zakat',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Quel est le taux de la zakat sur l'argent et l'or thésaurisés (une fois le nisab et l'année atteints) ?",
    texte_ar: 'ما مقدار الزكاة الواجبة في النقود والذهب المدخر؟',
    dalil_ref: 'Sunan Abi Dawud 1573',
    dalil_texte_ar: 'فَإِذَا كَانَتْ لَكَ مِائَتَا دِرْهَمٍ وَحَالَ عَلَيْهَا الْحَوْلُ فَفِيهَا خَمْسَةُ دَرَاهِمَ',
    dalil_texte_fr: "Si tu possèdes deux cents dirhams et qu'une année s'est écoulée, alors il y a dessus cinq dirhams.",
    explication: "La zakat sur l'argent monétaire est de 2,5 % (le quart du dixième) par an, une fois le nisab atteint et l'année lunaire écoulée.",
    savant_reference: 'Abu Dawud',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: '2,5 % (le quart du dixième)', texte_ar: 'ربع العشر (٢٫٥٪)', est_correcte: true },
      { texte_fr: '10 %', texte_ar: 'العشر', est_correcte: false },
      { texte_fr: '5 %', texte_ar: 'خمسة بالمئة', est_correcte: false },
      { texte_fr: '20 %', texte_ar: 'الخمس', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'zakat',
    niveau: 2,
    madhab: 'general',
    texte_fr: "La Zakat al-Fitr est due :",
    texte_ar: 'متى تجب زكاة الفطر؟',
    dalil_ref: 'Sahih Al-Bukhari 1503',
    dalil_texte_ar: 'فَرَضَ رَسُولُ اللَّهِ صلى الله عليه وسلم زَكَاةَ الْفِطْرِ صَاعًا مِنْ تَمْرٍ أَوْ صَاعًا مِنْ شَعِيرٍ',
    dalil_texte_fr: "Le Messager d'Allah a prescrit la zakat al-fitr d'un sa' de dattes ou d'un sa' d'orge.",
    explication: "La Zakat al-Fitr est obligatoire à la fin du Ramadan, à payer avant la prière de l'Aïd al-Fitr, à hauteur d'un sa' de nourriture par personne.",
    savant_reference: 'Al-Bukhari',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "À la fin du Ramadan, avant la prière de l'Aïd", texte_ar: 'في نهاية رمضان قبل صلاة العيد', est_correcte: true },
      { texte_fr: "Au début du Ramadan", texte_ar: 'في بداية رمضان', est_correcte: false },
      { texte_fr: "Le jour de Arafat", texte_ar: 'يوم عرفة', est_correcte: false },
      { texte_fr: "Une fois par an au mois de Rajab", texte_ar: 'مرة في رجب', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'siyam',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Quel mois lunaire le jeûne est-il obligatoire pour tout musulman pubère et capable ?",
    texte_ar: 'في أي شهر يجب الصيام على كل مسلم بالغ قادر؟',
    dalil_ref: 'Sourate Al-Baqara 2:185',
    dalil_texte_ar: 'شَهْرُ رَمَضَانَ الَّذِي أُنزِلَ فِيهِ الْقُرْآنُ',
    dalil_texte_fr: "Le mois de Ramadan au cours duquel le Coran a été descendu.",
    explication: 'Le jeûne du mois de Ramadan est le quatrième pilier de l\'Islam, obligatoire pour tout musulman pubère, sain d\'esprit et capable.',
    savant_reference: 'Consensus (ijma\')',
    reponses: [
      { texte_fr: 'Ramadan', texte_ar: 'رمضان', est_correcte: true },
      { texte_fr: 'Sha\'ban', texte_ar: 'شعبان', est_correcte: false },
      { texte_fr: 'Muharram', texte_ar: 'محرم', est_correcte: false },
      { texte_fr: 'Dhul-Hijja', texte_ar: 'ذو الحجة', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'siyam',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Lequel de ces actes annule le jeûne s'il est fait volontairement ?",
    texte_ar: 'أي من هذه الأفعال يفسد الصوم إذا فُعل عمدًا؟',
    dalil_ref: 'Sourate Al-Baqara 2:187',
    dalil_texte_ar: 'وَكُلُوا وَاشْرَبُوا حَتَّىٰ يَتَبَيَّنَ لَكُمُ الْخَيْطُ الْأَبْيَضُ مِنَ الْخَيْطِ الْأَسْوَدِ مِنَ الْفَجْرِ',
    dalil_texte_fr: "Mangez et buvez jusqu'à ce que se distingue pour vous le fil blanc du fil noir de l'aube.",
    explication: "Manger ou boire volontairement pendant la journée de jeûne l'annule. Manger par oubli ne l'annule pas, selon le hadith authentique.",
    savant_reference: "Ibn Uthaymin, Ash-Sharh Al-Mumti'",
    reponses: [
      { texte_fr: 'Manger ou boire volontairement', texte_ar: 'الأكل والشرب عمدًا', est_correcte: true },
      { texte_fr: 'Se brosser les dents avec un siwak', texte_ar: 'استعمال السواك', est_correcte: false },
      { texte_fr: 'Avaler sa salive', texte_ar: 'بلع الريق', est_correcte: false },
      { texte_fr: 'Sentir un parfum', texte_ar: 'شم الطيب', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'hajj',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Quel pilier du Hajj se déroule le 9 Dhul-Hijja et sans lequel le pèlerinage n'est pas valide ?",
    texte_ar: 'ما الركن الأعظم للحج الذي يكون في اليوم التاسع من ذي الحجة؟',
    dalil_ref: 'Sunan At-Tirmidhi 889',
    dalil_texte_ar: 'الْحَجُّ عَرَفَةُ',
    dalil_texte_fr: "Le Hajj, c'est Arafat.",
    explication: "La station à Arafat (wuquf bi Arafa) le 9 Dhul-Hijja est le plus grand pilier du Hajj ; celui qui la manque a manqué le pèlerinage.",
    savant_reference: 'At-Tirmidhi',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "La station à Arafat", texte_ar: 'الوقوف بعرفة', est_correcte: true },
      { texte_fr: "Le sacrifice de l'animal", texte_ar: 'ذبح الهدي', est_correcte: false },
      { texte_fr: "Le rasage de la tête", texte_ar: 'حلق الرأس', est_correcte: false },
      { texte_fr: "La visite de Médine", texte_ar: 'زيارة المدينة', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'hajj',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Combien de tours (tawaf) effectue-t-on autour de la Kaaba lors du tawaf ?",
    texte_ar: 'كم شوطًا يُطاف حول الكعبة في الطواف؟',
    explication: "Le tawaf autour de la Kaaba comporte sept tours, commençant et finissant à la Pierre Noire (Al-Hajar al-Aswad).",
    savant_reference: "Ibn Uthaymin, Manasik al-Hajj",
    reponses: [
      { texte_fr: 'Sept tours', texte_ar: 'سبعة أشواط', est_correcte: true },
      { texte_fr: 'Trois tours', texte_ar: 'ثلاثة أشواط', est_correcte: false },
      { texte_fr: 'Cinq tours', texte_ar: 'خمسة أشواط', est_correcte: false },
      { texte_fr: 'Dix tours', texte_ar: 'عشرة أشواط', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'muamalat',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Comment l'Islam qualifie-t-il le riba (usure/intérêt) ?",
    texte_ar: 'ما حكم الربا في الإسلام؟',
    dalil_ref: 'Sourate Al-Baqara 2:275',
    dalil_texte_ar: 'وَأَحَلَّ اللَّهُ الْبَيْعَ وَحَرَّمَ الرِّبَا',
    dalil_texte_fr: "Allah a rendu licite le commerce et illicite l'usure.",
    explication: "Le riba est catégoriquement interdit (haram) dans le Coran et la Sunna ; il fait partie des grands péchés.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: 'Strictement interdit (haram)', texte_ar: 'محرم تحريمًا قطعيًا', est_correcte: true },
      { texte_fr: 'Déconseillé seulement', texte_ar: 'مكروه فقط', est_correcte: false },
      { texte_fr: 'Permis en cas de besoin', texte_ar: 'مباح عند الحاجة', est_correcte: false },
      { texte_fr: 'Recommandé pour l\'économie', texte_ar: 'مستحب للاقتصاد', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'muamalat',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Qu'est-ce que le gharar interdit dans une transaction ?",
    texte_ar: 'ما هو الغرر المنهي عنه في البيع؟',
    dalil_ref: 'Sahih Muslim 1513',
    dalil_texte_ar: 'نَهَى رَسُولُ اللَّهِ صلى الله عليه وسلم عَنْ بَيْعِ الْغَرَرِ',
    dalil_texte_fr: "Le Messager d'Allah a interdit la vente comportant une incertitude excessive (gharar).",
    explication: "Le gharar est l'incertitude ou l'ambiguïté excessive dans l'objet d'une vente (ex. vendre le poisson dans l'eau). Le Prophète l'a interdit.",
    savant_reference: 'Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "L'incertitude ou l'ambiguïté excessive sur l'objet du contrat", texte_ar: 'الجهالة والغموض الفاحش في المبيع', est_correcte: true },
      { texte_fr: 'Le paiement comptant', texte_ar: 'الدفع نقدًا', est_correcte: false },
      { texte_fr: 'La vente à crédit autorisée', texte_ar: 'البيع بالأجل المباح', est_correcte: false },
      { texte_fr: 'La remise commerciale', texte_ar: 'الخصم التجاري', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'nikah',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Le mahr (dot) dans le mariage islamique est :",
    texte_ar: 'ما حكم المهر في عقد النكاح؟',
    dalil_ref: 'Sourate An-Nisa 4:4',
    dalil_texte_ar: 'وَآتُوا النِّسَاءَ صَدُقَاتِهِنَّ نِحْلَةً',
    dalil_texte_fr: 'Et donnez aux femmes leur dot, de bonne grâce.',
    explication: "Le mahr est un droit de l'épouse, obligatoire dans le contrat de mariage. Il lui appartient en propre.",
    savant_reference: 'Tafsir As-Sa\'di',
    reponses: [
      { texte_fr: "Un droit obligatoire de l'épouse", texte_ar: 'حق واجب للزوجة', est_correcte: true },
      { texte_fr: "Un cadeau facultatif", texte_ar: 'هدية اختيارية', est_correcte: false },
      { texte_fr: "Versé au père et non à l'épouse", texte_ar: 'يُدفع للأب لا للزوجة', est_correcte: false },
      { texte_fr: "Interdit en Islam", texte_ar: 'محرم في الإسلام', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'nikah',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Parmi les conditions de validité du mariage figure :",
    texte_ar: 'من شروط صحة عقد النكاح:',
    dalil_ref: 'Sunan At-Tirmidhi 1101',
    dalil_texte_ar: 'لَا نِكَاحَ إِلَّا بِوَلِيٍّ',
    dalil_texte_fr: "Pas de mariage sans tuteur (wali).",
    explication: "La majorité des savants (malikites, shafiites, hanbalites) exigent le wali pour la femme. Les hanafites permettent à la femme adulte de se marier sans wali, mais le hadith authentique appuie l'exigence du wali.",
    savant_reference: 'At-Tirmidhi',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Le consentement et la présence du tuteur (wali) selon la majorité", texte_ar: 'الرضا ووجود الولي عند الجمهور', est_correcte: true },
      { texte_fr: "La présence d'un seul témoin enfant", texte_ar: 'حضور شاهد طفل واحد', est_correcte: false },
      { texte_fr: "Un contrat écrit obligatoire signé devant un juge", texte_ar: 'عقد مكتوب أمام قاضٍ فقط', est_correcte: false },
      { texte_fr: "Que les époux soient de la même tribu", texte_ar: 'أن يكون الزوجان من قبيلة واحدة', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'mirath',
    niveau: 5,
    madhab: 'general',
    texte_fr: "Quelle est la part d'héritage de base d'un fils par rapport à une fille en science des successions ?",
    texte_ar: 'ما نصيب الابن مقارنة بالبنت في الميراث؟',
    dalil_ref: 'Sourate An-Nisa 4:11',
    dalil_texte_ar: 'يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنثَيَيْنِ',
    dalil_texte_fr: "Allah vous recommande au sujet de vos enfants : au garçon, une part égale à celle de deux filles.",
    explication: "Dans le partage successoral, le fils reçoit la part de deux filles (2:1), conformément au verset explicite de la sourate An-Nisa. Cette règle s'accompagne de responsabilités financières pour l'homme.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Le fils reçoit la part de deux filles", texte_ar: 'للذكر مثل حظ الأنثيين', est_correcte: true },
      { texte_fr: 'Ils reçoivent une part égale', texte_ar: 'يرثان بالتساوي', est_correcte: false },
      { texte_fr: 'La fille reçoit le double', texte_ar: 'للبنت الضعف', est_correcte: false },
      { texte_fr: 'Le fils n\'hérite pas', texte_ar: 'لا يرث الابن', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'janaiz',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Combien de takbirat comporte la prière funéraire (Salat al-Janaza) ?",
    texte_ar: 'كم عدد التكبيرات في صلاة الجنازة؟',
    dalil_ref: 'Sahih Al-Bukhari 1245',
    dalil_texte_ar: 'كَبَّرَ عَلَيْهِ أَرْبَعًا',
    dalil_texte_fr: "Il fit quatre takbirat sur lui.",
    explication: "La prière funéraire comporte quatre takbirat, sans inclinaison ni prosternation. Le Prophète a prié ainsi sur le Négus (Najashi).",
    savant_reference: 'Al-Bukhari',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: 'Quatre takbirat', texte_ar: 'أربع تكبيرات', est_correcte: true },
      { texte_fr: 'Deux takbirat', texte_ar: 'تكبيرتان', est_correcte: false },
      { texte_fr: 'Sept takbirat', texte_ar: 'سبع تكبيرات', est_correcte: false },
      { texte_fr: 'Aucune takbira', texte_ar: 'لا تكبير', est_correcte: false },
    ],
  },
  {
    domaine: 'fiqh',
    sous_domaine: 'salat',
    niveau: 4,
    madhab: 'maliki',
    texte_fr: "Selon l'école malikite, la position des mains pendant la station debout (qiyam) de la prière est :",
    texte_ar: 'عند المالكية، ما وضع اليدين في القيام في الصلاة؟',
    explication: "L'école malikite recommande le sadl (laisser les mains le long du corps) dans la prière obligatoire, contrairement aux hanafites, shafiites et hanbalites qui placent la main droite sur la gauche (qabd). Les deux pratiques reposent sur des transmissions.",
    savant_reference: 'Al-Mudawwana (Malik)',
    reponses: [
      { texte_fr: 'Le sadl (mains le long du corps) dans le fard', texte_ar: 'السدل في الفريضة', est_correcte: true },
      { texte_fr: 'Les mains levées en permanence', texte_ar: 'رفع اليدين دائمًا', est_correcte: false },
      { texte_fr: 'Les mains sur la tête', texte_ar: 'اليدان على الرأس', est_correcte: false },
      { texte_fr: 'Les bras croisés derrière le dos', texte_ar: 'تشبيك اليدين خلف الظهر', est_correcte: false },
    ],
  },

  // ===================== AQIDA (15) =====================
  {
    domaine: 'aqida',
    sous_domaine: 'tawhid',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Que signifie le Tawhid ar-Rububiyya ?",
    texte_ar: 'ما معنى توحيد الربوبية؟',
    dalil_ref: 'Sourate Al-Fatiha 1:2',
    dalil_texte_ar: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
    dalil_texte_fr: "Louange à Allah, Seigneur de l'univers.",
    explication: "Le Tawhid ar-Rububiyya consiste à reconnaître qu'Allah est l'unique Créateur, Maître et Pourvoyeur de toute chose.",
    savant_reference: 'Al-Aqida al-Wasitiyya (Ibn Taymiyya)',
    reponses: [
      { texte_fr: "Reconnaître Allah comme unique Créateur et Seigneur", texte_ar: 'إفراد الله بالخلق والربوبية', est_correcte: true },
      { texte_fr: "Adorer les saints", texte_ar: 'عبادة الأولياء', est_correcte: false },
      { texte_fr: "Croire en plusieurs dieux", texte_ar: 'الإيمان بآلهة متعددة', est_correcte: false },
      { texte_fr: "Nier l'existence d'Allah", texte_ar: 'إنكار وجود الله', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'tawhid',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Le Tawhid al-Uluhiyya (al-Ibada) signifie :",
    texte_ar: 'ما معنى توحيد الألوهية (العبادة)؟',
    dalil_ref: 'Sourate Adh-Dhariyat 51:56',
    dalil_texte_ar: 'وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ',
    dalil_texte_fr: "Je n'ai créé les djinns et les hommes que pour qu'ils M'adorent.",
    explication: "Le Tawhid al-Uluhiyya consiste à vouer toute forme d'adoration à Allah seul. C'est l'objet de l'appel de tous les prophètes.",
    savant_reference: "Ibn Uthaymin, Sharh al-Aqida al-Wasitiyya",
    reponses: [
      { texte_fr: "Vouer toute adoration à Allah seul", texte_ar: 'إفراد الله بالعبادة', est_correcte: true },
      { texte_fr: "Croire qu'Allah est le Créateur uniquement", texte_ar: 'الإيمان بأنه الخالق فقط', est_correcte: false },
      { texte_fr: "Adorer Allah à travers des intermédiaires", texte_ar: 'عبادة الله بالوسائط', est_correcte: false },
      { texte_fr: "Décrire les anges", texte_ar: 'وصف الملائكة', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'tawhid',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Quel est le plus grand péché (le plus grave) en Islam ?",
    texte_ar: 'ما هو أعظم الذنوب في الإسلام؟',
    dalil_ref: 'Sourate Luqman 31:13',
    dalil_texte_ar: 'إِنَّ الشِّرْكَ لَظُلْمٌ عَظِيمٌ',
    dalil_texte_fr: "Certes, l'association (shirk) est une immense injustice.",
    explication: "Le shirk (associer une divinité à Allah) est le plus grand des péchés ; Allah ne le pardonne pas si l'on meurt dessus sans repentir.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Le shirk (associationnisme)", texte_ar: 'الشرك بالله', est_correcte: true },
      { texte_fr: "Le mensonge", texte_ar: 'الكذب', est_correcte: false },
      { texte_fr: "Manger du porc", texte_ar: 'أكل الخنزير', est_correcte: false },
      { texte_fr: "Manquer une prière surérogatoire", texte_ar: 'ترك النافلة', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'iman',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Combien y a-t-il de prophètes mentionnés nommément dans le Coran (chiffre communément retenu) ?",
    texte_ar: 'كم عدد الأنبياء المذكورين بأسمائهم في القرآن (العدد المشهور)؟',
    explication: "On cite communément vingt-cinq prophètes et messagers nommés dans le Coran (comme Adam, Nuh, Ibrahim, Musa, Issa, Muhammad). Le nombre total de prophètes est connu d'Allah seul.",
    savant_reference: 'Tafsir As-Sa\'di',
    reponses: [
      { texte_fr: 'Vingt-cinq', texte_ar: 'خمسة وعشرون', est_correcte: true },
      { texte_fr: 'Dix', texte_ar: 'عشرة', est_correcte: false },
      { texte_fr: 'Cent', texte_ar: 'مئة', est_correcte: false },
      { texte_fr: 'Cinq', texte_ar: 'خمسة', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'iman',
    niveau: 1,
    madhab: 'general',
    texte_fr: "En combien de livres révélés mentionnés nommément le musulman doit-il croire ?",
    texte_ar: 'بكم من الكتب السماوية المذكورة بأسمائها يجب الإيمان؟',
    dalil_ref: 'Sourate Al-Baqara 2:285',
    dalil_texte_ar: 'آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ',
    dalil_texte_fr: "Le Messager a cru en ce qu'on a fait descendre vers lui... tous ont cru en Allah, en Ses anges, en Ses Livres.",
    explication: "Le musulman croit en tous les Livres révélés, dont quatre sont nommés : la Torah, l'Évangile (Injil), les Psaumes (Zabur) et le Coran, plus les Feuillets d'Ibrahim.",
    savant_reference: 'Al-Aqida al-Wasitiyya',
    reponses: [
      { texte_fr: "Quatre nommés (Torah, Injil, Zabur, Coran) en plus des Feuillets", texte_ar: 'أربعة مسماة: التوراة والإنجيل والزبور والقرآن مع الصحف', est_correcte: true },
      { texte_fr: 'Un seul (le Coran)', texte_ar: 'واحد فقط (القرآن)', est_correcte: false },
      { texte_fr: 'Sept', texte_ar: 'سبعة', est_correcte: false },
      { texte_fr: 'Deux', texte_ar: 'اثنان', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'qadar',
    niveau: 4,
    madhab: 'general',
    texte_fr: "La croyance au Qadar (destin) implique de croire que :",
    texte_ar: 'الإيمان بالقدر يقتضي الإيمان بأن:',
    dalil_ref: 'Sourate Al-Qamar 54:49',
    dalil_texte_ar: 'إِنَّا كُلَّ شَيْءٍ خَلَقْنَاهُ بِقَدَرٍ',
    dalil_texte_fr: "Nous avons créé toute chose avec mesure (selon un décret).",
    explication: "Le Qadar comporte quatre degrés : la science d'Allah, Son écriture dans la Tablette gardée, Sa volonté et Sa création de toute chose.",
    savant_reference: "Ibn Uthaymin, Sharh al-Aqida al-Wasitiyya",
    reponses: [
      { texte_fr: "Allah connaît, a écrit, veut et crée toute chose avec mesure", texte_ar: 'الله علم وكتب وشاء وخلق كل شيء بقدر', est_correcte: true },
      { texte_fr: "L'homme n'a aucune responsabilité de ses actes", texte_ar: 'الإنسان غير مسؤول عن أفعاله', est_correcte: false },
      { texte_fr: "Allah ignore l'avenir", texte_ar: 'الله لا يعلم المستقبل', est_correcte: false },
      { texte_fr: "Le destin peut être changé par la magie", texte_ar: 'القدر يُغيَّر بالسحر', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'ghayb',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Lequel de ces êtres fait partie du monde de l'invisible (al-ghayb) créé par Allah ?",
    texte_ar: 'أي من هؤلاء من عالم الغيب الذي خلقه الله؟',
    dalil_ref: 'Sourate Al-Hijr 15:27',
    dalil_texte_ar: 'وَالْجَانَّ خَلَقْنَاهُ مِن قَبْلُ مِن نَّارِ السَّمُومِ',
    dalil_texte_fr: "Et les djinns, Nous les avons créés auparavant d'un feu d'une chaleur ardente.",
    explication: "Les anges, les djinns et le Paradis/l'Enfer font partie du ghayb. Les djinns ont été créés d'un feu sans fumée.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Les djinns", texte_ar: 'الجن', est_correcte: true },
      { texte_fr: "Les dinosaures", texte_ar: 'الديناصورات', est_correcte: false },
      { texte_fr: "Les robots", texte_ar: 'الروبوتات', est_correcte: false },
      { texte_fr: "Les planètes visibles", texte_ar: 'الكواكب المرئية', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'ghayb',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quel ange est chargé de transmettre la révélation aux prophètes ?",
    texte_ar: 'أي ملك مكلف بتبليغ الوحي إلى الأنبياء؟',
    dalil_ref: 'Sourate Ash-Shu\'ara 26:193-194',
    dalil_texte_ar: 'نَزَلَ بِهِ الرُّوحُ الْأَمِينُ ۝ عَلَىٰ قَلْبِكَ لِتَكُونَ مِنَ الْمُنذِرِينَ',
    dalil_texte_fr: "L'Esprit fidèle est descendu avec cela sur ton cœur, pour que tu sois du nombre des avertisseurs.",
    explication: "L'ange Jibril (Gabriel), appelé ar-Ruh al-Amin (l'Esprit fidèle), est chargé de transmettre la révélation divine aux prophètes.",
    savant_reference: 'Tafsir As-Sa\'di',
    reponses: [
      { texte_fr: "Jibril (Gabriel)", texte_ar: 'جبريل', est_correcte: true },
      { texte_fr: "Mika'il (Michael)", texte_ar: 'ميكائيل', est_correcte: false },
      { texte_fr: "Israfil", texte_ar: 'إسرافيل', est_correcte: false },
      { texte_fr: "Malik", texte_ar: 'مالك', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'prophetologie',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Qui est le dernier des prophètes et messagers (Khatam an-Nabiyyin) ?",
    texte_ar: 'من هو خاتم الأنبياء والمرسلين؟',
    dalil_ref: 'Sourate Al-Ahzab 33:40',
    dalil_texte_ar: 'مَّا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِّن رِّجَالِكُمْ وَلَٰكِن رَّسُولَ اللَّهِ وَخَاتَمَ النَّبِيِّينَ',
    dalil_texte_fr: "Muhammad n'a jamais été le père de l'un de vos hommes, mais le Messager d'Allah et le sceau des prophètes.",
    explication: "Muhammad (sallallahu alayhi wa sallam) est le dernier des prophètes ; aucun prophète ne viendra après lui. C'est un fondement de la foi.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Muhammad (sallallahu alayhi wa sallam)", texte_ar: 'محمد صلى الله عليه وسلم', est_correcte: true },
      { texte_fr: "Issa (Jésus)", texte_ar: 'عيسى', est_correcte: false },
      { texte_fr: "Musa (Moïse)", texte_ar: 'موسى', est_correcte: false },
      { texte_fr: "Ibrahim (Abraham)", texte_ar: 'إبراهيم', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'prophetologie',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quels prophètes sont appelés Ulul-Azm (les doués de fermeté) ?",
    texte_ar: 'من هم أولو العزم من الرسل؟',
    dalil_ref: 'Sourate Al-Ahqaf 46:35',
    dalil_texte_ar: 'فَاصْبِرْ كَمَا صَبَرَ أُولُو الْعَزْمِ مِنَ الرُّسُلِ',
    dalil_texte_fr: "Endure donc comme ont enduré les messagers doués de fermeté.",
    explication: "Les Ulul-Azm sont les cinq plus grands messagers : Nuh, Ibrahim, Musa, Issa et Muhammad (paix sur eux tous).",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Nuh, Ibrahim, Musa, Issa et Muhammad", texte_ar: 'نوح وإبراهيم وموسى وعيسى ومحمد', est_correcte: true },
      { texte_fr: "Adam, Idris et Yusuf", texte_ar: 'آدم وإدريس ويوسف', est_correcte: false },
      { texte_fr: "Tous les prophètes sans exception", texte_ar: 'كل الأنبياء بلا استثناء', est_correcte: false },
      { texte_fr: "Les anges rapprochés", texte_ar: 'الملائكة المقربون', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'iman',
    niveau: 5,
    madhab: 'general',
    texte_fr: "Selon Ahlus-Sunna, les attributs d'Allah (sifat) doivent être :",
    texte_ar: 'عند أهل السنة، كيف تُثبت صفات الله؟',
    dalil_ref: 'Sourate Ash-Shura 42:11',
    dalil_texte_ar: 'لَيْسَ كَمِثْلِهِ شَيْءٌ ۖ وَهُوَ السَّمِيعُ الْبَصِيرُ',
    dalil_texte_fr: "Rien ne Lui ressemble ; et c'est Lui l'Audient, le Clairvoyant.",
    explication: "Ahlus-Sunna affirment les attributs d'Allah tels qu'Il les a décrits, sans tahrif (déformation), ta'til (négation), takyif (questionnement du comment) ni tamthil (assimilation).",
    savant_reference: 'Al-Aqida al-Wasitiyya (Ibn Taymiyya)',
    reponses: [
      { texte_fr: "Affirmés sans déformation, négation, comment ni assimilation", texte_ar: 'تُثبت بلا تحريف ولا تعطيل ولا تكييف ولا تمثيل', est_correcte: true },
      { texte_fr: "Tous niés et interprétés métaphoriquement", texte_ar: 'تُنفى وتُؤول كلها', est_correcte: false },
      { texte_fr: "Assimilés à ceux des créatures", texte_ar: 'تُشبَّه بصفات المخلوقين', est_correcte: false },
      { texte_fr: "Inventés selon la raison humaine", texte_ar: 'تُبتدع بالعقل', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'tawhid',
    niveau: 5,
    madhab: 'general',
    texte_fr: "Le Tawhid al-Asma was-Sifat consiste à :",
    texte_ar: 'ما معنى توحيد الأسماء والصفات؟',
    dalil_ref: 'Sourate Al-A\'raf 7:180',
    dalil_texte_ar: 'وَلِلَّهِ الْأَسْمَاءُ الْحُسْنَىٰ فَادْعُوهُ بِهَا',
    dalil_texte_fr: "C'est à Allah qu'appartiennent les plus beaux noms. Invoquez-Le par ces noms.",
    explication: "Ce tawhid consiste à attribuer à Allah les noms et attributs qu'Il S'est donnés et que Son Messager Lui a attribués, dans leur sens véritable, sans assimilation aux créatures.",
    savant_reference: "Ibn Uthaymin, Al-Qawa'id al-Muthla",
    reponses: [
      { texte_fr: "Affirmer pour Allah Ses noms et attributs tels qu'Il S'est décrit", texte_ar: 'إثبات أسماء الله وصفاته كما وصف نفسه', est_correcte: true },
      { texte_fr: "Inventer de nouveaux noms à Allah", texte_ar: 'اختراع أسماء لله', est_correcte: false },
      { texte_fr: "Nier tous les noms d'Allah", texte_ar: 'نفي جميع أسماء الله', est_correcte: false },
      { texte_fr: "Donner les noms d'Allah aux créatures", texte_ar: 'إعطاء أسماء الله للمخلوقات', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'ghayb',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Que se passe-t-il dans la tombe selon la croyance authentique ?",
    texte_ar: 'ماذا يحدث في القبر حسب العقيدة الصحيحة؟',
    dalil_ref: 'Sahih Al-Bukhari 1369',
    dalil_texte_ar: 'إِنَّ الْعَبْدَ إِذَا وُضِعَ فِي قَبْرِهِ ... أَتَاهُ مَلَكَانِ',
    dalil_texte_fr: "Lorsque le serviteur est mis dans sa tombe... deux anges viennent à lui.",
    explication: "Le défunt est interrogé dans sa tombe par deux anges sur son Seigneur, sa religion et son prophète. C'est la première étape de l'au-delà.",
    savant_reference: 'Al-Bukhari',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Le défunt est interrogé par deux anges", texte_ar: 'يُسأل الميت من قبل ملكين', est_correcte: true },
      { texte_fr: "Le défunt se réincarne", texte_ar: 'يتناسخ الميت', est_correcte: false },
      { texte_fr: "Rien ne se passe", texte_ar: 'لا يحدث شيء', est_correcte: false },
      { texte_fr: "Le défunt revient sur terre une semaine", texte_ar: 'يعود الميت أسبوعًا', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'iman',
    niveau: 3,
    madhab: 'general',
    texte_fr: "L'un des signes majeurs (alamat al-kubra) de l'Heure (la fin des temps) est :",
    texte_ar: 'من علامات الساعة الكبرى:',
    dalil_ref: 'Sahih Muslim 2901',
    dalil_texte_ar: 'إِنَّهَا لَنْ تَقُومَ حَتَّى تَرَوْنَ قَبْلَهَا عَشْرَ آيَاتٍ',
    dalil_texte_fr: "Elle ne surviendra pas avant que vous ne voyiez dix signes (avant cela).",
    explication: "Parmi les signes majeurs de l'Heure : la sortie du Dajjal, la descente de Issa fils de Maryam, la sortie de Yajuj et Majuj, et le lever du soleil à l'Occident.",
    savant_reference: 'Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "La descente de Issa (Jésus) fils de Maryam", texte_ar: 'نزول عيسى ابن مريم', est_correcte: true },
      { texte_fr: "L'invention de l'écriture", texte_ar: 'اختراع الكتابة', est_correcte: false },
      { texte_fr: "La construction de la première mosquée", texte_ar: 'بناء أول مسجد', est_correcte: false },
      { texte_fr: "La naissance du Prophète", texte_ar: 'ولادة النبي', est_correcte: false },
    ],
  },
  {
    domaine: 'aqida',
    sous_domaine: 'tawhid',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quelle sourate du Coran est dédiée à la description de l'unicité d'Allah et équivaut au tiers du Coran ?",
    texte_ar: 'أي سورة تختص بوصف توحيد الله وتعدل ثلث القرآن؟',
    dalil_ref: 'Sahih Al-Bukhari 5013',
    dalil_texte_ar: 'قُلْ هُوَ اللَّهُ أَحَدٌ تَعْدِلُ ثُلُثَ الْقُرْآنِ',
    dalil_texte_fr: "« Dis : Il est Allah, l'Unique » équivaut au tiers du Coran.",
    explication: "La sourate Al-Ikhlas résume le tawhid et le Prophète a dit qu'elle équivaut au tiers du Coran par son sens.",
    savant_reference: 'Al-Bukhari',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Al-Ikhlas", texte_ar: 'الإخلاص', est_correcte: true },
      { texte_fr: "Al-Kafirun", texte_ar: 'الكافرون', est_correcte: false },
      { texte_fr: "An-Nas", texte_ar: 'الناس', est_correcte: false },
      { texte_fr: "Al-Masad", texte_ar: 'المسد', est_correcte: false },
    ],
  },

  // ===================== TAFSIR (10) =====================
  {
    domaine: 'tafsir',
    sous_domaine: 'ulum_quran',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Quelle est la première sourate révélée au Prophète (les premiers versets) ?",
    texte_ar: 'ما أول ما نزل من القرآن على النبي؟',
    dalil_ref: 'Sourate Al-Alaq 96:1',
    dalil_texte_ar: 'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',
    dalil_texte_fr: "Lis, au nom de ton Seigneur qui a créé.",
    explication: "Les premiers versets révélés sont le début de la sourate Al-Alaq (Iqra), reçus dans la grotte de Hira par l'intermédiaire de Jibril.",
    savant_reference: 'Al-Bukhari (récit du début de la révélation)',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Les premiers versets d'Al-Alaq (Iqra)", texte_ar: 'أوائل سورة العلق (اقرأ)', est_correcte: true },
      { texte_fr: "Al-Fatiha en entier", texte_ar: 'الفاتحة كاملة', est_correcte: false },
      { texte_fr: "Ayat al-Kursi", texte_ar: 'آية الكرسي', est_correcte: false },
      { texte_fr: "La sourate Al-Baqara", texte_ar: 'سورة البقرة', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'ulum_quran',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Quelle est la sourate la plus courte du Coran (en nombre de versets) ?",
    texte_ar: 'ما أقصر سورة في القرآن بعدد الآيات؟',
    explication: "Sourate Al-Kawthar est la plus courte du Coran avec trois versets.",
    savant_reference: 'Ulum al-Quran',
    reponses: [
      { texte_fr: "Al-Kawthar", texte_ar: 'الكوثر', est_correcte: true },
      { texte_fr: "Al-Fatiha", texte_ar: 'الفاتحة', est_correcte: false },
      { texte_fr: "Al-Asr", texte_ar: 'العصر', est_correcte: false },
      { texte_fr: "An-Nasr", texte_ar: 'النصر', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'tafsir_sourates',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quel est le verset considéré comme le plus grand verset du Coran ?",
    texte_ar: 'ما أعظم آية في القرآن؟',
    dalil_ref: 'Sahih Muslim 810',
    dalil_texte_ar: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
    dalil_texte_fr: "Allah, point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même.",
    explication: "Ayat al-Kursi (Al-Baqara 2:255) est le plus grand verset du Coran selon le hadith authentique rapporté par Ubayy ibn Ka'b.",
    savant_reference: 'Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Ayat al-Kursi (Al-Baqara 2:255)", texte_ar: 'آية الكرسي (البقرة ٢٥٥)', est_correcte: true },
      { texte_fr: "Le premier verset d'Al-Fatiha", texte_ar: 'أول آية من الفاتحة', est_correcte: false },
      { texte_fr: "Le dernier verset d'Al-Baqara", texte_ar: 'آخر آية من البقرة', est_correcte: false },
      { texte_fr: "Le verset du trône d'Al-Imran", texte_ar: 'آية في آل عمران', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'tafsir_sourates',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Quelle sourate est appelée « le cœur du Coran » selon une tradition rapportée ?",
    texte_ar: 'أي سورة تُسمى قلب القرآن؟',
    explication: "La sourate Ya-Sin est traditionnellement appelée « le cœur du Coran ». On la lit notamment auprès des mourants.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Ya-Sin", texte_ar: 'يس', est_correcte: true },
      { texte_fr: "Al-Mulk", texte_ar: 'الملك', est_correcte: false },
      { texte_fr: "Ar-Rahman", texte_ar: 'الرحمن', est_correcte: false },
      { texte_fr: "Al-Waqi'a", texte_ar: 'الواقعة', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'ulum_quran',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Quelle est la différence entre les sourates makkiyya et madaniyya ?",
    texte_ar: 'ما الفرق بين السور المكية والمدنية؟',
    explication: "Les sourates makkiyya furent révélées avant la Hijra (axées sur le tawhid et l'au-delà), et les madaniyya après la Hijra à Médine (axées sur les lois et l'organisation sociale).",
    savant_reference: 'As-Suyuti, Al-Itqan fi Ulum al-Quran',
    reponses: [
      { texte_fr: "Makkiyya = avant la Hijra, Madaniyya = après la Hijra", texte_ar: 'المكية قبل الهجرة والمدنية بعدها', est_correcte: true },
      { texte_fr: "Makkiyya = courtes, Madaniyya = longues toujours", texte_ar: 'المكية قصيرة والمدنية طويلة دائمًا', est_correcte: false },
      { texte_fr: "Aucune différence", texte_ar: 'لا فرق بينهما', est_correcte: false },
      { texte_fr: "Makkiyya = révélées en arabe, Madaniyya = en hébreu", texte_ar: 'المكية بالعربية والمدنية بالعبرية', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'tajwid',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Que désigne la règle de tajwid appelée « al-ghunna » ?",
    texte_ar: 'ما المقصود بالغنة في التجويد؟',
    explication: "Al-ghunna est le son nasal produit lors de la prononciation du noun et du mim, notamment lorsqu'ils portent une shadda (noun mushaddad et mim mushaddad).",
    savant_reference: 'Sciences du tajwid',
    reponses: [
      { texte_fr: "Le son nasal accompagnant le noun et le mim", texte_ar: 'صوت يخرج من الأنف مع النون والميم', est_correcte: true },
      { texte_fr: "L'allongement d'une voyelle", texte_ar: 'مد الحركة', est_correcte: false },
      { texte_fr: "L'arrêt sur un verset", texte_ar: 'الوقف على الآية', est_correcte: false },
      { texte_fr: "La récitation rapide", texte_ar: 'الإسراع في القراءة', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'tajwid',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Que désigne l'idgham en tajwid ?",
    texte_ar: 'ما معنى الإدغام في التجويد؟',
    explication: "L'idgham consiste à fusionner une lettre dans une autre, transformant le noun sakin ou le tanwin en la lettre suivante (par exemple dans certains cas avec les lettres yarmaloun).",
    savant_reference: 'Sciences du tajwid',
    reponses: [
      { texte_fr: "Fusionner une lettre dans la lettre suivante", texte_ar: 'إدخال حرف في حرف بعده', est_correcte: true },
      { texte_fr: "Prononcer chaque lettre distinctement (izhar)", texte_ar: 'إظهار كل حرف', est_correcte: false },
      { texte_fr: "Allonger le son six temps", texte_ar: 'المد ست حركات', est_correcte: false },
      { texte_fr: "Sauter une lettre", texte_ar: 'حذف حرف', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'memorisation',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Comment appelle-t-on une personne qui a mémorisé l'intégralité du Coran ?",
    texte_ar: 'ماذا يُسمى من حفظ القرآن كاملًا؟',
    explication: "Celui qui mémorise tout le Coran par cœur est appelé hafiz (au pluriel huffaz).",
    savant_reference: 'Terminologie islamique',
    reponses: [
      { texte_fr: "Un hafiz", texte_ar: 'حافظ', est_correcte: true },
      { texte_fr: "Un mufti", texte_ar: 'مفتٍ', est_correcte: false },
      { texte_fr: "Un muhaddith", texte_ar: 'محدّث', est_correcte: false },
      { texte_fr: "Un faqih", texte_ar: 'فقيه', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'ulum_quran',
    niveau: 5,
    madhab: 'general',
    texte_fr: "Qu'est-ce que le naskh (abrogation) dans les sciences du Coran ?",
    texte_ar: 'ما هو النسخ في علوم القرآن؟',
    dalil_ref: 'Sourate Al-Baqara 2:106',
    dalil_texte_ar: 'مَا نَنسَخْ مِنْ آيَةٍ أَوْ نُنسِهَا نَأْتِ بِخَيْرٍ مِّنْهَا أَوْ مِثْلِهَا',
    dalil_texte_fr: "Tout verset que Nous abrogeons ou que Nous faisons oublier, Nous en apportons un meilleur, ou un semblable.",
    explication: "Le naskh est le remplacement d'un jugement légal antérieur par un jugement postérieur. Il relève de la sagesse d'Allah dans la législation progressive.",
    savant_reference: 'As-Suyuti, Al-Itqan',
    reponses: [
      { texte_fr: "Le remplacement d'un jugement par un jugement postérieur", texte_ar: 'رفع حكم شرعي بحكم لاحق', est_correcte: true },
      { texte_fr: "La copie manuscrite du Coran", texte_ar: 'نسخ المصحف باليد', est_correcte: false },
      { texte_fr: "La traduction du Coran", texte_ar: 'ترجمة القرآن', est_correcte: false },
      { texte_fr: "La récitation à voix haute", texte_ar: 'الجهر بالقراءة', est_correcte: false },
    ],
  },
  {
    domaine: 'tafsir',
    sous_domaine: 'tafsir_sourates',
    niveau: 2,
    madhab: 'general',
    texte_fr: "De quoi parle principalement la sourate Al-Kahf (la Caverne) ?",
    texte_ar: 'عن ماذا تتحدث سورة الكهف بشكل رئيسي؟',
    dalil_ref: 'Sourate Al-Kahf 18:13',
    dalil_texte_ar: 'إِنَّهُمْ فِتْيَةٌ آمَنُوا بِرَبِّهِمْ وَزِدْنَاهُمْ هُدًى',
    dalil_texte_fr: "Ce sont des jeunes gens qui crurent en leur Seigneur, et Nous leur avons accru leur guidée.",
    explication: "La sourate Al-Kahf relate notamment l'histoire des Gens de la Caverne (Ashab al-Kahf), de Musa et al-Khidr, et de Dhul-Qarnayn. Sa lecture le vendredi est recommandée.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Les Gens de la Caverne et d'autres récits d'épreuves de la foi", texte_ar: 'أصحاب الكهف وقصص الفتن', est_correcte: true },
      { texte_fr: "Les règles de l'héritage", texte_ar: 'أحكام الميراث', est_correcte: false },
      { texte_fr: "Les rites du Hajj", texte_ar: 'مناسك الحج', est_correcte: false },
      { texte_fr: "Les lois du commerce", texte_ar: 'أحكام التجارة', est_correcte: false },
    ],
  },

  // ===================== HADITH (10) =====================
  {
    domaine: 'hadith',
    sous_domaine: 'kutub_sitta',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Quel recueil de hadith est considéré comme le plus authentique après le Coran ?",
    texte_ar: 'ما أصح كتاب بعد القرآن الكريم؟',
    explication: "Sahih Al-Bukhari est unanimement considéré comme le livre le plus authentique après le Coran, suivi de Sahih Muslim.",
    savant_reference: 'Consensus des savants du hadith',
    reponses: [
      { texte_fr: "Sahih Al-Bukhari", texte_ar: 'صحيح البخاري', est_correcte: true },
      { texte_fr: "Sunan Ibn Maja", texte_ar: 'سنن ابن ماجه', est_correcte: false },
      { texte_fr: "Musnad Ahmad", texte_ar: 'مسند أحمد', est_correcte: false },
      { texte_fr: "Al-Muwatta", texte_ar: 'الموطأ', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'kutub_sitta',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Combien de recueils composent les Kutub as-Sitta (les six livres) ?",
    texte_ar: 'كم عدد كتب السنة المعروفة بالكتب الستة؟',
    explication: "Les Kutub as-Sitta sont au nombre de six : Bukhari, Muslim, Abu Dawud, At-Tirmidhi, An-Nasa'i et Ibn Maja.",
    savant_reference: 'Ulum al-Hadith',
    reponses: [
      { texte_fr: "Six", texte_ar: 'ستة', est_correcte: true },
      { texte_fr: "Quatre", texte_ar: 'أربعة', est_correcte: false },
      { texte_fr: "Dix", texte_ar: 'عشرة', est_correcte: false },
      { texte_fr: "Trois", texte_ar: 'ثلاثة', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'ulum_hadith',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Qu'est-ce que l'isnad (la chaîne de transmission) d'un hadith ?",
    texte_ar: 'ما هو الإسناد في علم الحديث؟',
    explication: "L'isnad est la chaîne des rapporteurs qui transmettent le texte (matn) du hadith jusqu'au Prophète. Son examen permet de juger l'authenticité.",
    savant_reference: "Ibn As-Salah, Muqaddima",
    reponses: [
      { texte_fr: "La chaîne des rapporteurs transmettant le hadith", texte_ar: 'سلسلة الرواة الناقلين للحديث', est_correcte: true },
      { texte_fr: "Le texte du hadith uniquement", texte_ar: 'متن الحديث فقط', est_correcte: false },
      { texte_fr: "Le titre du chapitre", texte_ar: 'عنوان الباب', est_correcte: false },
      { texte_fr: "Le nom du livre", texte_ar: 'اسم الكتاب', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'ulum_hadith',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Quel terme désigne un hadith dont la chaîne est faible (non fiable) ?",
    texte_ar: 'ما المصطلح الذي يطلق على الحديث ضعيف السند؟',
    explication: "Un hadith daif (faible) est celui dont la chaîne ou le texte présente un défaut (rapporteur faible, rupture de chaîne, etc.) le rendant non probant en soi.",
    savant_reference: "Nuzhat an-Nazar (Ibn Hajar)",
    reponses: [
      { texte_fr: "Daif (faible)", texte_ar: 'ضعيف', est_correcte: true },
      { texte_fr: "Sahih (authentique)", texte_ar: 'صحيح', est_correcte: false },
      { texte_fr: "Mutawatir (largement transmis)", texte_ar: 'متواتر', est_correcte: false },
      { texte_fr: "Hasan (bon)", texte_ar: 'حسن', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'arbain',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Selon un hadith célèbre des 40 de An-Nawawi, les actes valent par :",
    texte_ar: 'بحسب حديث مشهور من الأربعين النووية، الأعمال تُقيَّم بـ:',
    dalil_ref: 'Sahih Al-Bukhari 1, Sahih Muslim 1907',
    dalil_texte_ar: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    dalil_texte_fr: "Les actes ne valent que par les intentions, et chacun n'a que ce qu'il a eu l'intention de faire.",
    explication: "Ce hadith fondamental, premier des 40 de An-Nawawi, établit que la validité et la récompense des actes dépendent de l'intention (niyya).",
    savant_reference: 'Al-Bukhari et Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Les intentions (niyyat)", texte_ar: 'النيات', est_correcte: true },
      { texte_fr: "Leur quantité", texte_ar: 'كثرتها', est_correcte: false },
      { texte_fr: "L'argent dépensé", texte_ar: 'المال المنفق', est_correcte: false },
      { texte_fr: "Le lieu où ils sont faits", texte_ar: 'مكان فعلها', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'arbain',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Selon un hadith de An-Nawawi, fait partie du bon Islam d'une personne :",
    texte_ar: 'من حسن إسلام المرء بحسب حديث نووي:',
    dalil_ref: 'Sunan At-Tirmidhi 2317',
    dalil_texte_ar: 'مِنْ حُسْنِ إِسْلَامِ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ',
    dalil_texte_fr: "Fait partie du bon Islam d'une personne le fait de délaisser ce qui ne la concerne pas.",
    explication: "Ce hadith (12e des 40 de An-Nawawi) enseigne à se préoccuper de ce qui est utile et à délaisser le superflu et l'inutile.",
    savant_reference: 'At-Tirmidhi',
    grade_hadith: 'hasan',
    reponses: [
      { texte_fr: "Délaisser ce qui ne la concerne pas", texte_ar: 'ترك ما لا يعنيه', est_correcte: true },
      { texte_fr: "Parler beaucoup", texte_ar: 'كثرة الكلام', est_correcte: false },
      { texte_fr: "Accumuler les richesses", texte_ar: 'جمع المال', est_correcte: false },
      { texte_fr: "Voyager souvent", texte_ar: 'كثرة السفر', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'riyad_salihin',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Selon un hadith de Riyad as-Salihin, le musulman aime pour son frère :",
    texte_ar: 'بحسب حديث في رياض الصالحين، يحب المسلم لأخيه:',
    dalil_ref: 'Sahih Al-Bukhari 13, Sahih Muslim 45',
    dalil_texte_ar: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    dalil_texte_fr: "Nul d'entre vous ne croit véritablement tant qu'il n'aime pas pour son frère ce qu'il aime pour lui-même.",
    explication: "Ce hadith établit que la foi complète exige d'aimer pour son frère musulman le bien qu'on aime pour soi-même.",
    savant_reference: 'Al-Bukhari et Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Ce qu'il aime pour lui-même", texte_ar: 'ما يحب لنفسه', est_correcte: true },
      { texte_fr: "La pauvreté", texte_ar: 'الفقر', est_correcte: false },
      { texte_fr: "Moins de bien qu'à lui-même", texte_ar: 'أقل مما لنفسه', est_correcte: false },
      { texte_fr: "Rien de particulier", texte_ar: 'لا شيء', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'riyad_salihin',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Selon un hadith, celui qui croit en Allah et au Jour dernier doit :",
    texte_ar: 'بحسب حديث، من كان يؤمن بالله واليوم الآخر فعليه أن:',
    dalil_ref: 'Sahih Al-Bukhari 6018, Sahih Muslim 47',
    dalil_texte_ar: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    dalil_texte_fr: "Que celui qui croit en Allah et au Jour dernier dise du bien ou se taise.",
    explication: "Ce hadith lie la foi au comportement : dire du bien ou se taire, honorer son voisin et son hôte.",
    savant_reference: 'Al-Bukhari et Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Dire du bien ou se taire", texte_ar: 'يقول خيرًا أو يصمت', est_correcte: true },
      { texte_fr: "Parler en toutes circonstances", texte_ar: 'يتكلم في كل حال', est_correcte: false },
      { texte_fr: "Critiquer les autres", texte_ar: 'ينتقد الآخرين', est_correcte: false },
      { texte_fr: "Ne jamais saluer personne", texte_ar: 'لا يسلم على أحد', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'ulum_hadith',
    niveau: 5,
    madhab: 'general',
    texte_fr: "Qu'est-ce qu'un hadith mutawatir ?",
    texte_ar: 'ما هو الحديث المتواتر؟',
    explication: "Le hadith mutawatir est rapporté par un nombre de transmetteurs si grand à chaque maillon qu'il est impossible qu'ils se soient concertés sur un mensonge ; il procure la certitude.",
    savant_reference: "Nuzhat an-Nazar (Ibn Hajar)",
    reponses: [
      { texte_fr: "Transmis par un très grand nombre excluant l'entente sur un mensonge", texte_ar: 'ما رواه عدد كثير تحيل العادة تواطؤهم على الكذب', est_correcte: true },
      { texte_fr: "Rapporté par un seul compagnon faible", texte_ar: 'ما رواه صحابي ضعيف واحد', est_correcte: false },
      { texte_fr: "Un hadith sans chaîne", texte_ar: 'حديث بلا سند', est_correcte: false },
      { texte_fr: "Un hadith inventé", texte_ar: 'حديث موضوع', est_correcte: false },
    ],
  },
  {
    domaine: 'hadith',
    sous_domaine: 'kutub_sitta',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Qui est l'auteur du célèbre Sahih connu comme le second plus authentique recueil ?",
    texte_ar: 'من مؤلف صحيح مسلم؟',
    explication: "L'imam Muslim ibn al-Hajjaj an-Naysaburi (m. 261 H) est l'auteur du Sahih Muslim, deuxième recueil le plus authentique après Bukhari.",
    savant_reference: 'Ulum al-Hadith',
    reponses: [
      { texte_fr: "Muslim ibn al-Hajjaj", texte_ar: 'مسلم بن الحجاج', est_correcte: true },
      { texte_fr: "Abu Dawud as-Sijistani", texte_ar: 'أبو داود السجستاني', est_correcte: false },
      { texte_fr: "Ibn Maja", texte_ar: 'ابن ماجه', est_correcte: false },
      { texte_fr: "Malik ibn Anas", texte_ar: 'مالك بن أنس', est_correcte: false },
    ],
  },

  // ===================== SIRAH (10) =====================
  {
    domaine: 'sirah',
    sous_domaine: 'sirah_nabawiyya',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Dans quelle ville est né le Prophète Muhammad (sallallahu alayhi wa sallam) ?",
    texte_ar: 'في أي مدينة وُلد النبي محمد صلى الله عليه وسلم؟',
    explication: "Le Prophète est né à La Mecque (Makka) vers l'an 570 CE, l'année de l'Éléphant.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "La Mecque", texte_ar: 'مكة', est_correcte: true },
      { texte_fr: "Médine", texte_ar: 'المدينة', est_correcte: false },
      { texte_fr: "Taïf", texte_ar: 'الطائف', est_correcte: false },
      { texte_fr: "Jérusalem", texte_ar: 'القدس', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sirah_nabawiyya',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Vers quelle ville le Prophète a-t-il émigré lors de la Hijra ?",
    texte_ar: 'إلى أي مدينة هاجر النبي في الهجرة؟',
    explication: "Le Prophète a émigré de La Mecque vers Yathrib, qui devint Médine (Al-Madina al-Munawwara), en l'an 622 CE.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "Médine (Yathrib)", texte_ar: 'المدينة (يثرب)', est_correcte: true },
      { texte_fr: "Damas", texte_ar: 'دمشق', est_correcte: false },
      { texte_fr: "Le Caire", texte_ar: 'القاهرة', est_correcte: false },
      { texte_fr: "Bagdad", texte_ar: 'بغداد', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sirah_nabawiyya',
    niveau: 3,
    madhab: 'general',
    texte_fr: "En quelle année de l'Hégire eut lieu la bataille de Badr ?",
    texte_ar: 'في أي عام هجري وقعت غزوة بدر؟',
    dalil_ref: 'Sourate Al-Imran 3:123',
    dalil_texte_ar: 'وَلَقَدْ نَصَرَكُمُ اللَّهُ بِبَدْرٍ وَأَنتُمْ أَذِلَّةٌ',
    dalil_texte_fr: "Allah vous a donné la victoire à Badr alors que vous étiez humiliés (faibles).",
    explication: "La grande bataille de Badr eut lieu en l'an 2 de l'Hégire (624 CE) ; les musulmans, bien que peu nombreux, y remportèrent une victoire décisive.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "An 2 de l'Hégire", texte_ar: 'السنة الثانية للهجرة', est_correcte: true },
      { texte_fr: "An 10 de l'Hégire", texte_ar: 'السنة العاشرة للهجرة', est_correcte: false },
      { texte_fr: "An 6 de l'Hégire", texte_ar: 'السنة السادسة للهجرة', est_correcte: false },
      { texte_fr: "Avant la Hijra", texte_ar: 'قبل الهجرة', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sirah_nabawiyya',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Comment s'appelait le compagnon qui accompagna le Prophète dans la grotte lors de la Hijra ?",
    texte_ar: 'من الصحابي الذي صحب النبي في الغار أثناء الهجرة؟',
    dalil_ref: 'Sourate At-Tawba 9:40',
    dalil_texte_ar: 'ثَانِيَ اثْنَيْنِ إِذْ هُمَا فِي الْغَارِ إِذْ يَقُولُ لِصَاحِبِهِ لَا تَحْزَنْ إِنَّ اللَّهَ مَعَنَا',
    dalil_texte_fr: "Le second de deux, quand ils étaient dans la grotte et qu'il disait à son compagnon : Ne t'afflige pas, car Allah est avec nous.",
    explication: "Abu Bakr as-Siddiq accompagna le Prophète dans la grotte de Thawr. Le Coran y fait allusion dans la sourate At-Tawba.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Abu Bakr as-Siddiq", texte_ar: 'أبو بكر الصديق', est_correcte: true },
      { texte_fr: "Umar ibn al-Khattab", texte_ar: 'عمر بن الخطاب', est_correcte: false },
      { texte_fr: "Ali ibn Abi Talib", texte_ar: 'علي بن أبي طالب', est_correcte: false },
      { texte_fr: "Bilal ibn Rabah", texte_ar: 'بلال بن رباح', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sahaba',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Qui fut le premier homme adulte à embrasser l'Islam ?",
    texte_ar: 'من أول الرجال إسلامًا؟',
    explication: "Abu Bakr as-Siddiq fut le premier homme adulte libre à embrasser l'Islam, parmi les premiers à croire au Prophète.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "Abu Bakr as-Siddiq", texte_ar: 'أبو بكر الصديق', est_correcte: true },
      { texte_fr: "Abu Talib", texte_ar: 'أبو طالب', est_correcte: false },
      { texte_fr: "Abu Sufyan", texte_ar: 'أبو سفيان', est_correcte: false },
      { texte_fr: "Abu Lahab", texte_ar: 'أبو لهب', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sahaba',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Qui fut la première épouse du Prophète et la première personne à croire en lui ?",
    texte_ar: 'من أول زوجات النبي وأول من آمن به؟',
    explication: "Khadija bint Khuwaylid fut la première épouse du Prophète et la première personne à croire en sa mission.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "Khadija bint Khuwaylid", texte_ar: 'خديجة بنت خويلد', est_correcte: true },
      { texte_fr: "Aïcha bint Abi Bakr", texte_ar: 'عائشة بنت أبي بكر', est_correcte: false },
      { texte_fr: "Hafsa bint Umar", texte_ar: 'حفصة بنت عمر', est_correcte: false },
      { texte_fr: "Umm Salama", texte_ar: 'أم سلمة', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sahaba',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quel compagnon était surnommé « le sabre dégainé d'Allah » (Sayfullah al-maslul) ?",
    texte_ar: 'أي صحابي لُقّب بسيف الله المسلول؟',
    explication: "Khalid ibn al-Walid fut surnommé « le sabre dégainé d'Allah » par le Prophète pour son génie militaire et ses victoires.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "Khalid ibn al-Walid", texte_ar: 'خالد بن الوليد', est_correcte: true },
      { texte_fr: "Sa'd ibn Abi Waqqas", texte_ar: 'سعد بن أبي وقاص', est_correcte: false },
      { texte_fr: "Talha ibn Ubaydillah", texte_ar: 'طلحة بن عبيد الله', est_correcte: false },
      { texte_fr: "Az-Zubayr ibn al-Awwam", texte_ar: 'الزبير بن العوام', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'khilafa',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Qui fut le premier calife (khalifa) après le Prophète ?",
    texte_ar: 'من أول الخلفاء الراشدين بعد النبي؟',
    explication: "Abu Bakr as-Siddiq fut le premier des califes bien guidés (Khulafa ar-Rashidun) après le décès du Prophète.",
    savant_reference: "At-Tabari, Tarikh al-Umam",
    reponses: [
      { texte_fr: "Abu Bakr as-Siddiq", texte_ar: 'أبو بكر الصديق', est_correcte: true },
      { texte_fr: "Umar ibn al-Khattab", texte_ar: 'عمر بن الخطاب', est_correcte: false },
      { texte_fr: "Uthman ibn Affan", texte_ar: 'عثمان بن عفان', est_correcte: false },
      { texte_fr: "Ali ibn Abi Talib", texte_ar: 'علي بن أبي طالب', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'khilafa',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quel calife bien guidé est connu pour avoir unifié le Coran dans un mushaf de référence ?",
    texte_ar: 'أي خليفة راشد عُرف بجمع القرآن في مصحف موحد؟',
    explication: "Uthman ibn Affan ordonna la compilation et l'unification du Coran en un mushaf de référence (mushaf Uthmani), envoyant des copies aux grandes villes.",
    savant_reference: "Sahih Al-Bukhari (récit de la compilation)",
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Uthman ibn Affan", texte_ar: 'عثمان بن عفان', est_correcte: true },
      { texte_fr: "Ali ibn Abi Talib", texte_ar: 'علي بن أبي طالب', est_correcte: false },
      { texte_fr: "Mu'awiya ibn Abi Sufyan", texte_ar: 'معاوية بن أبي سفيان', est_correcte: false },
      { texte_fr: "Umar ibn Abd al-Aziz", texte_ar: 'عمر بن عبد العزيز', est_correcte: false },
    ],
  },
  {
    domaine: 'sirah',
    sous_domaine: 'sirah_nabawiyya',
    niveau: 4,
    madhab: 'general',
    texte_fr: "En quelle année eut lieu la conquête (Fath) de La Mecque ?",
    texte_ar: 'في أي عام كان فتح مكة؟',
    dalil_ref: 'Sourate An-Nasr 110:1',
    dalil_texte_ar: 'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ',
    dalil_texte_fr: "Lorsque vient le secours d'Allah ainsi que la victoire.",
    explication: "La conquête pacifique de La Mecque eut lieu en l'an 8 de l'Hégire (630 CE) ; le Prophète y entra et purifia la Kaaba des idoles.",
    savant_reference: "Ibn Hisham, As-Sira an-Nabawiyya",
    reponses: [
      { texte_fr: "An 8 de l'Hégire", texte_ar: 'السنة الثامنة للهجرة', est_correcte: true },
      { texte_fr: "An 2 de l'Hégire", texte_ar: 'السنة الثانية للهجرة', est_correcte: false },
      { texte_fr: "An 13 de l'Hégire", texte_ar: 'السنة الثالثة عشرة للهجرة', est_correcte: false },
      { texte_fr: "Avant la Hijra", texte_ar: 'قبل الهجرة', est_correcte: false },
    ],
  },

  // ===================== AKHLAQ (10) =====================
  {
    domaine: 'akhlaq',
    sous_domaine: 'vertus',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Quel fut l'un des principaux objectifs de la mission du Prophète concernant le caractère ?",
    texte_ar: 'ما من أهداف بعثة النبي فيما يخص الأخلاق؟',
    dalil_ref: 'Musnad Ahmad 8952',
    dalil_texte_ar: 'إِنَّمَا بُعِثْتُ لِأُتَمِّمَ مَكَارِمَ الْأَخْلَاقِ',
    dalil_texte_fr: "Je n'ai été envoyé que pour parfaire les nobles caractères.",
    explication: "Le Prophète a déclaré avoir été envoyé pour parachever les nobles comportements, montrant la place centrale de l'éthique en Islam.",
    savant_reference: 'Ahmad (authentifié par Al-Albani)',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Parfaire les nobles caractères", texte_ar: 'إتمام مكارم الأخلاق', est_correcte: true },
      { texte_fr: "Accumuler des richesses", texte_ar: 'جمع المال', est_correcte: false },
      { texte_fr: "Conquérir des terres", texte_ar: 'فتح الأراضي', est_correcte: false },
      { texte_fr: "Construire des palais", texte_ar: 'بناء القصور', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'adab',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Que doit dire un musulman avant de commencer à manger ?",
    texte_ar: 'ماذا يقول المسلم قبل الأكل؟',
    dalil_ref: 'Sunan Abi Dawud 3767',
    dalil_texte_ar: 'إِذَا أَكَلَ أَحَدُكُمْ فَلْيَذْكُرِ اسْمَ اللَّهِ',
    dalil_texte_fr: "Lorsque l'un de vous mange, qu'il mentionne le nom d'Allah.",
    explication: "On dit « Bismillah » avant de manger. Si on l'oublie, on dit « Bismillah awwalahu wa akhirahu ».",
    savant_reference: 'Abu Dawud',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Bismillah", texte_ar: 'بسم الله', est_correcte: true },
      { texte_fr: "Subhanallah seulement", texte_ar: 'سبحان الله فقط', est_correcte: false },
      { texte_fr: "Rien du tout", texte_ar: 'لا شيء', est_correcte: false },
      { texte_fr: "Allahu Akbar trois fois", texte_ar: 'الله أكبر ثلاثًا', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'adab',
    niveau: 1,
    madhab: 'general',
    texte_fr: "Avec quelle main est-il recommandé de manger et de boire selon la Sunna ?",
    texte_ar: 'بأي يد يُستحب الأكل والشرب حسب السنة؟',
    dalil_ref: 'Sahih Muslim 2020',
    dalil_texte_ar: 'إِذَا أَكَلَ أَحَدُكُمْ فَلْيَأْكُلْ بِيَمِينِهِ وَإِذَا شَرِبَ فَلْيَشْرَبْ بِيَمِينِهِ',
    dalil_texte_fr: "Lorsque l'un de vous mange, qu'il mange de sa main droite, et lorsqu'il boit, qu'il boive de sa main droite.",
    explication: "Manger et boire de la main droite est une Sunna confirmée ; manger de la gauche imite le comportement du diable selon le hadith.",
    savant_reference: 'Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "La main droite", texte_ar: 'اليد اليمنى', est_correcte: true },
      { texte_fr: "La main gauche", texte_ar: 'اليد اليسرى', est_correcte: false },
      { texte_fr: "Les deux mains ensemble", texte_ar: 'كلتا اليدين', est_correcte: false },
      { texte_fr: "Peu importe", texte_ar: 'لا يهم', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'dua',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Que signifie le terme « dua » en Islam ?",
    texte_ar: 'ما معنى الدعاء في الإسلام؟',
    dalil_ref: 'Sourate Ghafir 40:60',
    dalil_texte_ar: 'وَقَالَ رَبُّكُمُ ادْعُونِي أَسْتَجِبْ لَكُمْ',
    dalil_texte_fr: "Et votre Seigneur dit : Invoquez-Moi, Je vous répondrai.",
    explication: "Le dua est l'invocation, le fait de s'adresser à Allah pour Lui demander quelque chose ou Le louer. C'est l'essence de l'adoration.",
    savant_reference: 'Tafsir As-Sa\'di',
    reponses: [
      { texte_fr: "L'invocation adressée à Allah", texte_ar: 'الدعاء الموجه إلى الله', est_correcte: true },
      { texte_fr: "Le jeûne surérogatoire", texte_ar: 'صوم النافلة', est_correcte: false },
      { texte_fr: "L'aumône obligatoire", texte_ar: 'الزكاة', est_correcte: false },
      { texte_fr: "Le pèlerinage", texte_ar: 'الحج', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'dua',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Que dit-on en entrant dans la mosquée selon la Sunna ?",
    texte_ar: 'ماذا يُقال عند دخول المسجد حسب السنة؟',
    dalil_ref: 'Sahih Muslim 713',
    dalil_texte_ar: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    dalil_texte_fr: "Ô Allah, ouvre-moi les portes de Ta miséricorde.",
    explication: "En entrant à la mosquée, on invoque : « Allahumma iftah li abwaba rahmatik », et en sortant on demande la grâce d'Allah.",
    savant_reference: 'Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Allahumma iftah li abwaba rahmatik", texte_ar: 'اللهم افتح لي أبواب رحمتك', est_correcte: true },
      { texte_fr: "Rien, on entre en silence", texte_ar: 'لا شيء', est_correcte: false },
      { texte_fr: "Allahu Akbar uniquement", texte_ar: 'الله أكبر فقط', est_correcte: false },
      { texte_fr: "Une invocation pour la pluie", texte_ar: 'دعاء الاستسقاء', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'vertus',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Quelle qualité le Prophète a-t-il décrite comme étant la plus lourde dans la balance des bonnes œuvres ?",
    texte_ar: 'ما الخُلق الذي وصفه النبي بأنه أثقل في الميزان؟',
    dalil_ref: 'Sunan At-Tirmidhi 2002',
    dalil_texte_ar: 'مَا مِنْ شَيْءٍ أَثْقَلُ فِي مِيزَانِ الْمُؤْمِنِ يَوْمَ الْقِيَامَةِ مِنْ حُسْنِ الْخُلُقِ',
    dalil_texte_fr: "Rien n'est plus lourd dans la balance du croyant, au Jour de la Résurrection, que le bon caractère.",
    explication: "Le bon caractère (husn al-khuluq) est, selon ce hadith, ce qui pèse le plus lourd dans la balance des bonnes actions.",
    savant_reference: 'At-Tirmidhi',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Le bon caractère (husn al-khuluq)", texte_ar: 'حسن الخلق', est_correcte: true },
      { texte_fr: "L'abondance de richesses", texte_ar: 'كثرة المال', est_correcte: false },
      { texte_fr: "La force physique", texte_ar: 'القوة البدنية', est_correcte: false },
      { texte_fr: "L'éloquence", texte_ar: 'الفصاحة', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'vertus',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Comment l'Islam considère-t-il le respect et la bonté envers les parents (birr al-walidayn) ?",
    texte_ar: 'كيف ينظر الإسلام إلى بر الوالدين؟',
    dalil_ref: 'Sourate Al-Isra 17:23',
    dalil_texte_ar: 'وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا',
    dalil_texte_fr: "Ton Seigneur a décrété de n'adorer que Lui, et de faire le bien envers les parents.",
    explication: "La bonté envers les parents est ordonnée juste après l'adoration d'Allah, ce qui souligne son immense importance.",
    savant_reference: 'Tafsir Ibn Kathir',
    reponses: [
      { texte_fr: "Une obligation majeure, mentionnée juste après l'adoration d'Allah", texte_ar: 'واجب عظيم بعد عبادة الله مباشرة', est_correcte: true },
      { texte_fr: "Une simple coutume facultative", texte_ar: 'عادة اختيارية', est_correcte: false },
      { texte_fr: "Réservée uniquement aux parents musulmans", texte_ar: 'خاص بالوالدين المسلمين فقط', est_correcte: false },
      { texte_fr: "Sans importance après le mariage", texte_ar: 'لا أهمية له بعد الزواج', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'adab',
    niveau: 2,
    madhab: 'general',
    texte_fr: "Que doit faire un musulman lorsqu'il éternue selon la Sunna ?",
    texte_ar: 'ماذا يفعل المسلم عند العطاس حسب السنة؟',
    dalil_ref: 'Sahih Al-Bukhari 6224',
    dalil_texte_ar: 'إِذَا عَطَسَ أَحَدُكُمْ فَلْيَقُلِ الْحَمْدُ لِلَّهِ',
    dalil_texte_fr: "Lorsque l'un de vous éternue, qu'il dise : Al-hamdulillah (louange à Allah).",
    explication: "Celui qui éternue dit « Al-hamdulillah » ; celui qui l'entend lui répond « Yarhamuk Allah », et l'éternueur réplique « Yahdikum Allah ».",
    savant_reference: 'Al-Bukhari',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Dire Al-hamdulillah", texte_ar: 'يقول الحمد لله', est_correcte: true },
      { texte_fr: "Dire Astaghfirullah", texte_ar: 'يقول أستغفر الله', est_correcte: false },
      { texte_fr: "Ne rien dire", texte_ar: 'لا يقول شيئًا', est_correcte: false },
      { texte_fr: "Refaire ses ablutions", texte_ar: 'يعيد الوضوء', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'vertus',
    niveau: 4,
    madhab: 'general',
    texte_fr: "Comment l'Islam qualifie-t-il la patience (sabr) face aux épreuves ?",
    texte_ar: 'كيف يصف الإسلام الصبر عند الابتلاء؟',
    dalil_ref: 'Sourate Al-Baqara 2:153',
    dalil_texte_ar: 'يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
    dalil_texte_fr: "Ô vous qui avez cru, cherchez secours dans la patience et la prière. Allah est avec les endurants.",
    explication: "La patience est une grande vertu : Allah est avec les patients et leur récompense est sans compter (Az-Zumar 39:10).",
    savant_reference: 'Tafsir As-Sa\'di',
    reponses: [
      { texte_fr: "Une grande vertu dont la récompense est immense", texte_ar: 'فضيلة عظيمة أجرها كبير', est_correcte: true },
      { texte_fr: "Une faiblesse à éviter", texte_ar: 'ضعف يُتجنب', est_correcte: false },
      { texte_fr: "Réservée aux prophètes uniquement", texte_ar: 'خاصة بالأنبياء فقط', est_correcte: false },
      { texte_fr: "Sans aucune récompense", texte_ar: 'بلا أجر', est_correcte: false },
    ],
  },
  {
    domaine: 'akhlaq',
    sous_domaine: 'vertus',
    niveau: 3,
    madhab: 'general',
    texte_fr: "Que dit l'Islam au sujet du mensonge ?",
    texte_ar: 'ماذا يقول الإسلام عن الكذب؟',
    dalil_ref: 'Sahih Al-Bukhari 6094, Sahih Muslim 2607',
    dalil_texte_ar: 'وَإِنَّ الْكَذِبَ يَهْدِي إِلَى الْفُجُورِ وَإِنَّ الْفُجُورَ يَهْدِي إِلَى النَّارِ',
    dalil_texte_fr: "Le mensonge mène à la perversité, et la perversité mène au Feu.",
    explication: "Le mensonge est blâmé : il conduit à la perversité puis au Feu, tandis que la véracité conduit à la piété puis au Paradis.",
    savant_reference: 'Al-Bukhari et Muslim',
    grade_hadith: 'sahih',
    reponses: [
      { texte_fr: "Il est blâmé et conduit à la perversité", texte_ar: 'مذموم ويهدي إلى الفجور', est_correcte: true },
      { texte_fr: "Il est encouragé en affaires", texte_ar: 'محمود في التجارة', est_correcte: false },
      { texte_fr: "Il est neutre sans conséquence", texte_ar: 'محايد بلا أثر', est_correcte: false },
      { texte_fr: "Il est obligatoire entre amis", texte_ar: 'واجب بين الأصدقاء', est_correcte: false },
    ],
  },
];

export async function seedQuestionsExtra(client: Client): Promise<void> {
  let count = 0;
  for (const q of QUESTIONS_EXTRA) {
    const qResult = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, dalil_texte_ar, dalil_texte_fr, explication, savant_reference, grade_hadith)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
       RETURNING id`,
      [
        q.domaine, q.sous_domaine, q.niveau, q.madhab,
        q.texte_fr, q.texte_ar, q.dalil_ref,
        q.dalil_texte_ar, q.dalil_texte_fr,
        q.explication, q.savant_reference, q.grade_hadith,
      ]
    );
    const question_id = qResult.rows[0].id;
    for (const r of q.reponses) {
      await client.query(
        'INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte) VALUES ($1, $2, $3, $4)',
        [question_id, r.texte_fr, r.texte_ar, r.est_correcte]
      );
    }
    count++;
  }
  console.log(`Seeded ${count} extra questions.`);
}
