import { Client } from 'pg';

interface Q {
  domaine: string;
  niveau: number;
  texte_fr: string;
  texte_ar?: string;
  explication: string;
  dalil_ref?: string;
  grade_hadith?: string;
  sous_domaine?: string;
  reponses: { texte_fr: string; texte_ar?: string; est_correcte: boolean }[];
}

const Q: Q[] = [
  // ===== TAFSIR N1 =====
  { domaine:'tafsir', niveau:1, texte_fr:"Combien y a-t-il de sourates dans le Coran ?", texte_ar:'كم عدد سور القرآن؟', explication:"Le Coran contient 114 sourates, de la plus longue (al-Baqara) à la plus courte (al-Kawthar).", reponses:[{texte_fr:"114",est_correcte:true},{texte_fr:"100",est_correcte:false},{texte_fr:"99",est_correcte:false},{texte_fr:"30",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Combien y a-t-il de juz' (parties) dans le Coran ?", texte_ar:'كم جزءاً في القرآن؟', explication:"30 juz', pratique pour mémoriser ou réciter le Coran en entier en un mois.", reponses:[{texte_fr:"30",est_correcte:true},{texte_fr:"7",est_correcte:false},{texte_fr:"60",est_correcte:false},{texte_fr:"114",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quelle est la première sourate du Coran ?", texte_ar:'ما هي أول سورة في القرآن؟', explication:"Sourate al-Fatiha (l'Ouvrante), récitée dans chaque rakat de prière.", reponses:[{texte_fr:"Al-Fatiha",est_correcte:true},{texte_fr:"Al-Baqara",est_correcte:false},{texte_fr:"An-Nas",est_correcte:false},{texte_fr:"Al-Ikhlas",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quelle est la dernière sourate du Coran ?", texte_ar:'ما هي آخر سورة في القرآن؟', explication:"Sourate an-Nas, une sourate de protection contre les insufflations du Mauvais.", reponses:[{texte_fr:"An-Nas",est_correcte:true},{texte_fr:"Al-Falaq",est_correcte:false},{texte_fr:"Al-Ikhlas",est_correcte:false},{texte_fr:"Al-Kafirun",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quelle est la sourate la plus longue ?", texte_ar:'ما هي أطول سورة في القرآن؟', explication:"Sourate al-Baqara (la Vache), 286 versets, sourate médinoise.", reponses:[{texte_fr:"Al-Baqara",est_correcte:true},{texte_fr:"Al-Imran",est_correcte:false},{texte_fr:"An-Nisa",est_correcte:false},{texte_fr:"At-Tawba",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quel est le plus grand verset du Coran ?", texte_ar:'ما أعظم آية في القرآن؟', explication:"Le verset du Trône (Ayat al-Kursi), Sourate al-Baqara 2:255. Le Prophète ﷺ a dit : « C'est le plus grand verset du Coran. »", dalil_ref:"Sahih Muslim n°810", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Ayat al-Kursi (2:255)",est_correcte:true},{texte_fr:"Al-Ikhlas",est_correcte:false},{texte_fr:"Bismillah",est_correcte:false},{texte_fr:"Le dernier verset",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Combien de versets contient Sourate al-Fatiha ?", texte_ar:'كم آية في سورة الفاتحة؟', explication:"7 versets, surnommée les « Sept Versets répétés » (Sab' al-Mathani).", reponses:[{texte_fr:"7 versets",est_correcte:true},{texte_fr:"3 versets",est_correcte:false},{texte_fr:"10 versets",est_correcte:false},{texte_fr:"5 versets",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"En combien d'années le Coran fut-il révélé ?", texte_ar:'في كم سنة نزل القرآن؟', explication:"Environ 23 ans : 13 ans à La Mecque et 10 ans à Médine, par étapes selon les circonstances.", reponses:[{texte_fr:"23 ans",est_correcte:true},{texte_fr:"10 ans",est_correcte:false},{texte_fr:"5 ans",est_correcte:false},{texte_fr:"40 ans",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"En quelle nuit la révélation du Coran a-t-elle commencé ?", texte_ar:'في أي ليلة بدأ نزول القرآن؟', explication:"Laylat al-Qadr (la Nuit du Décret) en Ramadan, dans la grotte de Hira. Allah dit : « Nous l'avons fait descendre pendant une nuit bénie. » (Ad-Dukhan 44:3)", dalil_ref:"Sourate Al-Qadr 97:1", reponses:[{texte_fr:"Laylat al-Qadr en Ramadan",est_correcte:true},{texte_fr:"Une nuit d'hiver",est_correcte:false},{texte_fr:"La nuit du Mi'raj",est_correcte:false},{texte_fr:"Une nuit d'Aïd",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quel ange a apporté la révélation au Prophète ﷺ ?", texte_ar:'أي ملك نزل بالوحي؟', explication:"L'archange Jibril (Gabriel), nommé « Ar-Ruh al-Amin » (l'Esprit fidèle) dans le Coran.", dalil_ref:"Sourate Ash-Shu'ara 26:193", reponses:[{texte_fr:"Jibril",est_correcte:true},{texte_fr:"Mika'il",est_correcte:false},{texte_fr:"Israfil",est_correcte:false},{texte_fr:"Ridwan",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quel est le premier verset révélé ?", texte_ar:'ما أول آية نزلت؟', explication:"« Lis au nom de ton Seigneur qui a créé. » (Sourate al-Alaq 96:1) — révélé dans la grotte de Hira.", dalil_ref:"Sahih al-Bukhari n°3", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Iqra' (Lis) — Sourate Al-Alaq 96:1",est_correcte:true},{texte_fr:"La Fatiha",est_correcte:false},{texte_fr:"Al-Ikhlas",est_correcte:false},{texte_fr:"Bismillah",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quelle sourate est appelée « le cœur du Coran » ?", texte_ar:'ما السورة التي تسمى قلب القرآن؟', explication:"Sourate Yasin, selon un hadith rapporté par at-Tirmidhi : « Tout a un cœur, et le cœur du Coran est Yasin. »", dalil_ref:"Sunan at-Tirmidhi n°2887", grade_hadith:"Hadith Da'if", reponses:[{texte_fr:"Yasin",est_correcte:true},{texte_fr:"Al-Baqara",est_correcte:false},{texte_fr:"Al-Fatiha",est_correcte:false},{texte_fr:"Ar-Rahman",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quelle sourate équivaut à un tiers du Coran ?", texte_ar:'ما السورة التي تعدل ثلث القرآن؟', explication:"Sourate al-Ikhlas (Le Monothéisme Pur), car elle résume la doctrine du Tawhid.", dalil_ref:"Sahih al-Bukhari n°5013", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Al-Ikhlas",est_correcte:true},{texte_fr:"Al-Fatiha",est_correcte:false},{texte_fr:"Al-Kawthar",est_correcte:false},{texte_fr:"An-Nasr",est_correcte:false}] },
  { domaine:'tafsir', niveau:1, texte_fr:"Quelle est la sourate la plus courte du Coran ?", texte_ar:'ما أقصر سورة في القرآن؟', explication:"Sourate al-Kawthar (l'Abondance), seulement 3 versets, révélée à La Mecque.", reponses:[{texte_fr:"Al-Kawthar (3 versets)",est_correcte:true},{texte_fr:"Al-Ikhlas",est_correcte:false},{texte_fr:"An-Nas",est_correcte:false},{texte_fr:"Al-Asr",est_correcte:false}] },

  // ===== TAFSIR N2 =====
  { domaine:'tafsir', niveau:2, texte_fr:"Quelles sont les 3 dernières sourates appelées « al-Mu'awwidhat » ?", texte_ar:'ما هي المعوذات؟', explication:"Al-Ikhlas, al-Falaq, an-Nas. Le Prophète ﷺ les récitait pour se protéger chaque matin et soir.", dalil_ref:"Sunan Abi Dawud n°5082", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Al-Ikhlas, al-Falaq, an-Nas",est_correcte:true},{texte_fr:"Al-Fatiha, al-Baqara, Yasin",est_correcte:false},{texte_fr:"Al-Mulk, As-Sajda, Yasin",est_correcte:false},{texte_fr:"3 premières sourates",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Combien de sourates mecquoises et médinoises y a-t-il environ ?", texte_ar:'كم سورة مكية ومدنية تقريباً؟', explication:"Environ 86 mecquoises (avant Hijra) et 28 médinoises (après). Les sourates mecquoises traitent surtout du tawhid, les médinoises des règles de la communauté.", reponses:[{texte_fr:"86 mecquoises, 28 médinoises",est_correcte:true},{texte_fr:"50/50",est_correcte:false},{texte_fr:"114/0",est_correcte:false},{texte_fr:"30/80",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quelle est la 2e plus longue sourate du Coran ?", texte_ar:'ما هي ثاني أطول سورة؟', explication:"Sourate Al-Imran (la famille d'Imran), 200 versets, médinoise. Mère de Marie et sa famille.", reponses:[{texte_fr:"Al-Imran (200 versets)",est_correcte:true},{texte_fr:"An-Nisa",est_correcte:false},{texte_fr:"Al-Maida",est_correcte:false},{texte_fr:"Al-Anam",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Combien de versets contient Ayat al-Kursi ?", texte_ar:'كم آية في آية الكرسي؟', explication:"Un seul verset, le 255 de Sourate al-Baqara. Il décrit la grandeur d'Allah, Sa science et Son Trône.", reponses:[{texte_fr:"1 verset (al-Baqara 2:255)",est_correcte:true},{texte_fr:"3 versets",est_correcte:false},{texte_fr:"7 versets",est_correcte:false},{texte_fr:"10 versets",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quel verset clôt Sourate al-Baqara ?", texte_ar:'بماذا تختم سورة البقرة؟', explication:"Les deux derniers versets (285-286) appelés « Khawatim al-Baqara ». Le Prophète ﷺ a dit qu'il suffisait à celui qui les récite la nuit.", dalil_ref:"Sahih al-Bukhari n°5009", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Khawatim al-Baqara (versets 285-286)",est_correcte:true},{texte_fr:"Ayat al-Kursi",est_correcte:false},{texte_fr:"Bismillah",est_correcte:false},{texte_fr:"Versets de l'usure",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quelle sourate est appelée « l'amie » ou « la protectrice » selon un hadith ?", texte_ar:'ما السورة التي تشفع لقارئها؟', explication:"Sourate al-Mulk. Le Prophète ﷺ : « Une sourate de 30 versets a intercédé pour son lecteur jusqu'à ce qu'il soit pardonné. »", dalil_ref:"Sunan at-Tirmidhi n°2891", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Al-Mulk (la Royauté)",est_correcte:true},{texte_fr:"Yasin",est_correcte:false},{texte_fr:"Al-Kahf",est_correcte:false},{texte_fr:"Ar-Rahman",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quelle sourate est recommandée à réciter chaque vendredi ?", texte_ar:'ما السورة المستحب قراءتها يوم الجمعة؟', explication:"Sourate al-Kahf. Le Prophète ﷺ : « Quiconque récite Sourate al-Kahf le vendredi, une lumière l'éclairera entre les deux Jumu'a. »", dalil_ref:"al-Mustadrak al-Hakim n°3392", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Al-Kahf",est_correcte:true},{texte_fr:"Al-Mulk",est_correcte:false},{texte_fr:"Yasin",est_correcte:false},{texte_fr:"Al-Ikhlas",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quel est le sujet principal des sourates mecquoises ?", texte_ar:'ما موضوع السور المكية الرئيسي؟', explication:"Tawhid (unicité d'Allah), prophétologie, vie après la mort, récits des anciens peuples, fondements de la foi.", reponses:[{texte_fr:"Tawhid, foi, vie après la mort, récits",est_correcte:true},{texte_fr:"Lois pénales détaillées",est_correcte:false},{texte_fr:"Règles d'héritage",est_correcte:false},{texte_fr:"Calendrier des prières",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quel est le sujet principal des sourates médinoises ?", texte_ar:'ما موضوع السور المدنية الرئيسي؟', explication:"Législation détaillée (mariage, héritage, jihad, transactions), traités, relations avec les autres communautés.", reponses:[{texte_fr:"Législation et organisation de la communauté",est_correcte:true},{texte_fr:"Mécréants mecquois uniquement",est_correcte:false},{texte_fr:"Vie quotidienne au Yémen",est_correcte:false},{texte_fr:"Histoire des Perses",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Comment s'appelle l'ensemble des sourates très courtes à la fin du Coran ?", texte_ar:'ما اسم السور القصيرة في آخر القرآن؟', explication:"Al-Mufassal — sourates allant de Qaf (50) à an-Nas (114). Subdivisé en grand, moyen et court Mufassal.", reponses:[{texte_fr:"Al-Mufassal",est_correcte:true},{texte_fr:"Al-Mathani",est_correcte:false},{texte_fr:"As-Sab'",est_correcte:false},{texte_fr:"Al-Hizb",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quelle sourate fut révélée d'un seul coup ?", texte_ar:'ما السورة التي نزلت جملة واحدة؟', explication:"Sourate al-An'am, environ 165 versets, descendue d'un seul coup la nuit selon les rapports. Accompagnée de 70 000 anges.", reponses:[{texte_fr:"Al-An'am",est_correcte:true},{texte_fr:"Yasin",est_correcte:false},{texte_fr:"Al-Baqara",est_correcte:false},{texte_fr:"An-Nas",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Combien d'occurrences du mot « Allah » dans le Coran environ ?", texte_ar:'كم مرة ذكر اسم الله في القرآن؟', explication:"Environ 2697 occurrences du Nom « Allah » dans le Coran.", reponses:[{texte_fr:"Environ 2697 fois",est_correcte:true},{texte_fr:"100 fois",est_correcte:false},{texte_fr:"10 000 fois",est_correcte:false},{texte_fr:"114 fois",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quelle est l'origine du mot « Coran » (Qur'an) ?", texte_ar:'ما أصل كلمة قرآن؟', explication:"Du verbe arabe « qara'a » (lire, réciter). Le Coran est « ce qui est récité ».", reponses:[{texte_fr:"De « qara'a » : lire, réciter",est_correcte:true},{texte_fr:"De « karama » : honorer",est_correcte:false},{texte_fr:"De « qarana » : associer",est_correcte:false},{texte_fr:"Du persan ancien",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quel calife a fait compiler le Coran dans un mushaf unique ?", texte_ar:'أي خليفة جمع المصحف الموحد؟', explication:"Uthman ibn Affan رضي الله عنه (24-35 H) standardisa la version du Coran en un mushaf de référence, dit « Mushaf Uthmani », à partir des copies déjà recueillies par Abu Bakr.", dalil_ref:"Sahih al-Bukhari n°4987", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Uthman ibn Affan",est_correcte:true},{texte_fr:"Umar",est_correcte:false},{texte_fr:"Ali",est_correcte:false},{texte_fr:"Mu'awiya",est_correcte:false}] },
  { domaine:'tafsir', niveau:2, texte_fr:"Quelle sourate commence sans Bismillah ?", texte_ar:'ما السورة التي تبدأ بدون بسملة؟', explication:"Sourate at-Tawba (9), la seule sourate du Coran sans Bismillah au début. Les savants l'expliquent par son sujet (rupture des pactes).", reponses:[{texte_fr:"At-Tawba (9)",est_correcte:true},{texte_fr:"Al-Fatiha",est_correcte:false},{texte_fr:"An-Naml",est_correcte:false},{texte_fr:"Al-Ikhlas",est_correcte:false}] },

  // ===== TAFSIR N3 =====
  { domaine:'tafsir', niveau:3, texte_fr:"Combien de prophètes sont nommés dans le Coran ?", texte_ar:'كم نبياً ذكر في القرآن؟', explication:"25 prophètes sont nommés explicitement, parmi les 124 000 envoyés selon la tradition.", reponses:[{texte_fr:"25 nommés",est_correcte:true},{texte_fr:"10",est_correcte:false},{texte_fr:"100",est_correcte:false},{texte_fr:"50",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelle sourate raconte l'histoire complète de Yusuf ?", texte_ar:'ما السورة التي تروي قصة يوسف كاملة؟', explication:"Sourate Yusuf (la 12e), unique car elle raconte toute l'histoire dans une seule sourate. Allah l'appelle « la plus belle des histoires » (12:3).", dalil_ref:"Sourate Yusuf 12:3", reponses:[{texte_fr:"Sourate Yusuf",est_correcte:true},{texte_fr:"Al-Baqara",est_correcte:false},{texte_fr:"Al-Maida",est_correcte:false},{texte_fr:"Al-Kahf",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel est le verset de l'usure (Riba) le plus sévère ?", texte_ar:'ما أشد آيات الربا؟', explication:"Sourate Al-Baqara 2:279 : « ...déclarez la guerre à Allah et à Son Messager... ». Seul péché où Allah déclare la guerre.", dalil_ref:"Sourate Al-Baqara 2:279", reponses:[{texte_fr:"Al-Baqara 2:279 (déclaration de guerre)",est_correcte:true},{texte_fr:"An-Nisa 4:36",est_correcte:false},{texte_fr:"Al-Maida 5:3",est_correcte:false},{texte_fr:"An-Nas 114:1",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelles sourates sont les 4 « Tawal » (les longues) ?", texte_ar:'ما السبع الطوال؟', explication:"Sept sourates longues : Al-Baqara, Al-Imran, An-Nisa, Al-Maida, Al-An'am, Al-A'raf, et At-Tawba (ou Yunus selon une autre opinion).", reponses:[{texte_fr:"Les 7 premières grandes sourates après al-Fatiha",est_correcte:true},{texte_fr:"Les 4 dernières",est_correcte:false},{texte_fr:"Les sourates mecquoises",est_correcte:false},{texte_fr:"4 sourates de Médine",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelle sourate est appelée « la fiancée du Coran » ?", texte_ar:'ما السورة التي تسمى عروس القرآن؟', explication:"Sourate Ar-Rahman (le Tout-Miséricordieux), 78 versets. Refrain célèbre : « Lequel des bienfaits de votre Seigneur nierez-vous ? »", reponses:[{texte_fr:"Ar-Rahman",est_correcte:true},{texte_fr:"Yasin",est_correcte:false},{texte_fr:"Al-Fatiha",est_correcte:false},{texte_fr:"Al-Mulk",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel est le verset le plus court du Coran ?", texte_ar:'ما أقصر آية في القرآن؟', explication:"« Mudhammatan » (Sourate Ar-Rahman 55:64) ou « Wa-d-Duha » (93:1). Un seul mot.", reponses:[{texte_fr:"Un seul mot (ex: Mudhammatan en 55:64)",est_correcte:true},{texte_fr:"3 mots",est_correcte:false},{texte_fr:"5 mots",est_correcte:false},{texte_fr:"10 mots",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quels sont les Hurof Muqatta'at (lettres isolées) ?", texte_ar:'ما الحروف المقطعة؟', explication:"Lettres en début de 29 sourates (Alif-Lam-Mim, Ha-Mim, Ya-Sin...). Leur sens véritable est connu d'Allah Seul selon la majorité des Salaf.", reponses:[{texte_fr:"Lettres énigmatiques au début de 29 sourates",est_correcte:true},{texte_fr:"Notes musicales",est_correcte:false},{texte_fr:"Lettres pour enfants",est_correcte:false},{texte_fr:"Marquages pour le scribe",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Qu'est-ce que les « Sajdat at-Tilawa » (prosternations de récitation) ?", texte_ar:'ما هي سجدات التلاوة؟', explication:"15 versets du Coran (selon la majorité) où il est recommandé de se prosterner en les récitant ou les écoutant.", reponses:[{texte_fr:"15 versets où se prosterner",est_correcte:true},{texte_fr:"5 versets",est_correcte:false},{texte_fr:"30 versets",est_correcte:false},{texte_fr:"Aucun verset",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelle est l'histoire des Gens de la Caverne (Ashab al-Kahf) ?", texte_ar:'ما قصة أصحاب الكهف؟', explication:"Jeunes croyants ayant fui la persécution d'un roi tyran ; Allah les fit dormir 309 ans dans une caverne. Racontée dans Sourate al-Kahf 18:9-26.", dalil_ref:"Sourate Al-Kahf 18:9-26", reponses:[{texte_fr:"Jeunes endormis 309 ans pour fuir la persécution",est_correcte:true},{texte_fr:"Histoire d'amour",est_correcte:false},{texte_fr:"Bataille militaire",est_correcte:false},{texte_fr:"Construction de la Ka'ba",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel est le verset sur la perfection de la religion ?", texte_ar:'ما آية إكمال الدين؟', explication:"« Aujourd'hui, J'ai parfait pour vous votre religion, et accompli sur vous Mon bienfait. » (Al-Maida 5:3) — révélée à Arafat lors du Hajj d'Adieu.", dalil_ref:"Sourate Al-Maida 5:3", reponses:[{texte_fr:"Al-Maida 5:3 — révélée à Arafat",est_correcte:true},{texte_fr:"Al-Fatiha 1:1",est_correcte:false},{texte_fr:"Yasin 36:1",est_correcte:false},{texte_fr:"An-Nas 114:1",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelles sourates traitent principalement de l'héritage ?", texte_ar:'ما السور التي تفصل أحكام الميراث؟', explication:"Sourate An-Nisa (4), versets 11-12 et 176. Allah fixe les parts héréditaires avec précision.", dalil_ref:"Sourate An-Nisa 4:11-12, 176", reponses:[{texte_fr:"An-Nisa 4:11-12, 176",est_correcte:true},{texte_fr:"Al-Fatiha",est_correcte:false},{texte_fr:"An-Nas",est_correcte:false},{texte_fr:"Yasin",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelle femme est nommée par son prénom dans le Coran ?", texte_ar:'ما الامرأة الوحيدة التي ذكر اسمها في القرآن؟', explication:"Maryam (Marie), mère de Jésus عليها السلام. Une sourate entière porte son nom (Sourate 19).", reponses:[{texte_fr:"Maryam (Marie)",est_correcte:true},{texte_fr:"Khadija",est_correcte:false},{texte_fr:"Aïcha",est_correcte:false},{texte_fr:"Fatima",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel est le sujet principal de Sourate al-Asr ?", texte_ar:'ما موضوع سورة العصر؟', explication:"« Par le temps ! L'homme est vraiment en perte, sauf ceux qui croient et accomplissent les bonnes œuvres, se recommandent mutuellement la vérité et la patience. » Imam Shafi'i : si Allah n'avait révélé que cette sourate, elle aurait suffi.", dalil_ref:"Sourate Al-Asr 103", reponses:[{texte_fr:"Foi, bonnes œuvres, vérité et patience",est_correcte:true},{texte_fr:"Histoire d'Abraham",est_correcte:false},{texte_fr:"Lois de l'héritage",est_correcte:false},{texte_fr:"Description du Paradis",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Combien de fois Moïse est-il mentionné dans le Coran ?", texte_ar:'كم مرة ذكر موسى في القرآن؟', explication:"Environ 136 fois, le prophète le plus cité. Son histoire avec Pharaon est racontée dans plusieurs sourates.", reponses:[{texte_fr:"Environ 136 fois (le plus cité)",est_correcte:true},{texte_fr:"10 fois",est_correcte:false},{texte_fr:"50 fois",est_correcte:false},{texte_fr:"500 fois",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel verset est appelé « le verset de l'épée » (Ayat as-Sayf) ?", texte_ar:'ما آية السيف؟', explication:"Sourate At-Tawba 9:5, traitant des polythéistes qui ont rompu les traités. Les savants soulignent qu'elle s'applique en contexte de combat avec règles strictes.", dalil_ref:"Sourate At-Tawba 9:5", reponses:[{texte_fr:"At-Tawba 9:5",est_correcte:true},{texte_fr:"Al-Fatiha 1:1",est_correcte:false},{texte_fr:"Al-Baqara 2:1",est_correcte:false},{texte_fr:"An-Nas 114:1",est_correcte:false}] },

  // ===== TAFSIR N4 =====
  { domaine:'tafsir', niveau:4, texte_fr:"Qu'est-ce que le Naskh (abrogation) dans le Coran ?", texte_ar:'ما هو النسخ في القرآن؟', explication:"Annulation d'un jugement antérieur par une révélation postérieure. Ex: changement de qibla de Jérusalem à La Mecque. Les Mufassirun ont identifié plusieurs cas certains.", reponses:[{texte_fr:"Annulation d'un jugement par révélation postérieure",est_correcte:true},{texte_fr:"Erreur de copie",est_correcte:false},{texte_fr:"Traduction libre",est_correcte:false},{texte_fr:"Innovation moderne",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Qu'est-ce que « Asbab an-Nuzul » ?", texte_ar:'ما هي أسباب النزول؟', explication:"Causes de la révélation : événements ou questions précédant la révélation d'un verset, indispensables pour saisir son contexte et son sens.", dalil_ref:"al-Itqan d'as-Suyuti", reponses:[{texte_fr:"Causes/contextes de la révélation",est_correcte:true},{texte_fr:"Versets mecquois",est_correcte:false},{texte_fr:"Sourates abrogées",est_correcte:false},{texte_fr:"Versets de combat",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Quels sont les principaux Tafsirs classiques sunnites ?", texte_ar:'ما أبرز كتب التفسير السني؟', explication:"Tafsir at-Tabari (mère des tafsirs, IIIe siècle), Tafsir Ibn Kathir (par hadith, VIIIe siècle), Tafsir al-Qurtubi (jurisprudence), Tafsir as-Sa'di (moderne, simple).", reponses:[{texte_fr:"Tabari, Ibn Kathir, Qurtubi, Sa'di",est_correcte:true},{texte_fr:"Sahihayn",est_correcte:false},{texte_fr:"Muwatta seul",est_correcte:false},{texte_fr:"Bidaya wan-Nihaya",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Que sont les Muhkamat et Mutashabihat ?", texte_ar:'ما المحكم والمتشابه؟', explication:"Muhkamat = versets clairs, base du Livre. Mutashabihat = versets nécessitant interprétation à la lumière des Muhkamat (Al-Imran 3:7).", dalil_ref:"Sourate Al-Imran 3:7", reponses:[{texte_fr:"Clairs (base) vs nécessitant interprétation",est_correcte:true},{texte_fr:"Mecquois vs Médinois",est_correcte:false},{texte_fr:"Longs vs courts",est_correcte:false},{texte_fr:"Anciens vs récents",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Quelles sont les méthodologies du Tafsir selon Ibn Taymiyya ?", texte_ar:'ما طرق التفسير عند ابن تيمية؟', explication:"4 méthodes hiérarchiques : 1) Coran par Coran, 2) Coran par Sunnah, 3) Coran par paroles des Compagnons, 4) Coran par Tabi'in. À défaut, par la langue arabe.", dalil_ref:"Muqaddima fi Usul at-Tafsir", reponses:[{texte_fr:"Coran-Sunnah-Sahaba-Tabi'in (hiérarchique)",est_correcte:true},{texte_fr:"Opinion personnelle libre",est_correcte:false},{texte_fr:"Rêves et inspirations",est_correcte:false},{texte_fr:"Étymologie persane",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Qu'est-ce que « Tafsir bil-Ma'thur » ?", texte_ar:'ما هو التفسير بالمأثور؟', explication:"Tafsir basé sur la transmission : Coran, Sunnah, paroles des Sahaba et Tabi'in. Le plus sûr selon Ahlu Sunnah.", reponses:[{texte_fr:"Tafsir par transmission (Coran, Sunnah, Salaf)",est_correcte:true},{texte_fr:"Tafsir libre",est_correcte:false},{texte_fr:"Tafsir poétique",est_correcte:false},{texte_fr:"Tafsir mystique",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Qu'est-ce que « Tafsir bir-Ra'y » ?", texte_ar:'ما هو التفسير بالرأي؟', explication:"Tafsir par effort d'analyse rationnelle. Toléré (mahmud) s'il respecte les principes ; interdit (madhmum) s'il contredit les sources ou est arbitraire.", reponses:[{texte_fr:"Tafsir par effort rationnel (toléré sous conditions)",est_correcte:true},{texte_fr:"Toujours interdit",est_correcte:false},{texte_fr:"Toujours obligatoire",est_correcte:false},{texte_fr:"Tafsir des mu'tazila uniquement",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Combien de fois est mentionnée la prière dans le Coran ?", texte_ar:'كم مرة ذكرت الصلاة في القرآن؟', explication:"Le mot « Salat » apparaît environ 67 fois, témoignant de son importance centrale.", reponses:[{texte_fr:"Environ 67 fois",est_correcte:true},{texte_fr:"5 fois",est_correcte:false},{texte_fr:"500 fois",est_correcte:false},{texte_fr:"1 fois",est_correcte:false}] },

  // ===== SIRAH N1 =====
  { domaine:'sirah', niveau:1, texte_fr:"En quelle année est né le Prophète ﷺ ?", texte_ar:'في أي سنة ولد النبي ﷺ؟', explication:"En l'an de l'Éléphant (570 G), à La Mecque, l'année où Abraha tenta d'attaquer la Ka'ba.", reponses:[{texte_fr:"L'an de l'Éléphant (570 G)",est_correcte:true},{texte_fr:"500 G",est_correcte:false},{texte_fr:"622 G",est_correcte:false},{texte_fr:"600 G",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Quel était le nom du père du Prophète ﷺ ?", texte_ar:'ما اسم والد النبي ﷺ؟', explication:"Abdullah ibn Abdul-Muttalib, mort avant la naissance de Muhammad ﷺ.", reponses:[{texte_fr:"Abdullah",est_correcte:true},{texte_fr:"Abu Talib",est_correcte:false},{texte_fr:"Abdul-Muttalib",est_correcte:false},{texte_fr:"Abu Lahab",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Quel était le nom de la mère du Prophète ﷺ ?", texte_ar:'ما اسم والدة النبي ﷺ؟', explication:"Amina bint Wahb, morte alors que Muhammad ﷺ avait 6 ans.", reponses:[{texte_fr:"Amina bint Wahb",est_correcte:true},{texte_fr:"Khadija",est_correcte:false},{texte_fr:"Halima",est_correcte:false},{texte_fr:"Aïcha",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Qui éleva le Prophète ﷺ après la mort de sa mère ?", texte_ar:'من رعى النبي ﷺ بعد وفاة أمه؟', explication:"Son grand-père Abdul-Muttalib (2 ans) puis son oncle Abu Talib après la mort du grand-père.", reponses:[{texte_fr:"Abdul-Muttalib puis Abu Talib",est_correcte:true},{texte_fr:"Khadija",est_correcte:false},{texte_fr:"Abu Bakr",est_correcte:false},{texte_fr:"Hamza",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Qui était la nourrice du Prophète ﷺ enfant ?", texte_ar:'من أرضعت النبي ﷺ صغيراً؟', explication:"Halima as-Sa'diyya, qui l'a allaité dans le désert pendant 4 ans selon la coutume des Mecquois.", reponses:[{texte_fr:"Halima as-Sa'diyya",est_correcte:true},{texte_fr:"Khadija",est_correcte:false},{texte_fr:"Amina",est_correcte:false},{texte_fr:"Sumayya",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"À quel âge le Prophète ﷺ a-t-il reçu sa première révélation ?", texte_ar:'في أي سن نزل الوحي على النبي ﷺ؟', explication:"À 40 ans, dans la grotte de Hira, à La Mecque.", dalil_ref:"Sahih al-Bukhari n°3", reponses:[{texte_fr:"40 ans",est_correcte:true},{texte_fr:"25 ans",est_correcte:false},{texte_fr:"50 ans",est_correcte:false},{texte_fr:"30 ans",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Qui était la première épouse du Prophète ﷺ ?", texte_ar:'من هي أول زوجة للنبي ﷺ؟', explication:"Khadija bint Khuwaylid رضي الله عنها, épousée à ses 25 ans. Elle avait 40 ans. Mère de tous ses enfants sauf Ibrahim.", reponses:[{texte_fr:"Khadija bint Khuwaylid",est_correcte:true},{texte_fr:"Aïcha",est_correcte:false},{texte_fr:"Hafsa",est_correcte:false},{texte_fr:"Maymuna",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Combien d'enfants Khadija a-t-elle eus du Prophète ﷺ ?", texte_ar:'كم ولداً أنجبت خديجة من النبي ﷺ؟', explication:"Six : 2 fils (Qasim et Abdullah, morts en bas âge) et 4 filles (Zaynab, Ruqayya, Umm Kulthum, Fatima).", reponses:[{texte_fr:"6 enfants (2 fils, 4 filles)",est_correcte:true},{texte_fr:"1 enfant",est_correcte:false},{texte_fr:"10 enfants",est_correcte:false},{texte_fr:"Aucun",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Où a eu lieu la Hijra (émigration) ?", texte_ar:'إلى أين كانت الهجرة؟', explication:"De La Mecque à Médine (Yathrib), en l'an 1 H (622 G). Début du calendrier hijri.", reponses:[{texte_fr:"De La Mecque à Médine",est_correcte:true},{texte_fr:"De La Mecque à Taif",est_correcte:false},{texte_fr:"De Médine à La Mecque",est_correcte:false},{texte_fr:"Vers l'Éthiopie",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"En quelle année eut lieu la conquête de La Mecque ?", texte_ar:'في أي سنة فتح مكة؟', explication:"En l'an 8 de la Hijra (630 G). Le Prophète ﷺ entra avec 10 000 compagnons. Il pardonna aux Mecquois.", reponses:[{texte_fr:"8 H (630 G)",est_correcte:true},{texte_fr:"2 H",est_correcte:false},{texte_fr:"10 H",est_correcte:false},{texte_fr:"20 H",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"À quel âge le Prophète ﷺ est-il décédé ?", texte_ar:'في أي سن توفي النبي ﷺ؟', explication:"63 ans (selon l'année lunaire), en l'an 11 H, dans les bras d'Aïcha à Médine.", reponses:[{texte_fr:"63 ans (en 11 H)",est_correcte:true},{texte_fr:"50 ans",est_correcte:false},{texte_fr:"40 ans",est_correcte:false},{texte_fr:"80 ans",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Combien d'années le Prophète ﷺ a-t-il prêché à La Mecque ?", texte_ar:'كم سنة دعا النبي ﷺ في مكة؟', explication:"13 ans de prédication mecquoise (depuis la première révélation à 40 ans jusqu'à la Hijra à 53 ans).", reponses:[{texte_fr:"13 ans",est_correcte:true},{texte_fr:"5 ans",est_correcte:false},{texte_fr:"20 ans",est_correcte:false},{texte_fr:"40 ans",est_correcte:false}] },
  { domaine:'sirah', niveau:1, texte_fr:"Combien d'années le Prophète ﷺ a-t-il vécu à Médine ?", texte_ar:'كم سنة عاش النبي ﷺ في المدينة؟', explication:"10 ans, jusqu'à sa mort en 11 H. C'est la période de construction de l'État islamique.", reponses:[{texte_fr:"10 ans",est_correcte:true},{texte_fr:"3 ans",est_correcte:false},{texte_fr:"20 ans",est_correcte:false},{texte_fr:"40 ans",est_correcte:false}] },

  // ===== SIRAH N2 =====
  { domaine:'sirah', niveau:2, texte_fr:"Qui fut le premier calife après le Prophète ﷺ ?", texte_ar:'من أول الخلفاء؟', explication:"Abu Bakr as-Siddiq رضي الله عنه (11-13 H), élu par consensus des Compagnons à la Saqifa de Bani Sa'ida.", reponses:[{texte_fr:"Abu Bakr as-Siddiq",est_correcte:true},{texte_fr:"Umar",est_correcte:false},{texte_fr:"Uthman",est_correcte:false},{texte_fr:"Ali",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Combien d'années régna Umar ibn al-Khattab ?", texte_ar:'كم سنة حكم عمر؟', explication:"10 ans (13-23 H). Sous son califat, conquête de la Perse, Égypte, Syrie. Il fonda le Diwan et le calendrier hijri.", reponses:[{texte_fr:"10 ans (13-23 H)",est_correcte:true},{texte_fr:"2 ans",est_correcte:false},{texte_fr:"30 ans",est_correcte:false},{texte_fr:"50 ans",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Quel fut le premier conflit majeur sous Abu Bakr ?", texte_ar:'ما أول حرب كبرى في عهد أبي بكر؟', explication:"Les guerres de la Ridda (apostasie) contre les tribus qui voulaient renoncer à l'islam après la mort du Prophète ﷺ.", reponses:[{texte_fr:"Les guerres de la Ridda (apostasie)",est_correcte:true},{texte_fr:"Conquête de la Mecque",est_correcte:false},{texte_fr:"Bataille de Badr",est_correcte:false},{texte_fr:"Conquête de Jérusalem",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Qui était le 3e calife ?", texte_ar:'من الخليفة الثالث؟', explication:"Uthman ibn Affan رضي الله عنه (23-35 H). Il compila le Mushaf unique.", reponses:[{texte_fr:"Uthman ibn Affan",est_correcte:true},{texte_fr:"Ali",est_correcte:false},{texte_fr:"Mu'awiya",est_correcte:false},{texte_fr:"Hasan",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Qui était le 4e calife ?", texte_ar:'من الخليفة الرابع؟', explication:"Ali ibn Abi Talib رضي الله عنه (35-40 H), cousin et gendre du Prophète ﷺ, l'un des 10 promis au Paradis.", reponses:[{texte_fr:"Ali ibn Abi Talib",est_correcte:true},{texte_fr:"Mu'awiya",est_correcte:false},{texte_fr:"Hasan",est_correcte:false},{texte_fr:"Husayn",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Quels sont les 4 califes bien guidés (Rashidun) ?", texte_ar:'من هم الخلفاء الراشدون؟', explication:"Abu Bakr, Umar, Uthman, Ali رضي الله عنهم. Le Prophète ﷺ a dit : « Tenez-vous fermement à ma Sunnah et à celle des califes bien guidés. »", dalil_ref:"Sunan Abi Dawud n°4607", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Abu Bakr, Umar, Uthman, Ali",est_correcte:true},{texte_fr:"Les fils du Prophète",est_correcte:false},{texte_fr:"Hamza et Abbas",est_correcte:false},{texte_fr:"Les califes omeyyades",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Quand a eu lieu la bataille de Yarmuk ?", texte_ar:'متى كانت معركة اليرموك؟', explication:"En 15 H (636 G), sous Umar. Khalid ibn al-Walid commanda la victoire décisive contre l'Empire byzantin en Syrie.", reponses:[{texte_fr:"15 H (636 G)",est_correcte:true},{texte_fr:"5 H",est_correcte:false},{texte_fr:"30 H",est_correcte:false},{texte_fr:"100 H",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Quand fut bâtie la mosquée du Prophète ﷺ à Médine ?", texte_ar:'متى بنيت مسجد النبي ﷺ؟', explication:"Dès l'arrivée à Médine en 1 H. Le Prophète ﷺ participa lui-même à la construction.", reponses:[{texte_fr:"1 H (à l'arrivée à Médine)",est_correcte:true},{texte_fr:"5 H",est_correcte:false},{texte_fr:"10 H",est_correcte:false},{texte_fr:"Après sa mort",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Combien d'épouses le Prophète ﷺ a-t-il eues ?", texte_ar:'كم زوجة للنبي ﷺ؟', explication:"11 au total au cours de sa vie. Toutes après Khadija qui resta sa seule épouse pendant 25 ans.", reponses:[{texte_fr:"11 épouses au total",est_correcte:true},{texte_fr:"4 maximum",est_correcte:false},{texte_fr:"1 seule",est_correcte:false},{texte_fr:"20 épouses",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Quand a eu lieu le pèlerinage d'Adieu (Hajjat al-Wada') ?", texte_ar:'متى كانت حجة الوداع؟', explication:"En 10 H, dernière année du Prophète ﷺ. Il prononça le célèbre discours à Arafat.", reponses:[{texte_fr:"10 H",est_correcte:true},{texte_fr:"1 H",est_correcte:false},{texte_fr:"5 H",est_correcte:false},{texte_fr:"15 H",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Combien d'expéditions militaires le Prophète ﷺ a-t-il dirigées personnellement ?", texte_ar:'كم غزوة قاد النبي ﷺ بنفسه؟', explication:"27 « ghazawat » (où il était présent), parmi lesquelles 9 où il combattit réellement.", reponses:[{texte_fr:"27 ghazawat (9 avec combat réel)",est_correcte:true},{texte_fr:"3 batailles",est_correcte:false},{texte_fr:"100 batailles",est_correcte:false},{texte_fr:"Aucune",est_correcte:false}] },
  { domaine:'sirah', niveau:2, texte_fr:"Qui était Salman al-Farisi ?", texte_ar:'من هو سلمان الفارسي؟', explication:"Compagnon perse qui chercha la vraie religion à travers plusieurs maîtres avant de rencontrer le Prophète ﷺ. Il suggéra la stratégie du Khandaq.", reponses:[{texte_fr:"Compagnon perse, conseiller du Khandaq",est_correcte:true},{texte_fr:"Roi perse",est_correcte:false},{texte_fr:"Prophète",est_correcte:false},{texte_fr:"Calife",est_correcte:false}] },

  // ===== SIRAH N3 =====
  { domaine:'sirah', niveau:3, texte_fr:"Que se passa-t-il lors de l'expédition de Taif (8 H) ?", texte_ar:'ماذا حدث في غزوة الطائف؟', explication:"Après Hunayn, les musulmans assiégèrent Taif (forteresse des Thaqif). Le siège fut levé. Les Thaqif vinrent eux-mêmes embrasser l'islam un an plus tard.", reponses:[{texte_fr:"Siège levé, Thaqif convertis l'année suivante",est_correcte:true},{texte_fr:"Bataille perdue",est_correcte:false},{texte_fr:"Conquête immédiate",est_correcte:false},{texte_fr:"Aucun affrontement",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que le serment de Aqaba ?", texte_ar:'ما هي بيعة العقبة؟', explication:"Deux serments des Médinois (Aws et Khazraj) au Prophète ﷺ à La Mecque : 1er Aqaba (12 hommes) et 2e Aqaba (73 hommes + 2 femmes), préparant la Hijra.", reponses:[{texte_fr:"Serments des Médinois préparant la Hijra",est_correcte:true},{texte_fr:"Serment de paix avec les mecquois",est_correcte:false},{texte_fr:"Bataille à La Mecque",est_correcte:false},{texte_fr:"Serment des juifs",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quelle fut la première mosquée construite en islam ?", texte_ar:'ما أول مسجد في الإسلام؟', explication:"Masjid Quba, fondée par le Prophète ﷺ lors de son arrivée à Médine, avant la mosquée prophétique. Mentionnée en Sourate At-Tawba 9:108.", dalil_ref:"Sourate At-Tawba 9:108", reponses:[{texte_fr:"Masjid Quba",est_correcte:true},{texte_fr:"Masjid an-Nabawi",est_correcte:false},{texte_fr:"Al-Aqsa",est_correcte:false},{texte_fr:"Masjid al-Haram",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que le pacte de Hudaybiyya (6 H) ?", texte_ar:'ما هي صلح الحديبية؟', explication:"Traité de paix de 10 ans entre le Prophète ﷺ et les Mecquois. Considéré au début défavorable mais qualifié de « victoire éclatante » par le Coran (Sourate Al-Fath).", dalil_ref:"Sourate Al-Fath 48", reponses:[{texte_fr:"Traité de paix de 10 ans avec Quraysh",est_correcte:true},{texte_fr:"Déclaration de guerre",est_correcte:false},{texte_fr:"Conquête de La Mecque",est_correcte:false},{texte_fr:"Hijra vers l'Éthiopie",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Que sont les Muhajirun et les Ansar ?", texte_ar:'من هم المهاجرون والأنصار؟', explication:"Muhajirun = émigrés de La Mecque à Médine. Ansar = aides médinois qui les accueillirent. Le Prophète ﷺ établit un pacte de fraternité (Mu'akhat) entre eux.", reponses:[{texte_fr:"Émigrés de La Mecque et aides médinois",est_correcte:true},{texte_fr:"Deux tribus en guerre",est_correcte:false},{texte_fr:"Cousins du Prophète",est_correcte:false},{texte_fr:"Deux dynasties politiques",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quelle fut la première délégation à La Mecque pour la prédication ?", texte_ar:'ما أول وفد دعوي خرج من مكة؟', explication:"L'émigration en Éthiopie (Hijra Habasha), première et seconde vagues sous protection du roi An-Najashi (chrétien juste qui se convertit).", reponses:[{texte_fr:"Hijra Habasha vers l'Éthiopie",est_correcte:true},{texte_fr:"Voyage vers Taif",est_correcte:false},{texte_fr:"Délégation à Médine",est_correcte:false},{texte_fr:"Mission au Yémen",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que le boycott des Bani Hashim ?", texte_ar:'ما هي مقاطعة بني هاشم؟', explication:"Pendant 3 ans (7e à 10e année de la mission), les Quraysh boycottèrent les Bani Hashim et Bani Muttalib pour les forcer à livrer le Prophète ﷺ. Ils furent confinés dans Shi'b Abi Talib.", reponses:[{texte_fr:"Boycott de 3 ans imposé par Quraysh",est_correcte:true},{texte_fr:"Fête religieuse",est_correcte:false},{texte_fr:"Bataille militaire",est_correcte:false},{texte_fr:"Pacte commercial",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que l'Isra et le Mi'raj ?", texte_ar:'ما هو الإسراء والمعراج؟', explication:"Voyage nocturne miraculeux : Isra = La Mecque → Jérusalem ; Mi'raj = ascension vers les cieux. Les 5 prières furent prescrites cette nuit-là.", dalil_ref:"Sourate Al-Isra 17:1", reponses:[{texte_fr:"Voyage nocturne et ascension céleste",est_correcte:true},{texte_fr:"Bataille rêvée",est_correcte:false},{texte_fr:"Pèlerinage",est_correcte:false},{texte_fr:"Vision mentale uniquement",est_correcte:false}] },

  // ===== SIRAH N4 =====
  { domaine:'sirah', niveau:4, texte_fr:"Combien de musulmans participèrent à la bataille de Mu'tah (8 H) ?", texte_ar:'كم مسلماً شارك في غزوة مؤتة؟', explication:"3000 musulmans face à 200 000 byzantins. 3 commandants successifs (Zayd, Ja'far, Abdullah ibn Rawaha) tombèrent en martyrs ; Khalid ibn al-Walid prit le commandement.", reponses:[{texte_fr:"3000 face à 200 000 byzantins",est_correcte:true},{texte_fr:"100 000 musulmans",est_correcte:false},{texte_fr:"500 musulmans",est_correcte:false},{texte_fr:"1 million",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Qui dirigea l'armée de l'islam après les 3 commandants tombés à Mu'tah ?", texte_ar:'من قاد الجيش بعد سقوط القادة في مؤتة؟', explication:"Khalid ibn al-Walid, qui n'avait pas été nommé. Le Prophète ﷺ le surnomma « Sayf Allah al-Maslul » (l'Épée tirée d'Allah) après cette bataille.", dalil_ref:"Sahih al-Bukhari n°4262", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Khalid ibn al-Walid",est_correcte:true},{texte_fr:"Ali",est_correcte:false},{texte_fr:"Umar",est_correcte:false},{texte_fr:"Abu Bakr",est_correcte:false}] },

  // ===== SIRAH N5 =====
  { domaine:'sirah', niveau:5, texte_fr:"Qui était l'imam de la prière lorsque le Prophète ﷺ tomba malade ?", texte_ar:'من كان إمام الصلاة في مرض النبي ﷺ؟', explication:"Abu Bakr رضي الله عنه, sur instruction du Prophète ﷺ. C'est l'un des arguments forts en faveur de sa primauté au califat.", dalil_ref:"Sahih al-Bukhari n°678", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Abu Bakr as-Siddiq",est_correcte:true},{texte_fr:"Umar",est_correcte:false},{texte_fr:"Ali",est_correcte:false},{texte_fr:"Uthman",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quand eut lieu la fitna assassinant Uthman رضي الله عنه ?", texte_ar:'متى استشهد عثمان رضي الله عنه؟', explication:"En 35 H, à Médine, par des rebelles venus d'Égypte. Il fut assassiné alors qu'il lisait le Coran. Sa mort déclencha la « Grande Fitna ».", reponses:[{texte_fr:"35 H, par des rebelles venus d'Égypte",est_correcte:true},{texte_fr:"11 H",est_correcte:false},{texte_fr:"23 H",est_correcte:false},{texte_fr:"100 H",est_correcte:false}] },

  // ===== AKHLAQ N3 =====
  { domaine:'akhlaq', niveau:3, texte_fr:"Que dit le hadith sur celui qui ne fait pas miséricorde ?", texte_ar:'ما يقول الحديث عن من لا يرحم؟', explication:"Le Prophète ﷺ : « Celui qui ne fait pas miséricorde aux gens, Allah ne lui fera pas miséricorde. »", dalil_ref:"Sahih al-Bukhari n°7376 ; Muslim n°2319", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Allah ne lui fait pas miséricorde",est_correcte:true},{texte_fr:"Il sera riche",est_correcte:false},{texte_fr:"Il sera honoré",est_correcte:false},{texte_fr:"Aucune conséquence",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Qu'est-ce que l'Ihsan envers les parents (Birr al-Walidayn) ?", texte_ar:'ما هو بر الوالدين؟', explication:"Obéir, respecter, servir et invoquer pour ses parents — surtout en leur vieillesse. Allah l'a placé juste après l'adoration de Lui-même (Al-Isra 17:23).", dalil_ref:"Sourate Al-Isra 17:23-24", reponses:[{texte_fr:"Obéir, servir, respecter et invoquer pour eux",est_correcte:true},{texte_fr:"Leur donner de l'argent uniquement",est_correcte:false},{texte_fr:"Ne pas les voir",est_correcte:false},{texte_fr:"Les héberger seulement",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Que dit le hadith sur le sourire ?", texte_ar:'ما الحديث عن التبسم؟', explication:"« Ton sourire à l'égard de ton frère est une aumône. »", dalil_ref:"Sunan at-Tirmidhi n°1956", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"C'est une aumône",est_correcte:true},{texte_fr:"C'est un péché",est_correcte:false},{texte_fr:"C'est interdit",est_correcte:false},{texte_fr:"Cela coûte de l'argent",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quelle est la définition de l'humilité (Tawadu') ?", texte_ar:'ما تعريف التواضع؟', explication:"Accepter la vérité quelle que soit sa source et ne pas mépriser les gens. Le Prophète ﷺ : « Allah m'a révélé d'être humble afin que nul ne s'enorgueillisse. »", dalil_ref:"Sahih Muslim n°2865", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Accepter la vérité et ne pas mépriser les gens",est_correcte:true},{texte_fr:"Se rabaisser injustement",est_correcte:false},{texte_fr:"Refuser tout honneur",est_correcte:false},{texte_fr:"Ne pas parler",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quelle est la valeur d'une bonne parole ?", texte_ar:'ما قيمة الكلمة الطيبة؟', explication:"Le Prophète ﷺ : « La parole bonne est une aumône. » Une bonne parole peut adoucir un cœur et écarter une calamité.", dalil_ref:"Sahih al-Bukhari n°2989", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Elle vaut une aumône",est_correcte:true},{texte_fr:"Sans valeur",est_correcte:false},{texte_fr:"Mauvaise habitude",est_correcte:false},{texte_fr:"Réservée aux savants",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Que sont les droits du voisin ?", texte_ar:'ما حقوق الجار؟', explication:"Le Prophète ﷺ insistait tellement sur le voisin qu'on a cru qu'il allait l'inclure dans l'héritage. Lui faire du bien, ne pas le nuire, partager parfois la nourriture.", dalil_ref:"Sahih al-Bukhari n°6014 ; Muslim n°2624", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Lui faire du bien et éviter le mal",est_correcte:true},{texte_fr:"L'ignorer",est_correcte:false},{texte_fr:"L'éviter complètement",est_correcte:false},{texte_fr:"Aucun droit particulier",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quel est le statut de la promesse non tenue ?", texte_ar:'ما حكم خلف الوعد؟', explication:"L'un des signes du nifaq (hypocrisie) selon le hadith : « Quand il promet il trahit. » Le musulman doit toujours tenir sa parole.", dalil_ref:"Sahih al-Bukhari n°33", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Signe d'hypocrisie selon le hadith",est_correcte:true},{texte_fr:"Sans gravité",est_correcte:false},{texte_fr:"Recommandé",est_correcte:false},{texte_fr:"Obligatoire dans le commerce",est_correcte:false}] },
];

export async function seedQuestionsCombler2(client: Client): Promise<void> {
  console.log('Seeding lot 2 (Tafsir + Sirah + Akhlaq)...');
  let inserted = 0; let skipped = 0;

  for (const q of Q) {
    const exists = await client.query('SELECT id FROM questions WHERE texte_fr = $1', [q.texte_fr]);
    if (exists.rows.length > 0) { skipped++; continue; }

    const qResult = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, explication, grade_hadith, statut)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'valide') RETURNING id`,
      [q.domaine, q.sous_domaine ?? null, q.niveau, 'general', q.texte_fr, q.texte_ar ?? null, q.dalil_ref ?? null, q.explication, q.grade_hadith ?? null]
    );
    const id = qResult.rows[0].id;
    for (const r of q.reponses) {
      await client.query(`INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte) VALUES ($1,$2,$3,$4)`, [id, r.texte_fr, r.texte_ar ?? null, r.est_correcte]);
    }
    inserted++;
  }
  console.log(`Combler2: ${inserted} inserted, ${skipped} skipped.`);
}

if (require.main === module) {
  const { Client } = require('pg');
  const c = new Client({ connectionString: process.env.DATABASE_URL });
  c.connect().then(async () => { await seedQuestionsCombler2(c); await c.end(); }).catch((e: unknown) => { console.error(e); process.exit(1); });
}
