import { Client } from 'pg';
interface Q { domaine:string; niveau:number; texte_fr:string; texte_ar?:string; explication:string; dalil_ref?:string; grade_hadith?:string; sous_domaine?:string; reponses:{texte_fr:string;texte_ar?:string;est_correcte:boolean}[]; }

const Q: Q[] = [
  // ========== SIRAH N3 (+15) ==========
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que la délégation des Ansar à Aqaba ?", texte_ar:'ما وفد الأنصار في العقبة؟', explication:"Les Aws et Khazraj de Médine vinrent voir le Prophète ﷺ et lui prêtèrent serment, préparant la Hijra et fondant la communauté de Médine.", reponses:[{texte_fr:"Les Médinois qui ont préparé la Hijra",est_correcte:true},{texte_fr:"Une délégation égyptienne",est_correcte:false},{texte_fr:"Les Quraysh",est_correcte:false},{texte_fr:"Les juifs de Khaybar",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quel fut le rôle d'Abu Talib envers le Prophète ﷺ ?", texte_ar:'ما دور أبو طالب مع النبي ﷺ؟', explication:"Oncle protecteur qui éleva le Prophète ﷺ après son grand-père et le défendit contre Quraysh jusqu'à sa mort en l'an 10 de la prophétie. Il mourut sans embrasser l'islam.", reponses:[{texte_fr:"Oncle protecteur, mort sans embrasser l'islam",est_correcte:true},{texte_fr:"Père du Prophète ﷺ",est_correcte:false},{texte_fr:"Premier calife",est_correcte:false},{texte_fr:"Ennemi du Prophète ﷺ",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qui était Abu Lahab ?", texte_ar:'من هو أبو لهب؟', explication:"Oncle paternel du Prophète ﷺ et son pire ennemi. Sourate al-Masad (111) le condamne nommément avec sa femme Umm Jamil.", dalil_ref:"Sourate Al-Masad 111", reponses:[{texte_fr:"Oncle ennemi du Prophète ﷺ, condamné dans le Coran",est_correcte:true},{texte_fr:"Premier converti",est_correcte:false},{texte_fr:"Sahabi pieux",est_correcte:false},{texte_fr:"Père d'Aïcha",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Combien de musulmans ont émigré la première fois en Éthiopie ?", texte_ar:'كم عدد المهاجرين إلى الحبشة أولاً؟', explication:"En l'an 5 de la prophétie, 12 hommes et 4 femmes fuirent les persécutions mecquoises sous la protection du roi An-Najashi.", reponses:[{texte_fr:"16 personnes (12 hommes, 4 femmes)",est_correcte:true},{texte_fr:"100 personnes",est_correcte:false},{texte_fr:"3 personnes",est_correcte:false},{texte_fr:"1000 personnes",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qui était An-Najashi ?", texte_ar:'من هو النجاشي؟', explication:"Roi chrétien d'Éthiopie qui protégea les musulmans émigrés et embrassa l'islam secrètement. Le Prophète ﷺ pria sur lui à sa mort (jinaza par absence).", dalil_ref:"Sahih al-Bukhari n°1245", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Roi d'Éthiopie qui protégea les musulmans et se convertit",est_correcte:true},{texte_fr:"Roi de Perse",est_correcte:false},{texte_fr:"Empereur byzantin",est_correcte:false},{texte_fr:"Chef Quraysh",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Combien de batailles majeures (ghazawat) entre Badr et la conquête de La Mecque ?", texte_ar:'كم غزوة كبرى بين بدر وفتح مكة؟', explication:"Principales : Badr (2H), Uhud (3H), Khandaq (5H), Hudaybiyya (6H), Khaybar (7H), Mu'ta (8H), Fath Mecca (8H), Hunayn (8H), Tabuk (9H).", reponses:[{texte_fr:"~9 batailles majeures",est_correcte:true},{texte_fr:"1 seule",est_correcte:false},{texte_fr:"30 batailles",est_correcte:false},{texte_fr:"100 batailles",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quelle fut la bataille des Tranchées (Khandaq) ?", texte_ar:'ما هي غزوة الخندق؟', explication:"En 5 H : 10 000 alliés assiégèrent Médine. Salman al-Farisi proposa de creuser une tranchée. Allah envoya un vent violent qui dispersa les coalisés.", dalil_ref:"Sourate Al-Ahzab 33:9", reponses:[{texte_fr:"Siège de Médine (5H), Allah envoya un vent",est_correcte:true},{texte_fr:"Bataille à La Mecque",est_correcte:false},{texte_fr:"Conquête de la Perse",est_correcte:false},{texte_fr:"Pèlerinage",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quel fut le résultat de la bataille de Hunayn (8 H) ?", texte_ar:'ما نتيجة غزوة حنين؟', explication:"Initialement perte de contrôle par sur-confiance des musulmans (12 000 contre les Hawazin). Allah envoya la sakina, victoire finale.", dalil_ref:"Sourate At-Tawba 9:25", reponses:[{texte_fr:"Quasi-défaite puis victoire par sakina d'Allah",est_correcte:true},{texte_fr:"Victoire facile",est_correcte:false},{texte_fr:"Défaite totale",est_correcte:false},{texte_fr:"Bataille évitée",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quelle fut l'expédition de Tabuk (9 H) ?", texte_ar:'ما غزوة تبوك؟', explication:"Le « jaysh al-usra » (armée de la difficulté), face à la rumeur d'invasion byzantine. 30 000 musulmans marchèrent en plein été. Pas de combat — démonstration de force.", reponses:[{texte_fr:"Expédition vers la frontière byzantine sans combat",est_correcte:true},{texte_fr:"Conquête de Damas",est_correcte:false},{texte_fr:"Bataille en Iraq",est_correcte:false},{texte_fr:"Voyage commercial",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Combien y eut-il de Madinois ayant prêté serment au 2e Aqaba ?", texte_ar:'كم عدد الأنصار في بيعة العقبة الثانية؟', explication:"73 hommes et 2 femmes (Nusayba et Asma). Ce serment de protection conduisit à la Hijra. Le 1er Aqaba comptait 12 hommes.", reponses:[{texte_fr:"73 hommes et 2 femmes",est_correcte:true},{texte_fr:"3 personnes",est_correcte:false},{texte_fr:"1000 personnes",est_correcte:false},{texte_fr:"100 hommes seulement",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Quelle est l'histoire du voyage à Taïf ?", texte_ar:'ما قصة الرحلة إلى الطائف؟', explication:"En l'an 10 de la prophétie, après la mort d'Abu Talib et Khadija. Le Prophète ﷺ y fut rejeté et lapidé par les enfants. C'est l'année dite « du chagrin » (am al-huzn).", reponses:[{texte_fr:"Rejet et lapidation après l'an du chagrin",est_correcte:true},{texte_fr:"Conquête de Taïf",est_correcte:false},{texte_fr:"Pèlerinage de masse",est_correcte:false},{texte_fr:"Conférence inter-religieuse",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qui était Khabbab ibn al-Aratt ?", texte_ar:'من هو خباب بن الأرت؟', explication:"Un des premiers musulmans, sévèrement torturé pour sa foi (les Quraysh le brûlaient sur des charbons). Le Prophète ﷺ lui rappela la patience des prophètes précédents.", dalil_ref:"Sahih al-Bukhari n°3852", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Premier musulman torturé par les Quraysh",est_correcte:true},{texte_fr:"Roi de Perse",est_correcte:false},{texte_fr:"Compagnon riche",est_correcte:false},{texte_fr:"Chef tribal Yémen",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que la conquête de Khaybar (7 H) ?", texte_ar:'ما فتح خيبر؟', explication:"Conquête de la principale forteresse juive du Hijaz. Ali ibn Abi Talib fut le héros — ouverture de la dernière forteresse par lui.", dalil_ref:"Sahih al-Bukhari n°4209", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Conquête des forteresses juives, Ali héros",est_correcte:true},{texte_fr:"Bataille à La Mecque",est_correcte:false},{texte_fr:"Pèlerinage d'adieu",est_correcte:false},{texte_fr:"Voyage en Syrie",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Comment a commencé la prédication publique du Prophète ﷺ ?", texte_ar:'كيف بدأت الدعوة الجهرية؟', explication:"3 ans après la 1re révélation, Allah ordonna « Avertis tes plus proches parents » (26:214). Le Prophète ﷺ monta sur le mont Safa et appela les Quraysh.", dalil_ref:"Sourate Ash-Shu'ara 26:214 ; Sahih al-Bukhari n°4770", reponses:[{texte_fr:"Sur le mont Safa, après 3 ans de da'wa discrète",est_correcte:true},{texte_fr:"Dans la Ka'ba",est_correcte:false},{texte_fr:"Devant les juifs",est_correcte:false},{texte_fr:"À Médine",est_correcte:false}] },
  { domaine:'sirah', niveau:3, texte_fr:"Qu'est-ce que le « Année du Chagrin » (Am al-Huzn) ?", texte_ar:'ما عام الحزن؟', explication:"L'an 10 de la prophétie : décès d'Abu Talib (oncle protecteur) puis de Khadija (épouse aimée), à 3 jours d'intervalle. Le Prophète ﷺ subit une grande tristesse.", reponses:[{texte_fr:"Mort d'Abu Talib et Khadija (an 10 prophétie)",est_correcte:true},{texte_fr:"Année de guerre",est_correcte:false},{texte_fr:"Année de famine",est_correcte:false},{texte_fr:"Année des pestes",est_correcte:false}] },

  // ========== SIRAH N4 (+11) ==========
  { domaine:'sirah', niveau:4, texte_fr:"Quels furent les pertes musulmanes à Uhud (3H) ?", texte_ar:'كم استشهد من المسلمين في أحد؟', explication:"70 martyrs musulmans, dont Hamza, Mus'ab ibn Umayr et Abdullah ibn Jahsh. Le Prophète ﷺ fut blessé.", reponses:[{texte_fr:"70 martyrs dont Hamza et Mus'ab",est_correcte:true},{texte_fr:"3 martyrs",est_correcte:false},{texte_fr:"Aucun mort",est_correcte:false},{texte_fr:"10 000 martyrs",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Qu'est-ce que l'expédition de Banu Quraydha (5H) ?", texte_ar:'ما غزوة بني قريظة؟', explication:"Après le Khandaq, expédition contre la tribu juive de Médine qui avait trahi le pacte. Le verdict de leur arbitre Sa'd ibn Mu'adh fut appliqué selon leur propre Torah.", dalil_ref:"Sahih al-Bukhari n°4121", reponses:[{texte_fr:"Expédition contre la tribu juive qui trahit le pacte",est_correcte:true},{texte_fr:"Bataille en Iraq",est_correcte:false},{texte_fr:"Pèlerinage",est_correcte:false},{texte_fr:"Voyage commercial",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Quelle fut la fonction du Sahifa de Médine ?", texte_ar:'ما وظيفة الصحيفة المدنية؟', explication:"Constitution écrite à l'arrivée à Médine entre musulmans, juifs et tribus polythéistes : organisation de la cité, sécurité commune, paix.", reponses:[{texte_fr:"Constitution de Médine pour vivre ensemble",est_correcte:true},{texte_fr:"Lettre à Quraysh",est_correcte:false},{texte_fr:"Pacte de guerre",est_correcte:false},{texte_fr:"Traité commercial",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Combien d'ennemis tombèrent à Badr (2H) ?", texte_ar:'كم قتلى المشركين في بدر؟', explication:"70 mecquois tués (dont Abu Jahl) et 70 captifs. Allah les humilia. Cette victoire éclatante avec si peu d'hommes confirma la prophétie.", reponses:[{texte_fr:"70 tués (dont Abu Jahl) et 70 captifs",est_correcte:true},{texte_fr:"Aucun",est_correcte:false},{texte_fr:"10 000",est_correcte:false},{texte_fr:"3 personnes",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Quelle fut l'attitude du Prophète ﷺ envers les captifs de Badr ?", texte_ar:'ما موقف النبي ﷺ من أسرى بدر؟', explication:"Il accepta la rançon (sur conseil d'Abu Bakr) et certains captifs apprirent à lire aux musulmans en guise de rançon (un captif = 10 musulmans alphabétisés).", dalil_ref:"Musnad Ahmad n°2216", reponses:[{texte_fr:"Rançon + alphabétisation des musulmans",est_correcte:true},{texte_fr:"Tous exécutés",est_correcte:false},{texte_fr:"Tous libérés gratuitement",est_correcte:false},{texte_fr:"Réduits en esclavage",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Que signifie le discours d'Adieu (Khutbat al-Wada') ?", texte_ar:'ما هي خطبة الوداع؟', explication:"Discours fondamental du Prophète ﷺ à Arafat (10 H) devant 100 000+ : sanctifié sang, honneur et biens des musulmans ; égalité des hommes ; droits des femmes ; héritage ; abolition du riba.", dalil_ref:"Sahih Muslim n°1218", reponses:[{texte_fr:"Discours à Arafat fondant les droits universels en islam",est_correcte:true},{texte_fr:"Sermon ordinaire",est_correcte:false},{texte_fr:"Lettre privée",est_correcte:false},{texte_fr:"Conversation informelle",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Pourquoi le Prophète ﷺ a-t-il envoyé des lettres aux rois en 6 H ?", texte_ar:'لماذا أرسل النبي ﷺ رسائل إلى الملوك؟', explication:"Après Hudaybiyya, pour les inviter à l'islam : Héraclius (Byzance), Khosroes (Perse), Muqawqis (Égypte), Najashi (Éthiopie), Harith (Ghassan), Hawdha (Yamama).", dalil_ref:"Sahih al-Bukhari n°7", reponses:[{texte_fr:"Inviter les rois à l'islam après Hudaybiyya",est_correcte:true},{texte_fr:"Demander de l'aide militaire",est_correcte:false},{texte_fr:"Faire du commerce",est_correcte:false},{texte_fr:"Demander la paix uniquement",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Quelle fut la réaction d'Héraclius à la lettre du Prophète ﷺ ?", texte_ar:'ما رد هرقل على رسالة النبي ﷺ؟', explication:"Il fut convaincu de la véracité de la prophétie, après avoir interrogé Abu Sufyan. Mais ne se convertit pas par peur des siens — comme rapporté dans Bukhari.", dalil_ref:"Sahih al-Bukhari n°7", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Convaincu mais ne se convertit pas (peur des siens)",est_correcte:true},{texte_fr:"Brûla la lettre",est_correcte:false},{texte_fr:"Embrassa l'islam publiquement",est_correcte:false},{texte_fr:"Déclara la guerre immédiate",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Pourquoi Khosroes (roi de Perse) déchira-t-il la lettre du Prophète ﷺ ?", texte_ar:'لماذا مزق كسرى رسالة النبي ﷺ؟', explication:"Par orgueil. Le Prophète ﷺ invoqua alors : « Qu'Allah déchire son royaume » — et l'Empire perse tomba sous Umar.", dalil_ref:"Sahih al-Bukhari n°4424", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Par orgueil ; sa dynastie tomba comme invoqué",est_correcte:true},{texte_fr:"Par humilité",est_correcte:false},{texte_fr:"Pour étudier le texte",est_correcte:false},{texte_fr:"Erreur de traduction",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Qui était Ja'far ibn Abi Talib ?", texte_ar:'من هو جعفر بن أبي طالب؟', explication:"Cousin du Prophète ﷺ, chef de la délégation en Éthiopie, où il récita Sourate Maryam au Najashi. Tomba en martyr à Mu'tah. Surnommé « Ja'far at-Tayyar » (le volant) pour ses bras coupés.", dalil_ref:"Sahih al-Bukhari n°4264", reponses:[{texte_fr:"Cousin du Prophète, chef à l'Éthiopie, martyr à Mu'tah",est_correcte:true},{texte_fr:"Fils du Prophète",est_correcte:false},{texte_fr:"Compagnon mineur",est_correcte:false},{texte_fr:"Calife",est_correcte:false}] },
  { domaine:'sirah', niveau:4, texte_fr:"Combien de musulmans participèrent à Hudaybiyya (6 H) ?", texte_ar:'كم عدد المسلمين في الحديبية؟', explication:"1400 Compagnons accompagnèrent le Prophète ﷺ pour la 'Umra. Ce sont les Compagnons de Bay'at ar-Ridwan (le serment sous l'arbre).", dalil_ref:"Sahih al-Bukhari n°4154 ; Muslim n°1856", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"1400 Compagnons (Bay'at ar-Ridwan)",est_correcte:true},{texte_fr:"100",est_correcte:false},{texte_fr:"10 000",est_correcte:false},{texte_fr:"3 seulement",est_correcte:false}] },

  // ========== SIRAH N5 (+14) ==========
  { domaine:'sirah', niveau:5, texte_fr:"Quel fut le calendrier instauré par Umar ?", texte_ar:'ما التقويم الذي وضعه عمر؟', explication:"Le calendrier hijri lunaire, prenant comme an 1 l'année de la Hijra (622 G). Instauré en 16 H sur conseil d'Ali رضي الله عنه.", reponses:[{texte_fr:"Calendrier hijri lunaire (Hijra = an 1)",est_correcte:true},{texte_fr:"Calendrier romain",est_correcte:false},{texte_fr:"Calendrier persan",est_correcte:false},{texte_fr:"Calendrier solaire",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quelle fut la première mesure de la « Ridda » contre les apostats ?", texte_ar:'ما أول قرار في حروب الردة؟', explication:"Abu Bakr déclara la guerre aux tribus qui refusaient de payer la zakat, considérant cela comme une rupture de l'unité de l'islam.", reponses:[{texte_fr:"Combat contre les refus de payer la zakat",est_correcte:true},{texte_fr:"Compromis financier",est_correcte:false},{texte_fr:"Tolérance totale",est_correcte:false},{texte_fr:"Pèlerinage commun",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quel fut le rôle de Khalid lors des guerres de la Ridda ?", texte_ar:'ما دور خالد في حروب الردة؟', explication:"Commandant en chef. Vainquit Musaylima le Menteur à al-Yamama (12 H) — où 700 mémorisateurs du Coran périrent, déclenchant la compilation par Abu Bakr.", reponses:[{texte_fr:"Vainqueur de Musaylima à al-Yamama",est_correcte:true},{texte_fr:"Combat contre Byzance",est_correcte:false},{texte_fr:"Compilation du Coran",est_correcte:false},{texte_fr:"Construction de Médine",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Qui était Musaylima al-Kadhdhab ?", texte_ar:'من هو مسيلمة الكذاب؟', explication:"Faux prophète de Banu Hanifa au Yamama, prétendit recevoir une révélation. Vaincu et tué à la bataille de al-Yamama en 12 H par Wahshi (le tueur de Hamza).", reponses:[{texte_fr:"Faux prophète tué à al-Yamama par Wahshi",est_correcte:true},{texte_fr:"Calife juste",est_correcte:false},{texte_fr:"Sahabi pieux",est_correcte:false},{texte_fr:"Imam des juifs",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quelles furent les conquêtes majeures sous Umar (13-23 H) ?", texte_ar:'ما الفتوحات الكبرى في عهد عمر؟', explication:"Syrie (Yarmuk 15H), Iraq (Qadisiyya 16H), Jérusalem (15H), Égypte (20H), chute de l'Empire perse sassanide. Doublement du territoire en 10 ans.", reponses:[{texte_fr:"Syrie, Iraq, Jérusalem, Égypte, fin Empire perse",est_correcte:true},{texte_fr:"Aucune conquête",est_correcte:false},{texte_fr:"Conquête de la Chine",est_correcte:false},{texte_fr:"Limite à l'Arabie",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Comment Umar est-il mort ?", texte_ar:'كيف توفي عمر؟', explication:"Assassiné en 23 H pendant la prière du Fajr par Abu Lulu'a (esclave perse mécréant) avec un poignard empoisonné.", reponses:[{texte_fr:"Assassiné en prière par Abu Lulu'a",est_correcte:true},{texte_fr:"Mort naturelle âgée",est_correcte:false},{texte_fr:"Tombé en bataille",est_correcte:false},{texte_fr:"Empoisonné par sa famille",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quel système Umar instaura-t-il pour la consultation ?", texte_ar:'ما نظام الشورى الذي أقامه عمر؟', explication:"Le Conseil des 6 (Shura) : Uthman, Ali, Talha, Zubayr, Abdurrahman ibn Awf, Saad ibn Abi Waqqas — pour élire son successeur après son décès.", reponses:[{texte_fr:"Shura des 6 pour élire son successeur",est_correcte:true},{texte_fr:"Désigna Uthman directement",est_correcte:false},{texte_fr:"Vote populaire",est_correcte:false},{texte_fr:"Hérédité familiale",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quelle est la fitna sous Uthman ?", texte_ar:'ما الفتنة في عهد عثمان؟', explication:"Rebelles venus d'Égypte, Iraq, Kufa l'assiégèrent à Médine, l'accusant à tort de népotisme. Il fut assassiné en lisant le Coran en 35 H.", reponses:[{texte_fr:"Siège par rebelles d'Égypte/Iraq, assassinat en 35H",est_correcte:true},{texte_fr:"Guerre contre Byzance",est_correcte:false},{texte_fr:"Famine",est_correcte:false},{texte_fr:"Maladie",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quelles furent les batailles entre Ali et Mu'awiya ?", texte_ar:'ما المعارك بين علي ومعاوية؟', explication:"Jamal (Bassora, 36H — Ali contre Aïcha/Talha/Zubayr) puis Siffin (37H — Ali contre Mu'awiya). Suivi de l'arbitrage et naissance des Khawarij.", reponses:[{texte_fr:"Jamal puis Siffin (36-37 H)",est_correcte:true},{texte_fr:"Aucune bataille",est_correcte:false},{texte_fr:"Conquête de Médine",est_correcte:false},{texte_fr:"Bataille contre Byzance",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Qui étaient les Kharijites (Khawarij) ?", texte_ar:'من هم الخوارج؟', explication:"Secte ayant déserté l'armée d'Ali après l'arbitrage à Siffin. Doctrine extrémiste : qualifient les pécheurs majeurs de mécréants. Combattus par Ali à Nahrawan (38 H).", reponses:[{texte_fr:"Secte extrémiste sortie de l'armée d'Ali",est_correcte:true},{texte_fr:"Sahaba pieux",est_correcte:false},{texte_fr:"Soufis modérés",est_correcte:false},{texte_fr:"Sunnites majoritaires",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Comment Ali est-il mort ?", texte_ar:'كيف توفي علي؟', explication:"Assassiné en 40 H à Kufa par le Kharijite Ibn Muljam pendant la prière du Fajr avec une épée empoisonnée.", reponses:[{texte_fr:"Assassiné par le Kharijite Ibn Muljam en prière",est_correcte:true},{texte_fr:"Mort de vieillesse",est_correcte:false},{texte_fr:"Tué en bataille",est_correcte:false},{texte_fr:"Empoisonné par Mu'awiya",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Combien dura le califat de Hasan ibn Ali ?", texte_ar:'كم دامت خلافة الحسن بن علي؟', explication:"6 mois. Hasan رضي الله عنه renonça en faveur de Mu'awiya en 41 H pour éviter l'effusion de sang — l'« Année de l'Union » (am al-Jama'a).", dalil_ref:"Sahih al-Bukhari n°2704", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"6 mois, puis renoncement à Mu'awiya pour la paix",est_correcte:true},{texte_fr:"20 ans",est_correcte:false},{texte_fr:"30 ans",est_correcte:false},{texte_fr:"50 ans",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quel fut l'événement de Karbala (61 H) ?", texte_ar:'ما حدث كربلاء؟', explication:"Husayn ibn Ali رضي الله عنه fut martyrisé par l'armée de Yazid à Karbala (Iraq). Tragédie majeure de l'histoire islamique.", reponses:[{texte_fr:"Martyre de Husayn par l'armée de Yazid",est_correcte:true},{texte_fr:"Conquête de la Perse",est_correcte:false},{texte_fr:"Construction d'une ville",est_correcte:false},{texte_fr:"Pèlerinage",est_correcte:false}] },
  { domaine:'sirah', niveau:5, texte_fr:"Quand commença la dynastie omeyyade ?", texte_ar:'متى بدأت الدولة الأموية؟', explication:"En 41 H (661 G) avec Mu'awiya ibn Abi Sufyan رضي الله عنه, après le renoncement de Hasan ibn Ali. Capitale : Damas. Dura jusqu'en 132 H (750 G).", reponses:[{texte_fr:"41 H (Mu'awiya), capitale Damas",est_correcte:true},{texte_fr:"1 H avec le Prophète",est_correcte:false},{texte_fr:"132 H",est_correcte:false},{texte_fr:"500 H",est_correcte:false}] },

  // ========== TAFSIR N3 (+7) ==========
  { domaine:'tafsir', niveau:3, texte_fr:"Quelles sourates parlent abondamment de la Création ?", texte_ar:'ما السور التي تكثر فيها آيات الخلق؟', explication:"Yasin, Ar-Ra'd, Al-Mu'minun, Fussilat, Adh-Dhariyat, Al-Mulk, Al-Qiyamah. Allah y montre Sa puissance dans la création comme preuve du Tawhid.", reponses:[{texte_fr:"Yasin, Ar-Ra'd, Mu'minun, Fussilat, Mulk",est_correcte:true},{texte_fr:"Al-Fatiha seule",est_correcte:false},{texte_fr:"An-Nas seule",est_correcte:false},{texte_fr:"Aucune",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Que dit Sourate Al-Anfal sur les fruits de la victoire ?", texte_ar:'ما تقول سورة الأنفال عن النصر؟', explication:"« La victoire ne vient que d'Allah » (8:10). Insiste sur la dépendance totale envers Allah et la cohésion de la communauté.", dalil_ref:"Sourate Al-Anfal 8:10", reponses:[{texte_fr:"La victoire ne vient que d'Allah",est_correcte:true},{texte_fr:"Par la force seule",est_correcte:false},{texte_fr:"Par l'argent",est_correcte:false},{texte_fr:"Par l'astuce",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quelle est la sagesse de la mention de Moïse 136 fois dans le Coran ?", texte_ar:'ما حكمة تكرر ذكر موسى؟', explication:"Plusieurs sagesses : exemplarité de sa lutte contre Pharaon (un parallèle à celle du Prophète ﷺ contre Quraysh), pédagogie progressive, multiples enseignements.", reponses:[{texte_fr:"Exemplarité de sa lutte, parallèle pédagogique",est_correcte:true},{texte_fr:"Sans raison",est_correcte:false},{texte_fr:"Préférence ethnique",est_correcte:false},{texte_fr:"Erreur de scribe",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel verset interdit explicitement l'alcool ?", texte_ar:'ما الآية التي تحرم الخمر صراحة؟', explication:"Sourate Al-Maida 5:90 : « Ô vous qui avez cru ! Le vin, le jeu de hasard, les pierres dressées et les flèches de divination ne sont qu'une souillure, œuvre du Diable. Écartez-vous-en. »", dalil_ref:"Sourate Al-Maida 5:90", reponses:[{texte_fr:"Al-Maida 5:90",est_correcte:true},{texte_fr:"Al-Fatiha 1:1",est_correcte:false},{texte_fr:"Yasin 36:1",est_correcte:false},{texte_fr:"An-Nas 114:1",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel verset cite les 5 piliers de l'islam implicitement ?", texte_ar:'ما الآية التي تجمع أركان الإسلام؟', explication:"Sourate Al-Baqara 2:177 cite la foi, la prière, la zakat, la patience dans l'épreuve. Hadith de Jibril ajoute les piliers manquants.", dalil_ref:"Sourate Al-Baqara 2:177", reponses:[{texte_fr:"Al-Baqara 2:177",est_correcte:true},{texte_fr:"An-Nas 114",est_correcte:false},{texte_fr:"Al-Asr 103",est_correcte:false},{texte_fr:"Al-Mulk 67",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Quel est le « plus grand verset » selon le Prophète ﷺ ?", texte_ar:'ما أعظم آية في القرآن؟', explication:"Ayat al-Kursi (al-Baqara 2:255). Le Prophète ﷺ à Ubayy ibn Ka'b : « C'est le plus grand verset du Coran. »", dalil_ref:"Sahih Muslim n°810", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Ayat al-Kursi",est_correcte:true},{texte_fr:"Al-Ikhlas 112:1",est_correcte:false},{texte_fr:"Al-Fatiha 1:5",est_correcte:false},{texte_fr:"An-Nas 114:1",est_correcte:false}] },
  { domaine:'tafsir', niveau:3, texte_fr:"Combien y a-t-il de sourates commençant par « Iqra' » ?", texte_ar:'كم سورة تبدأ بـ اقرأ؟', explication:"Une seule : Sourate al-Alaq, la 1re sourate révélée. Les 5 premiers versets furent les premiers à descendre.", reponses:[{texte_fr:"1 (Sourate al-Alaq)",est_correcte:true},{texte_fr:"10 sourates",est_correcte:false},{texte_fr:"Aucune",est_correcte:false},{texte_fr:"Toutes",est_correcte:false}] },

  // ========== TAFSIR N4 (+12) ==========
  { domaine:'tafsir', niveau:4, texte_fr:"Quel verset traite de l'égalité entre les races ?", texte_ar:'ما الآية الدالة على المساواة بين الأعراق؟', explication:"« Ô vous, les hommes ! Nous vous avons créés d'un mâle et d'une femelle, et fait peuples et tribus pour que vous vous entreconnaissiez. Le plus noble d'entre vous est le plus pieux. » (Al-Hujurat 49:13)", dalil_ref:"Sourate Al-Hujurat 49:13", reponses:[{texte_fr:"Al-Hujurat 49:13 — noblesse = piété",est_correcte:true},{texte_fr:"Aucun verset",est_correcte:false},{texte_fr:"Al-Fatiha 1:1",est_correcte:false},{texte_fr:"Yasin 36:1",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Quelles sourates traitent principalement des récits prophétiques ?", texte_ar:'ما السور التي تكثر فيها قصص الأنبياء؟', explication:"Al-Anbiya (les Prophètes), Hud, Yunus, Yusuf, Maryam, Al-Qasas, Sad, Ash-Shu'ara. Allah dit : « Dans leurs récits, il y a une leçon. » (12:111)", reponses:[{texte_fr:"Al-Anbiya, Hud, Yunus, Yusuf, Maryam, Qasas",est_correcte:true},{texte_fr:"Al-Fatiha uniquement",est_correcte:false},{texte_fr:"Mu'awwidhat seulement",est_correcte:false},{texte_fr:"Aucune",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Combien de versets parlent de la prière obligatoire ?", texte_ar:'كم آية تتحدث عن الصلاة المفروضة؟', explication:"Environ 78 versets mentionnent directement la salat. C'est la 2e obligation la plus mentionnée après le Tawhid.", reponses:[{texte_fr:"Environ 78 versets",est_correcte:true},{texte_fr:"3 versets",est_correcte:false},{texte_fr:"1 verset",est_correcte:false},{texte_fr:"500 versets",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Que sont les Hudud dans le Coran ?", texte_ar:'ما الحدود في القرآن؟', explication:"Châtiments fixes ordonnés par Allah pour certains crimes graves (vol, adultère, calomnie, brigandage, apostasie). Les conditions pour les appliquer sont très strictes.", dalil_ref:"Sourate Al-Maida 5:38-39", reponses:[{texte_fr:"Châtiments fixes pour 5 crimes graves",est_correcte:true},{texte_fr:"Limites territoriales",est_correcte:false},{texte_fr:"Limites de prière",est_correcte:false},{texte_fr:"Salaires",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Quels sont les arguments coraniques pour la résurrection ?", texte_ar:'ما الأدلة القرآنية على البعث؟', explication:"Nombreux : retour à la vie de la terre après la pluie (41:39), création initiale prouve la recréation (36:78-79), exemple des oiseaux d'Ibrahim (2:260).", reponses:[{texte_fr:"Pluie sur la terre, recréation, oiseaux d'Ibrahim",est_correcte:true},{texte_fr:"Pas d'argument",est_correcte:false},{texte_fr:"Argument unique",est_correcte:false},{texte_fr:"Hadiths uniquement",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Qu'est-ce que les « Asma' as-Suwar » ?", texte_ar:'ما أسماء السور؟', explication:"Les noms des sourates. Tous sont basés sur la Sunnah (transmis du Prophète ﷺ ou des Compagnons). Aucun n'est inventé.", reponses:[{texte_fr:"Noms des sourates, tous basés sur la Sunnah",est_correcte:true},{texte_fr:"Noms inventés",est_correcte:false},{texte_fr:"Choisis par les califes",est_correcte:false},{texte_fr:"Choisis par Ibn Kathir",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Que veut dire « al-Wahy al-Khafi » (révélation cachée) ?", texte_ar:'ما الوحي الخفي؟', explication:"Inspiration directe dans le cœur du Prophète ﷺ, sans intermédiaire visible. Différent du wahy clair (par Jibril) ou indirect (rêve).", reponses:[{texte_fr:"Inspiration directe dans le cœur",est_correcte:true},{texte_fr:"Rêve uniquement",est_correcte:false},{texte_fr:"Révélation aux savants",est_correcte:false},{texte_fr:"N'existe pas",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Combien d'années entre l'Iqra' et la mort du Prophète ﷺ ?", texte_ar:'كم سنة بين اقرأ ووفاة النبي ﷺ؟', explication:"23 ans : 13 ans à La Mecque et 10 ans à Médine. Période exacte de la révélation du Coran.", reponses:[{texte_fr:"23 ans",est_correcte:true},{texte_fr:"5 ans",est_correcte:false},{texte_fr:"40 ans",est_correcte:false},{texte_fr:"50 ans",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Quel verset prescrit la consultation (Shura) ?", texte_ar:'ما آية الشورى؟', explication:"« Et consulte-les sur l'affaire » (Al-Imran 3:159) et « ...leur affaire est consultation entre eux » (Ash-Shura 42:38). Base de la gouvernance islamique.", dalil_ref:"Sourate Al-Imran 3:159 ; Ash-Shura 42:38", reponses:[{texte_fr:"Al-Imran 3:159 et Ash-Shura 42:38",est_correcte:true},{texte_fr:"An-Nas 114",est_correcte:false},{texte_fr:"Aucun",est_correcte:false},{texte_fr:"Al-Fatiha 1:5",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Que sont les « Qisas al-Anbiya » dans le Coran ?", texte_ar:'ما قصص الأنبياء في القرآن؟', explication:"Récits de 25 prophètes (d'Adam à Muhammad ﷺ) avec leçons morales. Sourate Yusuf est la « plus belle des histoires » (12:3).", reponses:[{texte_fr:"Récits des 25 prophètes nommés",est_correcte:true},{texte_fr:"Histoires d'animaux",est_correcte:false},{texte_fr:"Contes pour enfants",est_correcte:false},{texte_fr:"Légendes locales",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Combien de noms a Allah dans le Coran ?", texte_ar:'كم اسماً لله في القرآن؟', explication:"99 Beaux Noms (Asma al-Husna). Certains apparaissent plusieurs fois, d'autres une seule fois. Tous sont des Attributs de perfection.", dalil_ref:"Sahih al-Bukhari n°2736", reponses:[{texte_fr:"99 Beaux Noms",est_correcte:true},{texte_fr:"3 noms",est_correcte:false},{texte_fr:"1000 noms",est_correcte:false},{texte_fr:"114 noms",est_correcte:false}] },
  { domaine:'tafsir', niveau:4, texte_fr:"Que signifie Wahy Mutluw vs ghayr Mutluw ?", texte_ar:'ما الفرق بين الوحي المتلو وغير المتلو؟', explication:"Mutluw = ce qu'on récite (le Coran). Ghayr Mutluw = ce qui n'est pas récité mais inspiré (la Sunnah). Tous deux sont révélation.", reponses:[{texte_fr:"Coran (récité) vs Sunnah (non récitée mais révélée)",est_correcte:true},{texte_fr:"Identiques",est_correcte:false},{texte_fr:"Pas de différence",est_correcte:false},{texte_fr:"Termes inventés",est_correcte:false}] },

  // ========== TAFSIR N5 (+20) ==========
  { domaine:'tafsir', niveau:5, texte_fr:"Qu'est-ce que les Mansukh dans le Coran ?", texte_ar:'ما المنسوخ في القرآن؟', explication:"Versets dont le jugement a été abrogé. Les savants distinguent 3 types : naskh de la récitation et du jugement, du jugement seul, de la récitation seule.", dalil_ref:"al-Itqan d'as-Suyuti", reponses:[{texte_fr:"Versets dont le jugement est abrogé (3 types)",est_correcte:true},{texte_fr:"Versets supprimés du Mushaf",est_correcte:false},{texte_fr:"Versets inconnus",est_correcte:false},{texte_fr:"N'existe pas",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quels sont les commentateurs du Coran les plus reconnus ?", texte_ar:'من أبرز المفسرين؟', explication:"Tabari (310 H — mère des tafsirs par transmission), Ibn Kathir (774 H — par hadith), Qurtubi (671 H — fiqh), Sa'di (1376 H — moderne et clair).", reponses:[{texte_fr:"Tabari, Ibn Kathir, Qurtubi, Sa'di",est_correcte:true},{texte_fr:"Aucun",est_correcte:false},{texte_fr:"Un seul",est_correcte:false},{texte_fr:"100 commentateurs",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Que dit Ibn Taymiyya sur le tafsir par la raison seule ?", texte_ar:'ما رأي ابن تيمية في التفسير بالرأي المجرد؟', explication:"Il dit : « Le tafsir par opinion sans connaissance est interdit. » Il faut connaître la langue arabe, les Asbab an-Nuzul, les méthodes des Salaf, etc.", dalil_ref:"Muqaddima fi Usul at-Tafsir", reponses:[{texte_fr:"Interdit sans connaissance préalable",est_correcte:true},{texte_fr:"Recommandé pour tous",est_correcte:false},{texte_fr:"Obligatoire pour chacun",est_correcte:false},{texte_fr:"Sans avis",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Combien y a-t-il de Lectures (qiraat) mutawatir ?", texte_ar:'كم القراءات المتواترة؟', explication:"10 lectures authentiques (mutawatir). Ibn Mujahid en avait reconnu 7, puis Ibn al-Jazari en ajouta 3 (Abu Ja'far, Ya'qub, Khalaf).", dalil_ref:"an-Nashr d'Ibn al-Jazari", reponses:[{texte_fr:"10 lectures mutawatir",est_correcte:true},{texte_fr:"1 seule",est_correcte:false},{texte_fr:"100 lectures",est_correcte:false},{texte_fr:"Aucune",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Que sont les « Wujuh wa an-Nadhair » du Coran ?", texte_ar:'ما الوجوه والنظائر في القرآن؟', explication:"Un même mot ayant plusieurs sens (wujuh) ou plusieurs mots ayant le même sens (nadhair). Science classique du tafsir. Ex: « Hadi » signifie guide ou ce qui guide.", reponses:[{texte_fr:"Polysémie et synonymie dans le Coran",est_correcte:true},{texte_fr:"Variantes de lecture",est_correcte:false},{texte_fr:"Sourates abrogées",est_correcte:false},{texte_fr:"Variantes étranges",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quels sont les 4 grands chefs de qiraat ?", texte_ar:'من هم القراء الأربعة الكبار؟', explication:"Nafi' al-Madani, Asim al-Kufi, Hamza al-Kufi, al-Kisa'i. Avec Ibn Kathir al-Makki, Abu Amr et Ibn Amir = les 7 originaux d'Ibn Mujahid.", reponses:[{texte_fr:"Nafi', Asim, Hamza, al-Kisa'i (+ 3 autres = 7)",est_correcte:true},{texte_fr:"Aucun",est_correcte:false},{texte_fr:"Les 4 califes",est_correcte:false},{texte_fr:"Les 4 imams",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Qu'est-ce que la « Riwaya » dans les qiraat ?", texte_ar:'ما الرواية في القراءات؟', explication:"Voie de transmission d'un qari donné. Ex: Nafi' a 2 riwayat principales : Warsh et Qalun. La récitation maghrébine est par Warsh, l'orientale par Hafs (de Asim).", reponses:[{texte_fr:"Voie de transmission d'une lecture (ex: Warsh, Qalun, Hafs)",est_correcte:true},{texte_fr:"Hadith",est_correcte:false},{texte_fr:"Poème",est_correcte:false},{texte_fr:"Sourate",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quelle est la lecture la plus répandue mondialement ?", texte_ar:'ما أكثر القراءات انتشاراً؟', explication:"Hafs 'an Asim — la lecture utilisée dans la majorité des pays musulmans (Égypte, Arabie, Asie, etc.). Au Maghreb, c'est Warsh 'an Nafi'.", reponses:[{texte_fr:"Hafs 'an Asim",est_correcte:true},{texte_fr:"Warsh 'an Nafi' seulement",est_correcte:false},{texte_fr:"Lecture inconnue",est_correcte:false},{texte_fr:"Aucune répandue",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Que signifient les « Ahruf » du Coran ?", texte_ar:'ما الأحرف السبعة؟', explication:"Le hadith mutawatir : « Le Coran fut révélé sur 7 ahruf, lis ce qui t'est facile. » Sens débattu par les savants : dialectes, synonymes, etc. Différent des 10 qiraat.", dalil_ref:"Sahih al-Bukhari n°4992", grade_hadith:"Hadith Mutawatir", reponses:[{texte_fr:"7 modes de récitation établis par hadith mutawatir",est_correcte:true},{texte_fr:"7 sourates",est_correcte:false},{texte_fr:"7 versets",est_correcte:false},{texte_fr:"7 dialectes uniquement",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Qu'est-ce que la « I'jaz al-Qur'an » ?", texte_ar:'ما إعجاز القرآن؟', explication:"L'inimitabilité du Coran : aucun être ne peut produire de semblable, ni même une sourate (cf. al-Baqara 2:23). Inimitabilité linguistique, scientifique, législative, narrative.", reponses:[{texte_fr:"Inimitabilité linguistique, scientifique, etc.",est_correcte:true},{texte_fr:"Erreur de copie",est_correcte:false},{texte_fr:"Mots magiques",est_correcte:false},{texte_fr:"Récitation rythmée",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quel est le défi du Coran aux Arabes ?", texte_ar:'ما تحدي القرآن للعرب؟', explication:"Allah les a défiés en 3 étapes : produire un Coran semblable, puis 10 sourates, puis 1 seule sourate. Aucun n'a pu — démonstration de son origine divine.", dalil_ref:"Sourate Al-Baqara 2:23 ; Yunus 10:38", reponses:[{texte_fr:"Produire 1 sourate semblable — impossible",est_correcte:true},{texte_fr:"Battre le Prophète militaire",est_correcte:false},{texte_fr:"Construire la Ka'ba",est_correcte:false},{texte_fr:"Mémoriser plus",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Que sont les Ayat al-Ahkam (versets juridiques) ?", texte_ar:'ما آيات الأحكام؟', explication:"Environ 500 versets traitant directement de jugements (salat, zakat, mariage, héritage, transactions, pénal). Base du fiqh.", reponses:[{texte_fr:"~500 versets directement juridiques",est_correcte:true},{texte_fr:"Aucun verset",est_correcte:false},{texte_fr:"Tous les versets",est_correcte:false},{texte_fr:"3 versets",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quels Sahaba étaient les plus grands savants du Tafsir ?", texte_ar:'من أعلم الصحابة بالتفسير؟', explication:"4 surtout : Ali ibn Abi Talib, Abdullah ibn Mas'ud, Abdullah ibn Abbas, Ubayy ibn Ka'b. Ibn Abbas est surnommé « Tarjuman al-Qur'an » (l'interprète).", reponses:[{texte_fr:"Ali, Ibn Mas'ud, Ibn Abbas, Ubayy ibn Ka'b",est_correcte:true},{texte_fr:"Tous identiques",est_correcte:false},{texte_fr:"Aucun particulier",est_correcte:false},{texte_fr:"Khadija seule",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Qui était Ibn Abbas en tafsir ?", texte_ar:'من ابن عباس في التفسير؟', explication:"« Tarjuman al-Qur'an » (interprète du Coran). Le Prophète ﷺ invoqua pour lui : « Allahumma faqqihhu fi ad-din wa 'allimhu at-ta'wil. »", dalil_ref:"Sahih al-Bukhari n°143", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Tarjuman al-Qur'an (l'interprète)",est_correcte:true},{texte_fr:"Calife",est_correcte:false},{texte_fr:"Compagnon mineur",est_correcte:false},{texte_fr:"Roi du Yémen",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Qu'est-ce que les « Mukhtasarat » des grands tafsirs ?", texte_ar:'ما مختصرات التفاسير؟', explication:"Versions abrégées de tafsirs colossaux. Ex: Mukhtasar Tafsir Ibn Kathir d'as-Sabuni, Tayseer al-Karim ar-Rahman d'as-Sa'di (chemin vers le sens facile).", reponses:[{texte_fr:"Versions abrégées des grands tafsirs",est_correcte:true},{texte_fr:"Tafsirs inventés",est_correcte:false},{texte_fr:"Tafsirs perdus",est_correcte:false},{texte_fr:"Recueils de hadiths",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Que sont les « Israa'iliyyat » dans le tafsir ?", texte_ar:'ما الإسرائيليات في التفسير؟', explication:"Récits hérités de la tradition juive et chrétienne. Acceptés s'ils correspondent à la révélation, rejetés s'ils la contredisent, neutres sinon.", dalil_ref:"Muqaddima d'Ibn Taymiyya", reponses:[{texte_fr:"Récits juifs/chrétiens à évaluer selon notre révélation",est_correcte:true},{texte_fr:"Toujours acceptés",est_correcte:false},{texte_fr:"Toujours rejetés",est_correcte:false},{texte_fr:"Inexistants",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quelle école de tafsir est « bil-Ishara » ?", texte_ar:'ما التفسير بالإشارة؟', explication:"Tafsir mystique soufi cherchant des indications spirituelles cachées. Toléré s'il ne contredit pas le sens apparent, sinon innovation.", reponses:[{texte_fr:"Tafsir mystique des soufis (sens caché)",est_correcte:true},{texte_fr:"Tafsir par opinion seule",est_correcte:false},{texte_fr:"Tafsir abrogé",est_correcte:false},{texte_fr:"Tafsir mathématique",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Que signifie le terme « Munasaba » dans le tafsir ?", texte_ar:'ما المناسبة في التفسير؟', explication:"Science des liens et harmonies entre versets, entre sourates, entre débuts et fins. Montre l'unité de l'œuvre coranique.", reponses:[{texte_fr:"Liens et harmonies entre versets/sourates",est_correcte:true},{texte_fr:"Anniversaires",est_correcte:false},{texte_fr:"Statistique",est_correcte:false},{texte_fr:"Sans rapport",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Qu'est-ce qu'un Tafsir Mawdu'i (thématique) ?", texte_ar:'ما التفسير الموضوعي؟', explication:"Tafsir suivant un thème (ex: tafsir du verset sur la patience, tafsir du Tawhid) à travers tout le Coran. Méthode moderne complémentaire.", reponses:[{texte_fr:"Tafsir par thème à travers le Coran",est_correcte:true},{texte_fr:"Tafsir d'une sourate",est_correcte:false},{texte_fr:"Tafsir verset par verset",est_correcte:false},{texte_fr:"Lecture rapide",est_correcte:false}] },
  { domaine:'tafsir', niveau:5, texte_fr:"Quels sont les outils linguistiques du Tafsir classique ?", texte_ar:'ما أدوات التفسير اللغوي؟', explication:"Connaissance de l'arabe classique, de la poésie pré-islamique (jahili), du nahw (grammaire), de la balagha (rhétorique), et des dialectes arabes anciens.", reponses:[{texte_fr:"Arabe classique, poésie jahili, nahw, balagha",est_correcte:true},{texte_fr:"Latin uniquement",est_correcte:false},{texte_fr:"Persan",est_correcte:false},{texte_fr:"Aucun outil",est_correcte:false}] },

  // ========== AKHLAQ N1 (+5) ==========
  { domaine:'akhlaq', niveau:1, texte_fr:"Qui est ton voisin selon le hadith ?", texte_ar:'من جارك في الحديث؟', explication:"Le Prophète ﷺ a dit : « 40 maisons à droite, 40 à gauche, 40 devant et 40 derrière. »", dalil_ref:"al-Adab al-Mufrad", reponses:[{texte_fr:"Les 40 maisons autour, dans chaque direction",est_correcte:true},{texte_fr:"La maison juste à côté",est_correcte:false},{texte_fr:"Aucun voisin spécifique",est_correcte:false},{texte_fr:"La même tribu",est_correcte:false}] },
  { domaine:'akhlaq', niveau:1, texte_fr:"Que dit l'islam sur la propreté ?", texte_ar:'ما يقول الإسلام عن النظافة؟', explication:"« La propreté fait partie de la foi » (Sahih Muslim). L'islam encourage la pureté du corps, des vêtements, du lieu et du cœur.", dalil_ref:"Sahih Muslim n°223", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Elle fait partie de la foi",est_correcte:true},{texte_fr:"Sans importance",est_correcte:false},{texte_fr:"Réservée aux savants",est_correcte:false},{texte_fr:"Obligatoire 1 fois par an",est_correcte:false}] },
  { domaine:'akhlaq', niveau:1, texte_fr:"Comment doit-on saluer en islam ?", texte_ar:'كيف يكون السلام في الإسلام؟', explication:"« Assalamu 'alaykum wa rahmatullah wa barakatuh » — la formule la plus complète. Répondre par « Wa 'alaykum as-salam... » avec mieux ou semblable.", dalil_ref:"Sourate An-Nisa 4:86", reponses:[{texte_fr:"Assalamu 'alaykum wa rahmatullah",est_correcte:true},{texte_fr:"Bonjour seulement",est_correcte:false},{texte_fr:"Aucun salut",est_correcte:false},{texte_fr:"Sourire uniquement",est_correcte:false}] },
  { domaine:'akhlaq', niveau:1, texte_fr:"Qu'est-ce que la véracité (Sidq) ?", texte_ar:'ما الصدق؟', explication:"Dire la vérité dans tous les domaines. Le Prophète ﷺ : « La véracité mène à la piété, et la piété au Paradis. »", dalil_ref:"Sahih al-Bukhari n°6094", reponses:[{texte_fr:"Dire la vérité partout",est_correcte:true},{texte_fr:"Mentir quand nécessaire",est_correcte:false},{texte_fr:"Cacher la vérité",est_correcte:false},{texte_fr:"Réservée aux saints",est_correcte:false}] },
  { domaine:'akhlaq', niveau:1, texte_fr:"Que dit l'islam sur la générosité ?", texte_ar:'ما يقول الإسلام عن الكرم؟', explication:"Le Prophète ﷺ : « Le généreux est proche d'Allah, du Paradis et des gens. L'avare est éloigné d'Allah et proche de l'Enfer. »", dalil_ref:"Sunan at-Tirmidhi n°1961", grade_hadith:"Hadith Hasan", reponses:[{texte_fr:"Proche d'Allah, du Paradis et des gens",est_correcte:true},{texte_fr:"Sans importance",est_correcte:false},{texte_fr:"Réservée aux riches",est_correcte:false},{texte_fr:"Synonyme d'extravagance",est_correcte:false}] },

  // ========== AKHLAQ N2 (+1), N3 (+12) ==========
  { domaine:'akhlaq', niveau:2, texte_fr:"Que dit le Prophète ﷺ sur la colère ?", texte_ar:'ما قول النبي ﷺ عن الغضب؟', explication:"Un homme demanda un conseil. Le Prophète ﷺ répéta 3 fois : « Ne te mets pas en colère. » Maîtriser la colère est signe de force.", dalil_ref:"Sahih al-Bukhari n°6116", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"« Ne te mets pas en colère » répété 3 fois",est_correcte:true},{texte_fr:"Recommandée fréquente",est_correcte:false},{texte_fr:"Signe de virilité",est_correcte:false},{texte_fr:"Naturelle, sans effort",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quel est le devoir envers les voisins juifs ou chrétiens ?", texte_ar:'ما حق الجار غير المسلم؟', explication:"Le Prophète ﷺ recommandait le bon traitement même envers les voisins non-musulmans, partage de nourriture et solidarité dans le bon.", dalil_ref:"al-Adab al-Mufrad", reponses:[{texte_fr:"Bon traitement, partage, solidarité dans le bien",est_correcte:true},{texte_fr:"Ignorance totale",est_correcte:false},{texte_fr:"Hostilité",est_correcte:false},{texte_fr:"Conversion forcée",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Qu'est-ce que la « Salat as-Sila » (préservation des liens) ?", texte_ar:'ما صلة الرحم؟', explication:"Maintenir les liens familiaux. Le Prophète ﷺ : « Celui qui rompt les liens familiaux n'entrera pas au Paradis. »", dalil_ref:"Sahih al-Bukhari n°5984", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Maintenir liens familiaux ; rompre = pas de Paradis",est_correcte:true},{texte_fr:"Couper avec la famille",est_correcte:false},{texte_fr:"Type de prière",est_correcte:false},{texte_fr:"Sans importance",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quel est le statut de l'aumône cachée ?", texte_ar:'ما حكم الصدقة المخفية؟', explication:"Recommandée et de plus haute récompense. Allah dit : « Si vous donnez en cachette aux pauvres, c'est meilleur pour vous. » (Al-Baqara 2:271)", dalil_ref:"Sourate Al-Baqara 2:271", reponses:[{texte_fr:"Meilleure que l'aumône publique",est_correcte:true},{texte_fr:"Interdite",est_correcte:false},{texte_fr:"Égale à publique",est_correcte:false},{texte_fr:"Moins méritoire",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quel est le statut de l'aumône visible ?", texte_ar:'ما حكم الصدقة الظاهرة؟', explication:"Permise et utile pour encourager d'autres au don. Allah ne mentionne pas seulement la cachée. Mais attention à la riya' (ostentation).", reponses:[{texte_fr:"Permise et utile pour inspirer, attention à la riya'",est_correcte:true},{texte_fr:"Interdite",est_correcte:false},{texte_fr:"Toujours préférable",est_correcte:false},{texte_fr:"Obligatoire",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Que dit l'islam sur le mensonge plaisanté ?", texte_ar:'ما حكم الكذب على سبيل المزاح؟', explication:"Interdit. Le Prophète ﷺ a dit : « Malheur à celui qui parle en mentant pour faire rire les gens. Malheur à lui ! Malheur à lui ! »", dalil_ref:"Sunan at-Tirmidhi n°2315", grade_hadith:"Hadith Hasan", reponses:[{texte_fr:"Interdit (malheur à celui qui le fait)",est_correcte:true},{texte_fr:"Permis",est_correcte:false},{texte_fr:"Recommandé",est_correcte:false},{texte_fr:"Obligatoire entre amis",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quelle est l'attitude correcte envers la maladie ?", texte_ar:'ما الموقف الصحيح من المرض؟', explication:"Patience et recherche de guérison. Le Prophète ﷺ : « Aucune souffrance n'atteint le croyant — même un piqûre — sans qu'Allah n'efface ses péchés. »", dalil_ref:"Sahih al-Bukhari n°5641", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Patience et recherche de guérison ; efface les péchés",est_correcte:true},{texte_fr:"Désespoir",est_correcte:false},{texte_fr:"Refus de soins",est_correcte:false},{texte_fr:"Punition à accepter passivement",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quel est le statut de l'orphelin en islam ?", texte_ar:'ما حق اليتيم؟', explication:"Statut très valorisé. « Moi et le tuteur d'un orphelin serons comme ces deux (doigts) au Paradis. » Le Prophète ﷺ caressait leur tête. Leurs biens sont sacrés.", dalil_ref:"Sahih al-Bukhari n°6005", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Très valorisé ; le tuteur au Paradis près du Prophète",est_correcte:true},{texte_fr:"Statut inférieur",est_correcte:false},{texte_fr:"À éviter",est_correcte:false},{texte_fr:"Sans droits",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Qu'est-ce que le Tabarruj (parure ostentatoire) ?", texte_ar:'ما هو التبرج؟', explication:"Pour la femme : étalage de sa parure ou de sa beauté hors du cadre légal. Interdit. Allah dit : « Ne vous parez pas comme se paraient les femmes de l'ère pré-islamique. » (Al-Ahzab 33:33)", dalil_ref:"Sourate Al-Ahzab 33:33", reponses:[{texte_fr:"Étalage hors cadre légal — interdit",est_correcte:true},{texte_fr:"Recommandé",est_correcte:false},{texte_fr:"Obligatoire pour la jeunesse",est_correcte:false},{texte_fr:"Sans avis",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Que dit le Prophète ﷺ sur l'humeur souriante ?", texte_ar:'ما قول النبي ﷺ في طلاقة الوجه؟', explication:"« Ne méprise aucune bonne action, même rencontrer ton frère avec un visage souriant. »", dalil_ref:"Sahih Muslim n°2626", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Visage souriant = bonne action récompensée",est_correcte:true},{texte_fr:"Réservé aux jeunes",est_correcte:false},{texte_fr:"Sans importance",est_correcte:false},{texte_fr:"Inadapté aux pieux",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Quel est le droit du chemin selon le hadith ?", texte_ar:'ما حقوق الطريق؟', explication:"Le Prophète ﷺ : « Si vous tenez assemblée sur le chemin, donnez-lui ses droits : baisser le regard, ne pas nuire, répondre au salut, commander le bien, interdire le mal. »", dalil_ref:"Sahih al-Bukhari n°2465", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Baisser regard, ne pas nuire, saluer, commander bien",est_correcte:true},{texte_fr:"Aucun droit",est_correcte:false},{texte_fr:"Construire à l'extérieur",est_correcte:false},{texte_fr:"Réservé aux savants",est_correcte:false}] },
  { domaine:'akhlaq', niveau:3, texte_fr:"Qu'est-ce que la générosité du Prophète ﷺ ?", texte_ar:'كيف كان كرم النبي ﷺ؟', explication:"Ibn Abbas : « Le Prophète ﷺ était le plus généreux des hommes. Il l'était encore plus en Ramadan quand Jibril le rencontrait pour réviser le Coran. »", dalil_ref:"Sahih al-Bukhari n°6", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Plus généreux des hommes, encore plus en Ramadan",est_correcte:true},{texte_fr:"Avare",est_correcte:false},{texte_fr:"Indifférent",est_correcte:false},{texte_fr:"Donnait peu",est_correcte:false}] },

  // ========== AQIDA N1 (+1), N2 (+3), N3 (+7) ==========
  { domaine:'aqida', niveau:1, texte_fr:"Allah a-t-il un fils ou un associé ?", texte_ar:'هل لله ولد أو شريك؟', explication:"« Dis : Il est Allah, Unique. Allah, le Soutien Absolu. Il n'a jamais engendré, n'a pas été engendré non plus, et nul n'est égal à Lui. » (Al-Ikhlas)", dalil_ref:"Sourate Al-Ikhlas 112", reponses:[{texte_fr:"Non, ni fils ni associé",est_correcte:true},{texte_fr:"Oui, plusieurs",est_correcte:false},{texte_fr:"Personne ne sait",est_correcte:false},{texte_fr:"3 personnes en Lui",est_correcte:false}] },
  { domaine:'aqida', niveau:2, texte_fr:"Quelle est la première chose obligatoire de connaître ?", texte_ar:'ما أول الواجبات؟', explication:"La connaissance de qui est ton Seigneur, quelle est ta religion, qui est ton Prophète. C'est la base de la responsabilité religieuse.", reponses:[{texte_fr:"Connaître Seigneur, religion, Prophète",est_correcte:true},{texte_fr:"Mémoriser le Coran",est_correcte:false},{texte_fr:"Apprendre l'arabe",est_correcte:false},{texte_fr:"Visiter La Mecque",est_correcte:false}] },
  { domaine:'aqida', niveau:2, texte_fr:"Qu'est-ce que la « 'Ubudiyya » ?", texte_ar:'ما العبودية؟', explication:"L'adoration totale d'Allah par soumission, amour, humilité, accomplissement de Ses ordres et évitement de Ses interdictions. Plus profond que la simple 'ibada.", reponses:[{texte_fr:"Adoration totale par soumission, amour, humilité",est_correcte:true},{texte_fr:"Esclavage humain",est_correcte:false},{texte_fr:"Travail forcé",est_correcte:false},{texte_fr:"Vie monacale",est_correcte:false}] },
  { domaine:'aqida', niveau:2, texte_fr:"Quelle est la différence entre Islam et Iman ?", texte_ar:'ما الفرق بين الإسلام والإيمان؟', explication:"Islam = soumission extérieure (les 5 piliers). Iman = foi du cœur (les 6 piliers). Quand ils sont mentionnés ensemble, l'islam = actes, l'iman = croyances. Séparés, ils signifient l'ensemble.", dalil_ref:"Sahih Muslim n°8 (Hadith de Jibril)", reponses:[{texte_fr:"Islam = actes, Iman = croyance du cœur",est_correcte:true},{texte_fr:"Identiques toujours",est_correcte:false},{texte_fr:"Opposés",est_correcte:false},{texte_fr:"Synonymes en arabe ancien",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que sont les Ahlu Sunnah par opposition aux Khawarij ?", texte_ar:'الفرق بين أهل السنة والخوارج؟', explication:"Khawarij = sectaires qui qualifient les pécheurs majeurs de mécréants. Ahlu Sunnah maintiennent qu'un musulman pécheur reste musulman, sa foi diminue mais ne disparaît pas.", reponses:[{texte_fr:"Sunnites : pécheur reste musulman ; Khawarij : devient mécréant",est_correcte:true},{texte_fr:"Identiques",est_correcte:false},{texte_fr:"Khawarij = Ahlu Sunnah",est_correcte:false},{texte_fr:"Sunnites sectaires",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que dit le Coran sur les anges porteurs du Trône ?", texte_ar:'ما تقول الآية عن حملة العرش؟', explication:"« Ceux qui portent le Trône et ceux qui l'entourent célèbrent la louange de leur Seigneur. » (Ghafir 40:7). 8 anges porteurs au Jour du Jugement (al-Haqqa 69:17).", dalil_ref:"Sourate Ghafir 40:7 ; Al-Haqqa 69:17", reponses:[{texte_fr:"Anges porteurs et entourant le Trône d'Allah",est_correcte:true},{texte_fr:"N'existent pas",est_correcte:false},{texte_fr:"Métaphores",est_correcte:false},{texte_fr:"Humains glorifiés",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que dit l'aqida sur les rêves véridiques ?", texte_ar:'ما حكم الرؤيا الصادقة؟', explication:"Le Prophète ﷺ : « La bonne vision est la 46e partie de la prophétie. » Les rêves véridiques proviennent d'Allah. Les rêves troublants proviennent de Shaytan.", dalil_ref:"Sahih al-Bukhari n°6983", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"46e partie de la prophétie ; les bonnes viennent d'Allah",est_correcte:true},{texte_fr:"Inventions",est_correcte:false},{texte_fr:"Toujours vraies",est_correcte:false},{texte_fr:"Toujours fausses",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que faire face à un rêve troublant ?", texte_ar:'ماذا يفعل من رأى رؤيا مزعجة؟', explication:"Le Prophète ﷺ : « Cracher 3 fois à sa gauche, demander la protection d'Allah contre Shaytan et le mal qu'il a vu, changer de côté et ne pas en parler. »", dalil_ref:"Sahih Muslim n°2261", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Cracher 3 fois à gauche, isti'adha, changer de côté, ne pas en parler",est_correcte:true},{texte_fr:"En parler à tout le monde",est_correcte:false},{texte_fr:"Croire à sa réalisation",est_correcte:false},{texte_fr:"Consulter un voyant",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Quels sont les 5 piliers de la foi en Allah ?", texte_ar:'ما أركان الإيمان بالله؟', explication:"Croire en : 1) Son existence, 2) Sa Seigneurie, 3) Sa divinité unique, 4) Ses Noms et Attributs, 5) Ne rien Lui associer.", reponses:[{texte_fr:"Existence, Seigneurie, divinité, Noms/Attributs, non-association",est_correcte:true},{texte_fr:"Salat, Zakat, Sawm, Hajj, Shahada",est_correcte:false},{texte_fr:"Foi, action, intention, sincérité, suivi",est_correcte:false},{texte_fr:"Aucun pilier",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que signifie l'expression « Innama al-A'mal bin-Niyat » ?", texte_ar:'ما معنى إنما الأعمال بالنيات؟', explication:"« Les actions ne valent que par les intentions. » 1er hadith de Sahih al-Bukhari. Fondement de l'aqida : la valeur d'une œuvre dépend de l'intention.", dalil_ref:"Sahih al-Bukhari n°1", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Valeur d'une œuvre = son intention",est_correcte:true},{texte_fr:"L'action seule compte",est_correcte:false},{texte_fr:"Intention sans action suffit",est_correcte:false},{texte_fr:"Sans rapport avec aqida",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Qu'est-ce que la « Mahabba » d'Allah envers le serviteur ?", texte_ar:'ما محبة الله للعبد؟', explication:"Attribut d'Allah confirmé par le Coran : « Allah aime les pieux » (3:76), « Allah aime les patients » (3:146), etc. Vraie réalité, pas simple récompense.", reponses:[{texte_fr:"Amour réel d'Allah pour Ses serviteurs pieux",est_correcte:true},{texte_fr:"Métaphore vide",est_correcte:false},{texte_fr:"Synonyme de récompense seulement",est_correcte:false},{texte_fr:"Inexistant",est_correcte:false}] },

  // ========== HADITH N1 (+8), N2 (+6), N3 (+9), N4 (+13) ==========
  { domaine:'hadith', niveau:1, texte_fr:"Comment doit-on traiter un hadith authentique ?", texte_ar:'كيف نتعامل مع الحديث الصحيح؟', explication:"L'appliquer et y croire. Le Coran ordonne : « Ce que le Messager vous donne, prenez-le ; ce qu'il vous interdit, abstenez-vous-en. » (Al-Hashr 59:7)", dalil_ref:"Sourate Al-Hashr 59:7", reponses:[{texte_fr:"L'appliquer et y croire",est_correcte:true},{texte_fr:"L'ignorer",est_correcte:false},{texte_fr:"Le critiquer",est_correcte:false},{texte_fr:"Le tester",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qu'est-ce qu'un Compagnon (Sahabi) ?", texte_ar:'من هو الصحابي؟', explication:"Celui qui a rencontré le Prophète ﷺ étant croyant et est mort musulman, même s'il n'a passé qu'un moment avec lui.", dalil_ref:"al-Isaba d'Ibn Hajar", reponses:[{texte_fr:"Celui qui rencontra le Prophète croyant et mourut musulman",est_correcte:true},{texte_fr:"Tout musulman ancien",est_correcte:false},{texte_fr:"Sa famille seule",est_correcte:false},{texte_fr:"Les 4 califes",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qu'est-ce qu'un Tabi'i ?", texte_ar:'من هو التابعي؟', explication:"Celui qui a rencontré un Compagnon étant musulman et est mort musulman, sans avoir rencontré le Prophète ﷺ. Génération après les Sahaba.", reponses:[{texte_fr:"Qui a rencontré un Sahabi croyant",est_correcte:true},{texte_fr:"Qui a rencontré le Prophète",est_correcte:false},{texte_fr:"Un calife",est_correcte:false},{texte_fr:"Un imam",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Que veut dire « Sallallahu 'alayhi wa sallam » ?", texte_ar:'ما معنى صلى الله عليه وسلم؟', explication:"« Qu'Allah lui accorde la grâce et la paix. » Salutation à invoquer après mention du Prophète ﷺ, recommandée chaque fois qu'on l'évoque.", dalil_ref:"Sourate Al-Ahzab 33:56", reponses:[{texte_fr:"Qu'Allah lui accorde grâce et paix",est_correcte:true},{texte_fr:"Adieu",est_correcte:false},{texte_fr:"Bonjour",est_correcte:false},{texte_fr:"Sans sens particulier",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Que signifie « radiAllahu 'anhu » après un nom de Sahabi ?", texte_ar:'ما معنى رضي الله عنه؟', explication:"« Qu'Allah l'agrée. » Salutation à dire après mentionner un Compagnon ou une Compagnonne (« 'anha » pour femme), signe de respect.", reponses:[{texte_fr:"Qu'Allah l'agrée",est_correcte:true},{texte_fr:"Qu'il soit content",est_correcte:false},{texte_fr:"Bienvenue",est_correcte:false},{texte_fr:"Adieu",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel hadith parle de la sincérité (Ikhlas) ?", texte_ar:'ما حديث الإخلاص؟', explication:"« Les actions ne valent que par les intentions, et à chaque personne ce qu'elle a eu pour intention. » Premier hadith des Arba'in d'an-Nawawi.", dalil_ref:"Sahih al-Bukhari n°1 ; Muslim n°1907", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Les actions par les intentions",est_correcte:true},{texte_fr:"L'argent suffit",est_correcte:false},{texte_fr:"L'apparence compte",est_correcte:false},{texte_fr:"Sans rapport",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quelle est la durée du Prophète ﷺ comme dernier prophète selon le hadith ?", texte_ar:'هل النبي ﷺ خاتم الأنبياء؟', explication:"« Je suis le sceau des prophètes » (Khatam an-Nabiyyin). Aucun prophète ne viendra après lui. Confirmé par Coran (33:40) et hadith mutawatir.", dalil_ref:"Sourate Al-Ahzab 33:40", reponses:[{texte_fr:"Oui, le sceau (Khatam) — aucun prophète après lui",est_correcte:true},{texte_fr:"Non, d'autres viendront",est_correcte:false},{texte_fr:"Il sera réincarné",est_correcte:false},{texte_fr:"Position inconnue",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel est le hadith le plus court ?", texte_ar:'ما أقصر حديث؟', explication:"De nombreux courts existent : « La haya' fa-la imana » (Pas de pudeur, pas de foi). « As-Salatu khayrun min an-nawm » (La prière vaut mieux que le sommeil), etc.", reponses:[{texte_fr:"Plusieurs très courts existent",est_correcte:true},{texte_fr:"Aucun court",est_correcte:false},{texte_fr:"Tous longs",est_correcte:false},{texte_fr:"Inconnu",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Que signifie « Mutawatir » dans la classification ?", texte_ar:'ما معنى المتواتر؟', explication:"Rapporté à chaque génération par un nombre rendant impossible l'entente sur un mensonge. Donne certitude absolue (yaqin).", reponses:[{texte_fr:"Rapporté par un nombre impossible à concerter",est_correcte:true},{texte_fr:"Rapporté une seule fois",est_correcte:false},{texte_fr:"Rapporté par les rois",est_correcte:false},{texte_fr:"Hadith inventé",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Combien de hadiths le Prophète ﷺ a-t-il rapportés en chiffres absolus ?", texte_ar:'كم عدد أحاديث النبي ﷺ تقريباً؟', explication:"On estime à environ 30 000 à 50 000 hadiths authentiques (sans répétitions). Bukhari a sélectionné 7000 parmi 600 000 rumeurs/hadiths.", reponses:[{texte_fr:"~30-50 000 authentiques",est_correcte:true},{texte_fr:"3 hadiths",est_correcte:false},{texte_fr:"100",est_correcte:false},{texte_fr:"Aucun",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Combien d'hommes ont rapporté plus de 1000 hadiths ?", texte_ar:'كم صحابياً روى أكثر من ألف حديث؟', explication:"7 Compagnons : Abu Hurayra (5374), Ibn Umar (2630), Anas (2286), Aïcha (2210), Ibn Abbas (1660), Jabir (1540), Abu Sa'id al-Khudri (1170). Le « Muksiruna ».", reponses:[{texte_fr:"7 Compagnons (Muksiruna)",est_correcte:true},{texte_fr:"1 seul",est_correcte:false},{texte_fr:"100 Compagnons",est_correcte:false},{texte_fr:"Aucun",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Quel imam classait systématiquement Sahih/Hasan/Da'if ?", texte_ar:'من الإمام الذي صنف الأحاديث؟', explication:"At-Tirmidhi (209-279 H) dans ses Sunan. C'est lui qui a institutionnalisé l'usage de ces termes pour chaque hadith.", reponses:[{texte_fr:"At-Tirmidhi",est_correcte:true},{texte_fr:"Bukhari uniquement",est_correcte:false},{texte_fr:"Abu Dawud",est_correcte:false},{texte_fr:"Ibn Majah",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Qu'est-ce qu'une « Sunna 'Amaliyya » ?", texte_ar:'ما السنة العملية؟', explication:"Sunnah pratique : actions du Prophète ﷺ. Différente de la Sunna Qawliyya (paroles) et Taqririyya (approbations tacites).", reponses:[{texte_fr:"Sunnah pratique : actes du Prophète",est_correcte:true},{texte_fr:"Hadith court",est_correcte:false},{texte_fr:"Hadith abrogé",est_correcte:false},{texte_fr:"Hadith inventé",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Combien de catégories y a-t-il de Sunnah selon les types ?", texte_ar:'كم أقسام السنة؟', explication:"3 : Qawliyya (paroles), Fi'liyya/'Amaliyya (actes), Taqririyya (approbations tacites — quand il voyait un acte et ne le réprimandait pas).", reponses:[{texte_fr:"Qawliyya, Fi'liyya, Taqririyya",est_correcte:true},{texte_fr:"1 seule catégorie",est_correcte:false},{texte_fr:"10 catégories",est_correcte:false},{texte_fr:"Inconnu",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce que le Sahihayn ?", texte_ar:'ما الصحيحان؟', explication:"« Les deux Sahih » : Sahih al-Bukhari et Sahih Muslim. Considérés par consensus comme les deux ouvrages les plus authentiques après le Coran.", reponses:[{texte_fr:"Bukhari et Muslim",est_correcte:true},{texte_fr:"Bukhari et Tirmidhi",est_correcte:false},{texte_fr:"Muslim et Abu Dawud",est_correcte:false},{texte_fr:"Bukhari et Malik",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Que signifie « Mukharrij » ?", texte_ar:'من هو المخرج؟', explication:"L'auteur d'un recueil qui « fait sortir » (yukhrij) les hadiths. Ex: Bukhari, Muslim sont les mukharrijun de leurs Sahih.", reponses:[{texte_fr:"L'auteur d'un recueil de hadiths",est_correcte:true},{texte_fr:"Le narrateur unique",est_correcte:false},{texte_fr:"Le calife",est_correcte:false},{texte_fr:"L'imam de la mosquée",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce que la Riwaya bil-Ma'na ?", texte_ar:'ما الرواية بالمعنى؟', explication:"Transmettre un hadith en gardant le sens mais avec d'autres mots. Tolérée si le narrateur connaît la langue et le sens — sinon innovation.", reponses:[{texte_fr:"Transmettre le sens avec d'autres mots (sous conditions)",est_correcte:true},{texte_fr:"Inventer un hadith",est_correcte:false},{texte_fr:"Le mémoriser exactement",est_correcte:false},{texte_fr:"Le traduire seulement",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Quels sont les recueils dits « Sunan » ?", texte_ar:'ما هي السنن الأربع؟', explication:"4 grands Sunan : Abu Dawud, Tirmidhi, Nasai, Ibn Majah. Avec Bukhari et Muslim = Kutub Sittah. Centrés sur les hadiths juridiques.", reponses:[{texte_fr:"Abu Dawud, Tirmidhi, Nasai, Ibn Majah",est_correcte:true},{texte_fr:"Bukhari et Muslim",est_correcte:false},{texte_fr:"Muwatta seul",est_correcte:false},{texte_fr:"Musnad seul",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce que le « Musannaf » ?", texte_ar:'ما المصنف؟', explication:"Recueil de hadiths classés par sujets (fiqh, aqida, etc.). Les célèbres : Musannaf 'Abd ar-Razzaq et Musannaf Ibn Abi Shayba — antérieurs aux Sahihayn.", reponses:[{texte_fr:"Recueil classé par sujets",est_correcte:true},{texte_fr:"Recueil par narrateur",est_correcte:false},{texte_fr:"Livre d'histoire",est_correcte:false},{texte_fr:"Recueil de poésie",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce que le « Musnad » ?", texte_ar:'ما المسند؟', explication:"Recueil classé par Compagnon. Le Musnad d'Ahmad est le plus célèbre (~27 000 hadiths organisés par Sahabi).", reponses:[{texte_fr:"Recueil classé par Compagnon",est_correcte:true},{texte_fr:"Recueil par sujet",est_correcte:false},{texte_fr:"Tafsir",est_correcte:false},{texte_fr:"Fiqh",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Combien y a-t-il de hadiths dans Musnad Ahmad ?", texte_ar:'كم حديثاً في مسند أحمد؟', explication:"Environ 27 000 hadiths organisés par Compagnon. Énorme volume contenant Sahih, Hasan et même certains faibles.", reponses:[{texte_fr:"~27 000 hadiths",est_correcte:true},{texte_fr:"100",est_correcte:false},{texte_fr:"1000",est_correcte:false},{texte_fr:"100 000",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Que signifie le terme « Muhaddith » ?", texte_ar:'من هو المحدث؟', explication:"Savant spécialisé dans le hadith : sa transmission, son authentification, ses sciences (mustalah, rijal, ilal, etc.). Doit avoir mémoire vaste.", reponses:[{texte_fr:"Savant spécialiste des hadiths",est_correcte:true},{texte_fr:"Récitateur du Coran",est_correcte:false},{texte_fr:"Juriste",est_correcte:false},{texte_fr:"Calife",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Quel est le statut du hadith chez Ahlu Sunnah comme source ?", texte_ar:'ما مكانة الحديث عند أهل السنة؟', explication:"2e source après le Coran. Sa Sunnah authentique a le même statut juridique que le Coran : « Ce que le Messager vous donne, prenez-le. » (59:7)", dalil_ref:"Sourate Al-Hashr 59:7", reponses:[{texte_fr:"2e source après le Coran, même statut juridique",est_correcte:true},{texte_fr:"Source mineure",est_correcte:false},{texte_fr:"Non-source",est_correcte:false},{texte_fr:"Au-dessus du Coran",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Quelle est la différence entre Sahih li-dhatih et Sahih li-ghayrih ?", texte_ar:'ما الفرق بين الصحيح لذاته ولغيره؟', explication:"Li-dhatih = par lui-même (5 conditions remplies). Li-ghayrih = un Hasan élevé au rang de Sahih grâce à plusieurs chaînes corroboratives (mutaba'at).", reponses:[{texte_fr:"Authentique par soi vs par plusieurs chaînes",est_correcte:true},{texte_fr:"Identiques",est_correcte:false},{texte_fr:"Bukhari vs Muslim",est_correcte:false},{texte_fr:"Anciens vs récents",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que la Tahmil (transmission) ?", texte_ar:'ما هي طرق التحمل في الحديث؟', explication:"8 modes : Sama' (entendre), Qira'a (lire devant le maître), Ijaza, Munawala, Kitaba, I'lam, Wasiyya, Wijada. Les 2 premiers sont les plus fiables.", reponses:[{texte_fr:"8 modes : sama', qira'a, ijaza, etc.",est_correcte:true},{texte_fr:"1 seule façon",est_correcte:false},{texte_fr:"Inconnu",est_correcte:false},{texte_fr:"Sans règle",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que les Mukhtalif al-Hadith ?", texte_ar:'ما مختلف الحديث؟', explication:"Hadiths apparemment contradictoires. Science visant à les réconcilier (jam') ou à appliquer l'abrogation, le tarjih, ou le tawaqquf. Discipline complexe.", reponses:[{texte_fr:"Hadiths apparemment contradictoires à concilier",est_correcte:true},{texte_fr:"Hadiths inventés",est_correcte:false},{texte_fr:"Faux hadiths",est_correcte:false},{texte_fr:"Hadiths courts",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Que sont les « Asbab Wurud al-Hadith » ?", texte_ar:'ما أسباب ورود الحديث؟', explication:"Circonstances de la formulation d'un hadith. Comme les Asbab an-Nuzul pour le Coran. Aide à comprendre le contexte et le sens.", reponses:[{texte_fr:"Circonstances de la formulation du hadith",est_correcte:true},{texte_fr:"Causes de chute",est_correcte:false},{texte_fr:"Lieu de naissance",est_correcte:false},{texte_fr:"Sans rapport",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Quel est le nom complet d'al-Bukhari ?", texte_ar:'ما اسم البخاري الكامل؟', explication:"Muhammad ibn Isma'il ibn Ibrahim al-Bukhari (194-256 H). Né à Boukhara (Ouzbékistan actuel). Mort à Khartank près de Samarcande.", reponses:[{texte_fr:"Muhammad ibn Isma'il al-Bukhari",est_correcte:true},{texte_fr:"Muslim ibn al-Hajjaj",est_correcte:false},{texte_fr:"Abu Hurayra",est_correcte:false},{texte_fr:"Ibn Hibban",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que le « Talkhis al-Habir » d'Ibn Hajar ?", texte_ar:'ما تلخيص الحبير؟', explication:"Œuvre majeure d'Ibn Hajar al-Asqalani (773-852 H) sur les hadiths cités par ar-Rafi'i dans son traité de fiqh shafi'ite. Référence en takhrij.", reponses:[{texte_fr:"Œuvre d'Ibn Hajar sur takhrij des hadiths d'ar-Rafi'i",est_correcte:true},{texte_fr:"Sunan abrégé",est_correcte:false},{texte_fr:"Tafsir",est_correcte:false},{texte_fr:"Recueil de sira",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que le « Takhrij » des hadiths ?", texte_ar:'ما تخريج الأحاديث؟', explication:"Science d'identifier les sources d'un hadith : qui l'a rapporté, dans quel livre, dans quelle chaîne, etc. Indispensable pour l'authentification.", reponses:[{texte_fr:"Science d'identifier sources et chaînes d'un hadith",est_correcte:true},{texte_fr:"Inventer des hadiths",est_correcte:false},{texte_fr:"Mémoriser des hadiths",est_correcte:false},{texte_fr:"Critiquer les sahaba",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Que sont les « Awwaliyyat as-Sajistani » et autres compendiums ?", texte_ar:'ما الأوائل؟', explication:"Recueils des « premières » paroles d'un narrateur ou de hadiths historiques. Outils du muhaddith pour traquer les chaînes les plus élevées.", reponses:[{texte_fr:"Recueils des premières paroles/chaînes hautes",est_correcte:true},{texte_fr:"Premiers califes",est_correcte:false},{texte_fr:"Premières sourates",est_correcte:false},{texte_fr:"Premières batailles",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Que signifie l'expression « Hadithun Mutaba'an » ?", texte_ar:'ما الحديث المتابع؟', explication:"Hadith ayant un appui (mutaba'a) : un autre narrateur a rapporté un hadith similaire à un même niveau de la chaîne, soutenant la version originale.", reponses:[{texte_fr:"Hadith ayant un autre rapporteur de soutien",est_correcte:true},{texte_fr:"Hadith isolé",est_correcte:false},{texte_fr:"Hadith inventé",est_correcte:false},{texte_fr:"Hadith long",est_correcte:false}] },

  // ========== FIQH N5 (+14) ==========
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que la qiyas (analogie) en usul al-fiqh ?", texte_ar:'ما القياس في أصول الفقه؟', explication:"Étendre un jugement d'un cas existant à un cas similaire par cause commune ('illa). 4e source du fiqh chez la majorité. Refusée par les Dhahirites.", reponses:[{texte_fr:"Étendre un jugement par cause commune",est_correcte:true},{texte_fr:"Innovation",est_correcte:false},{texte_fr:"Opinion libre",est_correcte:false},{texte_fr:"Devine",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que l'Istihsan (préférence juridique) ?", texte_ar:'ما الاستحسان؟', explication:"Méthode juridique d'Abu Hanifa : passer d'un qiyas apparent à un qiyas caché plus juste, ou s'écarter du qiyas par texte ou nécessité. Rejetée par Shafi'i.", reponses:[{texte_fr:"Préférer un qiyas caché ou un texte particulier",est_correcte:true},{texte_fr:"Sans règle",est_correcte:false},{texte_fr:"Innovation",est_correcte:false},{texte_fr:"Refus de la sunnah",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que la Maslaha Mursala ?", texte_ar:'ما المصلحة المرسلة؟', explication:"Considérer un intérêt général non couvert par un texte explicite. Source du fiqh malékite. Compilation du Coran par Abu Bakr en est un exemple.", reponses:[{texte_fr:"Intérêt général non couvert par texte explicite",est_correcte:true},{texte_fr:"Innovation libre",est_correcte:false},{texte_fr:"Opinion personnelle",est_correcte:false},{texte_fr:"Refus de la sunnah",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que le Sadd adh-Dhara'i' ?", texte_ar:'ما سد الذرائع؟', explication:"« Bloquer les moyens » : interdire ce qui mène au mal même si ce moyen est licite en soi. Ex: interdire la khalwa (isolement avec étranger) pour bloquer le zina.", reponses:[{texte_fr:"Interdire ce qui mène au mal",est_correcte:true},{texte_fr:"Construire des barrages",est_correcte:false},{texte_fr:"Interdire le commerce",est_correcte:false},{texte_fr:"Ouvrir les portes",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que la « 'Urf » (coutume) en fiqh ?", texte_ar:'ما العرف في الفقه؟', explication:"Coutume sociale acceptée. Source secondaire du fiqh : peut influencer les détails de l'application (ex: ce qui constitue un « repas convenable » dans une expiation).", reponses:[{texte_fr:"Coutume sociale comme source secondaire",est_correcte:true},{texte_fr:"Innovation principale",est_correcte:false},{texte_fr:"Loi suprême",est_correcte:false},{texte_fr:"Sans valeur",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que l'Ijtihad ?", texte_ar:'ما الاجتهاد؟', explication:"Effort de déduire un jugement juridique des textes par celui qui a les qualifications. Requiert connaissance approfondie du Coran, Sunnah, arabe, usul.", reponses:[{texte_fr:"Effort qualifié de déduction juridique",est_correcte:true},{texte_fr:"Opinion sans étude",est_correcte:false},{texte_fr:"Imitation aveugle",est_correcte:false},{texte_fr:"Refus du fiqh",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que le Taqlid (imitation d'un madhab) ?", texte_ar:'ما التقليد في المذاهب؟', explication:"Suivre l'avis d'un mujtahid sans connaître la preuve. Acceptable pour le non-savant ; le savant doit chercher la preuve.", reponses:[{texte_fr:"Suivre un mujtahid sans connaître la preuve",est_correcte:true},{texte_fr:"Innovation",est_correcte:false},{texte_fr:"Interdit toujours",est_correcte:false},{texte_fr:"Obligatoire pour tous",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Quelle est la position sur le passage entre les madhabs (talfiq) ?", texte_ar:'ما حكم التلفيق بين المذاهب؟', explication:"Combiner les avis de plusieurs madhabs dans un même acte. Toléré si fondé sur la preuve et sans manipulation pour la facilité. Refusé si c'est par caprice.", reponses:[{texte_fr:"Toléré si fondé sur la preuve",est_correcte:true},{texte_fr:"Toujours interdit",est_correcte:false},{texte_fr:"Toujours obligatoire",est_correcte:false},{texte_fr:"Refus des madhabs",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Que sont les Maqasid as-Shariah ?", texte_ar:'ما مقاصد الشريعة؟', explication:"Objectifs supérieurs de la Loi divine : préserver religion, vie, raison, descendance, biens. Toute règle vise un ou plusieurs.", dalil_ref:"al-Muwafaqat d'ash-Shatibi", reponses:[{texte_fr:"Préservation : religion, vie, raison, descendance, biens",est_correcte:true},{texte_fr:"Salat, Zakat, Sawm, Hajj",est_correcte:false},{texte_fr:"Coran et Sunnah seulement",est_correcte:false},{texte_fr:"Aucun objectif",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que les Qawaid Fiqhiyya ?", texte_ar:'ما القواعد الفقهية؟', explication:"Règles juridiques générales applicables à de nombreux cas. 5 règles maîtresses : Niya, Yaqin, Mashaqqa, Darar, Adah.", dalil_ref:"al-Ashbah wa an-Naza'ir d'as-Suyuti", reponses:[{texte_fr:"5 règles maîtresses : Niya, Yaqin, Mashaqqa, Darar, Adah",est_correcte:true},{texte_fr:"5 prières",est_correcte:false},{texte_fr:"Aucune règle",est_correcte:false},{texte_fr:"4 madhabs",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Que signifie la règle « ad-Darar yuzal » ?", texte_ar:'ما قاعدة الضرر يزال؟', explication:"« Le préjudice doit être écarté. » Allah ne légifère pas ce qui nuit. Fondement de nombreuses règles : annulation de contrat lésionnaire, divorce pour préjudice, etc.", reponses:[{texte_fr:"Le préjudice doit être écarté",est_correcte:true},{texte_fr:"Tout est permis",est_correcte:false},{texte_fr:"Tout est interdit",est_correcte:false},{texte_fr:"Sans règle",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Quelle est la règle « al-Yaqin la yazulu bi-sh-shakk » ?", texte_ar:'ما قاعدة اليقين لا يزول بالشك؟', explication:"« La certitude n'est pas annulée par le doute. » Si on est sûr d'avoir fait wudu et qu'on doute de l'avoir rompu, on reste en wudu. Vaste application.", reponses:[{texte_fr:"La certitude prévaut sur le doute",est_correcte:true},{texte_fr:"Le doute prévaut toujours",est_correcte:false},{texte_fr:"Sans règle",est_correcte:false},{texte_fr:"Refus de la sunnah",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que la « 'Ada Muhakkama » ?", texte_ar:'ما العادة محكمة؟', explication:"« La coutume est considérée comme un arbitre. » Quand un texte ne précise pas, la coutume locale détermine (ex: ce qui est un « repas convenable »).", reponses:[{texte_fr:"La coutume sert d'arbitre",est_correcte:true},{texte_fr:"Coutume innovation",est_correcte:false},{texte_fr:"Coutume interdite",est_correcte:false},{texte_fr:"Sans rapport",est_correcte:false}] },
  { domaine:'fiqh', niveau:5, texte_fr:"Qu'est-ce que le Fiqh al-Aqalliyyat ?", texte_ar:'ما فقه الأقليات؟', explication:"Branche moderne du fiqh traitant les questions spécifiques aux musulmans minoritaires (en Occident notamment). Approche tenant compte du contexte tout en restant fidèle aux principes.", reponses:[{texte_fr:"Fiqh des minorités musulmanes en contexte non-musulman",est_correcte:true},{texte_fr:"Fiqh ancien abrogé",est_correcte:false},{texte_fr:"Fiqh inventé",est_correcte:false},{texte_fr:"Refus du fiqh",est_correcte:false}] },
];

export async function seedQuestionsCombler4(client: Client): Promise<void> {
  console.log('Seeding lot 4 (Sirah/Tafsir/Akhlaq/Aqida/Hadith/Fiqh — combler final)...');
  let inserted = 0; let skipped = 0;
  for (const q of Q) {
    const exists = await client.query('SELECT id FROM questions WHERE texte_fr = $1', [q.texte_fr]);
    if (exists.rows.length > 0) { skipped++; continue; }
    const r = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, explication, grade_hadith, statut) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'valide') RETURNING id`,
      [q.domaine, q.sous_domaine ?? null, q.niveau, 'general', q.texte_fr, q.texte_ar ?? null, q.dalil_ref ?? null, q.explication, q.grade_hadith ?? null]
    );
    const id = r.rows[0].id;
    for (const rep of q.reponses) {
      await client.query(`INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte) VALUES ($1,$2,$3,$4)`, [id, rep.texte_fr, rep.texte_ar ?? null, rep.est_correcte]);
    }
    inserted++;
  }
  console.log(`Combler4: ${inserted} inserted, ${skipped} skipped.`);
}

if (require.main === module) {
  const { Client } = require('pg');
  const c = new Client({ connectionString: process.env.DATABASE_URL });
  c.connect().then(async () => { await seedQuestionsCombler4(c); await c.end(); }).catch((e: unknown) => { console.error(e); process.exit(1); });
}
