import { Client } from 'pg';

interface Q {
  domaine: string;
  niveau: number;
  texte_fr: string;
  texte_ar?: string;
  explication: string;
  dalil_ref?: string;
  grade_hadith?: string;
  sous_domaine?: string;
  reponses: { texte_fr: string; texte_ar?: string; est_correcte: boolean }[];
}

const Q: Q[] = [
  // ===== HADITH N1 =====
  { domaine:'hadith', niveau:1, texte_fr:"Qu'est-ce qu'un hadith ?", texte_ar:'ما هو الحديث؟', explication:"Un hadith est une parole, un acte ou une approbation attribués au Prophète ﷺ.", dalil_ref:"Mustalah al-Hadith", reponses:[{texte_fr:"Parole, acte ou approbation du Prophète ﷺ",est_correcte:true},{texte_fr:"Un verset du Coran",est_correcte:false},{texte_fr:"Une parole d'un savant",est_correcte:false},{texte_fr:"Un poème arabe",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel est le livre de hadith le plus authentique après le Coran ?", texte_ar:'ما هو أصح كتاب بعد القرآن؟', explication:"Sahih al-Bukhari est considéré par consensus comme le livre le plus authentique après le Coran.", dalil_ref:"Consensus des savants", reponses:[{texte_fr:"Sahih al-Bukhari",est_correcte:true},{texte_fr:"Sunan Abi Dawud",est_correcte:false},{texte_fr:"Muwatta de Malik",est_correcte:false},{texte_fr:"Musnad d'Ahmad",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel est le deuxième livre de hadith le plus authentique ?", texte_ar:'ما هو ثاني أصح كتاب في الحديث؟', explication:"Sahih Muslim vient juste après al-Bukhari en degré d'authenticité.", dalil_ref:"Consensus des savants", reponses:[{texte_fr:"Sahih Muslim",est_correcte:true},{texte_fr:"Sunan at-Tirmidhi",est_correcte:false},{texte_fr:"Sunan an-Nasai",est_correcte:false},{texte_fr:"Sunan Ibn Majah",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qui sont les Sahaba ?", texte_ar:'من هم الصحابة؟', explication:"Les Sahaba sont ceux qui ont rencontré le Prophète ﷺ en étant croyants et sont morts musulmans.", dalil_ref:"al-Isaba d'Ibn Hajar", reponses:[{texte_fr:"Ceux qui ont rencontré le Prophète ﷺ en croyants et morts musulmans",est_correcte:true},{texte_fr:"Tous ceux qui ont vu le Prophète ﷺ",est_correcte:false},{texte_fr:"Sa famille uniquement",est_correcte:false},{texte_fr:"Les 4 califes seulement",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Combien y a-t-il de Kutub as-Sittah (les 6 livres de hadith) ?", texte_ar:'كم عدد الكتب الستة في الحديث؟', explication:"Les 6 livres sont : Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasai, Ibn Majah.", dalil_ref:"Tradition académique sunnite", reponses:[{texte_fr:"6 livres",est_correcte:true},{texte_fr:"4 livres",est_correcte:false},{texte_fr:"10 livres",est_correcte:false},{texte_fr:"2 livres",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel compagnon a rapporté le plus de hadiths ?", texte_ar:'أي صحابي روى أكثر الأحاديث؟', explication:"Abu Hurayra رضي الله عنه a rapporté 5374 hadiths, le plus parmi tous les Sahaba.", dalil_ref:"Tabaqat al-Muhaddithin", reponses:[{texte_fr:"Abu Hurayra",est_correcte:true},{texte_fr:"Aïcha",est_correcte:false},{texte_fr:"Anas ibn Malik",est_correcte:false},{texte_fr:"Abdullah ibn Umar",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qu'est-ce qu'un Hadith Sahih ?", texte_ar:'ما هو الحديث الصحيح؟', explication:"Un hadith authentique dont la chaîne de transmission est ininterrompue avec des narrateurs intègres et précis, sans irrégularité.", dalil_ref:"Mustalah al-Hadith", reponses:[{texte_fr:"Hadith authentique avec chaîne ininterrompue de narrateurs fiables",est_correcte:true},{texte_fr:"Hadith long",est_correcte:false},{texte_fr:"Hadith rapporté par le calife",est_correcte:false},{texte_fr:"Hadith en arabe classique",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel est le premier hadith de Sahih al-Bukhari ?", texte_ar:'ما هو أول حديث في صحيح البخاري؟', explication:"« Les actions ne valent que par les intentions » (إنما الأعمال بالنيات) rapporté par Umar ibn al-Khattab.", dalil_ref:'Sahih al-Bukhari n°1', grade_hadith:'Hadith Sahih', reponses:[{texte_fr:"Les actions ne valent que par les intentions",est_correcte:true},{texte_fr:"Cherchez la science même en Chine",est_correcte:false},{texte_fr:"La propreté fait partie de la foi",est_correcte:false},{texte_fr:"Le paradis est sous les pieds des mères",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Que veut dire « Rapporté par al-Bukhari et Muslim » (Muttafaqun alayh) ?", texte_ar:'ما معنى متفق عليه؟', explication:"Cela signifie que le hadith est rapporté à la fois par al-Bukhari et Muslim, c'est le plus haut degré d'authenticité.", reponses:[{texte_fr:"Rapporté par les deux Sahih (Bukhari et Muslim)",est_correcte:true},{texte_fr:"Accepté par tous les madhabs",est_correcte:false},{texte_fr:"Rapporté plus de 100 fois",est_correcte:false},{texte_fr:"Mentionné dans le Coran",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qu'est-ce qu'un Hadith Qudsi ?", texte_ar:'ما هو الحديث القدسي؟', explication:"Un hadith où le Prophète ﷺ rapporte une parole d'Allah dont le sens vient d'Allah mais les mots du Prophète. Différent du Coran qui est mots et sens d'Allah.", reponses:[{texte_fr:"Parole d'Allah dont les mots viennent du Prophète ﷺ",est_correcte:true},{texte_fr:"Verset du Coran",est_correcte:false},{texte_fr:"Hadith très court",est_correcte:false},{texte_fr:"Hadith révélé à Médine",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Quel est le grade d'un Hadith Da'if ?", texte_ar:'ما درجة الحديث الضعيف؟', explication:"Da'if signifie « faible » : la chaîne de transmission contient un défaut (narrateur peu fiable, rupture, etc.). Il ne sert pas de preuve dans les questions juridiques.", reponses:[{texte_fr:"Faible : chaîne défectueuse, ne sert pas de preuve",est_correcte:true},{texte_fr:"Authentique sans défaut",est_correcte:false},{texte_fr:"Plus authentique que Sahih",est_correcte:false},{texte_fr:"Hadith mémorisé par tous",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qui était la Mère des Croyants la plus jeune ayant rapporté beaucoup de hadiths ?", texte_ar:'من هي أم المؤمنين التي روت كثيراً من الأحاديث؟', explication:"Aïcha رضي الله عنها a rapporté 2210 hadiths, étant la plus jeune épouse du Prophète ﷺ et la plus savante.", reponses:[{texte_fr:"Aïcha",est_correcte:true},{texte_fr:"Khadija",est_correcte:false},{texte_fr:"Hafsa",est_correcte:false},{texte_fr:"Umm Salama",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Qu'est-ce que la Sunnah ?", texte_ar:'ما هي السنة؟', explication:"La Sunnah désigne tout ce qui est rapporté du Prophète ﷺ : paroles, actes, approbations, descriptions. C'est la 2e source de l'islam après le Coran.", reponses:[{texte_fr:"Tout ce qui vient du Prophète ﷺ : paroles, actes, approbations",est_correcte:true},{texte_fr:"Les coutumes arabes",est_correcte:false},{texte_fr:"Les recommandations du calife",est_correcte:false},{texte_fr:"Les rites surérogatoires uniquement",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"L'auteur de Sahih Muslim s'appelle ?", texte_ar:'من مؤلف صحيح مسلم؟', explication:"Muslim ibn al-Hajjaj an-Naysaburi (206-261 H), élève de l'Imam al-Bukhari.", reponses:[{texte_fr:"Muslim ibn al-Hajjaj an-Naysaburi",est_correcte:true},{texte_fr:"Muhammad ibn Ismail al-Bukhari",est_correcte:false},{texte_fr:"Malik ibn Anas",est_correcte:false},{texte_fr:"Abu Hanifa",est_correcte:false}] },
  { domaine:'hadith', niveau:1, texte_fr:"Combien de hadiths environ contient Sahih al-Bukhari ?", texte_ar:'كم حديثاً في صحيح البخاري؟', explication:"Environ 7275 hadiths avec répétitions, et 2602 sans répétitions, sélectionnés parmi 600 000.", reponses:[{texte_fr:"Environ 7275 avec répétitions",est_correcte:true},{texte_fr:"100 hadiths",est_correcte:false},{texte_fr:"50 000 hadiths",est_correcte:false},{texte_fr:"1000 hadiths",est_correcte:false}] },

  // ===== HADITH N2 =====
  { domaine:'hadith', niveau:2, texte_fr:"Que signifie « Isnad » ?", texte_ar:'ما معنى الإسناد؟', explication:"L'Isnad est la chaîne de transmission des narrateurs : « Untel m'a rapporté de untel de untel... du Prophète ﷺ ». C'est unique à l'islam.", reponses:[{texte_fr:"Chaîne de transmission des narrateurs",est_correcte:true},{texte_fr:"Le texte du hadith",est_correcte:false},{texte_fr:"Le sujet du hadith",est_correcte:false},{texte_fr:"Le commentateur du hadith",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Que signifie « Matn » ?", texte_ar:'ما معنى المتن؟', explication:"Le Matn est le texte même du hadith (après l'Isnad), c'est-à-dire la parole rapportée du Prophète ﷺ.", reponses:[{texte_fr:"Le texte du hadith après la chaîne",est_correcte:true},{texte_fr:"La chaîne des narrateurs",est_correcte:false},{texte_fr:"Le commentaire du savant",est_correcte:false},{texte_fr:"La traduction du hadith",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"L'auteur des Sunan at-Tirmidhi est ?", texte_ar:'من مؤلف سنن الترمذي؟', explication:"Muhammad ibn Isa at-Tirmidhi (209-279 H), élève d'al-Bukhari, est connu pour son classement Sahih/Hasan/Da'if.", reponses:[{texte_fr:"Muhammad ibn Isa at-Tirmidhi",est_correcte:true},{texte_fr:"Abu Dawud as-Sijistani",est_correcte:false},{texte_fr:"Ahmad ibn Hanbal",est_correcte:false},{texte_fr:"Ibn Majah",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Combien de hadiths environ contient Sahih Muslim ?", texte_ar:'كم حديثاً في صحيح مسلم؟', explication:"Environ 7563 hadiths avec répétitions, sélectionnés parmi 300 000 collectés par Muslim.", reponses:[{texte_fr:"Environ 7563 avec répétitions",est_correcte:true},{texte_fr:"200 hadiths",est_correcte:false},{texte_fr:"100 000 hadiths",est_correcte:false},{texte_fr:"500 hadiths",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Qu'est-ce qu'un hadith Marfu' ?", texte_ar:'ما الحديث المرفوع؟', explication:"Hadith dont la chaîne remonte explicitement jusqu'au Prophète ﷺ (parole ou action attribuées à lui).", reponses:[{texte_fr:"Hadith attribué explicitement au Prophète ﷺ",est_correcte:true},{texte_fr:"Parole d'un Compagnon",est_correcte:false},{texte_fr:"Parole d'un Tabi'i",est_correcte:false},{texte_fr:"Hadith sans chaîne",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Qu'est-ce qu'un hadith Mawquf ?", texte_ar:'ما الحديث الموقوف؟', explication:"Hadith dont la chaîne s'arrête à un Compagnon (parole ou action attribuées au Sahabi sans remonter au Prophète).", reponses:[{texte_fr:"Parole attribuée à un Compagnon (s'arrête à lui)",est_correcte:true},{texte_fr:"Parole du Prophète ﷺ",est_correcte:false},{texte_fr:"Parole d'un Imam",est_correcte:false},{texte_fr:"Hadith inventé",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Qu'est-ce qu'un hadith Maqtu' ?", texte_ar:'ما الحديث المقطوع؟', explication:"Hadith dont la chaîne s'arrête à un Tabi'i (parole ou action d'un successeur des Compagnons).", reponses:[{texte_fr:"Parole attribuée à un Tabi'i",est_correcte:true},{texte_fr:"Parole d'un Compagnon",est_correcte:false},{texte_fr:"Parole du Prophète ﷺ",est_correcte:false},{texte_fr:"Hadith abrogé",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"L'auteur de Sunan Abi Dawud est ?", texte_ar:'من مؤلف سنن أبي داود؟', explication:"Sulayman ibn al-Ash'ath as-Sijistani (202-275 H), spécialisé dans les hadiths juridiques (ahkam).", reponses:[{texte_fr:"Abu Dawud as-Sijistani",est_correcte:true},{texte_fr:"al-Bukhari",est_correcte:false},{texte_fr:"at-Tirmidhi",est_correcte:false},{texte_fr:"an-Nasai",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Qu'est-ce que le Muwatta ?", texte_ar:'ما هو الموطأ؟', explication:"Le Muwatta de l'Imam Malik (93-179 H) est le plus ancien recueil de hadiths classés par chapitres juridiques, incluant aussi les pratiques de Médine.", reponses:[{texte_fr:"Recueil de l'Imam Malik, le plus ancien classé par fiqh",est_correcte:true},{texte_fr:"Livre de Bukhari",est_correcte:false},{texte_fr:"Tafsir du Coran",est_correcte:false},{texte_fr:"Sira du Prophète",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Qu'est-ce que le Musnad d'Ahmad ?", texte_ar:'ما هو مسند أحمد؟', explication:"Recueil de l'Imam Ahmad ibn Hanbal (164-241 H) contenant ~27 000 hadiths organisés par Compagnons (musnad).", reponses:[{texte_fr:"Recueil d'Ahmad ibn Hanbal organisé par Compagnons",est_correcte:true},{texte_fr:"Livre d'histoire",est_correcte:false},{texte_fr:"Tafsir court",est_correcte:false},{texte_fr:"Manuel de fiqh",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"L'auteur de Sunan an-Nasai est ?", texte_ar:'من مؤلف سنن النسائي؟', explication:"Ahmad ibn Shu'ayb an-Nasai (215-303 H), connu pour la rigueur de sa critique des narrateurs.", reponses:[{texte_fr:"Ahmad ibn Shu'ayb an-Nasai",est_correcte:true},{texte_fr:"Abu Dawud",est_correcte:false},{texte_fr:"Ibn Majah",est_correcte:false},{texte_fr:"at-Tirmidhi",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Quel hadith dit : « Quiconque ment volontairement sur moi qu'il prépare sa place en Enfer » ?", texte_ar:'ما حكم الكذب على النبي ﷺ؟', explication:"Hadith Mutawatir rapporté par plus de 70 Compagnons. Mentir sur le Prophète ﷺ est un péché majeur menant au feu de l'Enfer.", dalil_ref:"Sahih al-Bukhari n°110 ; Muslim", grade_hadith:"Hadith Mutawatir", reponses:[{texte_fr:"Préparer sa place en Enfer",est_correcte:true},{texte_fr:"Payer une amende",est_correcte:false},{texte_fr:"Être pardonné facilement",est_correcte:false},{texte_fr:"Recevoir une récompense",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Que sont les 40 hadiths de l'Imam an-Nawawi ?", texte_ar:'ما هي الأربعون النووية؟', explication:"Recueil de 42 hadiths fondamentaux compilés par an-Nawawi (631-676 H), couvrant les bases de la religion. Très étudié dans l'enseignement islamique.", reponses:[{texte_fr:"Recueil de 42 hadiths fondamentaux de an-Nawawi",est_correcte:true},{texte_fr:"40 versets du Coran",est_correcte:false},{texte_fr:"Histoire de 40 prophètes",est_correcte:false},{texte_fr:"40 règles de fiqh",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"L'auteur de Riyad as-Salihin est ?", texte_ar:'من مؤلف رياض الصالحين؟', explication:"Yahya ibn Sharaf an-Nawawi (631-676 H). Il compila ce recueil de hadiths sur l'éthique islamique.", reponses:[{texte_fr:"Imam an-Nawawi",est_correcte:true},{texte_fr:"Ibn Taymiyya",est_correcte:false},{texte_fr:"al-Ghazali",est_correcte:false},{texte_fr:"al-Bukhari",est_correcte:false}] },
  { domaine:'hadith', niveau:2, texte_fr:"Que signifie « Ijaza » en sciences du hadith ?", texte_ar:'ما هي الإجازة في علم الحديث؟', explication:"L'Ijaza est l'autorisation donnée par un maître à un élève de transmettre les hadiths/livres qu'il a appris de lui.", reponses:[{texte_fr:"Autorisation maître→élève de transmettre",est_correcte:true},{texte_fr:"Diplôme universitaire moderne",est_correcte:false},{texte_fr:"Salaire du muhaddith",est_correcte:false},{texte_fr:"Voyage pour collecter",est_correcte:false}] },

  // ===== HADITH N3 =====
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'un hadith Munqati' ?", texte_ar:'ما الحديث المنقطع؟', explication:"Hadith dont la chaîne présente une rupture (un narrateur manquant) entre les Sahaba et les Tabi'in ou plus tard.", reponses:[{texte_fr:"Hadith dont la chaîne a une rupture",est_correcte:true},{texte_fr:"Hadith très authentique",est_correcte:false},{texte_fr:"Hadith très long",est_correcte:false},{texte_fr:"Hadith abrogé",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'un hadith Mursal ?", texte_ar:'ما الحديث المرسل؟', explication:"Hadith rapporté directement du Prophète ﷺ par un Tabi'i sans mentionner le Compagnon intermédiaire. Considéré comme faible chez la majorité.", reponses:[{texte_fr:"Hadith d'un Tabi'i sans Compagnon intermédiaire",est_correcte:true},{texte_fr:"Hadith authentique de Bukhari",est_correcte:false},{texte_fr:"Hadith rapporté oralement",est_correcte:false},{texte_fr:"Hadith en arabe ancien",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'un hadith Mu'allaq ?", texte_ar:'ما الحديث المعلق؟', explication:"Hadith dont une partie du début de la chaîne (un ou plusieurs narrateurs après le compilateur) est omise. Bukhari en mentionne dans son Sahih.", reponses:[{texte_fr:"Hadith dont une partie de la chaîne est omise au début",est_correcte:true},{texte_fr:"Hadith pendu au mur",est_correcte:false},{texte_fr:"Hadith inventé",est_correcte:false},{texte_fr:"Hadith mutawatir",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'un hadith Mawdu' ?", texte_ar:'ما الحديث الموضوع؟', explication:"Hadith inventé, faussement attribué au Prophète ﷺ. Il est interdit de le transmettre sauf pour avertir.", reponses:[{texte_fr:"Hadith inventé, faussement attribué",est_correcte:true},{texte_fr:"Hadith faible mais utilisable",est_correcte:false},{texte_fr:"Hadith authentique",est_correcte:false},{texte_fr:"Hadith oublié",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Quels sont les 5 critères d'authenticité d'un hadith ?", texte_ar:'ما هي شروط الحديث الصحيح الخمسة؟', explication:"1) Chaîne ininterrompue, 2) Intégrité (adala) de chaque narrateur, 3) Précision (dabt), 4) Absence d'irrégularité (shadh), 5) Absence de défaut caché (illa).", reponses:[{texte_fr:"Continuité, intégrité, précision, absence d'irrégularité et de défaut",est_correcte:true},{texte_fr:"Longueur, beauté, popularité",est_correcte:false},{texte_fr:"Présence dans Bukhari uniquement",est_correcte:false},{texte_fr:"Approbation des 4 madhabs",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qui sont les 4 imams ayant compilé les Sunan principaux après Tirmidhi et Abu Dawud ?", texte_ar:'من أصحاب الكتب الأربعة بعد البخاري ومسلم؟', explication:"Les Sunan de : Abu Dawud, at-Tirmidhi, an-Nasai, Ibn Majah forment avec Bukhari et Muslim les Kutub as-Sitta.", reponses:[{texte_fr:"Abu Dawud, Tirmidhi, Nasai, Ibn Majah",est_correcte:true},{texte_fr:"Bukhari, Muslim, Malik, Ahmad",est_correcte:false},{texte_fr:"Bayhaqi, Hakim, Tabarani, Daraqutni",est_correcte:false},{texte_fr:"Les 4 califes",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'al-Jarh wa at-Ta'dil ?", texte_ar:'ما علم الجرح والتعديل؟', explication:"Science d'évaluation des narrateurs : « jarh » = critique d'un narrateur, « ta'dil » = sa réhabilitation/validation. Indispensable pour authentifier un hadith.", reponses:[{texte_fr:"Science d'évaluation et critique des narrateurs",est_correcte:true},{texte_fr:"Science de récitation",est_correcte:false},{texte_fr:"Science du tajwid",est_correcte:false},{texte_fr:"Comparaison des madhabs",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Quelle est la différence entre un Sahih li-dhatih et un Sahih li-ghayrih ?", texte_ar:'ما الفرق بين الصحيح لذاته والصحيح لغيره؟', explication:"Le Sahih li-dhatih est authentique par lui-même (5 conditions remplies). Le Sahih li-ghayrih est un Hasan élevé au rang de Sahih grâce à plusieurs chaînes corroboratives.", reponses:[{texte_fr:"L'un est sahih par lui-même, l'autre par appui d'autres chaînes",est_correcte:true},{texte_fr:"L'un de Bukhari, l'autre de Muslim",est_correcte:false},{texte_fr:"L'un en arabe, l'autre en perse",est_correcte:false},{texte_fr:"Aucune différence",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Que sont les Mustadrak ?", texte_ar:'ما هي المستدركات؟', explication:"Recueils rassemblant des hadiths conformes aux critères de Bukhari et/ou Muslim mais qu'ils n'ont pas inclus. Le plus célèbre est al-Mustadrak d'al-Hakim.", reponses:[{texte_fr:"Recueils de hadiths conformes à Bukhari/Muslim non inclus chez eux",est_correcte:true},{texte_fr:"Recueils de hadiths inventés",est_correcte:false},{texte_fr:"Livres de tafsir",est_correcte:false},{texte_fr:"Livres de jurisprudence",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Quelle est la position des 4 imams sur le hadith Da'if ?", texte_ar:'ما حكم العمل بالحديث الضعيف؟', explication:"La majorité accepte de l'utiliser uniquement dans les vertus (fada'il) sous 3 conditions strictes (Ibn Hajar). Il ne sert jamais à établir une obligation ou interdiction.", reponses:[{texte_fr:"Toléré dans les vertus sous conditions, jamais pour ahkam",est_correcte:true},{texte_fr:"Totalement rejeté",est_correcte:false},{texte_fr:"Égal au Sahih",est_correcte:false},{texte_fr:"Préféré au Sahih",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'un hadith Aziz ?", texte_ar:'ما الحديث العزيز؟', explication:"Hadith rapporté par exactement deux narrateurs à chaque génération. Vient entre Mashhur (3+) et Gharib (1).", reponses:[{texte_fr:"Hadith rapporté par 2 narrateurs à chaque génération",est_correcte:true},{texte_fr:"Hadith très précieux",est_correcte:false},{texte_fr:"Hadith rare",est_correcte:false},{texte_fr:"Hadith d'un Compagnon noble",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qu'est-ce qu'un hadith Mashhur ?", texte_ar:'ما الحديث المشهور؟', explication:"Hadith rapporté par 3 narrateurs ou plus à chaque génération, sans atteindre le degré de Mutawatir.", reponses:[{texte_fr:"Hadith rapporté par 3+ narrateurs par génération",est_correcte:true},{texte_fr:"Hadith le plus populaire",est_correcte:false},{texte_fr:"Hadith célèbre uniquement chez les gens",est_correcte:false},{texte_fr:"Hadith mentionné une fois",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Que signifie « 'An'ana » dans un isnad ?", texte_ar:'ما معنى العنعنة في السند؟', explication:"L'utilisation du mot « 'an » (de) pour indiquer la transmission. Ex: « Fulan 'an Fulan » — accepté si les narrateurs étaient contemporains et qu'il n'y a pas de tadlis.", reponses:[{texte_fr:"Transmission par « 'an » (de) entre narrateurs",est_correcte:true},{texte_fr:"Chanter le hadith",est_correcte:false},{texte_fr:"Répéter trois fois",est_correcte:false},{texte_fr:"Écrire le hadith",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Qui est l'auteur du Sahih d'Ibn Hibban ?", texte_ar:'من مؤلف صحيح ابن حبان؟', explication:"Muhammad ibn Hibban al-Busti (270-354 H), élève d'an-Nasai. Son Sahih contient des conditions différentes des Sahihayn.", reponses:[{texte_fr:"Ibn Hibban al-Busti",est_correcte:true},{texte_fr:"Ibn Khuzayma",est_correcte:false},{texte_fr:"al-Hakim",est_correcte:false},{texte_fr:"al-Bayhaqi",est_correcte:false}] },
  { domaine:'hadith', niveau:3, texte_fr:"Que signifie « Muttafaqun 'alayh » ?", texte_ar:'ما معنى متفق عليه؟', explication:"Hadith rapporté par les deux Sahih (Bukhari et Muslim) avec la même chaîne. Plus haut degré d'authenticité après les Mutawatir.", reponses:[{texte_fr:"Rapporté par Bukhari ET Muslim avec même chaîne",est_correcte:true},{texte_fr:"Accepté par les 4 madhabs",est_correcte:false},{texte_fr:"Connu de toute la oumma",est_correcte:false},{texte_fr:"Cité dans le Coran",est_correcte:false}] },

  // ===== HADITH N4 (compléter à 30) =====
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que la science du Rijal al-Hadith ?", texte_ar:'ما علم رجال الحديث؟', explication:"Science biographique des narrateurs : leur vie, fiabilité, défauts, contemporanéité. Sans elle, impossible d'authentifier un hadith.", reponses:[{texte_fr:"Biographies et critique des narrateurs",est_correcte:true},{texte_fr:"Histoire des califes",est_correcte:false},{texte_fr:"Généalogie des Arabes",est_correcte:false},{texte_fr:"Vie du Prophète ﷺ",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qui est Yahya ibn Ma'in ?", texte_ar:'من هو يحيى بن معين؟', explication:"Yahya ibn Ma'in (158-233 H), grand critique des narrateurs (jarh wa ta'dil), professeur d'Ahmad ibn Hanbal. On disait : « S'il dit qu'un narrateur est faible, il l'est. »", reponses:[{texte_fr:"Grand critique des narrateurs, prof d'Ahmad",est_correcte:true},{texte_fr:"Calife abbasside",est_correcte:false},{texte_fr:"Auteur d'un Sahih",est_correcte:false},{texte_fr:"Imam de prière à Médine",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Que sont les Sunan al-Kubra d'al-Bayhaqi ?", texte_ar:'ما هي السنن الكبرى للبيهقي؟', explication:"Vaste recueil de hadiths juridiques d'al-Bayhaqi (384-458 H), shafi'ite. Référence majeure pour le fiqh basé sur hadith.", reponses:[{texte_fr:"Vaste recueil juridique d'al-Bayhaqi",est_correcte:true},{texte_fr:"Livre de tafsir",est_correcte:false},{texte_fr:"Recueil d'invocations",est_correcte:false},{texte_fr:"Histoire islamique",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que le Tadlis ?", texte_ar:'ما هو التدليس؟', explication:"Dissimulation : un narrateur omet de nommer un intermédiaire faible. Les muhaddithun classent les mudallis en plusieurs catégories selon la gravité.", reponses:[{texte_fr:"Dissimulation d'un intermédiaire faible dans l'isnad",est_correcte:true},{texte_fr:"Faire l'éloge du Prophète ﷺ",est_correcte:false},{texte_fr:"Réciter à voix haute",est_correcte:false},{texte_fr:"Mémoriser le Coran",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Que sont les Mu'jam at-Tabarani ?", texte_ar:'ما هي معاجم الطبراني؟', explication:"Trois recueils d'al-Tabarani (260-360 H) : al-Kabir (par Compagnons), al-Awsat, as-Saghir. Vaste source mais comprend des hadiths faibles.", reponses:[{texte_fr:"3 recueils d'at-Tabarani (Kabir, Awsat, Saghir)",est_correcte:true},{texte_fr:"Dictionnaires de la langue arabe",est_correcte:false},{texte_fr:"Index du Coran",est_correcte:false},{texte_fr:"Livres de tafsir",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Quels sont les Six Livres (al-Sittah) reconnus en Sunnite ?", texte_ar:'ما الكتب الستة عند أهل السنة؟', explication:"Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasai, Ibn Majah. Certains substituent Ibn Majah par le Muwatta de Malik.", reponses:[{texte_fr:"Bukhari, Muslim, Abu Dawud, Tirmidhi, Nasai, Ibn Majah",est_correcte:true},{texte_fr:"6 livres de tafsir",est_correcte:false},{texte_fr:"6 recueils de Médine",est_correcte:false},{texte_fr:"6 livres des califes",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce qu'un hadith Shadh ?", texte_ar:'ما الحديث الشاذ؟', explication:"Hadith rapporté par un narrateur fiable mais contredisant un autre plus fiable. Classé faible malgré la fiabilité de son narrateur.", reponses:[{texte_fr:"Hadith d'un fiable contredisant un plus fiable",est_correcte:true},{texte_fr:"Hadith bizarre",est_correcte:false},{texte_fr:"Hadith oublié",est_correcte:false},{texte_fr:"Hadith authentique",est_correcte:false}] },
  { domaine:'hadith', niveau:4, texte_fr:"Qu'est-ce que les Sahihayn ?", texte_ar:'ما المقصود بالصحيحين؟', explication:"« Les deux Sahih » : Sahih al-Bukhari et Sahih Muslim. Considérés par consensus comme les deux livres les plus authentiques après le Coran.", reponses:[{texte_fr:"Sahih al-Bukhari et Sahih Muslim",est_correcte:true},{texte_fr:"Bukhari et Tirmidhi",est_correcte:false},{texte_fr:"Muslim et Abu Dawud",est_correcte:false},{texte_fr:"Bukhari et Malik",est_correcte:false}] },

  // ===== AQIDA N1 (compléter à 30) =====
  { domaine:'aqida', niveau:1, texte_fr:"Combien y a-t-il de piliers de la foi (Iman) ?", texte_ar:'كم عدد أركان الإيمان؟', explication:"Six : croire en Allah, Ses anges, Ses livres, Ses messagers, le Jour dernier, et au Qadar (bon ou mauvais).", dalil_ref:"Sahih Muslim n°8 (Hadith de Jibril)", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"6 piliers",est_correcte:true},{texte_fr:"5 piliers",est_correcte:false},{texte_fr:"7 piliers",est_correcte:false},{texte_fr:"3 piliers",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Combien y a-t-il de piliers de l'islam ?", texte_ar:'كم عدد أركان الإسلام؟', explication:"Cinq : Shahada, Salat, Zakat, Sawm de Ramadan, Hajj pour qui peut.", dalil_ref:"Sahih al-Bukhari n°8", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"5 piliers",est_correcte:true},{texte_fr:"6 piliers",est_correcte:false},{texte_fr:"4 piliers",est_correcte:false},{texte_fr:"10 piliers",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Qui est notre Seigneur ?", texte_ar:'من ربك؟', explication:"Notre Seigneur est Allah, l'unique Créateur, Pourvoyeur et Maître de tout l'univers.", reponses:[{texte_fr:"Allah",est_correcte:true},{texte_fr:"Le soleil",est_correcte:false},{texte_fr:"Les anges",est_correcte:false},{texte_fr:"Le Prophète ﷺ",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Quelle est notre religion ?", texte_ar:'ما دينك؟', explication:"L'Islam : la soumission à Allah Seul, sans Lui associer quoi que ce soit.", reponses:[{texte_fr:"L'Islam",est_correcte:true},{texte_fr:"Le judaïsme",est_correcte:false},{texte_fr:"Le christianisme",est_correcte:false},{texte_fr:"Le paganisme",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Qui est notre Prophète ?", texte_ar:'من نبيك؟', explication:"Muhammad ibn Abdullah ﷺ, le dernier des Prophètes, envoyé à toute l'humanité.", reponses:[{texte_fr:"Muhammad ibn Abdullah ﷺ",est_correcte:true},{texte_fr:"Moïse",est_correcte:false},{texte_fr:"Abraham",est_correcte:false},{texte_fr:"Adam",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Combien y a-t-il de divinité(s) digne(s) d'adoration ?", texte_ar:'كم إلهاً يستحق العبادة؟', explication:"Une seule : Allah. C'est le sens de « La ilaha illa Allah » — nul ne mérite l'adoration en dehors d'Allah.", dalil_ref:"Sourate Al-Ikhlas 112:1", reponses:[{texte_fr:"Une seule : Allah",est_correcte:true},{texte_fr:"Deux",est_correcte:false},{texte_fr:"Trois",est_correcte:false},{texte_fr:"Plusieurs selon les cultures",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Combien d'anges sont mentionnés nommément dans le Coran ?", texte_ar:'كم ملكاً ذكر اسمه في القرآن؟', explication:"Quatre anges sont nommés : Jibril, Mika'il, Malik (gardien de l'Enfer), et Harut et Marut.", reponses:[{texte_fr:"Jibril, Mika'il, Malik, Harut et Marut",est_correcte:true},{texte_fr:"Seulement Jibril",est_correcte:false},{texte_fr:"Dix anges",est_correcte:false},{texte_fr:"Aucun n'est nommé",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Quel ange transmettait la Révélation au Prophète ﷺ ?", texte_ar:'أي ملك كان ينزل بالوحي على النبي ﷺ؟', explication:"L'archange Jibril (Gabriel), appelé aussi « al-Ruh al-Amin » (l'Esprit fidèle).", dalil_ref:"Sourate Ash-Shu'ara 26:193", reponses:[{texte_fr:"Jibril",est_correcte:true},{texte_fr:"Mika'il",est_correcte:false},{texte_fr:"Israfil",est_correcte:false},{texte_fr:"Azra'il",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Combien de livres révélés sont mentionnés dans le Coran ?", texte_ar:'كم كتاباً سماوياً ذكر في القرآن؟', explication:"Cinq : la Torah (Moïse), l'Évangile (Jésus), les Psaumes (David), les Feuillets d'Abraham, et le Coran (Muhammad ﷺ).", reponses:[{texte_fr:"5 livres : Torah, Évangile, Psaumes, Feuillets d'Abraham, Coran",est_correcte:true},{texte_fr:"2 livres",est_correcte:false},{texte_fr:"10 livres",est_correcte:false},{texte_fr:"Aucun",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Qui est le premier Prophète ?", texte_ar:'من هو أول الأنبياء؟', explication:"Adam عليه السلام, père de l'humanité et premier homme, fut aussi le premier Prophète.", reponses:[{texte_fr:"Adam",est_correcte:true},{texte_fr:"Noé",est_correcte:false},{texte_fr:"Abraham",est_correcte:false},{texte_fr:"Moïse",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Que se passera-t-il après la mort ?", texte_ar:'ماذا يحدث بعد الموت؟', explication:"Le corps va dans la tombe (barzakh) où l'âme est interrogée. Au Jour du Jugement, tous ressusciteront pour les comptes, puis Paradis ou Enfer.", reponses:[{texte_fr:"Tombe, résurrection, jugement, paradis ou enfer",est_correcte:true},{texte_fr:"Réincarnation",est_correcte:false},{texte_fr:"Néant total",est_correcte:false},{texte_fr:"Retour terrestre",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Combien y a-t-il de paradis ?", texte_ar:'كم عدد الجنان؟', explication:"Selon plusieurs hadiths, le Paradis a 8 portes et plusieurs niveaux (Firdaws est le plus élevé). Le terme « jannat » est aussi au pluriel dans le Coran.", dalil_ref:"Sahih al-Bukhari n°3257", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Plusieurs niveaux, 8 portes",est_correcte:true},{texte_fr:"Un seul",est_correcte:false},{texte_fr:"3 paradis",est_correcte:false},{texte_fr:"100 paradis identiques",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Que veut dire « La ilaha illa Allah » ?", texte_ar:'ما معنى لا إله إلا الله؟', explication:"« Il n'y a aucune divinité méritant d'être adorée en dehors d'Allah. » C'est la profession de foi monothéiste.", reponses:[{texte_fr:"Aucune divinité ne mérite l'adoration sauf Allah",est_correcte:true},{texte_fr:"Allah n'existe pas",est_correcte:false},{texte_fr:"Il y a plusieurs dieux",est_correcte:false},{texte_fr:"Tout est dieu",est_correcte:false}] },
  { domaine:'aqida', niveau:1, texte_fr:"Combien de fois faut-il prononcer la Shahada pour entrer en islam ?", texte_ar:'كم مرة يجب نطق الشهادة لدخول الإسلام؟', explication:"Une seule fois, avec sincérité et compréhension, suffit. La Shahada englobe les deux témoignages : Allah Seul et Muhammad ﷺ Son Messager.", reponses:[{texte_fr:"Une fois avec sincérité",est_correcte:true},{texte_fr:"100 fois par jour",est_correcte:false},{texte_fr:"1000 fois",est_correcte:false},{texte_fr:"3 fois obligatoirement",est_correcte:false}] },

  // ===== AQIDA N3 =====
  { domaine:'aqida', niveau:3, texte_fr:"Quelles sont les 3 catégories du Tawhid ?", texte_ar:'ما أقسام التوحيد الثلاثة؟', explication:"1) Rububiyya (Seigneurie d'Allah dans la création et la providence), 2) Uluhiyya (Lui consacrer l'adoration), 3) Asma wa Sifat (Ses Noms et Attributs).", dalil_ref:"Sharh al-Aqida al-Wasitiyya", reponses:[{texte_fr:"Rububiyya, Uluhiyya, Asma wa Sifat",est_correcte:true},{texte_fr:"Foi, action, intention",est_correcte:false},{texte_fr:"Coran, Sunnah, Ijma",est_correcte:false},{texte_fr:"Passé, présent, futur",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Qu'est-ce que le Shirk majeur (Akbar) ?", texte_ar:'ما هو الشرك الأكبر؟', explication:"Consacrer une forme d'adoration à autre qu'Allah (invoquer les morts, se prosterner devant une idole). Il fait sortir de l'islam et n'est pas pardonné sans repentir.", dalil_ref:"Sourate An-Nisa 4:48", reponses:[{texte_fr:"Adorer autre qu'Allah, fait sortir de l'islam",est_correcte:true},{texte_fr:"Petit péché",est_correcte:false},{texte_fr:"Pardonné automatiquement",est_correcte:false},{texte_fr:"Permis exceptionnellement",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Qu'est-ce que le Shirk mineur (Asghar) ?", texte_ar:'ما هو الشرك الأصغر؟', explication:"Actes qualifiés de shirk sans faire sortir de l'islam : riya' (ostentation), jurer par autre qu'Allah, dire « si Allah veut et toi tu veux ». Reste grave.", dalil_ref:"Sunan at-Tirmidhi", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Riya', jurer par autre qu'Allah — sans sortir de l'islam",est_correcte:true},{texte_fr:"Sans gravité",est_correcte:false},{texte_fr:"Idolâtrie complète",est_correcte:false},{texte_fr:"Identique au shirk majeur",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Qu'est-ce que le Nifaq (hypocrisie) majeur ?", texte_ar:'ما النفاق الأكبر؟', explication:"Afficher l'islam extérieurement tout en mécroyant intérieurement. Le pire degré, comme Abdullah ibn Ubayy à l'époque du Prophète ﷺ. Mène à l'Enfer le plus bas.", dalil_ref:"Sourate An-Nisa 4:145", reponses:[{texte_fr:"Afficher l'islam tout en mécroyant intérieurement",est_correcte:true},{texte_fr:"Mentir parfois",est_correcte:false},{texte_fr:"Manquer une prière",est_correcte:false},{texte_fr:"Oublier l'aumône",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Quels sont les 3 signes du Nifaq pratique selon le hadith ?", texte_ar:'ما علامات المنافق الثلاث؟', explication:"« Trois signes de l'hypocrite : quand il parle il ment, quand il promet il trahit, quand on lui fait confiance il trahit. »", dalil_ref:"Sahih al-Bukhari n°33 ; Muslim n°59", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Mentir, trahir une promesse, trahir un dépôt",est_correcte:true},{texte_fr:"Manger, boire, dormir",est_correcte:false},{texte_fr:"Voyager, gagner, dépenser",est_correcte:false},{texte_fr:"Lire, écrire, parler",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Combien d'anges interrogent dans la tombe ?", texte_ar:'كم ملكاً يسأل في القبر؟', explication:"Deux anges, Munkar et Nakir, posent trois questions : Qui est ton Seigneur ? Quelle est ta religion ? Qui est ton prophète ?", dalil_ref:"Sunan at-Tirmidhi n°1071", grade_hadith:"Hadith Hasan", reponses:[{texte_fr:"2 anges : Munkar et Nakir",est_correcte:true},{texte_fr:"4 anges",est_correcte:false},{texte_fr:"1 ange",est_correcte:false},{texte_fr:"10 anges",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Quel est le sens du Tawhid ar-Rububiyya ?", texte_ar:'ما هو توحيد الربوبية؟', explication:"Reconnaître qu'Allah est l'unique Créateur, Pourvoyeur, Maître de l'univers. Même les polythéistes mecquois le reconnaissaient (Sourate Luqman 31:25).", reponses:[{texte_fr:"Allah est le seul Créateur, Pourvoyeur, Maître",est_correcte:true},{texte_fr:"Adorer Allah seul",est_correcte:false},{texte_fr:"Affirmer Ses Noms",est_correcte:false},{texte_fr:"Croire aux anges",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Quel est le sens du Tawhid al-Uluhiyya ?", texte_ar:'ما هو توحيد الألوهية؟', explication:"Consacrer toutes les formes d'adoration à Allah Seul (prière, invocation, sacrifice, vœu). C'est sur ce point qu'a porté le combat des prophètes.", reponses:[{texte_fr:"Adorer Allah Seul, sans associé",est_correcte:true},{texte_fr:"Croire en Sa seigneurie",est_correcte:false},{texte_fr:"Affirmer Ses noms",est_correcte:false},{texte_fr:"Aimer le Prophète ﷺ",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que signifie al-Wala' wa al-Bara' ?", texte_ar:'ما الولاء والبراء؟', explication:"Aimer (Wala') ce qu'Allah aime (Tawhid, croyants pieux) et se désavouer (Bara') de ce qu'Allah déteste (shirk, kufr).", dalil_ref:"Sourate Al-Mumtahana 60:4", reponses:[{texte_fr:"Aimer le Tawhid et se désavouer du shirk",est_correcte:true},{texte_fr:"Voyage et retour",est_correcte:false},{texte_fr:"Vente et achat",est_correcte:false},{texte_fr:"Naissance et mort",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Quelle est la définition du Kufr ?", texte_ar:'ما هو الكفر؟', explication:"Le Kufr est la mécréance : nier ce qui est obligatoire à croire (Allah, Ses prophètes, Ses livres). Il sort de l'islam. Peut être de croyance, parole ou acte.", reponses:[{texte_fr:"Nier ce qui est obligatoire à croire",est_correcte:true},{texte_fr:"Manquer une prière",est_correcte:false},{texte_fr:"Petit péché",est_correcte:false},{texte_fr:"Erreur involontaire",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Qu'est-ce que la Bid'a (innovation religieuse) ?", texte_ar:'ما هي البدعة؟', explication:"Introduire dans la religion ce qui n'en fait pas partie. Le Prophète ﷺ a dit : « Toute innovation est un égarement. »", dalil_ref:"Sahih Muslim n°867", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Introduire dans la religion ce qui n'y est pas",est_correcte:true},{texte_fr:"Toute nouveauté technologique",est_correcte:false},{texte_fr:"Apprendre de nouvelles langues",est_correcte:false},{texte_fr:"Construire des mosquées",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Qu'est-ce que la croyance au Jour Dernier (Yawm al-Akhir) ?", texte_ar:'ما الإيمان باليوم الآخر؟', explication:"Croire à : la mort, la tombe, la résurrection, le rassemblement, le pesage des œuvres, le pont (sirat), le Paradis et l'Enfer.", reponses:[{texte_fr:"Mort, tombe, résurrection, jugement, paradis/enfer",est_correcte:true},{texte_fr:"Seulement le paradis",est_correcte:false},{texte_fr:"Réincarnation",est_correcte:false},{texte_fr:"Néant final",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que sont les Asma al-Husna (les Beaux Noms d'Allah) ?", texte_ar:'ما الأسماء الحسنى؟', explication:"Allah a 99 Noms majestueux que celui qui les retient (les apprend, les comprend, les vit) entrera au Paradis.", dalil_ref:"Sahih al-Bukhari n°2736 ; Muslim n°2677", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"99 Noms d'Allah que celui qui les comprend entre au Paradis",est_correcte:true},{texte_fr:"99 prophètes",est_correcte:false},{texte_fr:"99 livres",est_correcte:false},{texte_fr:"99 anges",est_correcte:false}] },
  { domaine:'aqida', niveau:3, texte_fr:"Que signifie Ahlu Sunnah wal Jama'a ?", texte_ar:'ما معنى أهل السنة والجماعة؟', explication:"Les gens qui suivent la Sunnah du Prophète ﷺ et la voie des Sahaba (la jama'a). S'opposent aux sectes innovantes (Mu'tazila, Khawarij, etc.).", reponses:[{texte_fr:"Ceux qui suivent la Sunnah et la voie des Compagnons",est_correcte:true},{texte_fr:"Les chiites",est_correcte:false},{texte_fr:"Les soufis exclusivement",est_correcte:false},{texte_fr:"Les modernistes",est_correcte:false}] },

  // ===== AQIDA N4 =====
  { domaine:'aqida', niveau:4, texte_fr:"Quels sont les piliers du Tawhid al-Uluhiyya ?", texte_ar:'ما أركان توحيد الألوهية؟', explication:"Deux : la négation (« La ilaha ») de toute divinité, et l'affirmation (« illa Allah ») qu'Allah Seul mérite l'adoration.", reponses:[{texte_fr:"Négation puis affirmation",est_correcte:true},{texte_fr:"Prière et jeûne",est_correcte:false},{texte_fr:"Foi et action",est_correcte:false},{texte_fr:"Espoir et crainte",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Que signifie la règle « al-aslu fi ad-dima' wal-amwal at-tahrim » ?", texte_ar:'ما قاعدة الأصل في الدماء والأموال التحريم؟', explication:"« Le principe original concernant le sang et les biens est l'interdiction. » Ne peut être violé qu'avec preuve claire. Protection fondamentale en islam.", reponses:[{texte_fr:"Sang et biens sacrés par défaut, sauf preuve",est_correcte:true},{texte_fr:"Tout est permis par défaut",est_correcte:false},{texte_fr:"Tout est interdit par défaut",est_correcte:false},{texte_fr:"Selon les coutumes",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la croyance au Mizan (Balance) ?", texte_ar:'ما هو الإيمان بالميزان؟', explication:"Allah pèsera réellement les œuvres au Jour du Jugement. Cette balance a des plateaux. Les bonnes œuvres pèsent par leur sincérité et conformité.", dalil_ref:"Sourate Al-Anbiya 21:47", reponses:[{texte_fr:"Pesée réelle des œuvres par Allah au Jour Dernier",est_correcte:true},{texte_fr:"Symbole sans réalité",est_correcte:false},{texte_fr:"Balance terrestre",est_correcte:false},{texte_fr:"N'existe pas",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que le Sirat (le pont) ?", texte_ar:'ما هو الصراط؟', explication:"Pont placé au-dessus de l'Enfer, plus fin qu'un cheveu et plus tranchant qu'une épée. Les croyants le traversent à diverses vitesses, les autres tombent.", dalil_ref:"Sahih al-Bukhari n°7437", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Pont au-dessus de l'Enfer que tous traversent",est_correcte:true},{texte_fr:"Route vers La Mecque",est_correcte:false},{texte_fr:"Sentier de méditation",est_correcte:false},{texte_fr:"Type de prière",est_correcte:false}] },
  { domaine:'aqida', niveau:4, texte_fr:"Qu'est-ce que la Shafa'a (l'intercession) selon Ahlu Sunnah ?", texte_ar:'ما الشفاعة عند أهل السنة؟', explication:"L'intercession existe par autorisation d'Allah, sous deux conditions : Allah doit l'agréer pour l'intercesseur ET pour celui qui en bénéficie. Le Prophète ﷺ intercédera.", dalil_ref:"Sourate Al-Baqara 2:255", reponses:[{texte_fr:"Existe avec 2 conditions : agrément d'Allah pour les 2 parties",est_correcte:true},{texte_fr:"N'existe pas du tout",est_correcte:false},{texte_fr:"Tous peuvent intercéder librement",est_correcte:false},{texte_fr:"Seulement pour le Prophète ﷺ lui-même",est_correcte:false}] },

  // ===== AQIDA N5 supplémentaire =====
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que l'Istiwa' d'Allah sur le Trône selon les Salaf ?", texte_ar:'ما الاستواء على العرش عند السلف؟', explication:"Imam Malik dit : « L'Istiwa' est connu, le comment est inconnu, y croire est obligatoire, questionner est innovation. » On affirme l'attribut sans modalité ni assimilation.", dalil_ref:"Sourate Ta-Ha 20:5", reponses:[{texte_fr:"Connu en sens, inconnu en modalité — affirmer sans assimiler",est_correcte:true},{texte_fr:"Allah s'assied physiquement",est_correcte:false},{texte_fr:"Ne signifie rien",est_correcte:false},{texte_fr:"Allah est partout sans Trône",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Quelle est la définition du Ta'wil interdit chez les Salaf ?", texte_ar:'ما التأويل المذموم عند السلف؟', explication:"Détourner un texte de son sens apparent (zahir) sans preuve recevable, souvent pour nier un attribut d'Allah. Ex: interpréter « Main » par « pouvoir » sans nécessité.", reponses:[{texte_fr:"Détourner le sens apparent sans preuve, niant un attribut",est_correcte:true},{texte_fr:"Tout effort de compréhension",est_correcte:false},{texte_fr:"Traduire en arabe",est_correcte:false},{texte_fr:"Apprendre l'arabe",est_correcte:false}] },
  { domaine:'aqida', niveau:5, texte_fr:"Qu'est-ce que le 'Adhab al-Qabr (châtiment de la tombe) ?", texte_ar:'ما هو عذاب القبر؟', explication:"Châtiment réel dans la tombe pour les mécréants et les pécheurs. Confirmé par de nombreux hadiths mutawatir. Niable est une innovation des Mu'tazila.", dalil_ref:"Sahih al-Bukhari n°1374 ; Muslim n°2870", grade_hadith:"Hadith Sahih", reponses:[{texte_fr:"Châtiment réel dans la tombe pour mécréants et pécheurs",est_correcte:true},{texte_fr:"Légende sans fondement",est_correcte:false},{texte_fr:"Seulement spirituel",est_correcte:false},{texte_fr:"Limité aux 7 premiers jours",est_correcte:false}] },
];

export async function seedQuestionsCombler(client: Client): Promise<void> {
  console.log('Seeding questions complémentaires (Hadith N1-N4 + Aqida N1, N3-N5)...');
  let inserted = 0; let skipped = 0;

  for (const q of Q) {
    const exists = await client.query('SELECT id FROM questions WHERE texte_fr = $1', [q.texte_fr]);
    if (exists.rows.length > 0) { skipped++; continue; }

    const qResult = await client.query(
      `INSERT INTO questions (domaine, sous_domaine, niveau, madhab, texte_fr, texte_ar, dalil_ref, explication, grade_hadith, statut)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'valide') RETURNING id`,
      [q.domaine, q.sous_domaine ?? null, q.niveau, 'general', q.texte_fr, q.texte_ar ?? null, q.dalil_ref ?? null, q.explication, q.grade_hadith ?? null]
    );
    const id = qResult.rows[0].id;
    for (const r of q.reponses) {
      await client.query(`INSERT INTO reponses (question_id, texte_fr, texte_ar, est_correcte) VALUES ($1,$2,$3,$4)`, [id, r.texte_fr, r.texte_ar ?? null, r.est_correcte]);
    }
    inserted++;
  }
  console.log(`Combler: ${inserted} inserted, ${skipped} skipped.`);
}

if (require.main === module) {
  const { Client } = require('pg');
  const c = new Client({ connectionString: process.env.DATABASE_URL });
  c.connect().then(async () => { await seedQuestionsCombler(c); await c.end(); }).catch((e: unknown) => { console.error(e); process.exit(1); });
}
